### ISSUE TITLE
SPSS labeling feature updates

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1015]

**Comment by emilykferguson** [comment]
**Question Labels** 
- [ ] For long questions the labels are too long. The whole line (including name and label) needs to be 250 characters max.
- [ ] Question labels are already being trimmed, but they need to be trimmed even more. This needs to consider that variable names can have different lengths. 
- [ ] The leading spaces can be removed to save space.

**Question names**
- [ ] Group names should no longer be included in the syntax, so only the question names. 
So instead of 'groupnamequestionname' it should just read 'questionname'. (That's because it's now possible to export without group names in the dataset headers.)
- [ ] The leading spaces can be removed to save space. 

**Response labels**
- [ ] For each question, each response should start on a new line. 
(That's because here each line also needs to be max 250 characters, which is currently exceeded when a question has many/long responses.) 

**File names**
- [ ] currently the ZIP file and the SPS files are named `[formID]_[language]_labels.sps`
Instead it should be named `[form name] - [language] - SPSS labels.sps`
That's because the form IDs we use now are long randoms strings, so not very useful as file names.

**Comment by esmail** [comment]
@emilykferguson will contact @tinok to ask how he was able to export without group prefixing despite kobotoolbox/kobocat#85.

**Comment by emilykferguson** [comment]
@tinok

**Comment by tinok** [comment]
This requires kobotoolbox/kpi#1016 to be fixed first. @jnm will work on it.
