### ISSUE TITLE
403 when deploying if first saved "Account Settings".

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kpi#1030]
Create account -> go to Account Settings page and click save (regardless of Require authetication... setting) -> Create and attempt to deploy form -> 403

Missing [post-save signal](https://github.com/kobotoolbox/kobocat/blob/master/onadata/apps/main/models/user_profile.py#L71-L79) to set KC-side user permissions in [`kpi.deployment_backends.kc_reader.utils.set_kc_require_auth()`](https://github.com/kobotoolbox/kpi/blob/master/kpi/deployment_backends/kc_reader/utils.py#L52-L53).

Full-context discussion: https://www.flowdock.com/app/kobotoolbox/support/threads/bsudhUXGMIo_FazWrJ03w944UBs

**Comment by jnm** [comment]
How to fix the existing broken users:
```python
from onadata.apps.main.models.user_profile import UserProfile
from guardian.models import UserObjectPermission
from django.contrib.auth.models import User
from onadata.libs.utils.user_auth import set_api_permissions_for_user
from onadata.libs.permissions import OwnerRole
### Find the broken users (sorry for heinously long line) ###
uu = User.objects.filter(is_active=True).exclude(profile=None).exclude(id__in=UserObjectPermission.objects.filter(content_type__model='userprofile').values_list('user_id', flat=True).distinct())
profiles = UserProfile.objects.filter(user__in=uu)
for profile in profiles:
    set_api_permissions_for_user(profile.user)
    OwnerRole.add(profile.user, profile)
    if profile.created_by is not None:
        OwnerRole.add(profile.created_by, profile)
```
