### ISSUE TITLE
Add avatar endpoint to API

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1031]
`users/username/avatar` should return that user's avatar. Currently, there is no way to load a specific user's avatar (only the logged in user avatar). 

#865 depends on this.

**Comment by dorey** [comment]
Here's a temporary workaround to get an avatar loading from this URL:

`<img src="/users/kobousername/avatar/">`

It currently is hard-coded to a generic avatar, but should give you what you need to continue working on this page.

```
diff --git a/kpi/views.py b/kpi/views.py
index f8be420..a5b1cb8 100644
--- a/kpi/views.py
+++ b/kpi/views.py
@@ -291,6 +291,13 @@ class UserViewSet(viewsets.ReadOnlyModelViewSet):
     serializer_class = UserSerializer
     lookup_field = 'username'
 
+    @detail_route(renderer_classes=[renderers.StaticHTMLRenderer])
+    def avatar(self, *args, **kwargs):
+        return HttpResponseRedirect(
+            "https://www.gravatar.com/avatar/?s=40"
+        )
```

**Comment by dorey** [comment]
No longer needed, as we are likey moving away from gravatar because it leaks user metadata.
