### ISSUE TITLE
cachebuster prevents compilemessages from running

### ISSUE THREAD

**Issue by rhunwicks** [kobotoolbox/kpi#1039]
When I run `python manage.py compilemessages` using just the `kobo.settings` file, I get:

```
EnvironmentError: django-cachebuster could not find a '.git' directory in your project path
```

Django-Cachebuster was last updated in 2012 and its repo says *DJANGO 1.4+ USERS: You should probably look to use Django's included static template tag*. Also, kpi is already using WhiteNoise which handles cache attributes for static files.

Therefore, I think that we should remove django-cachebuster.

**Comment by jnm** [comment]
'twas fixed in https://github.com/kobotoolbox/kpi/pull/1040!
