### ISSUE TITLE
Running in a subdirectory using KPI_PREFIX breaks Whitenoise

### ISSUE THREAD

**Issue by rhunwicks** [kobotoolbox/kpi#1041]
KPI uses Whitenoise to serve static files, and it works out whether to attempt to serve the file itself by comparing the requested url to `settings.STATIC_URL`.

At the moment `kobo/settings.py` sets this value using:

```
# KPI_PREFIX should be set in the environment when running in a subdirectory
if KPI_PREFIX and KPI_PREFIX != '/':
    STATIC_URL = '{}/{}'.format(KPI_PREFIX, STATIC_URL)
    from django.conf.global_settings import LOGIN_URL
    LOGIN_URL = '{}/{}'.format(KPI_PREFIX, LOGIN_URL)
```

`STATIC_URL` is already set to `/static/`

Therefore, if `KPI_PREFIX` is set to `/forms` then the resulting `STATIC_URL` is `/forms//static`.

When a request comes in for `/forms/static/js/somefile.js` Whitenoise compares the request to `STATIC_URL` and doesn't find a match, and so doesn't serve the file.

The way that Kobocat updates settings based on `KOBOCAT_ROOT_URI_PREFIX` is much more reliable - see `onadata/settings/kc_environ.py`.

I will prepare a PR that implements that approach for KPI.

**Comment by jnm** [comment]
I believe this was closed by https://github.com/kobotoolbox/kpi/pull/1042
