### ISSUE TITLE
Unable to import collections from XLSX

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1046]
Importing XLS files as new collections is not working. UI shows `label` error. 

Console shows: 

`{"status":"error","uid":"iJn98rHGdEyDaweDtBJfcc","messages":{"error_type":"KeyError","error":"label"},"date_created":"2016-11-29T23:57:45.653301Z"}`

Files for testing: 

[questionbank_irc_13__500__noblocks.xlsx](https://github.com/kobotoolbox/reports/files/620595/questionbank_irc_13__500__noblocks.xlsx)
[questionbank_irc_13__500.xlsx](https://github.com/kobotoolbox/reports/files/620596/questionbank_irc_13__500.xlsx)
[questionbank_irc_13.xlsx](https://github.com/kobotoolbox/kpi/files/620610/questionbank_irc_13.xlsx)

**Comment by dorey** [comment]
This is a case of a bad error message for an invalid choice list.

I have added a new issue for this to provide a better error message (or, perhaps we could just ignore the invalid choice list.

![image](https://cloud.githubusercontent.com/assets/97589/20818020/1a956236-b7f9-11e6-9939-0349ea5b25f4.png)

**Comment by tinok** [comment]
@dorey I would say we can close this issue since importing collections works. Getting better error messages would be a different issue, so I'd say we can either close this one and create a new one or rename this issue. Not a priority for me, though very nice to have for usability.

**Comment by jnm** [comment]
So say we all.
