### ISSUE TITLE
Missing columns in exports/table for some projects.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kpi#1056]
I.e. Rebecca's project.

**Comment by dorey** [comment]
Is this a duplicate of #882 ?

Are there specific columns in a dataset to reference for this? Can it be replicated with a new form?

**Comment by esmail** [comment]
An example is the `deppevaluation_philippines` form `aSHhJhLkw575FRZtZqmtJh`. Unsure about which columns.

Possibly the same root issue as #882, but that refers to reports.

**Comment by jnm** [comment]
Fixed by https://github.com/kobotoolbox/kpi/pull/1461
