### ISSUE TITLE
problem for deploying questionnaire

### ISSUE THREAD

**Issue by Nnaing** [kobotoolbox/kpi#1057]
Please help me. I cannot deploy my questionnaire. It shows as" Unexpected KoBoCAT error 403: {"detail":"You do not have permission to perform this action." 
What should I do?
email for Kobo account is nnaing82@gmail.com  and name is Naing Naing.

**Comment by pmusaraj** [comment]
Please open a support request at support.kobotoolbox.org -- Github issues are for development tickets only, we cannot follow up on support issues here.
