### ISSUE TITLE
OtherFormBuilderRedirectMiddleware causing redirect loop

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1087]
Observed on OCHA `mp03`:

* `KPI_PREFIX` set to `/forms`
* Logged in as user who prefers KPI
* [`if prefix != preferred_prefix`](https://github.com/kobotoolbox/kpi/blob/fd4e3f6c0e87b49a741205d7aea841a6fa793b9b/hub/middleware.py#L21) evaluated to `True` resulting in redirect, regardless of whether request URL ended with `forms` or `forms/`
* Logged values of `prefix` and `preferred_prefix`: found that `prefix` was `/forms` and `preferred_prefix` was `/forms/`
* Changing `KPI_PREFIX` to `/forms/` did not help
* Calling `strip('/')` on both prefixes seems a suitable solution

**Comment by esmail** [comment]
I'm sure you already noticed, but for posterity, `KPI_PREFIX`, and [therefore](https://github.com/kobotoolbox/kpi/blob/fd4e3f6c0e87b49a741205d7aea841a6fa793b9b/hub/middleware.py#L12) `preferred_prefix`, are [forced](https://github.com/kobotoolbox/kpi/blob/fd4e3f6c0e87b49a741205d7aea841a6fa793b9b/kobo/settings.py#L181) to begin and end with single `/` characters.

**Comment by jnm** [comment]
@esmail, I actually didn't notice the [`settings.py` change](https://github.com/kobotoolbox/kpi/pull/1042). It appears to be causing another problem: https://github.com/kobotoolbox/kpi/issues/1091
