### ISSUE TITLE
Replacing a form from XLS returns Resolver404 error

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1091]
Console shows import status as error: 

    {"status":"error","uid":"iYmu8VQY4XdSibgAiTCYTC","messages":{"error_type":"Resolver404","error":{"path":"assets/adypZWmaQXEMzrESqtU33z/"}},"date_created":"2017-01-17T16:25:52.794872Z"}

UI shows:
![image](https://cloud.githubusercontent.com/assets/673511/22029327/32ab88c2-dca8-11e6-9ab9-74d8a331898e.png)

**Comment by jnm** [comment]
[Sentry logging](http://sentry.kbtdev.org/kobo/kpi/issues/1878/) obtained by temporarily adding a `raise` to https://github.com/kobotoolbox/kpi/blob/2dac63f286212986bf064449df0f35f8505089a5/kpi/models/import_task.py#L112.

The problem occurs when `resolve()` is passed a path that lacks a leading `/`:
```
In [1]: from django.core.urlresolvers import resolve

In [2]: resolve('assets/adypZWmaQXEMzrESqtU33z/')
---------------------------------------------------------------------------
Resolver404                               Traceback (most recent call last)
<ipython-input-2-9a13516a0651> in <module>()
----> 1 resolve('assets/adypZWmaQXEMzrESqtU33z/')

/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.pyc in resolve(path, urlconf)
    519     if urlconf is None:
    520         urlconf = get_urlconf()
--> 521     return get_resolver(urlconf).resolve(path)
    522 
    523 

/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.pyc in resolve(self, path)
    386                     tried.append([pattern])
    387             raise Resolver404({'tried': tried, 'path': new_path})
--> 388         raise Resolver404({'path': path})
    389 
    390     @property

Resolver404: {u'path': u'assets/adypZWmaQXEMzrESqtU33z/'}
```
Successful resolution with leading `/`:
```
In [3]: resolve('/assets/adypZWmaQXEMzrESqtU33z/')
Out[3]: ResolverMatch(func=kpi.views.AssetViewSet, args=(), kwargs={u'uid': u'adypZWmaQXEMzrESqtU33z'}, url_name=asset-detail, app_name=None, namespaces=[])
```

Temporary workaround: revert https://github.com/kobotoolbox/kpi/pull/1042/commits/df4e058e68e926802c3f429124358b329867bf2d
