### ISSUE TITLE
URGENT: Failure to submit data via Chrome

### ISSUE THREAD

**Issue by maskoamas** [kobotoolbox/kpi#1101]
Inputed data on Chrome cannot be submitted - error message Failed (offline?)0

The connection is perfect and we have tested it for multiple users.

See attachment

This issue is quite urgent as the OCHA CASS team are about to launch a huge survey in an hour. Thanks you for prioritizing it.

https://ee.kobotoolbox.org/x/#Yi3C  - survey link

![cass_survey](https://cloud.githubusercontent.com/assets/9807096/22210564/8b02f2da-e18a-11e6-9a04-7c7ecad6608f.png)
![img_23012017_162816](https://cloud.githubusercontent.com/assets/9807096/22210563/8b0075a0-e18a-11e6-92e8-b75b9af2ae42.png)
![img_23012017_162959](https://cloud.githubusercontent.com/assets/9807096/22210565/8b07c936-e18a-11e6-9788-f977143cd1b7.png)

**Comment by maskoamas** [comment]
@emilykferguson  John worked on this ticket and it worked on Monday , today the issue has re-occurred again see the attached screen shots. In addition if you choose to empty cache via the pop up message and re-submit again the cache doesn't empty for some reason.
![capture 10](https://cloud.githubusercontent.com/assets/9807096/22299357/07f82a4a-e324-11e6-9680-fcc243e2cfd2.png)
![capture 11](https://cloud.githubusercontent.com/assets/9807096/22299356/07d3fa8a-e324-11e6-9b44-c026a778c401.png)

**Comment by maskoamas** [comment]
@jnm 
![image1](https://cloud.githubusercontent.com/assets/9807096/22373938/3fbda1fe-e4a4-11e6-8b73-aedd287b168b.PNG)
Same error from another user received today

**Comment by maskoamas** [comment]
@jnm  @emilykferguson any progress on this bug? i just attached another screen shot i received from another user.
![image1](https://cloud.githubusercontent.com/assets/9807096/22374129/23fc0b80-e4a5-11e6-8f54-a5e54c670fa2.PNG)

**Comment by jnm** [comment]
Finally figured out how to reproduce this:

1. Ensure no one is accessing the project via KPI;
1. Open project in KC;
1. Click "Enter data in browser";
1. Attempt to submit data via EE;
1. Observe failure but leave EE open;
1. In a new window, merely navigate to the project's page in KPI;
1. Return to EE, click upload, and notice success.

**Comment by jnm** [comment]
I have to remember that we are behind a load balancer that does SSL termination and redirection of HTTP to HTTPS requests. In the logs that I can view, i.e. not the load balancer's, I see a lot of `HEAD`s returning `204`s followed by `GET`s returning 405s:

    HEAD /unhcrlivelihood/submission => generated 0 bytes in 21 msecs (HTTP/1.1 204) 9 headers in 355 bytes (1 switches on core 0)
    GET /unhcrlivelihood/submission => generated 94 bytes in 15 msecs (HTTP/1.1 405) 4 headers in 163 bytes (1 switches on core 0)
    HEAD /unhcrlivelihood/submission => generated 0 bytes in 24 msecs (HTTP/1.1 204) 9 headers in 355 bytes (1 switches on core 0)
    GET /unhcrlivelihood/submission => generated 94 bytes in 10 msecs (HTTP/1.1 405) 4 headers in 163 bytes (1 switches on core 0)

...but the missing piece must be a `POST` that returns a `301`, which results in the failing `GET`. Sure enough, KC's `ENKETO_PROTOCOL` is set to `http`. Simulating this on the command line:

    john@scrappy:/tmp$ wget --method POST http://kc.humanitarianresponse.info/jnm/submission
    --2017-01-27 18:36:10--  http://kc.humanitarianresponse.info/jnm/submission
    Resolving kc.humanitarianresponse.info (kc.humanitarianresponse.info)... 162.249.110.118
    Connecting to kc.humanitarianresponse.info (kc.humanitarianresponse.info)|162.249.110.118|:80... connected.
    HTTP request sent, awaiting response... 301 Moved Permanently
    Location: https://kc.humanitarianresponse.info/jnm/submission [following]
    --2017-01-27 18:36:10--  https://kc.humanitarianresponse.info/jnm/submission
    Connecting to kc.humanitarianresponse.info (kc.humanitarianresponse.info)|162.249.110.118|:443... connected.
    HTTP request sent, awaiting response... 405 METHOD NOT ALLOWED
    2017-01-27 18:36:10 ERROR 405: METHOD NOT ALLOWED.

**Comment by jnm** [comment]
This issue was moved to UN-OCHA/kobo-stack#16
