### ISSUE TITLE
Form builder UI issues with library questions drag-and-drop

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1102]
Two issues reported by a user:

### 1. Sometimes dragging and dropping items from the sidebar doesn't work. And sometimes it only works when adding above another question, and not below it. 

_Proposed solution_: better demarcate the drop area and add padding to the last list element, so that items can be dropped after it. This is better explained using a screencast
[screencast 2017-01-24 15-26-08.mp4.zip](https://github.com/kobotoolbox/kpi/files/727940/screencast.2017-01-24.15-26-08.mp4.zip)

### 2. When there is an error while dragging and dropping to the form builder, no error message is shown to user. 

_Proposed solution_: include the error message using alertify.

**Comment by Pedro719** [comment]
I agree with your solution tom (1) better demarcating the drop area and adding padding so items can be dropped after it. I think we can get a better understanding of how to execute this by looking at Trello when the user is moving cards from one board to another.

<img width="348" alt="screen shot 2017-01-24 at 4 45 19 pm" src="https://cloud.githubusercontent.com/assets/25228823/22270059/fdbfa102-e25b-11e6-8b95-a204c7cd900f.png">



[trello 2.zip](https://github.com/kobotoolbox/kpi/files/728146/trello.2.zip)

**Comment by Pedro719** [comment]
When dragging block of questions to form builder I received an error as expected.
[Test 1102.zip](https://github.com/kobotoolbox/kpi/files/742588/Test.1102.zip)
