### ISSUE TITLE
Set, attain, and maintain minimum test coverage thresholds.

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1107]
KPI Python currently at 66% -> 75%
KPI client unknown -> +10%

**Comment by dorey** [comment]
KPI is [listed at 81%](https://landscape.io/github/kobotoolbox/kpi/) and coverage checks are automated on PRs thanks to @Esmail and landscape.io

**Comment by esmail** [comment]
Landscape is actually just giving us a "health" rating: [![Code Health](https://landscape.io/github/kobotoolbox/kpi/master/landscape.svg?style=flat)](https://landscape.io/github/kobotoolbox/kpi/master)
Coveralls, on the otherhand, has our coverage and we're still below 75%: [![Coverage Status](https://coveralls.io/repos/github/kobotoolbox/kpi/badge.svg?branch=master)](https://coveralls.io/github/kobotoolbox/kpi?branch=master)

**Comment by esmail** [comment]
Part of kobotoolbox/tasks#113

**Comment by joshuaberetta** [comment]
Moved to: https://www.notion.so/kobotoolbox/Set-attain-and-maintain-minimum-test-coverage-thresholds-ca63935040754687828d0661dcc08fd7
