### ISSUE TITLE
Intial setup of automatically-generated documentation (e.g. DRF and Sphinx-generated HTML).

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1108]

**Comment by esmail** [comment]
@dorey, what do you think about [`react-docgen`](https://github.com/reactjs/react-docgen) for the React code?

**Comment by joshuaberetta** [comment]
Moved to: https://www.notion.so/kobotoolbox/Improve-state-of-documentation-5ab0f402c9324cbab662847d600b31ee
