### ISSUE TITLE
API token endpoint

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#1124]
* Discuss any improvements? Django apps we can leverage to increase security?
* Replicate kc's `/<username>/api-token` feature in a KPI endpoint, perhaps as `/token`

**Comment by jnm** [comment]
Discussed at today's standup:
* CR~~U~~D endpoint at `/token`
* Don't implicitly create, i.e. return 404 if no token exists
* Support `/token?username=otheruser` (for superusers only)
* Use same authenticators as existing API endpoints
