### ISSUE TITLE
form builder does not properly reflect required questions in checkbox

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#1127]

**Comment by magicznyleszek** [comment]
I tried reproducing it and it worked ok - i.e. `*` appears next to the question, saving the form and reloading page still shows it:

<img width="733" alt="screen shot 2018-06-05 at 10 04 04" src="https://user-images.githubusercontent.com/2521888/40963143-eafaa2dc-68a7-11e8-95e0-e2807c0918bc.png">

Please try to reproduce it and add the steps if you will be able to do so :)
