### ISSUE TITLE
HA Mongo

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1139]
(Requested by OCHA)

We should support high-availability Mongo (where available) by allowing connections to a replica set, e.g.
```
>>> MongoClient('mongodb://localhost:27017,localhost:27018/?replicaSet=foo')
```
See http://api.mongodb.com/python/current/examples/high_availability.html#id1.

**Comment by joshuaberetta** [comment]
Moved to: https://www.notion.so/kobotoolbox/HA-Mongo-f23d1e62b68c4d1e970ebcf342387158
