### ISSUE TITLE
Checkboxes in "Delete Project" modal not initialized

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1153]
1. Make sure you have at least two projects that you'd like to delete;
1. From the projects list, click more actions, then delete;
1. When the confirmation modal appears, check all four boxes and click DELETE;
1. On a different project's row, but in the same browser tab, click more actions, then delete;
1. Notice that the confirmation modal appears with all boxes already checked;
1. Notice that DELETE is disabled (workaround: toggle any checkbox off and back on).
![image](https://cloud.githubusercontent.com/assets/2085013/23185528/bcac9128-f851-11e6-839b-92cb824b4a13.png)

**Comment by pmusaraj** [comment]
Reopening, issue resurfacing...
