### ISSUE TITLE
extend asset sharing permissions to assetversions

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#1164]
Fix the `AssetOwnerFilterBackend` filter on #1155 so that all users with necessary permissions can view the asset versions.

**Comment by dorey** [comment]
Mostly handled in #bd41b1 but still needs tests

**Comment by jnm** [comment]
Hmm, that's quite an old PR: https://github.com/kobotoolbox/kpi/pull/1168

**Comment by dickoa** [comment]
Hi @joshuaberetta 

I hope all is good. I wanted to know if there's something we (users) can do to help you for this bug.
I'm working on a tool to export data from kobo to R using kpi and without asset versions I can't extract the data correctly (like what the export does, combining all versions).
 
Thanks again,
Ahmadou
