### ISSUE TITLE
Update Collections list after importing and show a confirmation to user

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1179]
As a user, I would like to see once a Collection has imported from XLS. Depending on the size of the file this can take between a few seconds to several minutes, but the user never sees the Collection unless they refresh do a **hard** refresh of the page. 

Suggested solutions: 

1) Collection simply appears in the left sidebar once it's imported

2) user gets a nice notification once the collection has imported. Right now you have to refresh the page after the collection imported.

**Comment by pmusaraj** [comment]
@tinok how does user import a collection from XLS? I can't seem to find where this is done.

**Comment by tinok** [comment]
@pmusaraj There's a template file on [this support page](http://support.kobotoolbox.org/customer/en/portal/articles/2758486-importing-collections) with some more background.
