### ISSUE TITLE
Tag search box does not work on kf.kobotoolbox.org

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kpi#1188]
I have set some tags for a project. Still the *Search Tags* box displays *No results found*.

![image](https://cloud.githubusercontent.com/assets/121946/23790650/c3959e1e-0588-11e7-8e93-d6da8f7cd17d.png)

Looking at the network activity there doesn't seem to be any request happening.
Searching does work when using the *Search Projects* box.

**Comment by pmusaraj** [comment]
Closing, UI has since changed (there is no longer a dedicated tag search box).
