### ISSUE TITLE
Synchronize kpi tags to kobocat

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kpi#1189]
At the moment, there doesn't seem to be an interface (apart from the API) to set and use tags in _kobocat_. There is an interface to create and delete tags in _kpi_ though. For our use-case, we need tags in _kobocat_ to be able to logically group forms.  For us it would be ideal, if the tags that are created (and deleted) in _kpi_ were synchronized to _kobocat_.
For that, we would also have to push tags that exist in _kpi_  to _kobocat_ when a form is deployed.
If we add this functionality in a fork of _kpi_, would you consider merging it?

**Comment by joshuaberetta** [comment]
Tentatively closing this. Please create a [suggestion in the forum](https://community.kobotoolbox.org/c/feature-wishlist/6) if this is still desired.
