### ISSUE TITLE
Groups have wrong appearance text label

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1239]
Instead of 'Appearance (advanced)' it should be 'Show questions in this group on the same screen'

![image](https://cloud.githubusercontent.com/assets/673511/25495855/d65ce63a-2b4c-11e7-8947-bb0af528dade.png)

**Comment by pmusaraj** [comment]
So, I found the culprit for this issue (which was [me a month ago](https://github.com/kobotoolbox/kpi/commit/653a66d79390115eeda283e003717bf386d90a0d#diff-f2ad8e783c2aa9fce52ab11ab4652321L104)) and it's now fixed. 

But, "Show all questions in this group on the same screen" replaces the "Yes" label on the right of the checkbox, not "Appearance (Advanced)".
