### ISSUE TITLE
Question created in the form builder interface should be required=true

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#1240]
This has been the default behavior, because requiring questions leads to complete responses.

_However_ , we need to undo the way we did this because it has caused `undefined` values or questions with no specified `required` to default to true.

So, in fixing #636, we are introducing this bug. which can be fixed in the `view.row.coffee` file, rather than in the model row's defaults.

**Comment by magicznyleszek** [comment]
I couldn't reproduce this by testing, so I'm assuming this is fixed.
