### ISSUE TITLE
Validation criteria operator disappears

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1244]
@dorey, I gave this to you because you mentioned wanting to check if it was related to `select2`. Feel free to give it back to me.

1. Create or open a form that has a question with validation criteria;
1. Click the gear on the question with validation criteria to open Settings;
1. Click "Validation Criteria";
1. Observe the operator displaying as expected;
1. Click the "X" button to close the settings pane;
1. Click the gear to reopen Settings;
1. Click "Validation Criteria";
1. Observe that the operator is missing.

First time opening Settings (correct):
![image](https://cloud.githubusercontent.com/assets/2085013/25558681/808831fc-2cf9-11e7-8be8-e24773e55787.png)

Subsequent times (bug):
![image](https://cloud.githubusercontent.com/assets/2085013/25558682/91814142-2cf9-11e7-9b94-2c45f407a245.png)

**Comment by magicznyleszek** [comment]
Could not reproduce, works as expected ✔️
