### ISSUE TITLE
Local Docker environment failing since kobotoolbox/kpi dockerhub image updates

### ISSUE THREAD

**Issue by russbiggs** [kobotoolbox/kpi#1246]
After running docker-compose for a local build the application runs but I'm receiving a 504 Gateway Timeout error after filling out the account registration form.  This was functioning last week around 4/25 before the dockerhub image updates of kobotoolbox/kpi.  I've had this same issue for the dockerhub images, bjsgja3mk5cu5dhjvn2yzm3 and bjht3wpferqqgbzqbfdjcig this week.

Here is an example of the kpi error logs I'm getting:

2017/05/02 16:51:18 [error] 31#31: *6 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /accounts/register/ HTTP/1.1",

I have not tried a docker build on a server since these updates
If this would be better placed in kobotoolbox/kobo-docker I can move the issue.

**Comment by jnm** [comment]
Closing due to age; hopefully it worked for you eventually. People who stumble across this should refer to https://github.com/kobotoolbox/kobo-install.
