### ISSUE TITLE
Add ccemail and bccemail in new user registration

### ISSUE THREAD

**Issue by smoksmanh** [kobotoolbox/kpi#1248]
Dear All
I would like to add CC email and Bcc email in new user registration. when new user fill the registration form and submit. i want that app send email to admin. So admin know that new user has been register. does anyone know, how can i do like that?

Thanks,

**Comment by jnm** [comment]
Closing due to age.

For reference, we use a Python library called `django-registration-redux` (version 1.3) for registration. It doesn't look like it supports (b)cc recipients at first glance. Custom coding would be involved, or perhaps a mail service that handles this automatically.
