### ISSUE TITLE
Auto report is shown as empty 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1252]
To reproduce: Have only experienced this in [this project](https://kf.kobotoolbox.org/forms/#/forms/aDzNoQyXsZwgsBkx5ohWyW/reports) so far. 

Expected: Auto report shows usual summary for all questions. 

Instead: Shows up completely empty with `This report has no data.` message. The [API request](https://kobo.humanitarianresponse.info/forms/reports/aDzNoQyXsZwgsBkx5ohWyW/) shows `    "detail": "Not found."`. 
![image](https://cloud.githubusercontent.com/assets/673511/25766488/da83d8c0-31c0-11e7-84e0-e9a571243e59.png)

Further information: Labeled XLS download and HTML table in KPI all work as expected. 

Need to know if there are other projects that have the same issue.

**Comment by tinok** [comment]
Is it possible that the label in kpi for this issue has changed? It seems to now be "This report cannot be loaded" (see below) 

![image](https://user-images.githubusercontent.com/673511/31517925-7834a180-af6b-11e7-8e54-33bd142bf589.png)

**Comment by maurween** [comment]
Hello,
Have you had a answer to your troubleshooting issue ?
Thank you.

**Comment by pmusaraj** [comment]
Closing. Addressed by PR #1534
