### ISSUE TITLE
HXL tags

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1258]
- [x] User can add HXL tags for the form
- [x] Users can add HXL tags for the questions
- [x] HXL input fields are Predictive text, pulling from a specified HXL library
- [x] User can add their own HXL tags

Designs here:
https://projects.invisionapp.com/d/main#/projects/prototypes/10742605

**Comment by jnm** [comment]
KPI/KC accept uploading XLSForm with an `instance::hxl` column; see [hxlsform.xls.zip](https://github.com/kobotoolbox/kpi/files/1154869/hxlsform.xls.zip) for an example. KPI sees this as a new language, though, and expects it to behave as such:
![image](https://user-images.githubusercontent.com/2085013/28303410-0b07d0f8-6b61-11e7-8ade-18b93c3b276b.png)
