### ISSUE TITLE
Project Summary UI

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1259]
- [x] Include number of submissions
- [x] Add map view if there is a GPS question
- [x] Include meta data: Description, Country, Sector

Designs here:  https://projects.invisionapp.com/d/#/projects/prototypes/10978027

**Comment by tinok** [comment]
@john As for a submissions graph, here is my wishlist:

* See total number of submissions (already possible)
* # of submissions past week (7 days)
* # of submissions past month (30 days)
* # of submissions per day, displayed as a graph. User can choose between [past week with 7 bars | past month with 30 bars | past year as a line chart with 365 points]
* If any submissions in last 7 days, default to bar chart for last 7 days
* If submissions in last 30 days but not last 7 days, default to chart for last 30 days
* If no submissions in last 30 days, show past year
* If no submissions yet or none in the past year, don't show chart

**Comment by jnm** [comment]
@tinok, I think this is done from a technical perspective, but the "Past" and "Previous" terminology (for the counts at the bottom) that we're using right now seems confusing.
![image](https://user-images.githubusercontent.com/2085013/34544009-dbc4e0de-f0b1-11e7-851e-a62093b605bc.png)

**Comment by pmusaraj** [comment]
We could use date ranges instead of Past/Previous.

**Comment by pmusaraj** [comment]
I have updated the UI to display the date range instead of "past 7 days" and "previous 7 days". Testable in `unu`.

**Comment by jnm** [comment]
Thanks @pmusaraj! This looks really nice.
