### ISSUE TITLE
ActivityInfo Integration

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1262]
Support retrieval of forms and submission of data to Activity Info - https://about.activityinfo.org/2013/08/30/mobile-data-collection-with-activityinfo-and-odk-collect/

**Comment by jnm** [comment]
We need to understand the use case / write some concrete user stories for this.
The link is dead; article I found (https://www.activityinfo.org/blog/posts/2013-08-30-mobile-data-collection-with-activityinfo-and-odk-collect.html) describes using ActivityInfo as a replacement for KoBoCAT—but doesn't describe importing/exporting forms/data

**Comment by jnm** [comment]
Closing until budgeted. See https://github.com/orgs/kobotoolbox/projects/9.
