### ISSUE TITLE
XLS exports should format dates and numbers as such

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1266]
When a user downloads their data into Excel/XLS/XLSX the cells should be formatted properly to allow easy analysis. 

- [x] Dates: Currently dates are written YYYY-MM-DD, which Excel doesn't interpret as a date. The cells need to be specifically formatted as dates so that Excel understands them as such. 

- [x] Integers, decimals: Can be formatted as 'General' (no specific number formatting), but formpack stores them as text strings, so they are not recognized as such.

- [x] Select_One/Select_Many: If the response is a number, it should be stored as a number and not as a text string (see above).

**Comment by tinok** [comment]
To convert date columns to proper (Excel-recognized) dates, users need to use this formula for now: `=DATE(LEFT(A2,4),MID(A2,6,2),RIGHT(A2,2))`

**Comment by tinok** [comment]
@jnm Pinging this issue again. Converting all numbers stored as text in Excel is cumbersome and a big time sink for large surveys (e.g. DRC survey with 10k rows and 600 columns takes several hours to process on 3.1Ghz i7). 

Maybe we should split this issue into three?

**Comment by jnm** [comment]
See kobotoolbox/formpack#44, kobotoolbox/formpack#58, kobotoolbox/formpack#59

**Comment by Kalyan-Lama** [comment]
**Community:** https://community.kobotoolbox.org/t/downloaded-xls-dates/20418/2
