### ISSUE TITLE
Public Collections don't always display their contents for regular users

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1282]
This was tested in production as well is in `develop`: 

I tested the Public Collections as multiple users, and the contents of a public collection isn't always displayed to a regular user (a superuser sees things correctly). 

Here is how I tested: 

- using two browsers side-by-side, with user A and user S (superuser) in each browser, I was creating public collections from one user and testing whether the other user had access
- I made sure that all the public collections I created had at least 1 question or block
- initially there were no issues, but once user A subscribed to a collection and then unsubscribed from it, user A could no longer see the contents of Public Collections

An additional issue: the "move to collection" functionality (now under the "more actions" ...) should be disabled for subscribed public collections. Superusers can move an asset in a subscribed public collection of another user (which means, that the asset would be no longer in the initial public collection). For regular users, that operation fails with a 403.

**Comment by jnm** [comment]
Fixed by #2559
