### ISSUE TITLE
Webpack CORS issue on dev server

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1285]
Recently, font files aren't loaded on a Docker dev server setup, because of a CORS issue. 

See https://github.com/webpack/webpack-dev-server/issues/897

**Comment by ivan-navarro-75** [comment]
I am trying to get the token
`https://[kpi-url]/token/?format=json`
from my create-react-app development server and my fetch is blocked by CORS.
Could this issue be related? How can I avoid this issue?
