### ISSUE TITLE
Can't replace form from XLS two times in a row

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1288]
To reproduce: 

1. Create form 
1. From form page, click replace button and choose valid XLSForm file
1. After form has been uploaded, try to replace it again with a different XLSForm file.

Expected result: Form is replaced with the second form file and user is notified of new replacement.
Instead: Nothing happens, the second form file is never uploaded.

**Comment by pmusaraj** [comment]
I cannot reproduce this on a site under the upcoming `develop` branch.

**Comment by pmusaraj** [comment]
@tinok please test this again, it seems fixed on my end (may have been related to Mac XLS mimetype issues).

**Comment by tinok** [comment]
I just tested again on `tri` and I can still reproduce this issue. Nothing
happens when trying to upload an `xls` file, but `xlsx` files work.

**Comment by tinok** [comment]
@pmusaraj Issue can't be reproduced on `tri` anymore. Closing this issue.
