### ISSUE TITLE
Undeployed draft form version is not displayed properly 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1292]
When a user makes a change to a deployed form but hasn't deployed it yet, the draft undeployed form is not shown as such. Instead, the deployed version is displayed with the timestamp of the undeployed (modified) draft.  

To reproduce: 

1. Create and deploy form. 
1. Edit form. 
1. View form history

Before deploying the new draft, **the form history should show at the top `Current version: v7 (undeployed)`**. Instead it shows `Current version: V6 (deployed)`.

After updating form but not yet redeploying:
![image](https://cloud.githubusercontent.com/assets/673511/26428712/7ee27f9e-40e3-11e7-9f40-13ca1f022ab3.png)

After redeploying: 
![image](https://cloud.githubusercontent.com/assets/673511/26428844/0cc44928-40e4-11e7-8f16-3e16720ea35a.png)

**Comment by tinok** [comment]
@pmusaraj Is this resolved with the new version already?

**Comment by pmusaraj** [comment]
When the form is modified but undeployed, there is a bar with a message that is shown, see screenshot: 

![test form kobotoolbox 2017-06-06 09-22-49](https://cloud.githubusercontent.com/assets/368961/26831298/e51cccd2-4a99-11e7-9a33-a4824f3f4b70.jpg)

I think the message isn't clear though, in my opinion it should say: "You have made changes to the form. If you want to make these changes public, click Redeploy below."
