### ISSUE TITLE
Double scroll bar in reports (for a long form)

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1296]
There is a second scroll bar displaying that shouldn't be there on the reports page. See screenshot. 

![image](https://cloud.githubusercontent.com/assets/673511/26655217/363354a4-465a-11e7-9578-4445ebf31aea.png)

**Comment by tinok** [comment]
@pmusaraj I have shared the project with you on prod with `view` rights.

**Comment by pmusaraj** [comment]
I need to test this on the `develop` branch, the layout of the reports page has changed slightly, and this double-scrollbar issue should be already solved.

**Comment by tinok** [comment]
@pmusaraj Can you retest this after the develop branch has been deployed? Or can you confirm already that the issue has disappeared?

**Comment by pmusaraj** [comment]
Retested, it is now fixed.
