### ISSUE TITLE
'Labels' showing in addition to list of languages in download dropdown

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1303]
When a form has two specific label languages, the data download dropdown is also showing `Labels` as an option in addition to the two languages and `XML Values and Headers`. `Labels` should not be displayed in this case (when a user selects it the data downloaded is just the XML values, which is not what a user would expect). 

![image](https://cloud.githubusercontent.com/assets/673511/26786952/8b9af4e0-4a08-11e7-900a-5643225311e5.png)

```
     "languages": [
            "Sango",
            "Français"
        ],
```
[asset source](https://kf.kobotoolbox.org/forms/assets/anMyZ5r4968Dx79BXnFAsB/)

**Comment by tinok** [comment]
Bumping this to high priority since it affects all multi-language forms and is (hopefully) a small  fix.

**Comment by pmusaraj** [comment]
Now fixed in `tri`, PR ready to be merged.

**Comment by jnm** [comment]
Closed by https://github.com/kobotoolbox/kpi/pull/1414
