### ISSUE TITLE
Reflect more details of translations in JSON

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#1304]
In the `asset.content` JSON structure, the `translations` is just a list of strings.

The field needs to contain:

* language code (e.g. `en_US`)
* order that it appears in
* active = true (the one that appears in the form builder)

Proposal: make a new structure

```
"translation_list": [
    {"name": "English",
    "order": 0,
    "code": "en_US",
    "active": true},
    {"name": "French",
    "order": 1,
    "code": "fr"},
]
```

And also, remove `#active_translation_name` from the JSON structure / python code.

**Comment by jnm** [comment]
I'm going to close this in light of https://github.com/kobotoolbox/kpi/pull/1913, which does away with the need for `active`. There might still be a need for `code` and `order`, but time is short.
