### ISSUE TITLE
Cannot download data for very large projects - times out

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1314]
- [ ] Getting a 504 error when trying to upload more than 18 records at a time
- [ ] Cannot download data from project with 270k submissions.

**Comment by emilykferguson** [comment]
Discussion notes here: https://www.flowdock.com/app/kobotoolbox/kobo/threads/26lzUiBZnmnrHqWwk-SIaYKmVh6

**Comment by jnm** [comment]
Hopefully fixed by https://github.com/kobotoolbox/kpi/pull/1461
