### ISSUE TITLE
Ashley Maher Support #2

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1330]
We have coding ability. We would like assistance as to where in the code we need to alter the code to:

When a survey is returned to KoBoToolbox the information is stored in the MongoDB.

We wish to stop the data returned in the survey being stored in the MongoDB. A record that a survey was returned and which survey the time and date being recorded is fine, but not the data in the survey.

We use the REST service facility to immediately pass the survey data to a secure data store, away from KoBoToolbox.

It is only the survey content we wish to prevent from being stored by KoBoToolbox.

We have coding ability and able to do the work. It is where in the code we should work to efficiently and effectively facilitate this use case we wish the assistance.

We are open to any suggestions you have to facilitate this intention.

**Comment by jnm** [comment]
some notes about this in https://www.flowdock.com/app/kobotoolbox/kobo/threads/Hg2XidTcGMN8KofMFbiqXXCG298

**Comment by emilykferguson** [comment]
On hold for the time being.

**Comment by jnm** [comment]
Even though I failed Ashley in the long run, this part was actually completed: https://github.com/kobotoolbox/kobocat/pull/391
