### ISSUE TITLE
Missing 'check marks' for Multiple select question

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1339]
For a multiple select question displayed as 'minimal' in appearance, all the selected options does not display check marks. Please see the attached image. 
link to the form: https://ee.kobotoolbox.org/x/#YdzX
Question: Please go to section E. Response + Markets: 
1. Do you observe any humanitarian assistance provided in the area:  select 'yes'. The following question i.e. '2. Type of actor' has the multiple select question.
 

![multiselect_issue](https://user-images.githubusercontent.com/5639037/27277062-52ca86aa-54dd-11e7-9be8-46c67fda5b53.png)

**Comment by magicznyleszek** [comment]
I tested it with latest KPI and it seems to be ok now:

<img width="341" alt="screen shot 2018-06-05 at 10 13 21" src="https://user-images.githubusercontent.com/2521888/40963581-433e519a-68a9-11e8-8b9e-02b1b9651b9e.png">

This is the form I used: [aFEHuR4gMkQhZAjjvDFddf.xls.zip](https://github.com/kobotoolbox/kpi/files/2071431/aFEHuR4gMkQhZAjjvDFddf.xls.zip)

@KashifMalick could you confirm it is no longer an issue for you? :)
