### ISSUE TITLE
Deployment and Edit issues for projects (XLS form) with multi-lingual questions uploaded in kpi 

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1341]
XLS forms with multi-lingual questions, uploaded through the kpi cannot be either opened and edited in form builder or deployed as a project. Please see the attached images of the errors generated. I have also attached the XLS form (English and Russian languages) for you to give it a try. Thanks. 

![problem_deploy_uploadedform](https://user-images.githubusercontent.com/5639037/27278510-e2ff26e6-54e1-11e7-8a99-e8f96dabe240.png)
![problem_editingform_after_upload](https://user-images.githubusercontent.com/5639037/27278517-e7438756-54e1-11e7-8e33-a8cbb4ffac56.png)

[Admin_module.xlsx](https://github.com/kobotoolbox/kpi/files/1084459/Admin_module.xlsx)

**Comment by magicznyleszek** [comment]
It is possible to deploy this form in current KPI. It will display an error message when editing in Form Builder - saying that unnamed translations are not allowed. Naming the translations in the new Translations UI fixes this. Alternative fix would be to remove `label` and `hint` columns from source file and renaming `label::English` and `hint::English` to `label` and `hint` and make english a default language.
