### ISSUE TITLE
Graphs are not displaying correct data in 'Analyze Data' option of the legacy system 

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1342]
Column charts does not display correct data in the legacy system. Please see the attached image. Column for the option 'No, 30%' is missing from the chart. 

Kobo account: https://kc.humanitarianresponse.info/caim2017
Form name: CAIM_2017_KR

![1](https://user-images.githubusercontent.com/5639037/27278990-5da09820-54e3-11e7-982f-5b424b816b26.png)

**Comment by jnm** [comment]
Closing because the legacy system is unsupported.
