### ISSUE TITLE
Report feature in the kpi is unable to load

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1343]
1. Since today morning (19 June 2017), the REPORT feature in the kpi is unable to load. Please see the attached image. 
![report](https://user-images.githubusercontent.com/5639037/27279197-3c0cf81a-54e4-11e7-9563-0a76c6ca1aab.png)

I was able to access the charts and graphs feature in the new kpi for a form with data few days ago. The biggest challenge is the pie charts , which when clicked for display, hangs the browser forever. 
For all type of charts (column, bar or pie charts) it would be helpful to display the labels on mouseover , the way it works in the legacy system. Please see the below image. 

![label](https://user-images.githubusercontent.com/5639037/27279388-c36537b4-54e4-11e7-9567-7c48814e3ecd.png)

Moving issue number 2 into new bug.
````
2. Probably related to spanish translations (see xls form attached) ,in some cases it states that this report has no data instead of generating the charts etc...  maybe when following it would good to clarify if this is a problem with the form (so we can avoid this for future adaptations) or with the system. 
[screen shot for multiple select spanish.docx](https://github.com/kobotoolbox/kpi/files/1084610/screen.shot.for.multiple.select.spanish.docx)
[DIRECT OBSERVATION_KLANNDESTAN.xlsx](https://github.com/kobotoolbox/kpi/files/1084612/DIRECT.OBSERVATION_KLANNDESTAN.xlsx)
````

**Comment by pmusaraj** [comment]
Item 1 in this issue may have been fixed, in part by limiting the number of questions loaded in the report to 50 (avoids the browser freezing when trying to draw too many graphs), see https://github.com/kobotoolbox/kpi/issues/1325 

Item 2 is also fixed by exposing the error from the API when the report doesn't load (I can't find the issue for it, but this is already fixed in the kobotoolbox.org server). 

There is a second thing mentioned in issue 1: showing labels on hover. I will open a separate ticket for it.

**Comment by maskoamas** [comment]
Link to direct observation form i.e. issue 2 above - https://ee.kobotoolbox.org/::YdzX

**Comment by pmusaraj** [comment]
So, the initial issue is still valid here, i.e. the form in the first screenshot doesn't load its report. I cloned that form to PROD and to `kf.master` and it doesn't load its report (after 1 submission) on those environments eithers. @dorey will take a look at this soon.

**Comment by tinok** [comment]
On hold, waiting for XLS form and project URL (for issue 1).
Splitting the second issue into new bug.

**Comment by maskoamas** [comment]
This is the XLS form account name is 
username: georgia
link to the project - https://kc.humanitarianresponse.info/georgia/forms/GEORGIAADMIN
XLS file - https://www.dropbox.com/s/mnwj7s81khye16v/GEORGIAADMIN.xlsx?dl=0

**Comment by pmusaraj** [comment]
Closing, both issue have since been fixed.
