### ISSUE TITLE
Search function in the kpi does not work

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1344]
Search function is not working. For example if I try to search for 'MIRA' , the resultant search display no forms. Whereas I do have a deployed form with the name MIRA. Please see the attached image.
![search](https://user-images.githubusercontent.com/5639037/27279550-41a598bc-54e5-11e7-9475-f9ac3efe4fc2.png)

**Comment by pmusaraj** [comment]
This issue has been fixed since the deployment of the updated UI. (Tested again, and it works.) Closing.
