### ISSUE TITLE
Projects deleted from the legacy system are still visible in kpi

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1345]
If a project is deleted from the legacy system , it is still visible in the kpi. For example I deleted the project 'Competency Survey' from the legacy system but it still shows in kpi. See the attached image. 
Kobo account: caim2017
Project: Competency Survey

![deleted](https://user-images.githubusercontent.com/5639037/27283073-e6535748-54f2-11e7-98a9-e8fac98626b5.png)

**Comment by jnm** [comment]
We will remove the ability to delete forms in the legacy system in a future release.
