### ISSUE TITLE
Form styling options difference in legacy and kpi

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1346]
There is a difference on how styling (e.g. span, font color, link break, bold , italic) are applied to XLS forms in legacy and kpi. 
Below image is an example of styling, when a project is uploaded in kpi. The text lines appears to be overlapping each other.

![tags_kpi](https://user-images.githubusercontent.com/5639037/27283246-b21da4dc-54f3-11e7-87dd-498a9e4072a5.png)

Link to Form: https://ee.kobotoolbox.org/x/#YT05

This image is an example of styling of a project uploaded through legacy system. Clearly much better , especially the line breaks are working here, whereas in kpi they don't.
![tags_legacy](https://user-images.githubusercontent.com/5639037/27283313-ee307d00-54f3-11e7-8bc1-712fac89d614.png)

Link to form: https://ee.kobotoolbox.org/x/#YT0W

[CompetencyMapping.xlsx](https://github.com/kobotoolbox/kpi/files/1084746/CompetencyMapping.xlsx)

**Comment by jnm** [comment]
I think this was corrected for XLSForm uploads when https://github.com/kobotoolbox/kpi/issues/849 was fixed. Issues with support in the graphical form builder are tracked at https://github.com/kobotoolbox/kpi/issues/680.
