### ISSUE TITLE
KPI data export is missing some data fields containing dots

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1348]
From user report:

    common characteristic of the variables that do not show in “XLS” have a dot in their name as “A_5.1_respondent_name”

Relevant form: https://kobo.humanitarianresponse.info/forms/#/forms/aGSY5YnYiydrgiksneomUK

**Comment by esmail** [comment]
These variables are also missing from the KC "Advanced Exports", so this bug's home should probably be `formpack`.

**Comment by jnm** [comment]
Apparently Mongo [doesn't allow dots in key names](https://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name), so KC [encodes them using Base64](https://github.com/kobotoolbox/kobocat/blob/b55c3ff789ac467012c5b88da8d8dd542087fdc4/onadata/apps/viewer/models/parsed_instance.py#L67). My guess is that formpack doesn't know about this
