### ISSUE TITLE
Form is automatically updating the version numbers after every 30 minutes

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1350]
We have experienced a strange behavior on KPI, where a form is auto updating the version after an interval of 25-30 minutes. Please see the attached images, where history shows that form 'Evaluation - HPC workshop - Berlin June 2017' versions are being updated automatically after 30 minutes or so.  As of 17.30 GVA time yesterday (19 June 2017), it had reached v270. Thanks for looking in to this.

Link to Form: https://ee.kobotoolbox.org/x/#Yd3n
KoBo Account: magsalazar

![0](https://user-images.githubusercontent.com/5639037/27321935-826e7bae-559c-11e7-8fba-8beddc630fd9.gif)
![1](https://user-images.githubusercontent.com/5639037/27321938-85741516-559c-11e7-9ace-34ef09611417.gif)

**Comment by jnm** [comment]
Thanks for the report. This is a much easier-to-read description of the problem than the one I recorded at https://github.com/kobotoolbox/kpi/issues/1302.

The fix has already been committed and will be applied to OCHA's server on the next deployment.

**Comment by jnm** [comment]
[Fixed version](https://github.com/kobotoolbox/kpi/tree/ocha-2.017.25) has been deployed.
