### ISSUE TITLE
OTHER field data not exporting in KPI

### ISSUE THREAD

**Issue by KashifMalick** [kobotoolbox/kpi#1351]
The problem occurs when you use a very specific syntax for "others", and more specifically when you append "or_other" to the select_one or select_multiple types of questions (instead of creating a dedicated text type line.

Example of problematic syntax:

type	name	                        label::English
select_one HR_Cat or_other	A_HR_Cat	A.07. Are you a Humanitarian Affairs Officer (HAO) or an Information Management Officer (IMO)?

In that case, the export will show the choice "other", but there is no dedicated column for the specified other (see column AI or AJ)
![other](https://user-images.githubusercontent.com/5639037/27330482-d988be50-55b9-11e7-8b56-e25c1faf475a.png)

XLS Form: See row # 22 & 23
[CompetencyMapping.xlsx](https://github.com/kobotoolbox/kpi/files/1087952/CompetencyMapping.xlsx)

Link to Form: https://ee.kobotoolbox.org/x/#YT9o

Downloaded data in XL: 
[Competency Survey - labels - 2017-06-20-11-08.xlsx](https://github.com/kobotoolbox/kpi/files/1087967/Competency.Survey.-.labels.-.2017-06-20-11-08.xlsx)

**Comment by jnm** [comment]
See https://github.com/kobotoolbox/formpack/issues/140

**Comment by Kalyan-Lama** [comment]
Community: https://community.kobotoolbox.org/t/allow-export-of-or-other-columns-before-retiring-legacy-xls-export/17342

**Comment by joshuaberetta** [comment]
Addressed in kobotoolbox/formpack#140
