### ISSUE TITLE
Changes to Enketo web form style settings in formbuilder

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1354]
1. The 'Read more...' link should open the page in a new tab.
1. Change the URL from the current one to http://help.kobotoolbox.org/creating-forms/formbuilder/using-alternative-enketo-web-form-styles
1. Instead of a dropdown there should be two [the form style values are written behind the labels]: 

Dropdown 1 ("Page mode"):
* Label: Default - single page []
* Label: Multiple pages [`pages`]

Dropdown 2 ("Grid format"): 
* Label: Regular display []
* Label: Grid theme [`theme-grid`]
* Label: Grid theme with questions in ALL CAPS [`theme-grid no-text-transform`]

This depends on https://github.com/kobotoolbox/enketo-express/issues/756 being deployed.

**Comment by pmusaraj** [comment]
Closing. Done within one dropdown (instead of two) and satisfies requirements.
