### ISSUE TITLE
XLS data downloads fail for large projects

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1359]
When a user tries to download the XLS data for a large project through formpack it fails with a 504 timeout error. 

This is limited to large projects (4000+ submissions with hundreds of indicators).

**Comment by jnm** [comment]
Don't recreate an export if no submissions have been received since the last one.

**Comment by jnm** [comment]
On HHI PROD, aP8pi9kgwTbNWfYWYaXQJb fails to export with a 504 and has only 1225 submissions and 269 questions.

**Comment by tinok** [comment]
On OCHA, a3fDZXVM8F76F3b4NTDm4Y fails with 100k submissions.

**Comment by jnm** [comment]
Fixed by https://github.com/kobotoolbox/kpi/pull/1461
