### ISSUE TITLE
Constraint regex with backslash works in preview but not deployed form

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1360]
This example works when previewing:
```json
"survey": [
    {
        "constraint_message": "you're wrong",
        "constraint": "regex(. , '^\\d{4}$')",
        "$autoname": "four_digits",
        "required": false,
        "label": [
            "four digits"
        ],
        "$kuid": "e2b2f9ec",
        "type": "text"
    }
],
```
...however, once deployed, the constraint in KC is `regex(. , '^d{4}$')`.

Escaping the `\` in the form builder, i.e.
![image](https://user-images.githubusercontent.com/2085013/27606940-2222294e-5b50-11e7-85cb-198a39e06e67.png)
yields `"constraint": "regex(. , '^\\\\d{4}$')",` in the KPI JSON, which breaks the preview but makes it work in the deployed form on KC.

(added in response to https://app.intercom.io/a/apps/s6hn3a8q/respond/inbox/conversation/10455930948)

**Comment by dorey** [comment]
* Possibly fix: change from CSV publishing to XLS publishing of forms to KC.

**Comment by joshuaberetta** [comment]
Tested with:

| type | name        | label       | constraint            |
| ---  | ---         | ---         | ---                   |
| text | four_digits | four digits | regex(., '^\d{4}$')   |

And works in both preview and deployed version. Regex shows correctly in the form-builder:

<img width="228" alt="Screen Shot 2021-09-01 at 12 49 28 PM" src="https://user-images.githubusercontent.com/50016008/131734768-b59a3ed6-c40f-4ef3-8b4b-e9dbfe116dfb.png">
<img width="188" alt="Screen Shot 2021-09-01 at 12 49 22 PM" src="https://user-images.githubusercontent.com/50016008/131734774-0b50b593-f76c-46fa-9c24-def6680796d1.png">


`asset.content.survey`:
```json
{
  "name": "four_digits",
  "type": "text",
  "$kuid": "56PCwsgMt",
  "label": [
    "four digits"
  ],
  "required": false,
  "$autoname": "four_digits",
  "constraint": "regex(., '^\\d{4}$')"
}
```

Form-builder:
<img width="575" alt="Screen Shot 2021-09-01 at 12 48 22 PM" src="https://user-images.githubusercontent.com/50016008/131734646-02e99d2b-9feb-481f-87e4-e71a866b66f2.png">
