### ISSUE TITLE
XLS upload from Chrome-Mac fails

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1363]
Direct uploads of `xls` files to deploy as new projects fails for Chrome on Mac on kpi-prod. 

When testing with `xlsx` files and with `xls` files in Safari the problem does not appear.

**Comment by jnm** [comment]
@tinok, @emilykferguson, I can't reproduce this with Chrome 59.0.3071.115 on Mac OS 10.11, but maybe that's too old? Which version are you running?

**Comment by tinok** [comment]
@jnm I've just confirmed that the issue persists on my end. I'm using Chrome Version 59.0.3071.115 (Official Build) (64-bit) on OS 10.12.5, so same version Chrome but newer OS. I confirmed that it's the same issue in a private browsing window, so not a plugin issue. Used this file:
[testing_formatting.xls](https://github.com/kobotoolbox/kpi/files/1131127/testing_formatting.xls.zip)

**Comment by jnm** [comment]
I got a hold of 10.12 (but not 10.12.5, downloading that now...), but I still can't reproduce it.
[1363.mov.zip](https://github.com/kobotoolbox/kpi/files/1131514/1363.mov.zip)

@tinok, the first time I tried an upload, it just "created" it and nothing more; it turned out that KPI Celery had a backlog of ~80 tasks and wasn't processing anything—probably related to the outage. I restarted it and it finished all the queued imports quickly, taking about a minute in total.

**Comment by tinok** [comment]
@jnm That's the difference, for me nothing is happening in the network tab, nothing is ever sent to /imports in the first place. Is there any kind of profiling I can do? We can share screens if you want.

**Comment by dorey** [comment]
Are you using any plug-ins or browser extensions that might affect uploads?

We had this issue a long time ago when content-types were being checked client side. We removed that check and now only run a `console.error(Invalid filetype: '${file.type}')`. Is this error showing up?

I can't reproduce this when I try uploading to the server, let alone locally. But in this case I think we would need to find which step of the upload is dropping the import on your machine.

**Comment by tinok** [comment]
@dorey No plugins used with incognito mode. I'm not seeing any error in the console when I try to upload an XLS file--console is blank, just like the network tab.

**Comment by jnm** [comment]
Internal discussion thread about this bug: https://www.flowdock.com/app/kobotoolbox/kobo/threads/0vxnKBavCV1W8EQYMuJ0lAK01b1. @pmusaraj and I were leaning toward an extension-only check.

Per @dorey, [this file type checking](https://github.com/kobotoolbox/kpi/blob/adc415ec364c5a32243d5c3bb885e632c85f1046/jsapp/js/utils.es6#L223-L231) seems not to work reliably on Chrome/Mac.

Interesting observation from @emilykferguson:

> @John, bug #1363  is being reported by more users on OCHA. I tested it with a file that World Relief sent me using their account "wrg".  Nothing happens when the Inspector is open. **When I changed the file extension to "XLSX" I was able to upload it into their account.**

**Comment by pmusaraj** [comment]
I cannot reproduce the issue with @tinok's file above (testing_formatting.xls). Tested using Chrome/Mac on latest Sierra (10.12.5) and both Chrome v. 59 and Chrome 60 (latest). 

Are there any other files that I can use to test this? @emilykferguson can you provide the file from World Relief? 

In our support channel I found two similar cases, one was of a user that had this issue on several browsers under Linux. Asked them to provide the XLS file.

**Comment by tinok** [comment]
@pmusaraj I just tested again on `tri` and I can still reproduce this issue. Nothing
happens when trying to upload an `xls` file, but `xlsx` files work.

**Comment by pmusaraj** [comment]
Reopening this issue because there are a variety of issues in Chrome on Windows and Linux.
