### ISSUE TITLE
Not possible to create new forms/assets on OCHA

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1367]
Users can import forms from XLSX but not create new ones from scratch. The server responds with 500 when trying to POST to /forms/assets. [Related discussion](https://www.flowdock.com/app/kobotoolbox/kobo/threads/1DxcGlqcsF21TB14Fmd-81Bi4Q8)

**Comment by jnm** [comment]
http://sentry.kbtdev.org/kobo/kpi/issues/1761/

Why is Django trying to insert `null` into the `date_created` column when the corresponding field has `auto_now_add=True`?
