### ISSUE TITLE
Add skip logic and validation within the XLSForm for kobomatrix rows

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#1373]
Re: feedback from #1328

In the ongoing work in [`kobomatrix-relevant-and-constraints`](https://github.com/kobotoolbox/kpi/tree/kobomatrix-relevant-and-constraints), the `required` column can now be added in the column that references the response to another question within the same row. `constraint` and `validation` should work as well.

**Comment by dorey** [comment]
Fixed in 2b9aa53b99cf4bfe92f58919856b22e7e5a53c41

**Comment by dorey** [comment]
Overlaps with #1202

**Comment by dorey** [comment]
Available to test out  on `kvar`

**Comment by magicznyleszek** [comment]
@jnm would you be able to verify if this was tested and merged? Because it seems so

**Comment by joshuaberetta** [comment]
@dorey the referenced commit is merged into master. Can I close out the issue?

**Comment by joshuaberetta** [comment]
Looks like this works well (example from docs):

__survey__

| type             | name | label                                | required | kobo--matrix_list | relevant      | constraint |
| ---              | ---  | ---                                  | ---      | ---               | ---           | ---        |
| begin_kobomatrix | M1   | Items                                |          | assets            |               |            |
| select_one yn    | Q1   | Q1. Which assets do you have at home | TRUE     |                   |               |            |
| integer          | Q2   | Q2. Number of assets                 | TRUE     |                   | ${Q1} = 'yes' | . > 2      |
| end_kobomatrix   |      |                                      |          |                   |               |            |

__choices__

| list_name | name | label |
| ---       | ---  | ---   |
| assets    | car  | Car   |
| assets    | bike | Bike  |
| assets    | tv   | TV    |
| yn        | yes  | Yes   |
| yn        | no   | No    |

__settings__

| style                        |
| ---                          |
| theme-grid no-text-transform |
