### ISSUE TITLE
Change the matrix default question formatting

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1375]
Remove h5 (`#####`) question formatting from notes inside question matrix feature. Instead, the note questions in each row should be formatted as by default Grid Theme formatting (not bold, no heading style)

![image](https://user-images.githubusercontent.com/673511/28128743-c829b91a-66fe-11e7-947a-722c23f0ca0c.png)

**Comment by dorey** [comment]
Currently, the configurations are like this:


But, they are also configurable by [adding columns with values such as](https://github.com/kobotoolbox/kpi/blob/adc415ec364c5a32243d5c3bb885e632c85f1046/kpi/utils/xlsform_preprocessors/kobomatrix_handler.py#L85-L86): `kobomatrix--row-header-wrap` and `kobomatrix--header-wrap`, formatted like this: `##### {}`.

I will change the defaults to be `{}`. (It will affect all the cells in your example image with a grey background.)
