### ISSUE TITLE
改字体

### ISSUE THREAD

**Issue by xupeihong** [kobotoolbox/kpi#1376]
您好，请问修改字体的是哪个文件呢？

**Comment by pmusaraj** [comment]
Font files are updated in the SCSS files. See `jsapp/scss/main.scss` for the included fonts and `jsapp/scss/libs/_mdl.scss` for the main font definition.

**Comment by xupeihong** [comment]
OK，thank you
发自网易邮箱大师
在2017年08月11日 22:58，Penar Musaraj 写道： Font files are updated in the SCSS files. See jsapp/scss/main.scss for the included fonts and jsapp/scss/libs/_mdl.scss for the main font definition.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kobotoolbox/kpi","title":"kobotoolbox/kpi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kobotoolbox/kpi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pmusaraj in #1376: Font files are updated in the SCSS files. See `jsapp/scss/main.scss` for the included fonts and `jsapp/scss/libs/_mdl.scss` for the main font definition. "}],"action":{"name":"View Issue","url":"https://github.com/kobotoolbox/kpi/issues/1376#issuecomment-321835584"}}}
