### ISSUE TITLE
Report states 'no data' when using Spanish

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1384]
From @KashifMalick, originally at #1343 

When trying to open a report the tool shows 'This report has no data', even though data has been submitted. 
Probably related to spanish translations (see xls form attached) ,in some cases it states that this report has no data instead of generating the charts etc...  maybe when following it would good to clarify if this is a problem with the form (so we can avoid this for future adaptations) or with the system. 

![image](https://user-images.githubusercontent.com/673511/28526457-9ff267ca-7055-11e7-85c2-c30c28638836.png)

[DIRECT OBSERVATION_KLANNDESTAN.xlsx](https://github.com/kobotoolbox/kpi/files/1084612/DIRECT.OBSERVATION_KLANNDESTAN.xlsx)

**Comment by tinok** [comment]
On hold, waiting for URL of affected project.

**Comment by jnm** [comment]
Link to Project per @maskoamas https://kobo.humanitarianresponse.info/forms/#/forms/ahFZ3aQew9CL5GE3NW2kJf/data/report

**Comment by jnm** [comment]
Looking at the original project, the autoreport still doesn't render as expected, but it no longer says "This report has no data." Instead, only "2. Contact Phone" appears:
![image](https://user-images.githubusercontent.com/2085013/30940115-ee1658ae-a3ad-11e7-9215-d3cb429fe5b6.png)
I reproduced this locally.

**Comment by jnm** [comment]
Removing the `label::Spanish` and `hint::Spanish` columns from the spreadsheet (see attached) had no effect. so this does not appear to be a translation issue.
[no spanish.xlsx](https://github.com/kobotoolbox/kpi/files/1338839/no.spanish.xlsx)

**Comment by jnm** [comment]
The XLSForm `survey` sheet had these rows that the bottom (empty columns removed for clarity):

`type` | `name` | `required` | `calculation` | `$given_name`
-- | -- | -- | -- | --
`calculate` | `__version__` | `false` | `'vKAsCGFeNHnHCejiPvaaZH'` |  
`calculate` | `_version_` |   | `'vF3R3wBwroMpCw7aM7hHZy'` | `__version__`

Removing those (see attached) made the autoreport begin working properly—for a freshly created form with new submissions. I do not think merely uploading XLS without these rows and redeploying will fix the autoreport. It's likely that the stored submissions will have to be cleaned, or formpack will need an update to process these submissions correctly.

**Comment by jnm** [comment]
Confirmed locally that a redeployment does not fix existing submissions.

**Comment by tinok** [comment]
Is this bug still reproducible?

**Comment by pmusaraj** [comment]
I can see another issue with that form. Looking into it...

**Comment by pmusaraj** [comment]
Fix is done, but once this is deployed to OCHA, need to check on user `undac_forms`.
