### ISSUE TITLE
Expose HXL tags in KC data API

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1385]
API should provide a JSON output that lists all question IDs and their equivalent HXL tags, i.e.

    [{"population_in_affected_area":"#affected" , "number_of_women" : "#affected+women"}]

**Comment by emilykferguson** [comment]
KC API should include HXL tags as unique question ID        When users query their HXL data through the API they should have the unique ID be the HXL tag. If there is no HXL tag it should fall back on the unique question name.

**Comment by tinok** [comment]
Tags are exposed through kpi `assets` endpoint and can be matched to API data output with a simple script. See https://github.com/kobotoolbox/hxlsearch as an example.

KC `form` endpoint should mention the KPI `asset` API URL.
