### ISSUE TITLE
RV: User can see table and filter it based on validation status

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1392]

**Comment by jnm** [comment]
- [x] see and edit validation status in table
- [ ] sort it (not working yet; front end sends `sub-status` sort field: `https://kf.kvar.kbtdev.org/assets/aM56RptBeM9ZTT3sQj8jyq/submissions/?limit=30&start=0&sort={"sub-status":1}`)
- [ ] filter it (table filtering isn't generally implemented yet?)

@pmusaraj, let me know if I can help with this.
