### ISSUE TITLE
RV: User can set individual record's validation status

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1394]

**Comment by jnm** [comment]
This works, but the table view continues to show the old validation status after after changing it in the single-record modal.

**Comment by jnm** [comment]
Now seeing a 400 error in the console when trying to change the validation status in the single-record modal (Chrome & FF)

**Comment by pmusaraj** [comment]
That 400 error is now fixed (though, strangely, it's not working on Safari for me).

**Comment by pmusaraj** [comment]
Fixed in Safari too.
