### ISSUE TITLE
RV: User can set validation status for multiple or all records at once

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1395]

**Comment by jnm** [comment]
@pmusaraj, am I right that this still needs both an API endpoint and a UI?

**Comment by pmusaraj** [comment]
Right you are.

**Comment by jnm** [comment]
I see that "update selected" works well, but is there an update all feature that includes records beyond those on the page being displayed? Ex.: I have 6000 submissions and want to update all of them at once instead of 30/50/100/200/500 at a time.

**Comment by noliveleger** [comment]
@jnm, there is one in the backend. (only submit the new status to endpoint - PATCH request).
@pmusaraj and I decided to add an extra parameter to trigger this action. ("confirm":true must be passed among payload properties).  It has to be tested with lots of submissions.

**Comment by pmusaraj** [comment]
Yes, I'm working on this.

**Comment by pmusaraj** [comment]
[ ] update all filtered submissions (if table has a filter)
[ ] update all submissions
