### ISSUE TITLE
Header flickers during mouse movements

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1407]
During mouse movements in the formbuilder the form header alternates between black and white. See video below: 

[formbuilder flickering.zip](https://github.com/kobotoolbox/kpi/files/1170574/formbuilder.flickering.zip)

**Comment by pmusaraj** [comment]
I couldn't reproduce this exactly on either of Safari, Firefox or Chrome on Mac (latest versions of each). 

Nonetheless, there was a display bug in the form builder on Safari, where the dark header background was displaying to the left and right of the form builder, in screens wider than 1440px. I fixed this issue in the `issue-1407` branch. 

@tinok please test this on `tri`. It is possible that this also fixes the flickering issue. If so, let me know, and I'll roll the branch above into a small PR.
