### ISSUE TITLE
Collections download fails 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1415]
When trying to export/download a Collection kpi responds 

    {"detail":"Not found."}

To reproduce: Open the URL in the 'downloads' part of any Collection in the API. Downloads of individual blocks in the collection to XLS works fine, but the Collection itself (zipping multiple XLS files together) can't be downloaded. 

![image](https://user-images.githubusercontent.com/673511/28925857-165e7d5a-7834-11e7-875a-8c68697cea73.png)

Once this issue is fixed we can again expose this feature in the UI as well.

**Comment by joshuaberetta** [comment]
Endpoint removed.
