### ISSUE TITLE
Authentication session problem

### ISSUE THREAD

**Issue by bogdhy** [kobotoolbox/kpi#1452]
Hello,

My final goal is to be able to preview a submisison instance in the same way that "Get enketo edit link for a submission instance" (<code><b>GET</b>                  /api/v1/data/{pk}/{dataid}/enketo</code>) works but without the edit mode. Looking through enketo API I came across "Load an instance for editing" (<code><b>POST</b>                  /instance/view</code>). My problem is that when I access the url that enketo generates, enketo redirects me to an login page  if I didn't previously login into the kobo platform. Is there a way to achive the same results using the kobo API endpoint for retriving the authetication and not having to manually login into kobo?

Thanks,
Bogdan

**Comment by joshuaberetta** [comment]
If this comes up again, please ask on the [forum](https://community.kobotoolbox.org).
