### ISSUE TITLE
How do you use the form REST API     How to create rest API for data collection

### ISSUE THREAD

**Issue by lizhiwen19900709** [kobotoolbox/kpi#1456]

**Comment by lizhiwen19900709** [comment]
How do you use the form REST API

**Comment by lizhiwen19900709** [comment]
![image](https://user-images.githubusercontent.com/15767823/31749881-35647ed6-b4af-11e7-8a8c-d1642811ae5a.png)

**Comment by lizhiwen19900709** [comment]
![image](https://user-images.githubusercontent.com/15767823/31758181-e66925ea-b4de-11e7-977a-5f0f38c07cf7.png)

**Comment by pmusaraj** [comment]
A new and updated REST Services feature is coming soon. Will close this, as in any case, the REST Services mentioned here belong to KoboCat.
