### ISSUE TITLE
Issues and improvements of new map feature

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1467]
- [x]  Legend to allow disaggregation only provides one label language. Instead, it should allow the user to change to the other label language. 
- [x] The point data color [is darker than the one used in the legend](https://user-images.githubusercontent.com/673511/32395418-66f33744-c0b7-11e7-9bcc-9709f48bb551.png)
. The darker one should be used in the legend as well.

**Comment by pmusaraj** [comment]
These are now ready for testing on `kf.master`. 

A quick explanation for the point color: point color are transparent, but if 3 or more points are at the exact same coordinates, then the color is at 100%, unlike in the legend. To fix this visual issue, I changed how the legend shows the color. It shows it at the transparent background for the left half of the circle, and at full background for the right half. That way, we can cover both forms with few overlapping map markers as well forms with plenty of overlapping markers. 

A few more additions: 
- I added a notice for forms with more than 2000 records
- I added more colors to the list of markers (20 total)

**Comment by tinok** [comment]
@pmusaraj I just tested and it looks great! But for the big Uganda form I'm getting a 500 error instead of the map: https://kf.master.kbtdev.org/#/forms/aYT4N9xiGqg6V9vUE4d2SN/data/map

**Comment by tinok** [comment]
500 error is resolved thanks to @jnm

**Comment by tinok** [comment]
@pmusaraj I'm adding two more issues here based on testing and feedback:

- [ ] The buttons in the top right should each have a mouseover text (Layers, Toggle fullscreen, Show as points, Show as heatmap)
- [ ] Users should be able to choose between available label languages
