### ISSUE TITLE
Form with only one deployed version shows undeployed v2

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1469]
Many projects that have only one deployed form version are listed in kpi as v2 - undeployed. But there is no version history that shows v1, and in most cases the original form deployed by the user was never edited. 

Instead, these project should only show a single version of the form and not show that there is an undeployed v2. It's confusing and misleading for users to see that their most recent changes were not deployed, even though they were.

![image](https://user-images.githubusercontent.com/673511/32448180-318d88e4-c2dc-11e7-85fc-ed1118d90892.png)

e.g. a9oJ7Zr47XR9LNQGTWFMVV on PROD

**Comment by pmusaraj** [comment]
I'm not sure what to do here. Right now, the frontend code shows `v2 (undeployed)` as soon as the deployed version id is different from the asset's version id. The asset's version id changes as soon as the form is saved, even if there are no changes to the form. And in the `v2` above, 2 is calculated as `currently_deployed_version + 1`. 

Maybe the solution here is to show the currently deployed version number (v1) but keep the warning bar. Screenshot prototype: 
<img width="971" alt="screen shot 2017-11-28 at 3 41 52 pm" src="https://user-images.githubusercontent.com/368961/33343306-cc3ad2b6-d452-11e7-971b-3480e6ae2257.png">

Thoughts @tinok ?

**Comment by tinok** [comment]
@pmusaraj IF the user saved the form (even without making an edit) then I think it's acceptable to see this warning (unless/until we have a way to compare the contents/hashes of the form versions). 

I would vote in favor of closing this issue and/or replacing it with a bug describing the following:

Any change to the project's settings (including name, description, or other details) marks the form as requiring to be redeployed -- even though the itself form hasn't changed. Expected behavior: Unless the form itself is changed, don't require the user to redeploy.

**Comment by pmusaraj** [comment]
Done. Closing.
