### ISSUE TITLE
Form details in UI don't update when viewing several assets quickly 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1470]
If a user opens a form from the sidebar but then opens another asset before the first finished rendering, the previous asset will persist on the screen regardless which asset the user chooses to open.

To reproduce: 
1. In project list open any form
1. Then quickly load several other projects from the sidebar 
1. After one or more clicks the asset details on the right no longer update, even if the user slows down again. 

[See recording from about 0:40](https://github.com/kobotoolbox/kpi/files/1446785/Asset.details.not.updating.zip)

**Comment by magicznyleszek** [comment]
I couldn't reproduce it. I wen through a list of 153 draft + 4 deployed projects and it worked ok. Maye it fixed itself since last year? Or maybe there is something more to it. @tinok could you please try reproducing it again?

**Comment by tinok** [comment]
@magicznyleszek I just tried again but can no longer reproduce this either on my account. Magic fixed it again! 
Closing issue.
