### ISSUE TITLE
Fix disaggregation for questions in a nested group in maps

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1476]
See also #1467.

**Comment by magicznyleszek** [comment]
@pmusaraj some reproduction/more info would be helpful :)

**Comment by tinok** [comment]
@magicznyleszek Here are details on reproducing this error:

Issue: 
When using a form with a select_one question **inside a nested group** the map is not able to disaggregate by the responses to that question. 

To reproduce:

1. Deploy [this form](https://github.com/kobotoolbox/kpi/files/3478487/nested_question.xlsx)
2. Submit random data
3. Go to map, choose question 'favorite music' to disaggregate by

Expected: 
Options (bjork, metallica, drake) are listed with different colors

Instead:
All responses are listed as 'not set'
![image](https://user-images.githubusercontent.com/673511/62649461-f27fd000-b922-11e9-8b4e-121a31483261.png)

**Comment by magicznyleszek** [comment]
@tinok thanks!

**Comment by magicznyleszek** [comment]
Fixed on `two-databases` branch, will be released (merged into `master`) soon
