### ISSUE TITLE
User can set select_multiple question to `literacy` 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1480]
A user should be able to set any select_multiple question in the formbuilder to be shown as the "literacy widget" in Enketo. 

- [ ] This can be done by adding `literacy` to the list of `appearance` dropdown. It should only be shown for select_multiple questions. 

When a user sets this appearance we also need the following: 

- [ ] Allow the user to set the custom flash timer vale as an integer when the user should be prompted, e.g. 30 (seconds). This will override the default 60. In XLSForm this is stored in the column `body::kb:flash`
- [ ] Add the custom value `kb="http://kobotoolbox.org/xforms"` to the settings sheet under the `namespaces` column.

**Comment by tinok** [comment]
@jnm Please confirm the approach the last two items on the list with Penar, including the namespace syntax, where we want to store it, etc.

**Comment by jnm** [comment]
We ended up taking an XLSForm-only approach to the literacy widget feature.
