### ISSUE TITLE
Split special values included in literacy question 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1481]
See STC reference doc and discussion.

This includes creating three separate numeric questions for the first three columns and then splitting the regular select_multiple responses across several columns as usual.

**Comment by jnm** [comment]
This issue was moved to kobotoolbox/formpack#145

**Comment by jnm** [comment]
Reopening this since we will need to change the formpack requirement in KPI

**Comment by jnm** [comment]
STC did some testing and responded:

> I’ve had a look through and tested this. It seems to work well when it’s a single literacy question. However, there are some issues when there are multiple passages in the same assessment.
> 
> The actual words themselves get recorded fine, but the three columns:  “Word at flash” / “Duration of exercise” / “Total words attempted” of the first literacy assessment get overwritten by the information from the latest literacy assessment. However, those three columns get repeated multiple times in the output, but the output gets scrambled.
> 
> I’ve made a powerpoint with a screen recording to illustrate this bug. It’s too big for email, so please find it here: https://drive.google.com/open?id=1iIBnPCPIwne3JyZsWnfM3dZYqU-VUxSI

The PPTX file can be unzipped to view an included screencast.
