### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1485]
Upgrade to React 16 (from 15.6.0) should be fairly straightforward.

**Comment by pmusaraj** [comment]
Found one bug with the package `react-hotkey`, which doesn't support React 16.

**Comment by magicznyleszek** [comment]
@pmusaraj how is this going? Maybe I should take over?

**Comment by pmusaraj** [comment]
This was done in May. Closing.
