### ISSUE TITLE
First look #1:  jquery-ui potential security vulnerability

### ISSUE THREAD

**Issue by mroswell** [kobotoolbox/kpi#1486]
The first encounter with a project brings fresh eyes, a good time to capture initial impressions. Here's First Look item 1:
<img width="1440" alt="screen shot 2017-11-27 at 12 52 42 pm" src="https://user-images.githubusercontent.com/192568/33281164-4c619d4e-d372-11e7-9f99-068cf130f263.png">

**Comment by pmusaraj** [comment]
Hi Marjorie, welcome!

Yes, we've got an issue for this jquery UI issue (and a PR with a fix). 

issue: https://github.com/kobotoolbox/kpi/issues/1483

PR: https://github.com/kobotoolbox/kpi/pull/1484

**Comment by mroswell** [comment]
Hello Penar! Sorry about that. Will close this.
