### ISSUE TITLE
First Look #2 - Home page text

### ISSUE THREAD

**Issue by mroswell** [kobotoolbox/kpi#1487]
Noting some issues with the  descriptive text on the http://www.kobotoolbox.org/ home page:

---------------
Long line-length; I suggest reducing the number of characters per line, for greater readability

---------------
> "Our team of developers and researchers are based in" 

should read:

> Our team**s** of developers and researchers are based in..."

--------------
The three-paragraph blurb mentions several topics more than once, for instance, that the software is open source, and functions in challenging environments. 

---------------
> In September 2014 we launched a significant new phase

feels a little outdated

-------------
I won't try to wordsmith new text, but thought I'd highlight these first impressions, in case anyone wants to take it on.

**Comment by jnm** [comment]
@magicznyleszek, yes, let's switch it to `our teams`. Some other boo-boos:
* A stray `)`
    ![image](https://user-images.githubusercontent.com/2085013/47376930-ee4f3280-d6c1-11e8-940f-8775d7fb5fe9.png)
* `I.e.` capitalized when it should not be:
    ![image](https://user-images.githubusercontent.com/2085013/47376963-01620280-d6c2-11e8-918a-94009a550ed5.png)

@noliveleger, should we update kobotoolbox.org to direct people to https://github.com/kobotoolbox/kobo-install instead of https://github.com/kobotoolbox/kobo-docker?

**Comment by noliveleger** [comment]
@jnm: It would be great to direct people to `kobo-install` but I'd prefer that our team use it for a while before "releasing" it.
