### ISSUE TITLE
Create a new permission 'Can validate' and map it with KC equivalent.

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#1499]

**Comment by jnm** [comment]
The [management command](https://github.com/kobotoolbox/kpi/commit/ad0c42a63ce8f1bb78034a17f655e527d4e59a9e#diff-6295e6b8aac41c4e0ac98c4aa48a41e0R18) can't yet handle a large database (e.g. `kf.master`'s)

**Comment by noliveleger** [comment]
@jnm is it because of a memory leak issue?

**Comment by jnm** [comment]
@noliveleger exactly. A workaround using chunking like this would probably be fine:
https://github.com/kobotoolbox/kpi/blob/045f5cc20a096f716a450433b43f5c5a2b932c8d/kobo/apps/superuser_stats/tasks.py#L97-L110

**Comment by noliveleger** [comment]
@jnm I've pushed some changes.  Latest tests show the command to use around 400 MB of RAM on my computer.
