### ISSUE TITLE
500 when new user creates first project

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1512]
d'oh https://github.com/kobotoolbox/kpi/blob/045f5cc20a096f716a450433b43f5c5a2b932c8d/kpi/deployment_backends/kc_access/utils.py#L58

`UnboundLocalError: local variable 'profile' referenced before assignment` on line 83
http://sentry.kbtdev.org/kobo/kpi/issues/4055/

**Comment by noliveleger** [comment]
This one should be fixed with https://github.com/kobotoolbox/kpi/pull/1741

**Comment by pmusaraj** [comment]
Fixed by #1745
