### ISSUE TITLE
Login via LDAP possible?

### ISSUE THREAD

**Issue by poVoq** [kobotoolbox/kpi#1514]
Hello.

If I install this on my own server, is there an easy way to link it to an LDAP user database?

In general, will additional Django modules work?

Thanks for answering.

**Comment by jnm** [comment]
Hi! Yes, you should be able to use other Django authentication modules. Make sure you apply the same changes to KoBoCAT as well so that `formList`, `submission`, and `/api/v1` authentication also use your LDAP database.
