### ISSUE TITLE
HXL tags are not updated / added after redeploying

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1515]
When updating or adding HXL tags in the form and redeploying the new version, only the first version of the tags is ever exported to Excel. If the first form version never had tags then there are no HXL tags included in Row 2 (after redeploying new form versions that do contain HXL tags).

Expected: The tags from the most recent form version are used in the exports.

**Comment by jnm** [comment]
OK, to reproduce this, the question names need to remain constant while the HXL tags change.

**Comment by jnm** [comment]
Issue also affects labels: https://github.com/kobotoolbox/formpack/issues/149

**Comment by jnm** [comment]
This is done with the exception of updating KPI's formpack requirement. That'll have to happen again for https://github.com/kobotoolbox/kpi/issues/1525, so the dependency change can be tracked there.
