### ISSUE TITLE
Uploading XLS forms doesn't show imported asset, results in library import message

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1521]
To reproduce:

1. Import a form from XLS to kf prod

Expected: Imported form loads and is displayed on form landing page
Instead: kpi shows the following status message, and in the `imports` API the [import asset job](https://kf.kobotoolbox.org/forms/imports/iXEmvcVfDcuUP9paiFBKS6/) has the status `"created"` rather than `"complete"`.

![image](https://user-images.githubusercontent.com/673511/35156645-7715a2fe-fcff-11e7-9620-cc7ed61cfeec.png)

**Comment by jnm** [comment]
caused by https://github.com/kobotoolbox/kpi/issues/1522
