### ISSUE TITLE
HXL testing issues 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1525]
- [ ] When adding a HXL attribute to a question and saving it and reopining in the formbuilder, the attribute is not displayed
- [x] A space is added between the HXL tag and an attribute when exporting to XLS

**Comment by jnm** [comment]
HXL space issue: https://github.com/kobotoolbox/formpack/issues/153

**Comment by jnm** [comment]
@tinok, I can't reproduce "When adding a HXL attribute to a question and saving it and reopining in the formbuilder, the attribute is not displayed." I did notice that working with HXL tags in the form builder doesn't mark the form as unsaved, so you can navigate away without warning. @pmusaraj, could you check into that?

**Comment by jnm** [comment]
- [ ] Mark asset as having unsaved changes in form builder when HXL tags change
- [ ] Update formpack requirement to include fix for https://github.com/kobotoolbox/formpack/issues/153
