### ISSUE TITLE
Edit the URLs for XLS and CSV in API

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1526]
Currently the links under `deployment__data_download_links` lead to the old export options, which time out after 120 seconds. Instead, they should point to the new route of POSTing to `exports`. See conversation [here](https://www.flowdock.com/app/kobotoolbox/kobo/threads/dPkFceR08leAt-9Upi3J0oawHU3).

**Comment by jnm** [comment]
Remember, remember, the 28th of November: https://www.flowdock.com/app/kobotoolbox/kobo/messages/1075649
![image](https://user-images.githubusercontent.com/2085013/35341985-ee94dee6-00f4-11e8-88c7-0eda97fe42dd.png)

**Comment by jnm** [comment]
https://github.com/kobotoolbox/kpi/blob/5a64fd6639fc325da5dcb873e190b926bc567b15/jsapp/js/components/formEditors.es6#L291
