### ISSUE TITLE
Refresh translation strings in transifex

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1540]
Following recent updates, Transifex source strings need to be updated, and translators need to be notified so transltions can be started.

**Comment by pmusaraj** [comment]
Also, check translations for strings that have had minor changes (like under Collect Data).

**Comment by pmusaraj** [comment]
The first step of this is now done. Next step: wait for translators to update strings in Transifex, and then pull those translations and update the locale repository.

**Comment by pmusaraj** [comment]
@emilykferguson @tinok please ping translators. Once translations have been updated, reassign this issue to me so I can update translations.

**Comment by emilykferguson** [comment]
Chinese, French, Polish, French, and Spanish are updated.

**Comment by pmusaraj** [comment]
Great, they've been pushed to the translations repository, and they will be included in the app in the next deployment. Closing.
