### ISSUE TITLE
Improve data/downloads UI

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1543]
Following discussion: https://www.flowdock.com/app/kobotoolbox/ux-ui/threads/YDU87DiZ3i36UZswJ0zJfLRsl6N 

- [x] Once a request for an export is submitted, disable the Export submit button (to prevent multiple quick Export requests)
- [x] rename "Previous exports" to simply "Exports"
- [x] make download button more prominent
- [ ] highlight row when state goes from "processing" to "ready to download (aka add effect to a new download button that is enabled)
- [x] remove automatic redirect to exported file if download is quick

**Comment by pmusaraj** [comment]
This is now ready to test on `kvar` @tinok @jnm with a few caveats: 

I added the CSS effect to the entire row, as soon as there is a new row added that is processing. I think this is visually enough to let the user know where the new export is. (I did not add an effect on the download button, because it's a little trickier to do.)

**Comment by tinok** [comment]
@pmusaraj Would it be possible to highlight the export in the list once it's available for download? E.g. a quick jquery-style highlight on the newly created download div in the list? Or create a placeholder for where the new download will appear, to be replaced when the download is actually available? 

![image](https://user-images.githubusercontent.com/673511/35980353-7ce39d8a-0cb8-11e8-860f-9f483d9da10f.png)

**Comment by jnm** [comment]
@pmusaraj @tinok I added a quick hack to kvar that makes all exports take at least 10 seconds:
```
diff --git a/kpi/tasks.py b/kpi/tasks.py
index 18de671..db85de8 100644
--- a/kpi/tasks.py
+++ b/kpi/tasks.py
@@ -15,6 +15,7 @@ def import_in_background(import_task_uid):
 
 @shared_task
 def export_in_background(export_task_uid):
+    import time; time.sleep(10)
     export_task = ExportTask.objects.get(uid=export_task_uid)
     export_task.run()
 
```
I do think it would be nice to re-emphasize the row once the export changes from processing to ready—maybe the same way it's emphasized when it's first created?

**Comment by jnm** [comment]
I left this open in spite of merging https://github.com/kobotoolbox/kpi/pull/1554. It seems like this work is ongoing, but please close if appropriate.

**Comment by pmusaraj** [comment]
Yes, let’s keep it open. I think you identified one last improvement: highlighting the row when it goes from processing to ready.

**Comment by pmusaraj** [comment]
Closing this, it works quite well as it currently is.
