### ISSUE TITLE
Add portuguese (pt) to KPI UI

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1544]
New portugues translation by peter@plan-eval.com needs to be integrated.

**Comment by pmusaraj** [comment]
I added the portuguese translation to our local repository, and tested it on `tri`. All seems good. @john assigning ticket to you for the next steps to include this in our environments.

**Comment by jnm** [comment]
in sum, we will have `DJANGO_LANGUAGE_CODES=en ar es fr ku pl pt hi zh-hans`
