### ISSUE TITLE
Use regex more specifically when querying submissions

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1551]
No need to have the regex apply to all kinds of fields, limit to text only.

**Comment by magicznyleszek** [comment]
@pmusaraj what is this about? :)

**Comment by pmusaraj** [comment]
Hmm, from a year ago... 

I think it's about this: 

https://github.com/kobotoolbox/kpi/blob/877d2c4c8180db8aa3702fb5260a77e6072a2a65/jsapp/js/components/table.es6#L78 

Ideally, we would want the regex only for text fields. It would be more efficient to have the other fields use a simple match.

**Comment by magicznyleszek** [comment]
Thanks :) There is a related issue https://github.com/kobotoolbox/kpi/issues/2162 - PR already in review.

**Comment by joshuaberetta** [comment]
Closed in favour of #2162.
