### ISSUE TITLE
Columns in kpi exports are out of sequence

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1570]
https://www.flowdock.com/app/kobotoolbox/support/threads/zHHqwWI9BgzwBK2kbQMC8YLrcvl

More details here.

**Comment by yeffercardona** [comment]
hola soy de colombia realice la instalacion de manera local y ahora cuando voy a previsualizar un formulario sale esto connect ehostunreach : y el puerto en el que me conecto necesito ayuda muchas gracias
