### ISSUE TITLE
Groups within blocks do not import when dragging into formbuilder

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1582]
(edited by @tinok)

When importing a question block, any groups and subsequent questions or groups are hidden. Only questions outside groups before the first group are displayed. After saving and refreshing the form the imported block displays properly.

Steps to reproduce:
1. Create block with grouped and non-grouped questions (see screenshot example)
1. Import this block into a blank form by dragging-and-dropping

Expected: Entire block is displayed in the formbuilder
Instead: Only questions preceding the first group are visible

Block containing non-grouped and grouped questions:
![image](https://user-images.githubusercontent.com/673511/36609666-a8a37ad2-189b-11e8-9c58-5a72a66c2a22.png)

After trying to drag this block into the formbuilder: 
![image](https://user-images.githubusercontent.com/673511/36609647-941a0310-189b-11e8-89d4-cd5286a18073.png)

After saving and refreshing the form:

![image](https://user-images.githubusercontent.com/673511/36609653-9c313442-189b-11e8-85ae-85eae92408eb.png)

**Comment by tinok** [comment]
Possibly related to #317 and #330
