### ISSUE TITLE
Data of project shared publicly is not accessible 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1589]
User 1 has shared a project publicly (i.e. all its data) but user 2 can't view any of the data tabs in the UI. 

User 2 **does** have access to data when accessing the direct URLs included in the `asset` via the API.

Expected: User 2 can see Data tab in UI and when clicking on it access all the sub pages with the project's data. 

![image](https://user-images.githubusercontent.com/673511/36611773-876215f2-18a2-11e8-9b8c-4faaaf9ae8f4.png)

**Comment by tinok** [comment]
I just tested and it doesn't matter if user 2 has any explicit permissions as well (can submit data) - the data is never accessible.

**Comment by pmusaraj** [comment]
The fronted work for this should now be ready on branch `issue-1589`. But there is a minor fix to do on the backend. 

@noliveleger can you take a look at this? Basically, when a form has the checkbox "Share data publicly" checked, the `AnonymousUser` gets the `view_submissions` permission. But the reports API call in `kobo/apps/reports/views.py` checks only whether the requesting user has that permission (and he/she doesn't, so it fails). This should return the asset if data is shared publicly. 

Feel free to work on the same branch.

**Comment by noliveleger** [comment]
@pmusaraj I have committed a fix in the backend.
Please try it and let me know. The tests I made on the API did return the expected results but I couldn't test the UI.
