### ISSUE TITLE
Can't drag a question or block from the library into a group

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1592]
1. Create a new form. Add two questions and group them
1. Select a question or block from the library sidebar and try to drag it between Q1 and Q2 (inside the group)

Expected: The library question can be placed anywhere inside the group
Instead: It can only be added before or after the group

NB: It's not necessary to add two questions to create a group, and it should be possible (and is, with #2242 merged) to drag a library question into a single-question group. —@jnm

**Comment by jnm** [comment]
Fixed by #2242
