### ISSUE TITLE
404 after editing record

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1605]
After editing a record on OCHA, I get redirected to https://ee.humanitarianresponse.info/url, which 404s.

The edit nevertheless completes successfully, so this isn't a super-urgent problem.

**Comment by pmusaraj** [comment]
Won’t have a chance to look until Tuesday evening, but is this only on OCHA?

**Comment by jnm** [comment]
No, just hadn't tested anywhere else :) It's an issue on PROD as well, with the redirect going to `https://ee.kobotoolbox.org/url`.

**Comment by pmusaraj** [comment]
This is now ready to test on `kvar`. After editing, I also added a prompt to the submission screen, to let the user refresh the submission data. It looks like this: https://monosnap.com/file/wf09jGfUn8in355enD6IvKd74rVKtj
