### ISSUE TITLE
Export SPSS labels

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1607]
Goal is to rewrite SPSS syntax (already existing) but then extend this model to also cover Stata and R.

* Variable labels: One for each question of the form that exists in the dataset, one per line, followed by period after the last item.
* Value labels: Only required for select_one or select_multiple questions. List question name, followed by each option name and label, one per line, followed by period after the last item.
* Max length per line 251 bytes (need to truncate labels accordingly. 
* One syntax file for each label language (needs to work with all kinds of labeling, e.g. `label`, `label::Spanish`, `label:Spanish`, label::Español`), saved as `[form name] - [language] - SPSS labels.sps` and put into a zip file `[form name] - [language] - SPSS labels.zip` with all SPS files.
* Desired testing: run this labeling script on large number of projects to find edge cases (e.g. old script can't handle two responses with the same name in the same question). 

Structure: 

```
VARIABLE LABELS

question_name1 "Label question 1"
/question_name2 "Label question2"
/question_name3 "Label question3"
/q4_multiple_select "Which of the following do you own?"
/q4_multiple_select_1 "Which of the following do you own? :: TV"
/q4_multiple_select_2 "Which of the following do you own? :: Radio"
/q4_multiple_select_3 "Which of the following do you own? :: Laptop computer"
/q4_multiple_select_4 "Which of the following do you own? :: Tamagotchi"


VALUE LABELS
question_name1
'option1' "Label option 1"
'option2' "Label option 2".

/question_name3
'option1' "Label option 1"
'option2' "Label option 2"
'option3' "Label option 3".
```

Use [spss_syntax.xlsx](https://github.com/kobotoolbox/kpi/files/1782282/spss_syntax.xlsx) for testing.

Previous version's output (not conforming to all the rules above): 
[aFZabsRgooHE76bukKe3Ah_spss_labels.zip](https://github.com/kobotoolbox/kpi/files/1782288/aFZabsRgooHE76bukKe3Ah_spss_labels.zip)

**Comment by tinok** [comment]
This replaces and closes #1015

**Comment by jnm** [comment]
Make sure Unicode is fully supported, e.g. avoid http://sentry.kbtdev.org/kobo/kobocat/issues/1332/
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 2: ordinal not in range(128)
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "onadata/apps/logger/views.py", line 469, in download_spss_labels
    zip_io= survey_to_spss_label_zip(survey, xform.id_string)
  File "pyxform/spss/spss.py", line 89, in survey_to_spss_label_zip
    syntaxes= survey_to_spss_label_syntaxes(survey)
  File "pyxform/spss/spss.py", line 76, in survey_to_spss_label_syntaxes
    exportable_label_mappings= get_per_language_labels(survey)
  File "pyxform/spss/spss.py", line 52, in get_per_language_labels
    question_label_mappings, option_label_mappings, label_languages= get_label_mappings(survey, path_prefixes=path_prefixes)
  File "pyxform/utilities/get_label_mappings.py", line 133, in get_label_mappings
    get_label_mappings_0(survey_element)
  File "pyxform/utilities/get_label_mappings.py", line 94, in get_label_mappings_0
    get_label_mappings_0(child_element, current_prefix=group_path)
  File "pyxform/utilities/get_label_mappings.py", line 119, in get_label_mappings_0
    multi_select_question_name= recorded_question_name + path_delimiter + option_name
```

**Comment by jnm** [comment]
It'd be nice if we could
```
VARIABLE LABELS

question_name1
/"Label question 1"
/question_name2
/"Label question2".
```
...that way, each label could have up to 249 characters. Trying to figure out if that's allowed.

**Comment by jnm** [comment]
[IBM_SPSS_Statistics_Command_Syntax_Reference.pdf](https://github.com/kobotoolbox/kpi/files/2320138/IBM_SPSS_Statistics_Command_Syntax_Reference.pdf)
* "Variable names can be up to 64 bytes long, and the first character must be a letter or one of the characters @, #, or $. Subsequent characters can be any combination of letters, numbers, nonpunctuation characters, and a period (.). In code page mode, sixty-four bytes typically means 64 characters in single-byte languages (for example, English, French, German, Spanish, Italian, Hebrew, Russian, Greek, Arabic, and Thai) and 32 characters in double-byte languages (for example, Japanese, Chinese, and Korean). Many string characters that only take one byte in code page mode take two or more bytes in Unicode mode. For example, é is one byte in code page format but is two bytes in Unicode format; so résumé is six bytes in a code page file and eight bytes in Unicode mode" (p. 46).
    * "When using data files with variable names longer than eight bytes in version 10.x or 11.x, unique, eight-byte versions of variable names are used; however, the original variable names are preserved for use in release 12.0 or later. In releases prior to 10.0, the original long variable names are lost if you save the data file" (p. 47).
* "Each variable label can be up to 255 bytes long, although some procedures print fewer than the 255 bytes. All statistical procedures display at least 40 bytes" (p. 2071).
* "To control line wrapping of labels in pivot tables and charts, insert \n as part of the label wherever you want a line break" (ibid; also applies to value labels: p. 2058).
* As of SPSS 14, "The maximum length of a value label is extended to 120 bytes (previous limit was 60 bytes)" (p. 2057).
* "To specify a single quote or apostrophe within a quoted string, either enclose the entire string in double quotes or double the single quote/apostrophe" (p. 39).
* "To specify double quotes within a string, use single quotes to enclose the string" (ibid).
* "String specifications can be broken across command lines by specifying each string segment within quotes and using a plus (+) sign to join segments" (ibid).
* There are "interactive" and "batch" modes:
    * For interactive, "Note: For compatibility with other modes of command execution (including command files run with INSERT or INCLUDE commands in an interactive session), each line of command syntax should not exceed 256 characters" (p. 38).
    * For batch, "A line cannot exceed 256 characters; any additional characters are truncated" (ibid).

Also of note:
* "A tape written with the following characteristics can be read by most computers: 9 track, 1600 BPI, unlabeled, and a blocksize of 3200 characters. However, there is no guarantee that a tape written with these characteristics can be read successfully. The best policy is to know the requirements of the receiving computer ahead of time" (p. 642).

**Comment by p2edwards** [comment]
This example tries to follow the common rules between interactive and production mode.
```spss
VARIABLE LABELS
 question_name 'Label q1'
 /question_name2 'label q2'
 /question_name3 'a particularly long'
  + ' label can be split with a plus'
 /question_name4 'let''s self-escape singlequotes'
 /question_name5 'terminate command with dot'
 .
VALUE LABELS
 question_name1
 'option1' 'Label option 1'
 'option2' 'Limit here is 120 bytes (or 60 bytes before R 14.0)'
 'option3' 'can still split the label like'
  + ' this'
 /question_name2
 'option1' 'Label option 1'
 'option2' 'hi again'
 'option3' 'one more group...'
 /question_name3
 'option1' 'note we indent by one space'
 'option2' 'for these multiline commands'
 'option3' 'because of production mode'
 'option4' 'dots optional in production mode but not interactive mode'
 .
```

**Comment by jnm** [comment]
We need to expose [formpack's `multiple_select`](https://github.com/kobotoolbox/formpack/blob/d87364f951eb17f321957469a189f8dcb3eab5d1/src/formpack/reporting/export.py#L28) in the UI so that people can suppress the Boolean columns for select multiple questions (`multiple_select='summary'`). @jnm, create an issue for this!

**Comment by jnm** [comment]
Getting there! Need to get SPSS to recognize that our files are UTF-8 encoded:
![image](https://user-images.githubusercontent.com/2085013/45190487-267edc80-b20c-11e8-967d-e619e39aba22.png)

At first, it seemed as simple as adding `* Encoding: UTF-8.` at the top of the file, but that's not enough. Saving a UTF-8 file from SPSS reveals that it expects the bytes `ef`, `bb`, and `bf` (hex) to be the first three bytes.
```
john@scrappy:/tmp/spssfun$ file eng*
eng trunc bad.sps:  UTF-8 Unicode text
eng trunc good.sps: UTF-8 Unicode (with BOM) text, with CRLF line terminators
john@scrappy:/tmp/spssfun$ diff <(head -n 1 eng\ trunc\ bad.sps | xxd) <(head -n 1 eng\ trunc\ good.sps | xxd)
1,2c1,2
< 00000000: 2a20 456e 636f 6469 6e67 3a20 5554 462d  * Encoding: UTF-
< 00000010: 382e 0a                                  8..
---
> 00000000: efbb bf2a 2045 6e63 6f64 696e 673a 2055  ...* Encoding: U
> 00000010: 5446 2d38 2e0d 0a                        TF-8...
```
Surprise (not): this is the UTF-8 BOM:
```
In [1]: import codecs

In [2]: codecs.BOM_UTF8
Out[2]: '\xef\xbb\xbf'
```
Apparently we can use `encode('utf-8-sig')` to get this BOM included without having to do anything gross:
> Without external information it’s impossible to reliably determine which encoding was used for encoding a Unicode string. Each charmap encoding can decode any random byte sequence. However that’s not possible with UTF-8, as UTF-8 byte sequences have a structure that doesn’t allow arbitrary byte sequences. To increase the reliability with which a UTF-8 encoding can be detected, Microsoft invented a variant of UTF-8 (that Python 2.5 calls "utf-8-sig") for its Notepad program: Before any of the Unicode characters is written to the file, a UTF-8 encoded BOM (which looks like this as a byte sequence: 0xef, 0xbb, 0xbf) is written. (https://docs.python.org/2/library/codecs.html#encodings-and-unicode).

I'll change the line endings to `\r\n` as well. It probably doesn't matter, but SPSS is a Windows program after all.

**Comment by jnm** [comment]
Better:
![happy-spss](https://user-images.githubusercontent.com/2085013/45191138-832fc680-b20f-11e8-93c7-9102af80597a.png)
