### ISSUE TITLE
When adding tags show suggestion / autocomplete

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#161]
Linked to #308

**Comment by magicznyleszek** [comment]
@noliveleger, @jnm - is it possible to get a list of all used tags by given user from some endpoint? Because such a list would be needed by FE :)

**Comment by magicznyleszek** [comment]
Blocked by #2624

**Comment by joshuaberetta** [comment]
moved to: https://www.notion.so/kobotoolbox/Advanced-improved-asset-tag-management-9f4083794c2a4a71aeb097c1b8111be3
