### ISSUE TITLE
Disable EE edit button for a submission if project is archived

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1615]
User can't load a submission in Enketo to edit it if project is archived, so button shouldn't be loaded.

**Comment by tinok** [comment]
@pmusaraj I tried different projects on kf.master in pmusaraj but couldn't get to table view (in order to try and edit specific records). I'm guessing some database issue?

![image](https://user-images.githubusercontent.com/673511/37441569-53d30e0e-27bf-11e8-8943-7ab93caec27b.png)

**Comment by pmusaraj** [comment]
@tinok it would be best to test this by creating a new form, adding data to it, and then archiving. it's very possible that older forms in your account on `kf.master` don't have the corresponding data in KC.
