### ISSUE TITLE
When opening archived project the (form) landing screen is shown 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1620]
Instead, the summary page should be displayed (as for deployed projects).

**Comment by pmusaraj** [comment]
I've pushed a branch to `kf.master` with a slightly modified fix for this. 

The link on the sidebar or asset row leads to the Summary screen when the form has at least one submission (in deployed or archived state). If forms have 0 submissions, the link still points to Form Landing. 

(This may appear weird, but forms with 0 submissions have nothing useful in the summary screen, so it makes more sense to only link to it when there is some data.)

**Comment by tinok** [comment]
Passed QA
