### ISSUE TITLE
A user can import a file with GPS coordinates (points) which are then displayed along with base map layers

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1656]

**Comment by pmusaraj** [comment]
@jnm @tinok we could try this Leaflet plugin: https://github.com/mapbox/leaflet-omnivore it covers CSV, WKT, KML and more. So, we could simply let users upload files, then let the plugin parse the data for each file type.

**Comment by tinok** [comment]
That looks amazing. Yes, let's try that indeed. I'll be happy to supply test KML (though you can find a million on Google).

What about edge cases (invalid file formats, extremely large files, timeouts, extremely large number of points)?

**Comment by jnm** [comment]
Closed by https://github.com/kobotoolbox/kpi/pull/1844/
