### ISSUE TITLE
Filtering in the table view should list questions by label

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1662]
Originally
> When picking the field whose values must match the search criterion, display the field labels in the selection control. If a field is not present in the latest version of the form, display its name instead.

This requirement was based on the assumption that there'd only be a way to filter by one field at a time, not that we'd have a filter row encompassing all columns. It still has some relevance to #1663.

**Comment by tinok** [comment]
@pmusaraj I think this can be marked as done since it's supported in all label languages now?

**Comment by pmusaraj** [comment]
Yes, it's done.
