### ISSUE TITLE
Form owner can hide columns, set primary column in table view

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1663]
1. A (project owner) user should be able to hide any number of columns 
1. User should be able to choose one column to be displayed in the first column space. 
1. The user should be able to save these settings to the server to become the default view of the table. Any user with whom the project is shared would see the view with the same settings. But other users can change the view though the changes can not be stored except by the owner. 
1. [Nice to have] Ideally, the backend request should exclude hidden columns.

Originally
> Owner of the project will assign the default field, but users can change and a session will be store in the browser, and the user session will override the owner's choice

**Comment by tinok** [comment]
@pmusaraj I updated the story, please check the above description

**Comment by pmusaraj** [comment]
A few improvements: 

- [ ] frozen column should be forced to be visible (even if not selected in col list)
- [ ] labels or xml group names should be settable by view only users
- [ ] add descriptive text for frozen column, list of visible columns, to describe that only users with "edit form" permission can modify those fields
- [ ] change order of fields in modal window
- [ ] refresh frozen dropdown and column visibility list when changing label language or group names
- [ ] always include column of checkboxes
