### ISSUE TITLE
Allow filtering by response labels in the table view

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1664]
Filter criteria may be labels as well as values. Only labels from the latest version of the form are considered.

**Comment by tinok** [comment]
This is now possible with a recent upgrade, allowing filtering select_one questions using the label (as well as xml) responses. 

![image](https://user-images.githubusercontent.com/673511/39328515-99071cec-4969-11e8-9c93-ae3b55b22fa4.png)
