### ISSUE TITLE
Can't edit a submission as a user with whom a form is shared

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1672]
1. Create and deploy a form;
1. Make a submission;
1. Share the form with another user, granting `Edit Submissions`;
1. Log in as other user;
1. Attempt to edit the submission;
1. Notice "Loading Error" in the UI and 404 in the console.

Support request: https://app.intercom.io/a/apps/s6hn3a8q/inbox/inbox/conversation/15166405865

**Comment by psmith18** [comment]
I also came across this bug today. Any idea when it might be fixed? Thanks!

**Comment by alnf** [comment]
I also confirm the issue.

**Comment by akahles** [comment]
Any news on this issue? - also experiencing the same behavior. Thanks for developing such a great tool!

**Comment by jnm** [comment]
This was actually a problem in https://github.com/kobotoolbox/kobocat, and has been fixed by https://github.com/kobotoolbox/kobocat/pull/459. We haven't made a release for this yet, though, but we will this week.

**Comment by jnm** [comment]
Fixed in release https://github.com/kobotoolbox/kobocat/releases/tag/2.018.26
