### ISSUE TITLE
How to format JSON to send a form submission to the API

### ISSUE THREAD

**Issue by puguji** [kobotoolbox/kpi#1680]
Hello,

When using [https://kc.kobotoolbox.org/api/v1/submissions](https://kc.kobotoolbox.org/api/v1/submissions), how do I know how to format my JSON ( given a specific form ) so that it get accepted by the API ?

eg:
I have one simple form on my kobo account with only one text question called "fooname" and I want to send a submission to this form using the api with the json format
 I have tried : 
`curl -X POST -d '{"id": "[my-form-id]", "submission": { "foo-name":"john"}}' https://kc.kobotoolbox.org/api/v1/submissions -u uji:[my-passsword] -H "Content-Type: application/json"`
but I got the answer:
`{"error":"Improperly formatted XML."}%`

**Comment by jnm** [comment]
Hello, if you're using our hosted instance at kc.kobotoolbox.org, please send your request to `help@kobotoolbox.org`.

**Comment by kevinholl** [comment]
I'm running into the same issue with a self hosted instance of Kobo. Was there a fix or other guidance offered here that you could share?
