### ISSUE TITLE
Copy permissions from one project to another project (without cloning the content)

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1683]
- [x] Decide if we copy _from_ or _to_ a project -> **from**
- [x] If the destination already has permissions not in the source, do we keep or remove them? -> **remove them**
~- [ ] @jnm, write another issue for backend~

**Comment by pmusaraj** [comment]
I would offer the option to **copy sharing permissions from** another form into the current form user the is editing. To me, this makes more sense than the inverse because user can see all the details of the form that is being edited by the change (whereas, a _copy to_ would not show all the details of the form being edited). 

Secondly, permissions in the destination form should be overriden by the copy action IMO. UI should warn the user that this is irreversible, but it's cleaner and more transparent to avoid merging the copied permissions with existing permissions.

**Comment by noliveleger** [comment]
Backend is done in this [PR](https://github.com/kobotoolbox/kpi/pull/1708).

**Comment by pmusaraj** [comment]
@smutnyleszek please set up the frontend for this, you can work on the same branch as PR #1708. 

Design screens for this are here: https://app.atomic.io/d/mYiUTk0o6Jiw 

After hitting Import, the user should see a confirmation screen, with: 

Title: Are you sure you want to copy permissions? 

Message: You are about to copy permissions from `Project Title A` to `Project Title B`. This action cannot be undone.

**Comment by smutnyleszek** [comment]
@noliveleger where can I get a list of projects to display in the "Select source project…" select?

**Comment by pmusaraj** [comment]
@smutnyleszek the source projects are any projects that the current user has `view` rights on, so basically the same list as on the main page of the app. you could get that list from the store that's already there. it may be simpler to look at the sidebar list, it's the same one, but easier to read that code than the main list (main list has some search params mixed in).

**Comment by smutnyleszek** [comment]
@pmusaraj would using `stores.allAssets.byUid` would be ok, or it could contain some inaccessible projects?

And second question: after OKing the confirmation screen, what backend call should be made? From #1708 I guess it is `PATCH /permissions/` with some parameters passed?

**Comment by smutnyleszek** [comment]
**(Note to self)**

Call `http://<kpi-url>/assets/<uid>/permissions` with `PATCH` and a payload:
```
{
    clone_from: <uid>
}
```

**Comment by smutnyleszek** [comment]
@noliveleger @pmusaraj what is left here to do to close it?

**Comment by pmusaraj** [comment]
Nothing, this is done. For future reference, if you mention the issue number in the commit or PR, Github automatically closes it: https://blog.github.com/2013-01-22-closing-issues-via-commit-messages/
