### ISSUE TITLE
Investigate removing Gulp

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1684]
We currently only use gulp to copy some font files. Investigate accomplishing the copy operation without gulp. 

Keep in mind though that we should be able to run this copy operation

* as a developer, using a simple command
* automatically, as part of the Docker container
* independent of OS (Linux, Mac, Windows)

Initially mentioned https://github.com/orgs/kobotoolbox/projects/6#card-8349246

**Comment by smutnyleszek** [comment]
I was initially thinking about writing a custom node script (with help of some npm package: ncp, cp-file, copyfiles) that will be run via npm run-script :)

**Comment by smutnyleszek** [comment]
Note: investigate if we can't just use fonts directly from node_modules
