### ISSUE TITLE
Include the Primary key to parent/child tables in repeats

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1685]
It was noted that _parent_index in detail sheet and _index in Master sheet are generated on fly which is only the Key to link between master detail record. This makes it hard to end users to store info in user database and after that only copy the latest info because the index keeps on changing with every new upload. If there is a possibility to **copy the primary ID to the child sheet in the excel export**, this will give more flexibility to users to only concentrate doing QC's on newly uploaded data hence saving a lot of time.
When downloading an excel export of a form with a repeat, users should be able to see the system primary key of the submission on both the main table and the child table

**Comment by noliveleger** [comment]
Done with Include the Primary key to parent/child tables in repeats 
#169
