### ISSUE TITLE
Make sure extraneous sheets are ignored

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1697]
Users may have other sheets in their XLSForms that are not part of the XLSForm spec. These should be ignored, but they're not.

Discussion: https://www.flowdock.com/app/kobotoolbox/support/threads/xzIIeRzFv0oDuOKXAvofgb9llgC

See also: https://kf.kobotoolbox.org/forms/#/forms/an65vn7c6VBvZoQtSGxuX7/json (extraneous sheets begin with `DELETED`)

**Comment by joshuaberetta** [comment]
This no longer appears to be an issue.
