### ISSUE TITLE
Filtering by Collection is not possible

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1707]
In the FB sidebar as well as the library view, when choosing collection none of its contents are being displayed. 

1. Use an account that already has questions/block inside collections (e.g. tinokreutzer on kpi prod)
1. Open formbuilder, library sidebar, choose the collection containing a question/block

AND

1. Open the library 
1. Select a collection on the left that contains at least one asset

Expected: The contents of the collection are displayed

Instead: 0 assets are returned in the UI (and in the network response)

May be related to #1282

**Comment by pmusaraj** [comment]
This isn't exactly the same issue as #1282, but both are current issues. 

I tested this on prod, with my account, and I couldn't reproduce it right away. I could, however, reproduce it on OCHA (and there are server-related explanations for why that may be).

I'll add John to the ticket here, and we should address this soon (see: likely next week).
