### ISSUE TITLE
Add terms/privacy policy link for logged-in users in app

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1709]
This should be included in the user dropdown (top/right), two separate links. They point to: 

http://www.kobotoolbox.org/terms 
http://www.kobotoolbox.org/privacy

**Comment by pmusaraj** [comment]
Needs backend fields for URLs.

**Comment by jnm** [comment]
@pmusaraj, here's the backend for this: https://github.com/kobotoolbox/kpi/pull/1765; endpoint is `/environment/`
