### ISSUE TITLE
Modal stays open after changing URL

### ISSUE THREAD

**Issue by mroswell** [kobotoolbox/kpi#1722]
Step 1: Click on form
Step 2: Select Data tab
Step 3: Table view
Step 4: Open a Record
Step 5: Visit https://kf.kobotoolbox.org/#/forms
by adding that URL in the address bar and pressing Enter

Expected behavior: Modal disappears
Actual behavior: Modal stays on screen.

**Comment by pmusaraj** [comment]
I don't understand how you completed Step 5. Can you maybe record the screen?
