### ISSUE TITLE
Some forms cannot be archived (assertionError)

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1729]
See http://sentry.kbtdev.org/kobo/kpi/issues/2562/ and https://www.flowdock.com/app/kobotoolbox/ux-ui/threads/4H_kb7crQm8aGHpeXKLBuLHXtXl

Note that this doesn't happen on a new form.

**Comment by joshuaberetta** [comment]
Log no longer in Sentry. Will reopen if the issue shows its head again 👌
