### ISSUE TITLE
Make `REGISTRATION_OPEN` configurable in admin interface

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1735]
How hard could it be?...

Nearly a duplicate of https://github.com/kobotoolbox/kobo-docker/issues/166.
Make sure this happens, too: https://github.com/kobotoolbox/kobocat/issues/436.

Seems nice: https://django-constance.readthedocs.io/en/latest/

**Comment by jnm** [comment]
Looks like registrations are disabled even with `REGISTRATION_OPEN=True` in https://github.com/kobotoolbox/kpi/tree/2e8bcaf46ea325e8a2a7dae34037712b01b7d02c

**Comment by noliveleger** [comment]
@jnm I did have the expected behaviour when I tested it locally. 
Did you notice if it happens everywhere this feature has been released?

**Comment by jnm** [comment]
The bad part of this was cleaned up by https://github.com/kobotoolbox/kpi/pull/1776, specifically https://github.com/kobotoolbox/kpi/pull/1776/commits/1c32363fbcb16138934bd3473ac1f9e990864322
