### ISSUE TITLE
Customize logo and background image

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1738]
via settings in the Django admin interface

**Comment by jnm** [comment]
django-constance does have some immature support for `ImageField`s, but it doesn't work for S3 / respect the storage class: https://github.com/jazzband/django-constance/blob/05ec0e9f1dc41be63f42bf75707a9d583c295bfa/constance/admin.py#L137-L144
On the upload side, this isn't terrible to fix with something like:
```
diff --git a/constance/admin.py b/constance/admin.py
index a2285cc..0f55566 100644
--- a/constance/admin.py
+++ b/constance/admin.py
@@ -13,6 +13,7 @@ from django.contrib import admin, messages
 from django.contrib.admin import widgets
 from django.contrib.admin.options import csrf_protect_m
 from django.core.exceptions import PermissionDenied, ImproperlyConfigured
+from django.core.files.storage import DefaultStorage
 from django.forms import fields
 from django.http import HttpResponseRedirect
 from django.template.response import TemplateResponse
@@ -135,13 +136,13 @@ class ConstanceForm(forms.Form):
         self.initial['version'] = version_hash.hexdigest()
 
     def save(self):
+        storage_instance = DefaultStorage()
         for file_field in self.files:
-            file = self.cleaned_data[file_field]
-            file_path = os.path.join(django_settings.MEDIA_ROOT, file.name)
-            with open(file_path, 'wb+') as destination:
-                for chunk in file.chunks():
-                    destination.write(chunk)
-                self.cleaned_data[file_field] = file.name
+            uploaded_file = self.cleaned_data[file_field]
+            # TODO: max_length
+            actual_name = storage_instance.save(uploaded_file.name,
+                                                uploaded_file)
+            self.cleaned_data[file_field] = actual_name
 
         for name in settings.CONFIG:
             if getattr(config, name) != self.cleaned_data[name]:
```
...but the file can't be accessed in the admin interface, nor does the context processor provide a way to retrieve the media file's URL. Other issues:

* "Reset to default" doesn't work for images
* Images left unselected ("No file selected") cause an `IntegrityError`

Question: do we work on django-constance to fix these issues or create our own model for custom images? The latter would use more built-in Django machinery and probably take less time and effort.

**Comment by pmusaraj** [comment]
@jnm we could also consider storing the overrides as CSS (with image as base64).

**Comment by jnm** [comment]
Good point. The background image is fairly large, though, and its base64-encoded version is about 135% the size of the original (240955 to 325504 bytes). I'm going to try a quick Django model

**Comment by jnm** [comment]
reopening to fix for local storage
see also kobotoolbox/kobo-docker#175
