### ISSUE TITLE
Missing account-box__initials on first login

### ISSUE THREAD

**Issue by mroswell** [kobotoolbox/kpi#1740]
- I created a new account (selenium_test_2) because I can't seem to do a password reset on selenium_test2

- The first time I logged in, instead of getting a proper account-box initial (which should be "S" in the upper right-hand corner) It said:
```
#n/a
```
- Subsequent logins (and a refresh on the initial login) display the proper account-box initial.

**Comment by pmusaraj** [comment]
See #1512
