### ISSUE TITLE
Enter key and Edit Name/Description

### ISSUE THREAD

**Issue by mroswell** [kobotoolbox/kpi#1756]
1. For this name input at the top of the page: 
```
XPATH, "//input[@type='text' and @placeholder='Project title']"
```
It would be help to add an Enter key to save an edit. Currently, I think I needed a Tab key. Would be great to have both.

2. For this name input on the Settings page:
```
XPATH, //input[@type='text' and @placeholder='Enter title of project here']
```
It might be helpful to also add an Enter. For now it saves the form, which may also be a desired behavior(?)

3. For the description input on the Settings page, the Enter key starts a new line.
That's probably an appropriate behavior.

In essence, 
- on the Name input at the top of the form, Enter seems to do nothing. 
- On the Settings page in the Name input Enter submits the form. 
- On the Settings page in the Name input Enter starts a new line. 

Three different behaviors. I think the main ask here would be to change the behavior of item 1 above, and then potentially leave the other two as-is. (Another option for the Description is to have the Enter key do a Save, and expect that people won't use a newline in a Description (or accept a Shift-Enter as a new line.) In that case, all three would consistently save the new content via Enter.

**Comment by magicznyleszek** [comment]
We have plans (#1883 with PR in review) to remove name editing option from header, so it will be clearer in the future. The question is if we should make it clearer that description is multiline with ENTER key not submitting the settings form @pmusaraj ?

**Comment by pmusaraj** [comment]
How would we do this?

**Comment by magicznyleszek** [comment]
We can display the description in 2 rows initially, or add a hint "Press ENTER to add new lines"

**Comment by pmusaraj** [comment]
We could add a hint, but OTOH, the description is not all that useful to the user (most projects have no description), so the hint seems like an unnecessary addition to the form.

**Comment by magicznyleszek** [comment]
Let's leave it as it is now then 👍
