### ISSUE TITLE
openpyxl temporary files are not cleaned up

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1758]
...when an export reaches the Celery timeout (`Failed to run exporttask: SoftTimeLimitExceeded()`).

1. Problem form `amyzicTCyUGGWyDArYYPzf` on OCHA
2. It has 132,229 submissions and ~510 questions

        >>> v.asset.deployment.submission_count
        132229
        >>> v.asset.summary['row_count']
        510

3. All of their recent attempts to export have failed (their successful exports are not recent)

        >>> ExportTask.objects.filter(data__contains=v.asset.uid).count()
        32
        >>> ExportTask.objects.filter(data__contains=v.asset.uid).values('status').distinct().annotate(Count('pk'))
        [{'status': u'error', 'pk__count': 29}, {'status': u'complete', 'pk__count': 3}]
        >>> ExportTask.objects.filter(data__contains=v.asset.uid, status=ExportTask.COMPLETE).values('date_created')
        [{'date_created': datetime.datetime(2018, 4, 23, 16, 30, 54, 805981, tzinfo=<UTC>)}, {'date_created': datetime.datetime(2018, 4, 25, 15, 39, 49, 94052, tzinfo=<UTC>)}, {'date_created': datetime.datetime(2018, 4, 23, 10, 19, 35, 984742, tzinfo=<UTC>)}]

To help the users, we need to [raise the export time limit above 1800 seconds](https://github.com/kobotoolbox/kpi/issues/1757).
To help ourselves, we need to make sure temporary files are cleaned up when exports fail. Otherwise, we end up with all these `openpyxl` files that end up crippling the server:

    root@kpi:/tmp# ls -S1 | xargs du -hs
    2.3G    openpyxl.Mwtwpg
    2.2G    openpyxl.bNbUT6
    2.2G    openpyxl.EaUDr2
    2.2G    openpyxl.a4k4LU
    1.9G    openpyxl.lttwJs
    1.8G    openpyxl.OCyK6M
    1.5G    openpyxl.6iW02b
    1.2G    openpyxl.yZgDSg
    830M    openpyxl.mxdUZC
    36K    hsperfdata_root
    6.7M    npm-8-9fe0256a
    4.0K    celery.pid
    4.0K    celery_sync_kobocat_xforms.pid

See also:
* http://sentry.kbtdev.org/kobo/kpi/issues/8368/
* https://www.flowdock.com/app/kobotoolbox/support/threads/eJPgfbO57DWq_oda8m3TQM8Eq-d

**Comment by joshuaberetta** [comment]
Zulip chat: https://chat.kobotoolbox.org/#narrow/stream/5-KoBo-SysAdmin/topic/XLSX.20export.20fragments.20in.20KPI.20.2Ftmp/near/54535

**Comment by jnm** [comment]
Let's close this since we [don't use](https://github.com/kobotoolbox/formpack/issues/171) openpyxl anymore.
