### ISSUE TITLE
Make signup email and welcome message translatable

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1767]
As discussed on Monday's standup call, the "create account" screen is now translatable, so there are two things left to translate during the signup flow: 

- [x] the "welcome message", displayed in the right column of the registration screen
- [x] the activation email sent to users

**Comment by jnm** [comment]
@noliveleger, now that your #1796 is merged, can this be closed?

**Comment by noliveleger** [comment]
@jnm sure.
