### ISSUE TITLE
Upgrade Python package cryptography

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kpi#1798]
The version of [cryptography](https://pypi.org/project/cryptography/) that *kpi* installs is very old (`1.5.2`). This version doesn't compile in most up-to-date systems, see these tickets [cryptography#3605](https://github.com/pyca/cryptography/issues/3605) and [cryptography#3751](https://github.com/pyca/cryptography/issues/3751).

If you try to install the package inside the build process of a Docker image based on `python:2.7`, it already doesn't work.
It is very likely that those OS changes will end up in `phusion/baseimage` eventually, which will break the building of the KoBo Docker images.
*cryptography* should be upgraded to the latest version, which is `2.2.2`.

**Comment by jnm** [comment]
Thanks for reporting. In your commits, are you using `pip-compile` to upgrade `pyopenssl`?
