### ISSUE TITLE
Indicate that library asset has tags

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#1809]
Currently the only way of knowing if an asset has any tags is to open the edit mode:
<img width="740" alt="screen shot 2018-06-05 at 11 00 42" src="https://user-images.githubusercontent.com/2521888/40966271-564baa92-68b0-11e8-92f0-cebb3251fce6.png">

It would be nice to have an option to display some/all of them on hover or alternatively display a counter near tag icon:
<img width="806" alt="screen shot 2018-06-05 at 11 50 09" src="https://user-images.githubusercontent.com/2521888/40968771-a33228a8-68b6-11e8-93b2-75d324193cd4.png">
<img width="233" alt="screen shot 2018-06-05 at 11 04 19" src="https://user-images.githubusercontent.com/2521888/40966330-83f67a80-68b0-11e8-8012-d2a54edf22ea.png">

Also the `#tags +` instruction is confusing to me. First I tried typing `#foo #bar`, then `#foo + #bar`, then `#foo<ENTER>#bar` to finally understand that I don't need `#` character at all. Maybe we should write this instead: `Type tag name and press ENTER`.

**Comment by pmusaraj** [comment]
I would prefer not to overload the display of the library list by showing the tags, especially since the tags are a feature that few users use. 

I agree that we should change the `#tags +` copy to something else. Maybe simply: `add tag`
