### ISSUE TITLE
A user can choose a template when replacing an existing project

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1810]
When replacing a form, users currently can choose to replace from an XLSForm file (on their device or using a URL). 

User should also be able to replace the form with a template (provided there are templates on his/her account).

Note also that the label for the replace option is currently "Replace with XLS". I suggest we update it to simply "Replace".

**Comment by magicznyleszek** [comment]
Due to some issues this is waiting for #1889
