### ISSUE TITLE
Design screens with changes to the form builder header

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1815]
_Note: FB below means "form builder"._ 

Users should be able to edit the settings fields (description, sector, country and (probably) the share sector/country checkbox) for a form template. We don't currently have a way to edit settings like these in the library. 

One way to accomplish this would be to add a button in the FB's header (next to Layout etc.) that loads a modal window with the settings fields. While looking into this though, there are some other improvements we can make, I'll write up a list below, these are just ideas at this point: 

- as Leszek mentioned in a chat, it would be nice to be able to identify the type of the current asset being edited in the FB (form, question, block, template). The icon in the top left corner of the FB was supposed to communicate this, but I don't think an icon is good enough. We could display the type as text, maybe above the title field (or elsewhere). 
- if we add the type as text, the top-left icon becomes meaningless. We can replace it with the square KoBo icon.
- option 1: add a new button in the button bar for "Layout & Settings". This would load a modal window with the two or three tabs for each of those mini-forms
- option 2: reorganize the button bar more dramatically by: a) moving the "search library" button outside the horizontal bar, and showing it as a 50-60 pixel vertical column to the right of the form builder (i.e. as if the question library pane was moved off-screen), b) creating two separate buttons, (Layout and Settings), and aligning them to the right of that header bar (just below Save). I like this option, because it separates these mini-forms from the other buttons in the header bar, and doesn't force users to do extra clicks (like in the case of a modal window with tabs). I would maintain text labels with icons for these buttons, as
- there may be an option 3, where metadata is also mixed with the changes to layout and settings. The only downside to changing Metadata, though, is that currently it displays succinctly the selected metadata, and as a button in the header bar, I don't see how it could do that. 

Assigning this to @magicznyleszek but @jnm, @noliveleger, @emilykferguson, feedback is more than welcome.

**Comment by noliveleger** [comment]
I like option 2 better too.

Maybe out of scope but, if the header is reorganized, what about adding a placeholder to the `name` textbox. I know it's mandatory when user creates a `survey` but it's not for a `question`/`block`. I did create a `question` asset without a name 3 times in a row. I think a placeholder would have been a visual reminder to add a name.

**Comment by magicznyleszek** [comment]
First idea/WIP https://app.atomic.io/d/2cWd85IOBmFv

**Comment by magicznyleszek** [comment]
New idea: icons on left, Layout & Settings and Search Library on right that opens aside

+ Leave current idea in atomic

**Comment by magicznyleszek** [comment]
Three ideas:
* aside with just icons: https://app.atomic.io/d/2cWd85IOBmFv
* aside: https://app.atomic.io/d/MLfKFurORgLN
* sub nav: https://app.atomic.io/d/82NlfhccJyO7

**Comment by magicznyleszek** [comment]
@pmusaraj did you get any feedback on those designs?

**Comment by pmusaraj** [comment]
After internal discussions, we've decided to go with the sub nav option. Please implement @magicznyleszek (I am marking this ticket as done)
