### ISSUE TITLE
Redesign Create New Form modal steps

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#1816]
Due to some issues with applying the template to already created project we need to rethink current modal flow.

Design "Create New Form" modal steps:

* First: Choose source first:
  * "Start from Scratch" (current "Design in Form Builder")
  * "Use a template"
  * "Upload an XLSForm"
  * "Import an XLSForm via URL"
* Further (depending on source):
  * "Start from Scratch"
    * "Define Project"
    * open Form Builder
  * "Use a template"
    * template selector
    * "Define Project" (data filled up)
    * open Project Landing
  * "Upload an XLSForm"
    * file selector
    * "Define Project" (data filled up)
    * open Project Landing
  * "Import an XLSForm via URL"
    * url importer
    * "Define Project" (data filled up)
    * open Project Landing
    
During the step `"Define Project" (data filled up)"` the button could be ~"SKIP"/"APPROVE"~ "Continue" and when user edits some filled up inputs it changes to ~"SAVE & GO"~ "Save & Continue"?

**Comment by pmusaraj** [comment]
Looks great. Instead of "SKIP/APPROVE", I would go with "Continue" for the default state of the button. And then "Save & Go", or "Save & Continue" if user makes changes.

**Comment by magicznyleszek** [comment]
First attempt: https://app.atomic.io/d/ZuDenTFzD11N

**Comment by magicznyleszek** [comment]
Drop the "SAVE & CONTINUE".

Updates from @jnm:

* Screens 1, 7, 10, 16
  * "Use a Template" -> "Use a template"
  * "You will be prompted to fill up..." -> "You will be prompted to enter..."
* Screens 2, 3, 4
  * "In case of troubles, read our Help Center article." -> "Please read our support article if you have trouble."
* Screens 5, 6, 8, 9, 14, 15, 19, 20
  * "Your project was crated. Review project details below and finish up." -> "Please review the details below to finish creating your project." [I know the asset has technically been created already on the BE, but I think it's fine to gloss over that for clarity.]
* Screen 17, 18
  * "adjust the details in next step" -> "adjust the name and other details in the next step" Maybe restating the bit about adjusting details is unnecessary at this point? I noticed the second step of the XLSForm URL sequence doesn't mention it.
* Screens 11, 12, 13: we should display template owner

**Comment by magicznyleszek** [comment]
Second iteration: https://app.atomic.io/d/ZuDenTFzD11N (same link, yes 😛)

**Comment by magicznyleszek** [comment]
Design accepted with these comments:

* don't change color for the icons from the current one
* in existing screens let's keep the same text
* to be consistent with the current library, a user's own templates should show me instead of You as the owner. Also, the owner column should show the username instead of first name

**Comment by magicznyleszek** [comment]
@pmusaraj do you think we can close this one? Design was done and already implemented on #1813

**Comment by pmusaraj** [comment]
Sure, closing.
