### ISSUE TITLE
Map doesn't load, timeout

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1825]
Reproduced with https://kf.kobotoolbox.org/#/forms/aKUUmL9SRz4Y56XKALPnbJ/data/map

Taking the liberty to mark as high priority since it may affect other large projects, feel free to remove if not accurate.

![image](https://user-images.githubusercontent.com/673511/41446054-6a929ade-701b-11e8-9fba-25864a545770.png)

**Comment by tinok** [comment]
Can't reproduce this with an [even larger survey](https://kf.kobotoolbox.org/#/forms/aWTqGEucEDTvRkguARfydo/data/map) with 8000 submissions, so unlikely it's the number of points.

**Comment by pmusaraj** [comment]
This is a backend issue, for some reason the request for submissions times out: https://kf.kobotoolbox.org/assets/aKUUmL9SRz4Y56XKALPnbJ/submissions?limit=5000&start=0&sort={%22_id%22:-1}&fields=[%22_id%22,%22_geolocation%22] 

@jnm I'm moving this to your to-do list.

**Comment by tinok** [comment]
@jnm Looks like this can be closed, I'm able to open this map again without any errors.
