### ISSUE TITLE
Autonames in latest KPI deployed version do not match KC XML

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1831]
Possibly related: https://github.com/kobotoolbox/kpi/issues/1625

1. Create a new form using the form builder;
1. Add a single integer question with label `رقم التسجيل`;
    * Important: use a label with no ASCII characters.
1. Deploy the form;
1. Go to `/assets/[new form uid]/versions`;
1. There should be two versions, with only one being deployed (see `date_deployed`). Click on the URL of the deployed version;
1. Look at `$autoname` for the integer question. In my case, it's `integer_nx3de17`;
1. Go to `https://kc/formList` and get the `downloadUrl` for your form (e.g. `https://kc.kobotoolbox.org/jnm_demo/forms/187491/form.xml`);
1. Find the XML element name for the integer question. In my case it's `integer_300566de`;
1. Note how the KC XML element name does not match the KPI deployed version's `$autoname`.

The table view falls back to showing the data with its XML name:
![image](https://user-images.githubusercontent.com/2085013/41628529-f3f50340-73f2-11e8-98de-ce99ef7785a6.png)

XLS exports, however, show a labeled but blank column:
![image](https://user-images.githubusercontent.com/2085013/41628508-db0dd8c0-73f2-11e8-91b6-6ce416b070de.png)

Switching the XLS export to use XML names instead of labels reveals the mismatched KPI autoname:
![image](https://user-images.githubusercontent.com/2085013/41628577-3a112728-73f3-11e8-87f2-cea0ad475bd1.png)

**Comment by jnm** [comment]
Example KPI `AssetVersion` JSON for an afflicted question:
```json
    {
        "$autoname": "integer_nx3de17",
        "$kuid": "300566de",
        "required": false,
        "type": "integer",
        "label": [
            "رقم التسجيل"
        ]
    }
```
KPI somehow arrives at `"$autoname": "integer_nx3de17"` while simultaneously having `"$kuid": "300566de"`; then, in KC, the question ends up being named `integer_300566d` (i.e. `${questiontype}_${kuid}`).

**Comment by jnm** [comment]
Sent by form builder to backend:
```json
{
  "settings": [
    {}
  ], 
  "survey": [
    {
      "$kuid": "xx9hd09", 
      "label": "\u0631\u0642\u0645+\u0627\u0644\u062a\u0633\u062c\u064a\u0644", 
      "required": "false", 
      "type": "integer"
    }, 
    {
      "name": "start", 
      "type": "start"
    }, 
    {
      "name": "end", 
      "type": "end"
    }
  ], 
  "translations": [
    null
  ]
}
```

Stored in `Asset.content`—the `$kuid` from the form builder is moved into `$autoname` and a new `$kuid` is generated:
```json
{
  "schema": "1", 
  "settings": {}, 
  "survey": [
    {
      "$autoname": "start", 
      "$kuid": "27193d0d", 
      "name": "start", 
      "type": "start"
    }, 
    {
      "$autoname": "end", 
      "$kuid": "041dd561", 
      "name": "end", 
      "type": "end"
    }, 
    {
      "$autoname": "integer_xx9hd09", 
      "$kuid": "216e4499", 
      "label": [
        "\u0631\u0642\u0645 \u0627\u0644\u062a\u0633\u062c\u064a\u0644"
      ], 
      "required": false, 
      "type": "integer"
    }
  ], 
  "translated": [
    "label"
  ], 
  "translations": [
    null
  ]
}
```

Returned by `XlsExportable.ordered_xlsform_content()`—the previous `$autoname` is discarded and a new `name` is created from the question type and the second `$kuid`; this content is _not_ saved anywhere in KPI:
```json
{
  "settings": [
    {
      "form_title": "nuh noh autoname", 
      "id_string": "aMdpGvoLSp4yHW6C5nLWFe", 
      "version": "vT4Ek7z2UFUwPTko3fek8L"
    }
  ], 
  "survey": [
    {
      "calculation": null, 
      "label": null, 
      "name": "start", 
      "required": null, 
      "type": "start"
    }, 
    {
      "calculation": null, 
      "label": null, 
      "name": "end", 
      "required": null, 
      "type": "end"
    }, 
    {
      "calculation": null, 
      "label": "\u0631\u0642\u0645 \u0627\u0644\u062a\u0633\u062c\u064a\u0644", 
      "name": "integer_216e4499", 
      "required": "false", 
      "type": "integer"
    }, 
    {
      "calculation": "'vT4Ek7z2UFUwPTko3fek8L'", 
      "label": null, 
      "name": "__version__", 
      "required": null, 
      "type": "calculate"
    }
  ]
}
```

**Comment by jnm** [comment]
`Asset._unlink_list_items()` taketh away the original `$kuid`, and `_populate_report_styles()` giveth again:
https://github.com/kobotoolbox/kpi/blob/ae11892d5a6594f48bf2c10a93359bc8091f58b2/kpi/models/asset.py#L565-L572
https://github.com/kobotoolbox/kpi/blob/ae11892d5a6594f48bf2c10a93359bc8091f58b2/kpi/models/asset.py#L531-L543
https://github.com/kobotoolbox/kpi/blob/ae11892d5a6594f48bf2c10a93359bc8091f58b2/kpi/models/asset.py#L204-L208
Back in `Asset.save()`:
https://github.com/kobotoolbox/kpi/blob/ae11892d5a6594f48bf2c10a93359bc8091f58b2/kpi/models/asset.py#L585
https://github.com/kobotoolbox/kpi/blob/ae11892d5a6594f48bf2c10a93359bc8091f58b2/kpi/models/asset.py#L635-L644

**Comment by jnm** [comment]
Probably related: https://github.com/kobotoolbox/kpi/issues/1833

**Comment by dorey** [comment]
Yep. You called it, @jnm. This was a big booboo and prevented `$kuid` s from being useful.

**Comment by dorey** [comment]
Fixed in branch: [issue-1833](https://github.com/kobotoolbox/kpi/tree/issue-1833)

**Comment by jnm** [comment]
Thanks @dorey! Could you PR this soon? Also, I wonder if the slumbering beast `sync_kobocat_xforms` can bring KPI's stored autonames in line with what's actually deployed to KC? I'll try it on some individual users who have submitted support requests.

**Comment by jnm** [comment]
Fixed by https://github.com/kobotoolbox/kpi/pull/1840
