### ISSUE TITLE
Deleted records are not removed from the data table view

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#1834]
Deleted records do not actually delete, yet cannot be opened again/edited/etc. 

To replicate:

1. Delete a record
2. Refresh browser
3. See the record still there
4. Try to open it (should show an indefinite loading button)

**Comment by pmusaraj** [comment]
Oh, this has actually been resolved already, but hasn't been deployed yet. Fixed in https://github.com/kobotoolbox/kpi/pull/1788
