### ISSUE TITLE
All alertify notifications look the same

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#1835]
There are 4 kinds of notifications:

```
.ajs-message
.ajs-message.ajs-error
.ajs-message.ajs-success
.ajs-message.ajs-warning
```

We override default styles (`jsapp/scss/libs/alertify.scss`) in `jsapp/scss/components/_kobo.alertify-overrides.scss`

**Comment by magicznyleszek** [comment]
We could add some icon for error, success and warning?

**Comment by pmusaraj** [comment]
I would opt for a color, maybe a colored bottom or top border for each type (red for error, orange for warning, green for success) without an icon. Just a personal preference, though.
