### ISSUE TITLE
Include record validation statuses in exports

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1851]
Given this validation status entry:
```json
"_validation_status": {
  "by_whom": "jnm",
  "timestamp": 1531168578,
  "uid": "validation_status_not_approved",
  "color": "#ff0000",
  "label": "Not Approved"
},
```
An export should include a `_validation_status` column: if labels are selected, the cell should include `Not Approved`; if "XML headers and values" are chosen, the cell should include `validation_status_not_approved`.

**Comment by noliveleger** [comment]
To be used with FormPack issue: L https://github.com/kobotoolbox/formpack/pull/179
