### ISSUE TITLE
Geojson in API output

### ISSUE THREAD

**Issue by Svensl** [kobotoolbox/kpi#1853]
The API currently allows for jsons but not geojsons. With GIS being more and more used to visualize data collected through kobo, it would be great if we could also have a geojson format for better integration into automatic GIS workflows. Is it something that is planned or could possibly be coded?

Ideally for my current uses, the specifications would look something like this:

-no more than one level per attribute in "properties" (allowed by the spec of GeoJSON but difficult to work with for an integration in PostgreSQL) -> each question should be a key/value pair in the first level of "properties"
- should pass those tests: http://geojsonlint.com/ & ogrinfo <name of GeoJSON>
- should be usable in a GIS (e.g. QGIS)

Example of what would be really helpful for me (one level per attribute):

{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Mr. X",
    "number": 127,
    "url": "https://media.wired.com/photos/5a970eb4927dc94e67685b0e/master/pass/matterhorn-802950172.jpg"
  }
}

Example of what to avoid (multiple levels per attribute):

{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Mr. X",
    "number": {
      "year": {
        "2000": ["a", "b", "c"],
        "2001": ["a", "b", "d"]
      }
    },
    "url": "https://media.wired.com/photos/5a970eb4927dc94e67685b0e/master/pass/matterhorn-802950172.jpg"
  }
}

Thanks for all the great work in any way! Kobo collect is en extremely useful and efficient tool.

**Comment by jnm** [comment]
https://github.com/kobotoolbox/enketo-express/issues/1059

**Comment by jnm** [comment]
Hi @Svensl, I think this is a great idea. Were you speaking with @maskoamas earlier? It'd be great if this could be funded through OCHA.

**Comment by Svensl** [comment]
Hi @jnm. Thanks for your answer and support with the idea. I was indeed speaking to @maskoamas earlier last month but we didn't talk about funding. My hope was that this wouldn't require too much coding (as the regular json format is already in the API) and thus could be done without additional funding? Please let me know if that could be the case or if I should contact Anwar again and see if and where we could find funding for this.

**Comment by jnm** [comment]
Closed per #2218
