### ISSUE TITLE
Public collections contain no questions

### ISSUE THREAD

**Issue by joeflack4** [kobotoolbox/kpi#1860]
## Description
When selecting any of the "public collections" listed in the question library, rather than displaying a list of questions, the message "Your search returned no results." is instead displayed. Even after subscribing to the list, the result is the same.

## Screenshots
1. Public collection, before subscribing
![1](https://user-images.githubusercontent.com/13045020/42516130-626332dc-842b-11e8-9710-d77f60554eef.png)

2. Subscribed public collection
![2](https://user-images.githubusercontent.com/13045020/42516137-649a991e-842b-11e8-8d71-d343671a34c2.png)

**Comment by tinok** [comment]
I can reproduce this issue. @pmusaraj

**Comment by jnm** [comment]
Fixed by #2559
