### ISSUE TITLE
Feature request - Add block or group of questions from form editor

### ISSUE THREAD

**Issue by joeflack4** [kobotoolbox/kpi#1861]
## Description
Feature request to make it possible to do one or more of the following in the form editor:
- Select more than question at a time and be able to add them all as a single block with a single click.
- Add a single question group as a question block. Currently, question groups do not have this option, as indicated in the screenshots below.

## Screenshots
1. Individual questions have option to add to library
![question options](https://user-images.githubusercontent.com/13045020/42517590-0e3dfb26-842e-11e8-958a-a3a420915bcd.png)

2. Question groups do not have option to add to library
![question group options](https://user-images.githubusercontent.com/13045020/42517594-10c57c84-842e-11e8-8f47-a21ba5bf0f05.png)

**Comment by magicznyleszek** [comment]
**Until this is done:**

If anyone really needs to clone a block that is too huge to be manually re-created, I would personally go with this approach:
1. Clone your template or form (either use "Clone" button in Library or "Create template" in Projects List)
2. Open the clone's Landing Page
3. Change the url from `http://kf.kobo.local/#/library/asset/<uid>` to `http://kf.kobo.local/api/v2/assets/<uid>/` (note the "assets" is plural)
4. Scroll all the way down and in the text editor change `"asset_type": "template",` to `"asset_type": "block",`
5. Click "PATCH" button
6. Go back to KPI interface and open clone in Form Builder
7. Delete everything that is not the block you wanted to save

**Comment by joshuaberetta** [comment]
Closing in favour of #3363

**Comment by magicznyleszek** [comment]
@joshuaberetta #3363 is a PR that closes this issue :P

**Comment by joeflack4** [comment]
I'm not working in the ODK (Open Data Kit) space. Now I'm working in the ODK (Ontology Development Kit) space =P.

But very glad to see this feature made it!

**Comment by joeflack4** [comment]
Wow, I remember opening this ages ago. Thanks guys!
