### ISSUE TITLE
Feature request - syncing changes between updated library questions and the forms or other question blocks where they are included

### ISSUE THREAD

**Issue by joeflack4** [kobotoolbox/kpi#1862]
## Description
This is a feature request for synchronizability of library questions and question blocks. It would be nice to have this _option_ for when questions or question blocks are imported into a form or other question blocks.

Perhaps it might be best to have synchronizability off by default, but that there should be a checkbox to add it after adding (dragging and dropping) it into a form or other question block.

## Example workflow
1. I create a question with label "my question" in the question library.
2. I create a new form.
3. I import "my question" from library by dragging and dropping it.
4. Before making any changes to "my question", I select open up additional question options / settings by clicking the "cog" icon.
5. If I still haven't made any changes to "my question", there is a checkbox with the label "sync updates from library".
6a. If I **do** make any changes to the question after importing into the form...
  - The "sync updates from library" checkbox becomes greyed out. If the user hovers over it, it displays the tooltip "Questions that have been changed before syncing can no longer be synced. To sync this question, please add it again and select this checkbox."
6b. If I **don't** make any changes to the question after importing into the form...
  - I can click the checkbox.
  - Then, if I change the original question, e.g. by changing the text from "my question" to --> "my new question" and save it,
  - And then, if I go back to the form I was editing and refresh the page, I the question label will appear as "my new question".

**Comment by joshuaberetta** [comment]
Moved to: https://www.notion.so/kobotoolbox/Synced-library-assets-with-form-question-blocks-f73118d13e8642ed96bf70207e53c5ea
