### ISSUE TITLE
URL encoding of query string values in attachment URLS

### ISSUE THREAD

**Issue by ggalmazor** [kobotoolbox/kpi#1863]
Hi, ODK Briefcase maintainer here.

I've run a quick search for this issue and, since I haven't found anything similar, I've decided to file an issue, just in case. Feel free to dismiss :)

We've received error reports from Briefcase users trying to pull forms from Kobo. 

We've investigated the issue and it turns out that it might have to do with the filenames of submission media attachments that go in the download URLs as query string parameters. Those filenames are not URL encoded and break when the filenames have, for example, a space character. Example of one of the URLs that have produced an error:

`https://server.com/attachment/original?media_file=formId/attachments/someHash/someUUID/2018-07-10 09.50.50-9_51_0.jpg`
(I've redacted sensible information in the URL)

As you can see, the `media_file` query string argument has a value that ends with a filename that contains a space. This value could be URL encoded to avoid having to do so client-side.

**Comment by tinok** [comment]
Closing this, appears to be fixed by https://github.com/kobotoolbox/kobocat/pull/506.
