### ISSUE TITLE
Form templates UI issues

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1865]
Some issues I ran into while doing a first look at the `form-template-frontend` branch for PR #1813.
 
In Library

- [x] cannot create a template, screen is blank with several console errors when clicking on New > Template

In Projects list, after clicking on New

- [x] In the first screen of the new project modal, the title should be "Create project: Choose a source" (instead of "Create project: Form source")
- [x] when uploading an XLS, the spinning icon is too large, and too close to text below it. 
- [x] in the "Project Details" screen, can we arrange for the dropdowns for Sector/Country to avoid triggering the scrollbars? (maybe some vertical padding before and after the submit button would do the trick)
- [x] when choosing "Build from scratch", in the "Project Details" screen, the text "In the next step, you can import an XLSForm (via upload or URL) or design the form from scratch in the Form Builder." no longer applies, so it should be removed
- [x] ~~(to be discussed) if there are no templates available, the "Use a template" option shouldn't be displayed (it's a dead end, and it likely confuses users)~~

**Comment by magicznyleszek** [comment]
I checked all fixed things (pushed to the `form-template-frontend` branch)

As for hiding option if no templates - I wouldn't consider it dead end per se, as we give user information what he can do to use this option. And hiding it could be confusing for some users. We could instead disable the button on first screen and show tooltip, but this means making a BE call to check for templates

**Comment by pmusaraj** [comment]
Ok, let's leave the form templates button as is for now. In any case, we will soon have curated templates, which means that there will always be available templates to choose from.
