### ISSUE TITLE
Integrate SMS submissions from Collect

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1876]
SMS submissions are now possible from Collect. KC should be able to receive the submissions (from a third party service) and include them as regular submissions. These submissions should be marked in the DB as being submitted_by SMS (this field already exists in the KC database).

See https://github.com/opendatakit/collect/pull/2163

**Comment by joshuaberetta** [comment]
Moved to: https://www.notion.so/kobotoolbox/SMS-submissions-to-Collect-fe829cc7c78241e9aad8a2b94655bac9
