### ISSUE TITLE
Using PATCH with clone_from should allow passing settings

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#1892]

**Comment by jnm** [comment]
looks like the request settings are being merged into the destination settings _before_ the destination settings are replaced with the source settings:
https://github.com/kobotoolbox/kpi/pull/1806/files?utf8=%E2%9C%93&diff=unified#diff-7efb57e207546d622f02cddb15ffa899R897
https://github.com/kobotoolbox/kpi/pull/1806/files?utf8=%E2%9C%93&diff=unified#diff-7efb57e207546d622f02cddb15ffa899R917
