### ISSUE TITLE
Allow table filtering by uuid (and other meta fields)

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#1918]
Table filtering is not possible yet by `_uuid` and other meta columns. It would be great if these columns could be filtered as well (`username, deviceid, __version__, today, _id, _submission_time`).

For doing quality control, a survey admin may identify a particular case through one of these meta fields and then wants to filter for it, or come back to a known case, etc. 

These filters should just be text fields like in regular `text` questions.

**Comment by magicznyleszek** [comment]
@tinok let me clarify - you would like to have same option for filtering in all columns as in "Pizza?" column in this example?:
<img width="793" alt="screen shot 2018-08-16 at 06 56 22" src="https://user-images.githubusercontent.com/2521888/44189072-a0e2a200-a121-11e8-9b32-92befc792785.png">

**Comment by tinok** [comment]
@magicznyleszek Yes. A text filter option for these fields would suffice.
