### ISSUE TITLE
Enhancement: pass more backend error messages to user

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#1926]
## Description

Frontend is displaying error notification for all backend failed requests. Sometimes we use error message provided by backend, but mostly we ignore it and display some general error message.

Frontend also has a facade for calling backend: `actions.es6` (plus we also call directly, but this should be changed into actions), so we could handle displaying errors there for each action.

## Additional details

Sometimes error message is in `response.responseJSON.detail`, sometimes in `response.messages.error`, and sometimes response is plain html code - we need to be prepared for handling that.

Best wait for most of: #1913 #1896 #1889 #1885 #1864 to be merged, as there are big changes or actions-related there.

**Comment by jnm** [comment]
@magicznyleszek, have you seen where this stuff comes from? I don't think the backend creates anything called `responseJSON`, and `response.messages.error` I'd think implies that `response` is parsed JSON—but maybe not!

Plain HTML errors are probably unavoidable and will appear for a host of HTTP 50x server-side problems. When the Django app is still alive enough to return an error message of its choosing, though, it would be nice to use standardized JSON, probably following http://www.django-rest-framework.org/api-guide/exceptions/.

**Comment by magicznyleszek** [comment]
@jnm PATCHing `/assets/${uid}/hooks/${hookUid}/retry/` returns `response.responseJSON.detail`, but maybe it also has `response.messages.error` - will need to check

**Comment by noliveleger** [comment]
@magicznyleszek:
Django Rest Framework returns JSON message like this
```
{
"detail": "lorem ipsum"
}
```

I'm used to use this kind of message.

```
{
"message": "lorem ipsum"
}
```
but I changed it everywhere I found it to use `detail` instead to be more DRF compliant. All responses (we control) are JSON.
So ajax calls in JS should retrieve errors in response.responseJSON.detail. I don't know from where `response.messages.error` comes from.

**Comment by magicznyleszek** [comment]
Ok, I don't know where I took `.messages.error`, as I can't find it in the code now -_-. I will move already existing errors to `actions.es6` and will try pluck some additional backend error or go with general one :) Thanks!

**Comment by magicznyleszek** [comment]
Most of the referenced PRs/issues in **Additional details** from description touched error handling a bit, so besides #1962 nothing spectacular to do here. If someone stumbles upon some particular weird error, please make a separate issue :heart:
