### ISSUE TITLE
Data inside of nested groups are not displayed when viewing data submission

### ISSUE THREAD

**Issue by prashantsh** [kobotoolbox/kpi#1931]
## Description
When you have a form which has a group inside of another group, the submitted data is not shown in the data submission detail view.

## Steps to Reproduce

1. Create a form which has a group inside a group and add some questions to it.
2. Submit some data
3. Goto table view of data and click on open link.
4. The submission view page shows the Group title but not the questions inside of the group

## Expected behavior 
The table should show all the questions and it's respective answer even when it is under nested groups.

## Actual behavior 
Only questions inside of the parent group (My Group) is displayed but the questions inside of child group (Contact) is not shown.
![screen shot 2018-08-15 at 11 38 42 am](https://user-images.githubusercontent.com/3199381/44133507-d24c140e-a07f-11e8-84d5-0c1234b81537.png)

In the above screenshot there are two questions inside of Contact group but it is not displayed. See the edited form below.
![screen shot 2018-08-15 at 11 40 15 am](https://user-images.githubusercontent.com/3199381/44133554-0a0b243e-a080-11e8-992d-2d6915d9f8ca.png)

## Additional details

I tried this on the kobotoolbox.org site.

**Comment by magicznyleszek** [comment]
@prashantsh good catch! Turned out it was a small thing :bug: Fix will be there after one of the nearest deploys (it needs to go through review and testing first).

**Comment by prashantsh** [comment]
@magicznyleszek thanks. I have a form with many nested groups and this bug was a big issue for me. Thank you for much for looking into it. I look forward to testing the fix.
