### ISSUE TITLE
Error creating row: [Error: Syntax error, unrecognized expression: .on-row-detail-change-label::<language>]

### ISSUE THREAD

**Issue by joeflack4** [kobotoolbox/kpi#1948]
# Scenario 1 - When creating a duplicate question
## Description
When trying to use the "create duplicate question" feature in the form editor, rather than a duplicate being created, I receive the following error:

`Error creating row: [Error: Syntax error, unrecognized expression: .on-row-detail-change-label::<language>]`

## Steps to Reproduce
1. Log in to KoBo Toolbox and go to the [projects module](https://kf.kobotoolbox.org/#/forms).
2. Upload the `.xls` file enclosed in the "source file"  zip in _attachments_ at the bottom of this issue.
3. Navigate to a question, for example, to the one with text that starts with "Provide your signature to acknowledge...".
4. Click the blue icon to attempt to create a duplicate question.

## Expected behavior 
A duplicate question is created when the "create duplicate question" icon is clicked in the form editor.

## Actual behavior 
Error received: `Error creating row: [Error: Syntax error, unrecognized expression: .on-row-detail-change-label::<language>]`

**Screenshot 1**  
![create-duplicate-bug 01](https://user-images.githubusercontent.com/13045020/44272154-0ad67680-a20a-11e8-834f-ebfb8a3eecb4.png)

**Screenshot 2**  
![create-duplicate-bug 02](https://user-images.githubusercontent.com/13045020/44272155-0ad67680-a20a-11e8-9820-53ecf03c4918.png)

**Screenshot 3**  
![create-duplicate-bug 03](https://user-images.githubusercontent.com/13045020/44272156-0ad67680-a20a-11e8-9f44-f873d709ebdf.png)

**Screenshot 4**  
![create-duplicate-bug 04](https://user-images.githubusercontent.com/13045020/44272157-0ad67680-a20a-11e8-826a-afc8bbda8c23.png)

# Scenario 2 - 
## Description

`Error creating row: [Error: Syntax error, unrecognized expression: .on-row-detail-change-label::<language>]`

## Steps to Reproduce
1. Log in to KoBo Toolbox and go to the [projects module](https://kf.kobotoolbox.org/#/forms).
2. Upload the `.xls` file enclosed in the "source form"  zip in _attachments_ at the bottom of this issue.
3. Navigate to the [question library](https://kf.kobotoolbox.org/#/library).
4. Upload the question block as shown in the attachment "source question block" at the bottom of this issue.
3. Go to the projects module and edit the recently uploaded form.
4. Try to import the newly added question block.

## Expected behavior 
Question block is added.

## Actual behavior 
1. Error received: `Error creating row: [Error: Syntax error, unrecognized expression: .on-row-detail-change-label::<language>]`
2. A non-manipulatable placeholder question block component is visible and just says "importing..." indefinitely.

**Screenshot 1**  
![error import](https://user-images.githubusercontent.com/13045020/44481844-e406ae80-a614-11e8-8b29-ba1f406c85b1.png)

**Screenshot 2**  
![error import 2](https://user-images.githubusercontent.com/13045020/44481850-e8cb6280-a614-11e8-9adb-14fa05351572.png)

---

**Attachments**
1. Source form: [female-questionnaire section-0.zip](https://github.com/kobotoolbox/kpi/files/2297644/female-questionnaire.section-0.zip)
2. Source question block: 
[phone-followup question block.zip](https://github.com/kobotoolbox/kpi/files/2311490/phone-followup.question.block.zip)

**Comment by joeflack4** [comment]
Updated with another separate scenario where this issue is encountered.

**Comment by magicznyleszek** [comment]
We have a new translations UI feature that is being reviewed right now - it will fix this problem :)

**Comment by joeflack4** [comment]
Excellent. Hope so!
