### ISSUE TITLE
Access denied shouldn't display title or submissions count

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#1953]
## Description

We shouldn't display any data about the form - please verify that title and submissions count is only one left.

<img width="1018" alt="screen shot 2018-08-20 at 16 35 14" src="https://user-images.githubusercontent.com/2521888/44353006-180f9180-a4a6-11e8-9e7f-af0aaf2effab.png">
<img width="777" alt="screen shot 2018-08-20 at 16 56 51" src="https://user-images.githubusercontent.com/2521888/44353008-18a82800-a4a6-11e8-81ba-5737587e105b.png">

## Steps to Reproduce

1. Open form that you don't have access rights to
2. Look at the title and submissions count

## Expected behavior 

We should not display title (empty header?) and submissions count.

## Additional details

It could be a good idea to work on route level here and just don't allow visiting forbidden routes?

**Comment by JacquelineMorrissette** [comment]
No longer reproducable so I'm closing the issue
