### ISSUE TITLE
Allow pushing a subset of fields to remote REST server

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#1965]
- [x] JSON
- [x] XML :grimacing: 

FE will pass an array of strings, the question names, to BE. BE will send only responses for questions whose names exactly match elements in that array.

**Comment by noliveleger** [comment]
fieldname should match one of these criteria  for `json` keys:

- ^question_name$ (exact match)
- ^question_name/ (parent group)
- /question_name/ (child group)
- /question_name$ (question inside group)

for `xml` nodes, keep every node (and its children) that matches the fieldname. Even if the node is nested.

If user specifies a name with a `/`, it will be considered as a perfect match with a group_name.
**JSON:**
```
{
  "group_name/question_name": "value",
  "group_name/question_name2": "value",
  "group_name_with_nested/group_name/question_name": "value", 
}
```
Only the first key `group_name/question_name` will be kept.
_Results:_
```
{
  "group_name/question_name": "value",
}
```

**XML:**
```
<root>
    <group_name>
        <question/>
        <question2/>
    </group_name>
    <group_name_with_nested>
        <group_name>
            <question/>
        </group_name>
    </group_name_with_nested>
</root>
```

Only the first node will be kept
_Results:_
```
<root>
    <group_name>
        <question/>
    </group_name>
</root>
```

Remove all others. None of the fields are mandory. User will have to specify each field he wants to send to remove REST server.
