### ISSUE TITLE
Endpoint for deleting multiple submissions

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#1970]
## Description

Probably a call to `${rootUrl}/assets/${uid}/submissions/` with either passing submission ids in array or a flag about deleting all submissions. We need delete all, because UI allows for selecting all submissions from all paginated pages - similarly to bulk updating approved/not approved status

**Comment by jnm** [comment]
@noliveleger, all of the above branches have been merged :)

**Comment by magicznyleszek** [comment]
@noliveleger @jnm any plans to do it soon? :)

**Comment by noliveleger** [comment]
@magicznyleszek As soon as the #2222 is merged.

**Comment by magicznyleszek** [comment]
So it is blocked after all 😛

**Comment by jnm** [comment]
Not anymore :wink:
