### ISSUE TITLE
Remove default geopoint hint

### ISSUE THREAD

**Issue by tiritea** [kobotoolbox/kpi#1971]
## Description

Remove the default hint that is always added for any geopoint question.

## Steps to Reproduce

1. …add geopoint question to form but dont add any hint
2. …preview form in Enketo
3. …

## Expected behavior 

no hint 

## Actual behavior 

see default hint "GPS coordinates can only be collected when outside."

## Additional details

displaying a default hint is not appropriate, and indeed this particular hint is not even correct! (it is quite easy to to get a GPS fix inside a house)

**Comment by tiritea** [comment]
I beleive this is probably being inserted by pyxform. see https://github.com/XLSForm/pyxform/issues/241

If/when fixed in pyxform it will require pulling in updated version with fix into kobo to address.

**Comment by joshuaberetta** [comment]
Seems to have been solved with the pyxform upgrade 👍
