### ISSUE TITLE
Add support for ODK Collect range widget

### ISSUE THREAD

**Issue by joeflack4** [kobotoolbox/kpi#1982]
## Description
The ["range" widget](https://docs.opendatakit.org/form-question-types/#range-widgets) (aka "slider" aka "likert scale") was added to ODK Collect in [v1.8 on Jul 27, 2017](https://github.com/opendatakit/collect/releases/tag/v1.8.0). For compatibility with ODK Collect, it would be great for KoBo Toolbox to support this widget.

---

The widget
![screen shot 2018-08-30 at 12 18 19 pm](https://user-images.githubusercontent.com/13045020/44864910-cbb71500-ac4e-11e8-88ac-8d42e7ed40a9.png)

Error message
![screen shot 2018-08-23 at 12 19 44 pm](https://user-images.githubusercontent.com/13045020/44864828-9f02fd80-ac4e-11e8-88c1-ace8c4932bb8.png)

**Comment by jnm** [comment]
Should be fixed by https://github.com/kobotoolbox/kpi/issues/2000

**Comment by joeflack4** [comment]
@jnm Awesome! Looking forward to that.

**Comment by jnm** [comment]
At last! This is deployed to kf.kobotoolbox.org. It's now possible to upload XLSForm with `range` questions. However, there's not yet any support for these in the form builder. That will be added according to https://github.com/kobotoolbox/kpi/issues/2051

**Comment by joeflack4** [comment]
@jnm Epic. That progress makes me happy though :)

How often do you guys deploy updates? As long as CI passes?
