### ISSUE TITLE
Question block not displaying fully in form editor

### ISSUE THREAD

**Issue by joeflack4** [kobotoolbox/kpi#1984]
## Description
There are some instances where question blocks do not appear fully in the form editor after being uploaded; not all questions/prompts appear.

## Steps to Reproduce
1. Upload the attached question block to the library.

2. Open the question block.
![question block not showing fully in form editor 1](https://user-images.githubusercontent.com/13045020/44867266-5bf85880-ac55-11e8-80a0-80d008076b8f.png)

3. Observe
![question block not showing fully in form editor 2](https://user-images.githubusercontent.com/13045020/44867267-5bf85880-ac55-11e8-88d8-ac9ffdc7f64e.png)

## Expected behavior 
When opening a question block in the form editor, all questions/prompts should appear.

## Actual behavior 
In some instances, not all questions/prompts in a question block appear in the form editor.

## Additional details
I believe it may be possible that what is causing this issue is the fact that the question block contains skip logic which contains references to elements which do not appear within the question block itself; external dependencies. For example, when loading in the form preview (Enketo), the following error message is (naturally) displayed:

> **`Error generating preview`**
> `There has been a problem trying to replace`${SOME VARIABLE}` with the XPath to the survey element named 'SOME VARIABLE'. There is no survey element with this name.
![question block not showing fully in form editor 3](https://user-images.githubusercontent.com/13045020/44867141-0623b080-ac55-11e8-943f-3185e39afe43.png)

As an additional note, I am happy that KoBo allows me to upload a question block that has external dependencies. It is the case that in my organization, we would like to share out certain content (i.e. form sections; question blocks) in isolated library collections only with the individuals who should have access to that content (e.g. content experts). Given that we are literally cutting sections out of an overall form, there are going to be external dependencies (references to variables outside o that question block), which do not resolve. This is acceptable to us. We do not expect Enketo to be able to render the form. However, we do expect/hope for the form editor to correctly display all the question block fully and allow us to edit it without error.

---

**Attachments**
1. [question block.xls.zip](https://github.com/kobotoolbox/kpi/files/2337072/question.block.xls.zip)

**Comment by magicznyleszek** [comment]
@joeflack4 my detective work found a culprit: the `id` column is causing the problem - JS framework Backbone uses `id`'s for building data models (i.e. rows), so it's silently failing if form has such column. I've added PR to display an error when this happens. The easiest fix from your side would be to rename the column name (and references to it). I will create an issue for handling forms with `id` column, but I wouldn't expect it to be done anytime soon

**Comment by joeflack4** [comment]
@magicznyleszek Thank you so much!

Name collisions are a pain.
