### ISSUE TITLE
Feature: Minor enhancements to translations UI

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kpi#1988]
## Description

Following the translations PR #1913, a few improvements: 

- [x] When a form has an unnamed language, when opening the form builder, we currently show an error message: "There is an unnamed translation in your form definition. Please give a name to all translations in your form." It would be nice to point the user in the direction of where they can fix this issue (i.e. the translations/languages modal.) _note: current message is also used in tests._
- [x] When changing the default language, we should warn the user about the action (even though, it is easily reversible). Message should be: "Are you sure you would like to set ##LANG## as the default language for this form?"
- [ ] When hovering over any of the buttons inside the modal, the modal jumps down by about a pixel, and reverts when removing the mouse from the hover position
- [ ] The 'update translation' button is the same as for KC (legacy) in the left sidebar, which could be confusing.

**Comment by magicznyleszek** [comment]
@pmusaraj #1991 is merged with those two fixes, should we close this?

**Comment by pmusaraj** [comment]
Yes!
