### ISSUE TITLE
Further improvements to REST Services

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2021]
The REST work is very good and needs to get out of our workshop and into the world. There are some aspects that merit further improvement, though. Let me know if you disagree with any of these or think they would take more than a day to implement.

- [x] `HookLog`s stay in a pending state for a long time. It would be easier to debug newly-configured REST endpoints if the message (and status code?) were displayed after the first attempt.
- [x] We don't present any way for a user to cross-reference a `HookLog` UIDs to any particular submission, so those UIDs aren't really useful to show in the UI (except, maybe, when corresponding with our support staff). If we could show the submission ~~UUIDs~~ IDs in the log list, that would be ideal. ~~If not, (or not without a lot of work), then the submission IDs (database primary keys) would still be an improvement.~~ (IDs are unique and UUIDs sometimes are not... so IDs are preferable)
- [x] We allow people to set invalid HTTP headers. I don't think this needs attention so long as people don't have to wait a very long time before they see their mistake (usually in the form of a 400 error being returned by the external REST endpoint).
- [x] We don't act on KC's `posted_to_kpi`, so any time KC cannot reach KPI, submissions may wind up in limbo (without being logged anywhere that the user can see). @noliveleger, what are your plans for that, if any? We should probably write that up as a separate issue.

**Comment by jnm** [comment]
Maybe other improvements pending discussion at https://www.flowdock.com/app/kobotoolbox/kobo/threads/P2X8C6dsGciWq4Z_VN1-VPWbrir

**Comment by noliveleger** [comment]
@jnm: About  `KC's posted_to_kpi`. I have created this field for "debugging" purpose. 
Celery tries to send the data 3 times with an exponential gap between each. I expect all the tries to succeed in the 3 times. 
But you're right. It can happen that it still fails after 3 times. We could a create a Management command which would:
- send failures to admin 
- or retry once on its own every night
- both?

**Comment by magicznyleszek** [comment]
All the improvements are done :)
