### ISSUE TITLE
Error message is misleadng when importing invalid XLSForm file fails 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2022]
## Description
When importing an invalid XLSForm the import fails with the message ``, even though the API import error from pyxform via `/import/` gives a more useful feedback. 

Users would greatly benefit from seeing the exact error message when their import fails. 

## Steps to Reproduce

1. Import invalid form (e.g. with 'signature' question type, see [kobo_equipment_form_xlsx.xlsx](https://github.com/kobotoolbox/kpi/files/2444517/kobo_equipment_form_xlsx.xlsx)

## Expected behavior 
Form upload fails with error message 
`XLSForm import failed. Errors: Unknown question type 'signature'.`

## Actual behavior 
![image](https://user-images.githubusercontent.com/673511/46447076-003a5700-c74e-11e8-83c5-3b02c5c61f5b.png)

## Additional details

Outputting XLSForm error output could mirror what is done by [PyXFormError](https://github.com/XLSForm/pyxform/blob/c81983ecf4feb26cd35e2067904152c1c412f711/pyxform/question.py#L18) instead of what is seen in the `/import/` error.

**Comment by magicznyleszek** [comment]
It is already fixed, but not deployed yet (PR #1924 and #1969). I see this on local environment:

<img width="343" alt="screen shot 2018-10-05 at 11 07 02" src="https://user-images.githubusercontent.com/2521888/46526596-fb30f100-c88e-11e8-95f6-6ea720fb2200.png">
