### ISSUE TITLE
Add support in the form builder for `range` question type 

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2051]
See http://xlsform.org/en/#range. This one may be trickier than #2050 due to the extra parameters, which should appear as soon as the question is added (and not require clicking on the settings gear).

Per our discussion (doesn't that sound offical): let's use semicolons to separate items in the `parameters` column.

For reference: https://github.com/kobotoolbox/tasks/issues/276

**Comment by magicznyleszek** [comment]
@tinok `range` question type has three important parameters: `start`, `end` and `step` - I wonder how should I display them:
1. Always visible, below question name
2. Openable in similar vain to `select_one`
3. In settings with the rest
Note that `range` has default values (from 0 to 10, step by 1)

I'm leaning towards 2, as these are too important for settings, but we don't have anything similar to 1 in the UI yet.
