### ISSUE TITLE
Add setting in form builder for randomizing choice order

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2052]
See http://xlsform.org/en/#randomize-choices

Should be available for `select_one` and `select_multiple`. It should be a checkbox (defaulting to unchecked for now) that's displayed in the question settings.

For reference: https://github.com/kobotoolbox/tasks/issues/276

**Comment by tiritea** [comment]
Please note there is an open issue (bug) in pyxform that prevents exporting an XML if the randomize() function is used with a seed that is not a integer literal (eg seed is a function, or more commonly a reference to see calculated in another field). See https://github.com/XLSForm/pyxform/issues/238
