### ISSUE TITLE
Uploading form from XLS fails sometimes

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2056]
## Description

When creating a new form and uploading an XLSForm file, the form never successfully imports. 

## Steps to Reproduce

1. Start new form, choose to upload XLS. [Used this for testing.](https://github.com/kobotoolbox/kpi/files/2553615/int_bug.xls.zip)
2. View network console (or check status of import in API).

## Expected behavior 

Form imports and displays in the formbuilder. 

## Actual behavior 

The API call to check the import status returns `processing` forever, meaning the form never imports and the screen remains the same.

![image](https://user-images.githubusercontent.com/673511/48071682-dccd5680-e1a8-11e8-8924-8513a80c55af.png)

## Additional details

I have only been able to reproduce this once. Here is incomplete import instance: https://kf.kobotoolbox.org/imports/iDJrZ4jjs7MFDcaeFQThnw/

**Comment by joshuaberetta** [comment]
Not able to replicate... possibly server load related? I'll close this for now.
