### ISSUE TITLE
Form preview fails with error `argument of type 'int' is not iterable`

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2057]
## Description

When previewing specific form, preview fails to load (`argument of type 'int' is not iterable`).

## Steps to Reproduce

1. Open [this project](https://kf.kobotoolbox.org/#/forms/agzXjv6TETFuJ8ibpV4GGk/landing) in the formbuilder (user: tinokreutzer)
2. Click on preview

## Expected behavior 

Form previews 

## Actual behavior 

Form preview fails. Error: 
![image](https://user-images.githubusercontent.com/673511/48072030-aba15600-e1a9-11e8-8a25-93cbe876e753.png)

## Additional details

When exporting the XLS and importing as new project, the form preview succeeds somehow.

**Comment by jnm** [comment]
@noliveleger, here's an example of how trying to handle exceptions gracefully can make debugging much harder:
https://github.com/kobotoolbox/kpi/blob/550dc439aa9a38fc444ba5745d27be21177b0625/kpi/models/asset.py#L885-L901

If the exception weren't caught, we'd get a stack trace with local variables in Sentry. Instead, we get `src`, `id_string`, `uid`, `_msg`, and `warnings` (and `_msg` isn't even shown?): https://sentry.kbtdev.org/kobo/kpi-backend/issues/2837/.

I think this is basically the same situation as https://github.com/kobotoolbox/kpi/issues/1705, but we'll have to figure out whether some of the exceptions that could be raised here have to do with user error, e.g. invalid XLSForms.

For now, I'll try calling [`FormPack.to_xml()`](https://github.com/kobotoolbox/kpi/blob/550dc439aa9a38fc444ba5745d27be21177b0625/kpi/models/asset.py#L877-L880) manually inside the Django shell to get a useful traceback.

**Comment by jnm** [comment]
Related to the Pyxform upgrade:
```
>>> from formpack import FormPack
>>> a = Asset.objects.get(uid='agzXjv6TETFuJ8ibpV4GGk')
>>> FormPack({'content': a.content})[0].to_xml()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/srv/pip/src/formpack/src/formpack/version.py", line 287, in to_xml
    self.to_dict(remove_sheets=['translations', 'translated'],
  File "/srv/pip/src/formpack/src/formpack/utils/xform_tools.py", line 39, in formversion_pyxform
    imported_survey_json = workbook_to_json(content)
  File "/usr/local/lib/python2.7/dist-packages/pyxform/xls2json.py", line 395, in workbook_to_json
    replace_smart_quotes_in_dict(choice_item)
  File "/usr/local/lib/python2.7/dist-packages/pyxform/xls2json.py", line 80, in replace_smart_quotes_in_dict
    if smart_quote in value:
TypeError: argument of type 'int' is not iterable
```

**Comment by jnm** [comment]
[`replace_smart_quotes_in_dict()`](https://github.com/XLSForm/pyxform/pull/118/files#diff-b29aeb282b118614b8333cdfc19f700dR76) attempts to check `if smart_quote in value` without first making sure that `value` is a string (and in this case, it's an `int` from `'order': 0`). Troublesome `dict`:
```python
{u'$autovalue': u'option_1',
 u'$kuid': u'sqUjrGI0R',
 u'label': u'Option 1',
 u'list_name': u'wj5sl24',
 u'name': u'option_1',
 u'order': 0}
```

**Comment by jnm** [comment]
Why does it work when exporting the form as XLS and re-importing? The `0` in the `order` column is exported as an empty cell!

list_name | name | label | order
-- | -- | -- | --
wj5sl24 | option_1 | Option 1 |  
wj5sl24 | option_2 | Option 2 | 1
wj5sl24 | option_3 | Option 3 | 2
wj5sl24 | option_4 | Option 4 | 3
wj5sl24 | other | Other | 4

**Comment by jnm** [comment]
Since @tinok reports this form was created entirely in the form builder, I was curious as to how the `order` column appeared, and why it was present for this choice list:
```json
{
    "$autovalue": "option_1",
    "name": "option_1",
    "label": [
        "Option 1"
    ],
    "$kuid": "sqUjrGI0R",
    "list_name": "wj5sl24",
    "order": 0
},
```
...but not others:
```json
{
    "$autovalue": "option_1",
    "list_name": "aa9wy77",
    "$kuid": "iug7hoytZ",
    "name": "option_1",
    "label": [
        "Option 1"
    ]
},
```
It seems that the form builder adds `order` only after changing the order of the choices by dragging and dropping.

**Comment by jnm** [comment]
PR'd a fix to Pyxform for this https://github.com/XLSForm/pyxform/pull/237
