### ISSUE TITLE
Tableau Web Data Connector

### ISSUE THREAD

**Issue by ValerioGiuffrida** [kobotoolbox/kpi#2062]
First of all thank you for the great work!

## Description
Many users of Kobo in WFP also use Tableau to show the results of the analysis. 
ONA recently added the functionality ONA-Tableau connector (https://api.ona.io/tableau/connector/)
Similarly also SurveyMonkey integrated this feature (https://help.surveymonkey.com/articles/en_US/kb/Tableau-Integration)

## Expected behavior 
Create a web connector that allows to use the data from a Kobo form into Tableau 
(http://tableau.github.io/webdataconnector/)

The web connector should also allow to browse and select forms in a user friendly way.

**Comment by iahmedani** [comment]
@ValerioGiuffrida  I have created Tableau Web Data Connector for Kobotoolbox and supports ona.io free accounts too. 
Checkout my github repository [Kobotoolbox Tableau WDC](https://github.com/iahmedani/kobo-wdc)

**Comment by joshuaberetta** [comment]
Moved to: https://www.notion.so/kobotoolbox/Tableau-Web-Data-Connector-a326135deb9747c99c977007a09acf82
