### ISSUE TITLE
An `order` of zero is omitted when exporting XLSForm

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2063]
1. Create a new form with a `select_one` question in the form builder.
1. Drag and drop at least one of the choices for that question:
    ![image](https://user-images.githubusercontent.com/2085013/48160531-19cb4300-e2a6-11e8-9869-1c70b1e2de60.png)
1. Observe that the first choice has `"order": 0` in the form content JSON:
    ```json
        "choices": [
            {
                "$autovalue": "i_was_last__bu",
                "name": "i_was_last__bu",
                "label": [
                    "I was last, but now I'm first!"
                ],
                "$kuid": "xbByS2Ejl",
                "list_name": "tj69u35",
                "order": 0
            },
    ```
1. Export the form as XLS and notice the empty cell in the order column, which should contain a `0`:

    list_name | name | label | order
    -- | -- | -- | --
    tj69u35 | i_was_last__bu | I was last, but now I'm first! |  
    tj69u35 | option_1 | Option 1 | 1
    tj69u35 | option_2 | Option 2 | 2
    tj69u35 | option_3 | Option 3 | 3

Noticed while working on https://github.com/kobotoolbox/kpi/issues/2057

**Comment by joshuaberetta** [comment]
Seems to no longer be an issue -- possibly fixed with the pyxform upgrade?
