### ISSUE TITLE
once(random()) not working

### ISSUE THREAD

**Issue by Mainuka33678** [kobotoolbox/kpi#2071]
## Description

bug : once(random()) not producing random number.

## Steps to Reproduce

1. …calculate once(int(9*random())+1)

## Expected behavior 

a random number 1-10 to be produced every time a new form is opened

## Actual behavior 

same number produced over and over again

**Comment by jnm** [comment]
Thanks for reporting this! We'll look into updating KoBoCollect. Try using ODK Collect 1.14.2 or later and see https://forum.opendatakit.org/t/random-numbers-are-the-same-by-device/12776/10 for more details.
