### ISSUE TITLE
Public collection icon does not always reflect permissions

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2074]
## Description

Sometimes a public collection—public, in the sense that `AnonymousUser` has view access—does not show the globe badge on its folder icon:
![image](https://user-images.githubusercontent.com/2085013/48450478-4c78ae00-e774-11e8-87ab-01ad33729070.png)
I think the opposite can happen as well, but this is not as concerning.

## Steps to Reproduce

1. Question Library, New, Collection
2. Click three dots next to collection name
3. Click "Make Public"
4. Notice the appearance of the globe badge:
    ![screen shot 2018-11-13 at 18 52 05](https://user-images.githubusercontent.com/2085013/48450702-459e6b00-e775-11e8-8283-ff9b11de0e7b.png)
5. (nerd alert) `PATCH` the collection with `{"discoverable_when_public": false}`
6. Notice the disappearance of the globe badge:
![screen shot 2018-11-13 at 18 55 59](https://user-images.githubusercontent.com/2085013/48450845-cf4e3880-e775-11e8-944e-51e52b6535fb.png)

## Alternative Steps to Reproduce

1. Question Library, New, Collection
2. Click three dots next to collection name
3. Click Share
4. For "Enter a username", input `AnonymousUser`
5. Select `View` permission
6. Notice the globe badge does not appear, even after reload.

## Expected behavior 

If a collection is available for access by another user (whether "discoverable" or not), the interface must inform the user somehow.

## Actual behavior 

The globe badge is shown if `discoverable_when_public` is `true`, regardless of permissions granted to `AnonymousUser`

## Why does this matter?

"Make Private" in the UI makes two separate requests to the backend:
![image](https://user-images.githubusercontent.com/2085013/48451272-b6df1d80-e777-11e8-8cf8-b725078905fe.png)
If the `PATCH` succeeds but the `DELETE` fails, then anyone who has subscribed to this collection could still access it, even as the UI shows the owner that it's no longer public.

:eyes:
https://github.com/kobotoolbox/kpi/blob/4eef7047227222a89ee6f84c8a21975a37d825b1/jsapp/js/components/librarySidebar.es6#L305-L306

**Comment by magicznyleszek** [comment]
Note to self: in `librarySidebar.es6` check whether `collection.discoverable_when_public` **or** `AnonymousUser` has permissions.
