### ISSUE TITLE
Loading Error: 'TypeError: Cannot set property 'textContent' of null' 

### ISSUE THREAD

**Issue by mdestaubin** [kobotoolbox/kpi#2078]
## Description

The users forms were reportedly working properly until Nov 5th, when some of their forms began showing the loading error: 'TypeError: Cannot set property 'textContent' of null' 

## Steps to Reproduce

1. Upload XLSForm from conversation https://app.intercom.io/a/apps/s6hn3a8q/inbox/inbox/2698693/conversations/19407773139 to the HHI server.
2. Try to open or preview the form.

## Expected behavior 

The form should open or be previewed properly with no loading errors.

## Actual behavior 

Loading Error: 'TypeError: Cannot set property 'textContent' of null' pops up. 

![image](https://user-images.githubusercontent.com/31933880/48559786-48ef3f00-e8ba-11e8-8358-40ff32a30107.png)

**Comment by tinok** [comment]
Congrats on your first bug report @mdestaubin 🙌 🕺

**Comment by jnm** [comment]
@magicznyleszek, maybe. I tried this `Multilingual_V_5_03.xls` form and a different error appears in Firefox: `TypeError: i[0].querySelector(...) is null`. Chrome still shows `TypeError: Cannot set property 'textContent' of null`, though.

In any event, this bug needs to be filed against Enketo Express: https://github.com/enketo/enketo-express/issues

**Comment by jnm** [comment]
With the handy-dandy browser developer tools, I was able to figure out that things were getting hung up around this part of the form:

type | name
-- | --
begin_repeat | group_csv
calculate | ex_date
calculate | ex_depatred
calculate | ex_staff
calculate | ex_order_no
calculate | ex_progrmm_loc
calculate | all_pujas_date
calculate | ex_lang
calculate | ex_name
calculate | ex_cc
calculate | ex_prasad_name
calculate | ex_adress
calculate | ex_zip_city
calculate | ex_country
calculate | ex_star
calculate | all_pujas_name
calculate | all_pujas_date_001
calculate | ex_notes
calculate | ex_mail
calculate | ex_phone
calculate | ex_birthdates
end_repeat |  

A minimal form to reproduce the problem needs only:

type | name | label
-- | -- | --
begin_repeat | mysterious_repeat | mysterious repeat
end_repeat |   |  

@magicznyleszek, I'll ask you to try your hand at this kind of troubleshooting in the future.

@tinok, is there a valid reason for someone to have a repeating group filled only with `calculate` questions? If not, can we tell the user that we appreciate the bug report, while advising them that their form design is actually broken?

**Comment by jnm** [comment]
If my understanding of https://github.com/kobotoolbox/enketo-express/issues/1112 is correct, this should be fixed by rejecting forms with empty repeating groups as invalid. I mentioned this particular manifestation of the issue to Martijn at https://github.com/enketo/enketo-validate/issues/38.
