### ISSUE TITLE
Importing label::language isn't recognized

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2085]
## Description

A user [reported](https://app.intercom.io/a/apps/s6hn3a8q/inbox/inbox/unassigned/conversations/19582386502) that `label::language` and `hint::language` doesn't import properly (language isn't recognized?). They were only able to import a multilingual form with a single colon, `label:language`. "The form uploads successfully when only one ":" exists in the label."

## Steps to Reproduce

1. Import xls form with label::language
2. Check translations

## Expected
both `:` and `::` should work when importing a form. Our documentation specifically lists `::`.

## Additional details

Haven't tested yet, relying on user bug report.

**Comment by jnm** [comment]
Apologies to the user, but this is clearly not true in a general sense.

Imported form: [multi-lingual label and hint.xlsx](https://github.com/kobotoolbox/kpi/files/2626599/multi-lingual.label.and.hint.xlsx)

Result in KPI:
![image](https://user-images.githubusercontent.com/2085013/49182400-35b38900-f328-11e8-8ce3-0040606e4961.png)

Preview:
![image](https://user-images.githubusercontent.com/2085013/49182522-83c88c80-f328-11e8-8511-42eed6923bac.png)

Form builder:
![image](https://user-images.githubusercontent.com/2085013/49182562-9fcc2e00-f328-11e8-81f4-cfa70de9d380.png)

Deployed form:
![image](https://user-images.githubusercontent.com/2085013/49182629-c8ecbe80-f328-11e8-8f81-b04f5637aeba.png)
