### ISSUE TITLE
Password strength meter messages are in English only

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2114]
Spun off from the discussion at https://github.com/kobotoolbox/kpi/pull/2043#pullrequestreview-182918998

Does https://github.com/dropbox/zxcvbn offer localized messages? It's showing English regardless of the language used by the rest of the form:
![image](https://user-images.githubusercontent.com/2085013/49678920-cccdbe80-fa55-11e8-9371-cc3d334b4f14.png)

**Comment by magicznyleszek** [comment]
@jnm I've checked and unfortunately it doesn't :( There was an attempt to enable overriding messages but PR was closed https://github.com/dropbox/zxcvbn/pull/124 I ~~could find~~ can take [the messages](https://github.com/dropbox/zxcvbn/blob/master/src/feedback.coffee) and display them with `t()` function? But then we would need to put them somewhere so it's clear they should be translated

**Comment by jnm** [comment]
OK, from reading through the discussion around https://github.com/dropbox/zxcvbn/pull/124, even if that's merged, we'd still have to supply our own translations even if that PR is merged sometime in the future. We may as well, then, start having our translators work on them in Transifex.
