### ISSUE TITLE
ODK Central integration

### ISSUE THREAD

**Issue by joeflack4** [kobotoolbox/kpi#2122]
## Description
ODK Central is the new version of ODK Aggregate. It has an OData spec RESTful API. An integration for that would be great, so that we could easily manage/edit our forms in KoBo, and seamlessly upload them to ODK Central.

**Comment by tiritea** [comment]
+1 for being able to leverage Central's new REST API to directly load (ie 'deploy') a form created in Kobo UI into Central.

**Comment by joshuaberetta** [comment]
Moved to: https://www.notion.so/kobotoolbox/ODK-Central-integration-50144ed67fcf432f95bd4879d3a3a166
