### ISSUE TITLE
Nested repeated group breaks submission detail view

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2137]
## Description

If you have a repeated group inside repeated group, submission detail view is broken

## Steps to Reproduce

1. Use this form: [nested-repeater-bug.xls.zip](https://github.com/kobotoolbox/kpi/files/2700074/nested-repeater-bug.xls.zip)
2. Add any submission
3. Go to Table View and open submissions detail (eye icon)
4. Observe a crash

## Additional details

May be connected to:

- #1994
- #1931
- #1574

**Comment by magicznyleszek** [comment]
An interesting idea: instead of maintaining our submission view, use Enketo in read-only mode - idea from https://github.com/kobotoolbox/kobocat/issues/460#issuecomment-452607774

**Comment by awemulya** [comment]
There is a pull request in kobocat by me.
The idea is use read only enketo view available in Enketo (api/v2/instance/view).
https://github.com/kobotoolbox/kobocat/pull/513
I would be happy to contribute on kobocat.

**Comment by jnm** [comment]
To save time when cross-referencing, see https://github.com/kobotoolbox/kpi/issues/2607 for discussion of the Enketo read only view.
