### ISSUE TITLE
When trying to select rows the table sometimes disappears 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2154]
## Steps to Reproduce

1. View a (large?) project in table view (fullscreen or regular view). Tested with [this project](https://kf.kobotoolbox.org/#/forms/aquYpKHzQfFdifEbYkAaQV/data/table). 
2. Try to select several rows randomly

## Expected behavior 

Rows are selected 

## Actual behavior 

At some point, seemingly at random, the table either disappears or shifts up significantly.
![image](https://user-images.githubusercontent.com/673511/50945445-a6d77780-1462-11e9-822d-b2dcb3683eac.png)

**Comment by magicznyleszek** [comment]
@jnm it seems I already replaced the checkboxes with better one - i.e. this should be fixed by deploying new version at https://kf.kobotoolbox.org :-)
