### ISSUE TITLE
Action menu "…" in form list and form landing should have identical options

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2157]
## Description

The reasoning is that these look and act similar, and users probably expect to find same options in them (with permissions filtering these options properly of course).

**Comment by arsea** [comment]
To confirm, @magicznyleszek , are these the ones you mean?

<img width="962" alt="Screen Shot 2019-08-24 at 3 25 24 PM" src="https://user-images.githubusercontent.com/1126329/63641883-76f08380-c683-11e9-92c2-ae7e7be45796.png">
<img width="656" alt="Screen Shot 2019-08-24 at 3 25 32 PM" src="https://user-images.githubusercontent.com/1126329/63641884-76f08380-c683-11e9-8318-f26fd10a700c.png">

**Comment by magicznyleszek** [comment]
@arsea these are the ones, yes :)

**Comment by magicznyleszek** [comment]
But as I already am building something similar (https://github.com/kobotoolbox/kpi/blob/2293-public-collections/jsapp/js/components/library/assetActionButtons.es6) this would be closed by the big Public Collections branch feature

**Comment by jnm** [comment]
Closed by #2559
