### ISSUE TITLE
Import GPS in Kobotoolbox

### ISSUE THREAD

**Issue by atchikpa** [kobotoolbox/kpi#2170]
Hello dear all,

Happy New Year, I hope my message finds you well?

I am going to go and investigate households for the second time, and I got the GPS coordinates during my first field survey with Kobo. I do not know how to do it !!! There is a way to integrate the old GPS coordinates into the system so that the investigator is directly direct to the points in question with precision.

I would also like to know how to customize the sources of kobotoolbox cards? That is integrated a card that I designed in the kobotoolbox server.

Thank you.

**Comment by joshuaberetta** [comment]
KoBo now includes case management features: https://support.kobotoolbox.org/dynamic_data_attachment.html
