### ISSUE TITLE
Map shows error when no GPS data has been collected yet

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2173]
## Description

A deployed project that has a GPS (`geopoint`) question but hasn't yet received any data for that question is causing an error to be displayed instead of the map. Identified [here](https://www.flowdock.com/app/kobotoolbox/kobo/threads/TgzQafedPzUyro6Q0SHNOPVRwF5).

## Steps to Reproduce

1. Create new form with `geopoint` question
2. Deploy and submit data (but don't add any gps points)
3. Open map

## Expected behavior 

Map is displayed but without any data on it. 

## Actual behavior 

Instead, an error is displayed: 
![image](https://user-images.githubusercontent.com/673511/51699133-f6c54b00-1fd9-11e9-86b2-e71095aa61a4.png)

## Additional details

The map is also not displayed when the form doesn't have a `geopoint` question. It's a separate issue, but it might be nice to just always display the map either way.

**Comment by magicznyleszek** [comment]
@duvld take a look at this when you don't have anything left to do :)
