### ISSUE TITLE
Drafts not loading for form with repeating structure

### ISSUE THREAD

**Issue by samfmoody** [kobotoolbox/kpi#2174]
## Description

I have a form that makes use of repeats, both as pages of the form and within pages. Once answers have been entered into the boxes that define the number of repeats, and then the form is saved as a draft, when you try to load that draft to continue working on it, an error occurs.

## Steps to Reproduce

[Error test 2.xlsx](https://github.com/kobotoolbox/kpi/files/2803525/Error.test.2.xlsx)

1. Upload the attached form into KoBo (on the humanitarianresponse.info server) and deploy it. I had to attach as .xlsx but it was created and uploaded into KoBo as xls.
2. Open form in Enketo 
3. Set the 'number of workstreams' to 2
4. Give the workstreams names and click 'next'
5. On the second page, set the 'number of objectives' to 1
6. Click next to get to the final page. You do not need to enter anything here
7. Save the form as a draft
8. Go to the queue and click on the draft to try to load it

## Expected behavior 

The form is loaded with the information that you previously saved in the draft

## Actual behavior 

The draft is not loaded and an error message appears saying "TypeError: Cannot read property 'nodeName' of undefined". The form opens and the number of repeat boxes match the draft but they are blank (e.g. if the draft listed 2 workstreams, the first page would show 2 boxes for workstreams but none of the text entered into the draft).

## Additional details

The issue does not occur if you enter '1' workstream and therefore get the second page only once.

**Comment by MartijnR** [comment]
Must be an Enketo issue since it doesn't involve submitting. Thanks!

**Comment by enketo-issue-mover** [comment]
This issue was moved to enketo/enketo-express#82

**Comment by jnm** [comment]
Thank you, Martijn, and thanks @samfmoody for the report.
