### ISSUE TITLE
After signing in, user is not redirected to original URL

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2190]
## Description

A user is not redirected to the original URL after signing in. 

## Steps to Reproduce

1. Open any project, copy the URL.
2. Sign out
3. Open the URL copied in step 1
4. Sign in

## Expected behavior 

After signing in, user is redirected to the original URL requested

## Actual behavior 

Instead, user sees project overview list.

**Comment by tinok** [comment]
@jnm Could be marked as a feature enhancement instead of a bug.

**Comment by jnm** [comment]
I'm stealing the superior title from this issue, but closing it in favor of its duplicate, #3222
