### ISSUE TITLE
Using dot in username

### ISSUE THREAD

**Issue by Stopi** [kobotoolbox/kpi#2192]
When I create a user with a dot in the user name, then the account cannot be used in KPI.
I mean you can connect but cannot perform most of the features, you can't even save when changes in your profile page.
It works perfectly with other user names.

## Steps to Reproduce
1. create a user named **e.xample**
2. connect to kpi
3. try to change anything on your `[ACCOUNT SETTINGS]`
4. when you click on `[SAVE CHANGES]`, you'll see the bug

## Expected behavior 
Either we can fix this, or at least prevent people to create user names with dots.

## Actual behavior 
You can't do many things, cannot import a form, cannot save profile...

## Additional details
Fresh install using the last kobo-install script.

**Comment by jnm** [comment]
Hello, how are you creating a user whose username contains a dot? These are [blocked](https://github.com/kobotoolbox/kpi/blob/94d88be1640f833b1d530180fe693b399b5cc427/kpi/forms.py#L9-L15) by the registration form:
![screenshot of validation error for username with dot](https://user-images.githubusercontent.com/2085013/52587804-df26f880-2e08-11e9-947d-e554a5eed497.png)

**Comment by Stopi** [comment]
Oh, I see.
Unfortunately, I didn't used this form.

Registration as been disabled on our server.
I, as admin, create the accounts using django admin console.

Maybe we should consider to put a warning in the documentation.
I'm not a Python dev, so I'm not sure if you can do this, but as I used django admin console to change **REGISTRATION_OPEN** to **False** (URL: `/admin/constance/config/`), maybe it is the place where to put a warning.

**Comment by joshuaberetta** [comment]
This seems very niche. I'm going to close this for now.
