### ISSUE TITLE
Cannot delete users, getting error 500

### ISSUE THREAD

**Issue by Stopi** [kobotoolbox/kpi#2193]
## Description
Some user cannot be deleted from the Django console.

## Steps to Reproduce
It's hard to tell, it works with some user, some don't.
For example, I had 10 users (created on the same day, one after the other).
They where named `tablet1`, `tablet2`, `tablet3`,...., `tablet10`.

Then I wanted to remove them all and create instead a unique account called `tablets`.

I've been in Django admin interface, selected some and tried to delete.
I've successfully deleted `tablet1`, `tablet2`, `tablet4`,`tablet6`, `tablet7` and `tablet10`.
I can't delete `tablet3`, `tablet5`, `tablet8` and `tablet9`.

I know as a fact that none of them had submit any data to the server.
They have been shortly connected from android tablets, download a form they were allowed and fill those forms during a training.
But no data have been submitted to the server.
Plus I've removed the permissions to this forms from its `[SETTINGS]` tab.

## Expected behavior 
I expect users to be removable.

## Actual behavior 
When selecting one of this buggy user (alone or in a list with some others) and deleting, then I get
**Server Error (500)**

## Additional details
I'm using a fresh install from `kobo-install` script

I couldn't see any log except in `kobo-docker/log/kpi/uwsgi.log`
`{address space usage: 351809536 bytes/335MB} {rss usage: 87961600 bytes/83MB} [pid: 3391|app: 0|req: 1348/4708] 172.xx.xx.xx () {58 vars in 1120 bytes} [Mon Feb 11 03:34:24 2019] GET /admin/auth/user/3/delete/ => generated 27 bytes in 117 msecs (HTTP/1.1 500) 4 headers in 145 bytes (1 switches on core 0)`

Nothing else poped up in `kobo-docker/log`, nor in docker logs (`python run.py --logs`).

**Comment by jnm** [comment]
Thanks for the detailed report. This is a frustrating situation because this application (KPI) and https://github.com/kobotoolbox/kobocat are two distinct Django applications that share the same database. Both applications have models that are related to `auth.User`, but neither knows about the models belonging to the other. This causes database integrity checks to fail when you try to delete a user who has related objects in both applications. For more detail, see https://github.com/kobotoolbox/kobocat/issues/92.

* We are already working to separate the applications' databases: https://github.com/kobotoolbox/kpi/issues/2155
* There is a workaround available by using the KPI admin interface:
    1. Go to https://your-kpi-hostname/admin/auth/user/;
    1. Check one or more users whom you'd like to delete (do not leave the list view, even if you are deleting just one user);
    1. From the "Action" dropdown, choose "Remove related objects for these users (deletion step 1)" and click Go;
    1. Review the list of objects to be deleted and click "Yes, I'm sure" at the bottom;
    1. Select the user(s) again;
    1. From the "Action" dropdown, choose "Remove these users from KoBoCAT (deletion step 2)" and click Go;
    1. ~~Review the list of objects to be deleted and click "Yes, I'm sure" at the bottom.~~ This is failing with a CSRF error. I'll investigate.

Once the workaround is fixed, it should be documented in the README.

**Comment by Stopi** [comment]
When trying to **Remove related objects for these users**, I get a **Server Error (500)**.
I tried to refresh or logout/login in order to avoid any CSRF issue, still no success so far.

For the users I've deleted successfully, I was ask to review and confirm all related object before, even if I didn't choose this option.

**Comment by Stopi** [comment]
I can declare those users as **not active** (in django console), so they're not visible in prod.
That's a workaround, but it's good enough for now.

**Comment by jnm** [comment]
@Stopi, you can also rename them if you need to reuse their usernames.

> For the users I've deleted successfully, I was ask to review and confirm all related object before, even if I didn't choose this option.

The problem is that the list you saw only contained KPI's related objects, not KoBoCAT's.

> When trying to **Remove related objects for these users**, I get a **Server Error (500)**.

It sounds like your KPI may predate the fix for https://github.com/kobotoolbox/kpi/issues/2148.
