### ISSUE TITLE
Pressing "delete" button while adding question in form builder closes the form without saving

### ISSUE THREAD

**Issue by Raph33** [kobotoolbox/kpi#2200]
## Description

Pressing "delete" button while adding question in form builder closes the form without saving

## Steps to Reproduce

1. Open form builder
2. Click the + button to add a question
3. Without entering any text in the field, click the "+ Add question" button". The list of question types appears
4. Press the computer's "delete" button

## Expected behavior 

Either nothing should happen (the "delete" button shouldn't have any impact) or KoBo should ask to "leave without saving?"

## Actual behavior 

The form editor closes, the user is taken back to the form's main screen. If there was unsaved edits, those edits are lost.

## Additional details

MacOS

**Comment by magicznyleszek** [comment]
@Raph33 I can't reproduce it 😭 My setup is MacBook Pro + [A1048 USB keyboard](https://en.wikipedia.org/wiki/Apple_Keyboard#/media/File:Apple_Keyboard_(A1048).jpg). I tried both `delete` on built-in and USB keyboards with no success. Do you possibly have the `delete` (`backspace`) key set up in the browser as "navigate back"?

**Comment by Raph33** [comment]
@magicznyleszek thanks for checking! I'm trying to look whether the delete (backspace) key is set up in the browser as "navigate back", but can't find where that would be (I'm in Firefox); any idea?

**Comment by magicznyleszek** [comment]
@Raph33 I think you can check this: when you reproduce all steps, at 5. check if your browser history forward button is enabled and takes you back to Form Builder. Because if it does, it means that `delete` button is doing history back

**Comment by magicznyleszek** [comment]
@Raph33 ok, I was able to reproduce it - i.e. the problem when you navigate back from Form Builder with unsaved changes. My PR should cover both keyboard navigation (`delete`/`backspace` key in your case) and using browser &larr; and &rarr; buttons.

**Comment by Raph33** [comment]
Nice, glad you could reproduce, and thanks for looking at it :)

**Comment by magicznyleszek** [comment]
It's good you reported it, as I'm sure it was happening to other users too. And it's really annoying bug when it happens 👿 

Note for future generations: We were already double-checking when user wanted to close the tab or navigate to other page with unsaved changes - but because KPI is a single page application some of navigation doesn't trigger the page unload. And this is when the bug happens.
