### ISSUE TITLE
Enable the saving in the library of entire groups of questions

### ISSUE THREAD

**Issue by Raph33** [kobotoolbox/kpi#2203]
## Description

In many cases, the same groups of questions of questions are used across forms. When those groups include dozens of questions, and hundreds of potential answers, saving questions to the library isn't enough. Users should be able to save entire groups, so that they can be added at once into new forms.

**Comment by magicznyleszek** [comment]
You can create a block of questions in Library:

<img width="763" alt="screenshot 2019-03-07 at 11 59 47" src="https://user-images.githubusercontent.com/2521888/53952336-c1c81000-40d0-11e9-858c-7300e90922e0.png">

And add it to a form:

<img width="390" alt="screenshot 2019-03-07 at 12 00 39" src="https://user-images.githubusercontent.com/2521888/53952348-c987b480-40d0-11e9-8ef3-d86ae4ab5b15.png">

Is this the thing you're describing? :)

**Comment by Raph33** [comment]
Yes, that's exactly what I was looking for! Thinking now if there is a way to make this more obvious. It's a little confusing that in order to create a block, we actually need to click New > Question (instead of New > Block). My instinct was to assume that a question in the library is, well, just a question; and I never considered that there would be an option to add additional questions to it to make a block

**Comment by magicznyleszek** [comment]
Do you think it would be better if button said `NEW` > `Block/Question` instead?

**Comment by Raph33** [comment]
It would definitely help clarify, yes. Or NEW > Question/Block rather, as the Question will probably remain the most used

**Comment by Raph33** [comment]
Actually, what would be quite useful, is to have, where the 'add question to library' button usually is for questions, to have an 'add block to library' button for groups

<img width="448" alt="screen shot 2019-03-07 at 7 27 42 pm" src="https://user-images.githubusercontent.com/27868414/53976383-8f89d300-410f-11e9-8434-b837cdfd6409.png">

**Comment by magicznyleszek** [comment]
We will change the button name to `Question/Block` and change the icon to more accurate one (current one is a "Q" for "question", new one should mean both)

**Comment by magicznyleszek** [comment]
For the "add block to library" idea there is already GH issue: https://github.com/kobotoolbox/kpi/issues/1861 :)

**Comment by Raph33** [comment]
> We will change the button name to Question/Block and change the icon to more accurate one (current one is a "Q" for "question", new one should mean both)

Great!

> For the "add block to library" idea there is already GH issue: #1861 :)

Great again! :)

**Comment by magicznyleszek** [comment]
Closing this in favor of #1861
