### ISSUE TITLE
The "expand/collapse questions" button should also expand/collapse groups

### ISSUE THREAD

**Issue by Raph33** [kobotoolbox/kpi#2204]
## Description

For forms that include many groups and subgroups, it is very frustrating to have to close each individual group in order to navigate up and down the form editor (particularly as when we open the form editor, all questions and groups are expanded)

## Steps to Reproduce

1. Open a form with large numbers of groups of questions, and nested groups
2. Notice how when you open the form all groups are expanded
3. Pressing the "expand/collapse questions" collapses all questions by not the groups

## Expected behavior 

Pressing the "expand/collapse questions" should expand or collapst all questions _and_ all groups and subgroups

**Comment by magicznyleszek** [comment]
You're making a good point about this functionality being missing and nice to have. But we think it would be better to make a second button to expand/collapse groups.

**Comment by Raph33** [comment]
Even better! It would give users more granularity: I definitely how in some cases having groups expanded and questions collapsed would be needed
