### ISSUE TITLE
Front-end attempts to deploy non-current version of form

### ISSUE THREAD

**Issue by mdestaubin** [kobotoolbox/kpi#2205]
## Description

On the UNHCR server, if you upload and deploy a new xlsform, then replace/change the form twice before redeploying a Server 500 Error occurs. 

## Steps to Reproduce

1. Upload a XLSForm on UNHCR server ([ac.xlsx](https://github.com/kobotoolbox/kpi/files/2889693/ac.xlsx))
2. Deploy the project 
3. Upload and replace the form twice
4. Click Redeploy

## Expected behavior 

The form should redeploy with no issue. 

## Actual behavior 

![image](https://user-images.githubusercontent.com/31933880/53177160-86502080-35bd-11e9-83ef-c25c5a27f3a6.png)

## Additional details

Request URL: https://kobo.unhcr.org/assets/aYkEM3qTrwPHXasdJxqiAW/deployment/
Request Method: PATCH
Status Code: 500 INTERNAL SERVER ERROR

**Comment by jnm** [comment]
`NotImplementedError: Only the current version_id can be deployed`
https://sentry.kbtdev.org/kobo/kpi-backend/issues/300661/?query=user.username:bareta

@magicznyleszek, any idea why the FE would be sending an older-than-current `version_id` to the backend when redeploying?
