### ISSUE TITLE
ImportError: cannot import name lazy_related_operation

### ISSUE THREAD

**Issue by MaskeyPuja** [kobotoolbox/kpi#2214]
## Steps to Reproduce

1. …git clone this repository
2. …pip install -r requirements/pip/requirements.txt
3. …python manage.py runserver

**Comment by MaskeyPuja** [comment]
output of pip freeze:
adium-theme-ubuntu==0.3.4
amqp==2.4.1
atomicwrites==1.3.0
attrs==18.2.0
billiard==3.5.0.5
celery==4.2.1
certifi==2018.11.29
chardet==3.0.4
configparser==3.7.3
confusable-homoglyphs==3.2.0
construct==2.5.3
contextlib2==0.5.5
cwm==1.2.1
dj-database-url==0.5.0
Django==1.8.19
django-celery-beat==1.4.0
django-constance==2.2.0
django-debug-toolbar==1.11
django-digest==1.13
django-extensions==2.1.6
django-js-asset==1.2.2
django-json-field==0.5.7
django-loginas==0.3.4
django-markitup==3.0.0
django-mptt==0.9.1
django-private-storage==2.1.3
django-registration==3.0
django-registration-redux==2.5
django-reversion==3.0.3
django-taggit==0.24.0
django-timezone-field==3.0
django-webpack-loader==0.6.0
djangorestframework==3.9.1
fontforge==1.0
funcsigs==1.0.2
future==0.17.1
gyp==0.1
haystack==0.42
idna==2.8
importlib==1.0.4
importlib-metadata==0.8
jsonfield==2.0.2
kombu==4.3.0
more-itertools==5.0.0
oauth2-provider==0.0
pathlib2==2.3.3
pefile==2018.8.8
phonenumbers==8.10.3
pluggy==0.9.0
py==1.8.0
pycurl==7.43.0
pyliblzma==0.5.3
pymongo==3.7.2
pysqlite==1.0.1
pytest==4.3.0
python-apt==1.1.0b1+ubuntu0.16.4.2
python-crontab==2.3.6
python-dateutil==2.7.5
python-digest==1.7
python-ptrace==0.9.3
pytz==2018.7
requests==2.21.0
rpm-python==4.12.0.1
scandir==1.9.0
six==1.12.0
sqlparse==0.2.4
testinfra==1.19.0
typing==3.6.6
unity-lens-photos==1.0
urlgrabber==3.9.1
urllib3==1.24.1
vine==1.2.0
virtualenv==16.1.0
yum-metadata-parser==1.1.4
zipp==0.3.3

**Comment by awemulya** [comment]
This happens when Installation of library Django was not completed sucessfully. Due to permission issues.
May be you need sudo in pip install, or create virtualenvirnment without sudo command. Permission Issue.
