### ISSUE TITLE
support (and expose?) XLSForm 'hidden' controls

### ISSUE THREAD

**Issue by tiritea** [kobotoolbox/kpi#2239]
## Description
Kobo form builder presently does not recognize XLSForms with a 'hidden' data type present in an imported form (nor, obviously, does the KPI form builder support creating one).

bug (and candidate for enhancement if want to expose as new form builder widget)

## Steps to Reproduce

1. manually create an XLSForm with a 'hidden' data type row 
2. create-from-XLSForm a new form in Kobo
3. edit form: will get "Row could not be displayed..." error
4. export form

## Expected behavior 

even if KPI doesnt yet support a 'hidden' control widget, it could simply ignore the control in the form builder, but still re-export is as-is when creating a new XLSForm/XML.

## Actual behavior 

Instead, the original hidden control will be missing in new export

## Additional details

'hidden' controls Kobo also referenced  here: https://github.com/XLSForm/xlsform.github.io/issues/116

See attached example:

[hiddentest.xlsx](https://github.com/kobotoolbox/kpi/files/3021124/hiddentest.xlsx)

**Comment by tinok** [comment]
@tiritea This feature is partially implemented with #2601. Do you have capacity to test this locally? 

I'm wondering about the UI implementation. There is no point in defining a label for the hidden question. Should it be hidden? Our current UX flow requires either a label or a calculation to be specified _before_ choosing the question type.   

Is the `default` field the only useful field here? Maybe we could give users a hint for `hidden` questions that they can use that field in the settings to specify a constant. 

If you have a specific use case that would be really helpful.

**Comment by tiritea** [comment]
>Our current UX flow requires either a label or a calculation to be specified before choosing the question type.

Yes, well, I have an opinion on that too... ;-)

**Comment by tiritea** [comment]
sorry. hit wrong button - didnt mean to close it :-(
