### ISSUE TITLE
Improve translations modal

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2245]
## Description

Things to change in translations modal:

- [x] 1. Make it possible to "Update translations" for the default language (or in other words, allow for changing the default strings outside Form Builder) - this action should be visible for default language too:
  <img width="517" alt="Screenshot 2019-07-22 at 21 08 46" src="https://user-images.githubusercontent.com/2521888/61658836-836d6f00-acc6-11e9-9210-65ce92121327.png">
- [x] 2. Add option to rename language (name and code) in "Update translations" view:
  <img width="1050" alt="Screenshot 2019-07-22 at 21 24 07" src="https://user-images.githubusercontent.com/2521888/61659144-1b6b5880-acc7-11e9-9e6f-ebd73cfe4e74.png">
  See how feasible it is - there is not much space here. Maybe `Language Form` displaying above/below table after clicking some icon button (next to "Polski (pl) translation" text?)? Make sure to update language with the same call as "Save changes" is doing, and to update `SAVE_BUTTON_TEXT.UNSAVED` state after changing name/code.
- [x] 3. Update "no default language set" initial view:
  - short TODO:
    - [x] Move "Please name your default…" bold text below the line
    - [x] Hide "Add language" button
    - [x] Instead of "Unnamed language" row, display the language form that will set default language properties (it's `LanguageForm` component from `jsapp/js/components/modalForms/translationSettings.es6`, maybe will need some slight changes to allow custom input labels and button name)
  - how it looks now:
    <img width="654" alt="Screenshot 2019-07-22 at 21 11 23" src="https://user-images.githubusercontent.com/2521888/61658333-6b492000-acc5-11e9-95df-bb3e170819e8.png">
  - what we want:
    <img width="663" alt="Screenshot 2019-07-22 at 21 11 11" src="https://user-images.githubusercontent.com/2521888/61658346-7439f180-acc5-11e9-9b0a-b7a2cbd8ec71.png">
- [x] 4. Create "pending" state for `LanguageForm` - disabling the submit button would be good enough. It should probably be set near `this.props.onLanguageChange` call, and unset after `componentWillReceiveProps` call? Will surely need testing. Currently it is not obvious if clicking the button did anything, and the success response sometimes takes few seconds.

- [x] 5. Move `LanguageForm`to its own file

**Comment by arsea** [comment]
@magicznyleszek i've done everything but #2. Since it's built with a ReactTable, I don't think I can add a button in the header. Should we maybe add another button on top of the table to do this?

**Comment by magicznyleszek** [comment]
@arsea it is possible to customize ReactTable headers, see: https://github.com/kobotoolbox/kpi/blob/master/jsapp/js/components/table.es6#L221 - but if it looks to confusing (it looks confusing for me after quick look! 😝), try doing above table 👍
