### ISSUE TITLE
Table view shows multiple columns for grouped questions

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2249]
Given a simple form with a grouped question:

type | name | label
-- | -- | --
start | start |  
end | end |  
text | not_in_a_group | not in a group
begin_group | the_group | the group
text | in_a_group | in a group
end_group |   |  

And, given an unremarkable submission:
```json
{
  "_notes": [],
  "__version__": "vdKnsdwokQcYE7zQQ8bMAe",
  "meta/instanceID": "uuid:ee19bcd5-7dcd-4b93-8437-bd049ffb6789",
  "end": "2019-04-15T16:14:01.870-04:00",
  "_submission_time": "2019-04-15T20:14:07",
  "_validation_status": {},
  "_uuid": "ee19bcd5-7dcd-4b93-8437-bd049ffb6789",
  "_bamboo_dataset_id": "",
  "_tags": [],
  "_attachments": [],
  "start": "2019-04-15T16:13:54.503-04:00",
  "_submitted_by": null,
  "_geolocation": [
    null,
    null
  ],
  "_xform_id_string": "ahrzuYwQpBZqnu2LWm7dtV",
  "the_group/in_a_group": "yep!",
  "_status": "submitted_via_web",
  "_id": 25966712,
  "not_in_a_group": "nope!",
  "formhub/uuid": "0ea52d3d7e4d4bd88fc8619b0c91a277"
}
```

The table view columns (set to `XML Values` for clarity) include `the_group`, `the_group / in_a_group`, and `in_a_group`. I would expect only `the_group / in_a_group` to appear, unless `Show group names in table headers` were unchecked; in that case, I would expect only `in_a_group` to appear.

The same behavior occurs in the "Restrict the visible columns in the table display" list inside the "Table display options" modal.

Original support request: https://community.kobotoolbox.org/t/data-table-view-duplicate-columns/2938/9

**Comment by ChloeLaborde** [comment]
Hi eveyrone,

Any idea if this bug is going to be fix?

All the best, 
Chloé
