### ISSUE TITLE
Display amount of disk space used by each project and user

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2254]
Once https://github.com/kobotoolbox/kobocat/issues/517 has been finished.

Projects:
- [ ] UI design
- [ ] Back-end implementation
- [ ] Front-end implementation

Users:
- [ ] UI design
- [ ] Back-end implementation
- [ ] Front-end implementation

@mdestaubin, I've assigned you thinking that you might want to propose a UI design for this.

**Comment by mdestaubin** [comment]
@jnm do you have any initial thoughts on where the disk space for both projects and username should be displayed? I'm assuming disk space per project makes most sense shown on the project landing page, but for information on total space used per account/username it's a little less clear. Maybe Account Settings?

**Comment by mdestaubin** [comment]
First round of wire frames: https://app.atomic.io/d/kRfQpOqv3878

slide 1: Project Landing Page
slide 2: Project Data Page (is landing page enough?) 
slide 3: User disk space in Account Settings pop up
slide 4: User disk space in project dashboard
slide 5: Attachment size shown in form

**Comment by joshuaberetta** [comment]
Superseded by https://github.com/kobotoolbox/kpi/issues/3097
