### ISSUE TITLE
Allow users to remove forms/assets shared with them

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2256]
## Description

As a user I'd like to remove a project from my project list that has been shared with me. At the moment, the only way to do this is if the owner changes sharing settings. But if the owner is unavailable or unresponsive, or if a project was shared in error, there is no way to remove the project (or collection/block/question) from your account.

## Steps to Reproduce

1. Share project from user 1 with user 2
2. Login as user 2 and delete project

## Expected behavior 

The modal screen should probably be different since the project isn't being deleted but just removed from user 2's account. I suggest "This will not delete the project but remove all sharing permissions for your account. Only the owner can delete the project. Are you sure you want to continue?

## Actual behavior 

![image](https://user-images.githubusercontent.com/673511/56438442-fbd02880-62b0-11e9-8306-d43fd1780557.png)

**Comment by magicznyleszek** [comment]
Blocked by #2268

**Comment by joshuaberetta** [comment]
Closed by https://github.com/kobotoolbox/kpi/pull/2945
