### ISSUE TITLE
Add (failing) unit test for library imports

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2262]
(second sim bug)

- [x] add failing test
- [x] fix it

Broken by #2000 / the fix for https://github.com/XLSForm/pyxform/issues/229

Hint: https://github.com/kobotoolbox/kpi/blob/0cde9029f37f3a8bac11f18d6f528801aefd4cca/kpi/models/import_export_task.py#L288

**Comment by noliveleger** [comment]
Just try to take a look. It's indeed broken.
PyXForm skips sheets whose names are not part of `constants.SUPPORTED_SHEET_NAMES`
https://github.com/XLSForm/pyxform/blob/8fb7934886a1e248a39eb802061e618ebceb60a4/pyxform/xls2json_backends.py#L209-L218

Tried to monkey-patch PyXform to add `library` but it still fails a little bit further.

**Comment by jnm** [comment]
pasted from https://www.flowdock.com/app/kobotoolbox/kobo/threads/x-uUMo8M2PfHGoC04PEBcDlmKz4, in the hope that it's helpful to future wanderers:

the import task is being run by Celery, which does not automatically reload when the python code changes and also logs to a separate file.
to get around that, this should work:

    ./run.py -cf exec kpi bash
    sv stop uwsgi
    ps faux # or however you like to list your processes, to make sure that runserver has actually stopped
    # kill runserver if it's still running
    SKIP_CELERY=True ./manage.py runserver_plus 0:8000

now the celery tasks should run inside the `manage.py` process instead of the celery worker processes, and your code changes should take effect right away. `print` statements and the like should appear on the screen along with all the other `runserver` output

**Comment by jnm** [comment]
here's my hack. Anji is working on a better solution\*

    diff --git a/kpi/models/import_export_task.py b/kpi/models/import_export_task.py
    index ead3644a..d2ad55aa 100644
    --- a/kpi/models/import_export_task.py
    +++ b/kpi/models/import_export_task.py
    @@ -665,7 +665,22 @@ class ExportTask(ImportExportTask):
     
     def _b64_xls_to_dict(base64_encoded_upload):
         decoded_str = base64.b64decode(base64_encoded_upload)
    -    survey_dict = xls2json_backends.xls_to_dict(BytesIO(decoded_str))
    +    #survey_dict = xls2json_backends.xls_to_dict(BytesIO(decoded_str))
    +    from collections import OrderedDict
    +    from kpi.management.commands.import_xls_to_collection import convert_xls_to_ss_structure
    +    survey_as_list_of_lists = convert_xls_to_ss_structure(BytesIO(decoded_str))
    +    survey_dict = OrderedDict()
    +    for sheet_name, rows in survey_as_list_of_lists.items():
    +        sheet_list = []
    +        row_iterator = iter(rows)
    +        header_row = next(row_iterator)
    +        for row in row_iterator:
    +            row_dict = OrderedDict()
    +            for key, value in zip(header_row, row):
    +                if value is not None:
    +                    row_dict[key] = value
    +            sheet_list.append(row_dict)
    +        survey_dict[sheet_name] = sheet_list
         return _strip_header_keys(survey_dict)

\*the modified `convert_xls_to_ss_structure()` and the new `convert_xls_to_dict()` should go into `kpi/kpi/utils`, probably in a new file there

also, don't forget to write a unit test for library collection imports (i.e. what you've fixed), and make sure it fails if you stash your other changes 😅

**Comment by jnm** [comment]
Fixed by #2887
