### ISSUE TITLE
Allow removal of one's own permissions via API

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2268]
Currently, [`ObjectPermissionViewSet`](https://github.com/kobotoolbox/kpi/blob/bebf52ff165397bef01b0f16a16c9081ee706382/kpi/views.py#L136) only allows users who have `share_` on an object to modify the permissions of that object. However, as described in https://github.com/kobotoolbox/kpi/issues/2256, users should be able to remove their own access to another object, even if they do not have `share_` for that object. We must not allow users to remove their own `deny` permissions, however.

**Comment by joshuaberetta** [comment]
Closed by https://github.com/kobotoolbox/kpi/pull/2945
