### ISSUE TITLE
Choice translations not saving

### ISSUE THREAD

**Issue by joeypedicini92** [kobotoolbox/kpi#2274]
## Description

See here: https://community.kobotoolbox.org/t/translations-not-saving/2373

Choices translations always being sent in request as null:
```
{"$kuid":"vwNHH4YSN","list_name":"bv1uy07","$autovalue":"yes","name":"yes","label":["Yes",null]}
```

## Steps to Reproduce

1. Click "edit translations"
2. Edit a choice value (questions seem to work fine)
3. Click "save"
4. You can see in the request/response it didn't save, so once you exit the modal and come back it's cleared out

## Expected behavior 

Choice translations should save properly

## Actual behavior 

Choice translations won't save

## Additional details

I'm using chrome. I only have 1 translation set. This was working when I was doing this about a month or 2 ago so seems like a recent bug

**Comment by joeypedicini92** [comment]
It appears to be caused by multiple choices using the same name (which I think is a common use case given that many of my form's questions use "Yes", "No" choices. 

This line here: https://github.com/kobotoolbox/kpi/blob/78e5ab0f238c0175db1565ff23dfc371bec73f3a/jsapp/js/components/modalForms/translationTable.es6#L113 
will always find the same item and will eventually override it to whatever the last instance of that name's value is

**Comment by joeypedicini92** [comment]
can confirm this is the issue. single instance choice names save fine

**Comment by jnm** [comment]
Thanks for the report. It looks like a missing check for `list_name` in the line that you identified.

**Comment by magicznyleszek** [comment]
Sorry for closing, I thought that fix commits only closes when merging to master 🤷‍♀ PR will fix this :)

**Comment by jnm** [comment]
This issue was mentioned on the forum, but I want to confirm that—according to my testing—the fix still works as expected :ok_hand:
https://community.kobotoolbox.org/t/second-language-text-not-saving/4158/7?u=jnm
