### ISSUE TITLE
Not able to view the collected data (under Reports) when using select one from file or select multiple from file

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2275]
## Description

I just tested the **select_one_from_file** and **select_multiple_from_file**. While testing the same I was not able to view the collected data (under Reports). 

I saw the following message: 
**This report cannot be loaded. error: <h1>Server Error (500)</h1>**

## Steps to Reproduce

1. Created a survey form with the following questions:
![image](https://user-images.githubusercontent.com/50188479/57633368-316fe500-75c3-11e9-8b5b-8f1902488328.png)
2. Then made the choices sheet with the following information:
![image](https://user-images.githubusercontent.com/50188479/57633301-12715300-75c3-11e9-840b-579be4ee7f5c.png)
3. Then created a csv file with the following choices:
![image](https://user-images.githubusercontent.com/50188479/57633693-99bec680-75c3-11e9-9694-211847de6756.png)
4. Then uploaded the xlsform as well as the csv form.

## Expected behavior 

I wasn't expecting the error message as seen below.

## Actual behavior 

I was expecting to see the data that i uploaded under the DATA>Reports but saw the following error message:
![image](https://user-images.githubusercontent.com/50188479/57633903-04700200-75c4-11e9-8b40-a704e9b1786e.png)

Besides, when trying to download the data in XLS format, i encountered the following (Export Failed):
![image](https://user-images.githubusercontent.com/50188479/57634036-47ca7080-75c4-11e9-9470-34dabfe9defa.png)

## Additional details

When downloading the data in XLS (legacy), i was able to download the data. However, even when trying to download the XLS(legacy) version of the data for select multiple from files, there seems to be a problem with the multiple choice options (e.g. if you select Apple, Watermelon and Nectarine you will be able to see only 1 2 7 under the fruits variable; but you won't be able to see complete list of variables that you generally get in a multiple choice question as you get normally. The image as a sample is as follows:
![image](https://user-images.githubusercontent.com/50188479/57635452-e3f57700-75c6-11e9-82ca-5b114bf677b8.png)

**Comment by jnm** [comment]
https://sentry.kbtdev.org/kobo/kpi-backend/issues/300733/
```
ValueError: invalid data_type: select_multiple_from_file fruits.csv
  File "django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "rest_framework/viewsets.py", line 90, in view
    return self.dispatch(request, *args, **kwargs)
  File "rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 58, in retrieve
    return Response(serializer.data)
  File "rest_framework/serializers.py", line 263, in data
    self._data = self.to_representation(self.instance)
  File "kobo/apps/reports/serializers.py", line 27, in to_representation
    _list = report_data.data_by_identifiers(obj, vnames, split_by=split_by)
  File "kobo/apps/reports/report_data.py", line 127, in data_by_identifiers
    pack, submission_stream = build_formpack(asset, submission_stream)
  File "kobo/apps/reports/report_data.py", line 60, in build_formpack
    pack = FormPack(versions=reversed(schemas), title=asset.name, id_string=asset.uid)
  File "formpack/pack.py", line 61, in __init__
    self.load_all_versions(versions)
  File "formpack/pack.py", line 119, in load_all_versions
    self.load_version(deepcopy(schema))
  File "formpack/pack.py", line 143, in load_version
    form_version = FormVersion(self, schema)
  File "formpack/version.py", line 193, in __init__
    translations=self.translations)
  File "formpack/schema/fields.py", line 165, in from_json_definition
    raise ValueError('invalid data_type: %s' % data_type)
```

**Comment by joshuaberetta** [comment]
Closed by https://github.com/kobotoolbox/formpack/pull/247
