### ISSUE TITLE
Feature: Public Collections 2.0

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2293]
## Description

Improving whole Public Collections and Library experience :)

## Additional details

Discussion and wireframes: https://community.kobotoolbox.org/t/public-collections-design-improvement/2284

## Related PRs 

[Link to whole list as Gh search](https://github.com/kobotoolbox/kpi/pulls?q=is%3Apr+is%3Aopen+base%3Apublic-collections-all)

1. #2559 - the main branch, ~~has (mostly Backend) merge conflicts~~
2. ~~#2972 - not reviewed yet by @jnm~~ backported to master, #2980
3. #2952 - ~~not~~ reviewed ~~yet~~ by @jnm
4. ~~#2946 - draft~~ built on top of public collections, but will be included in a later release
5. ~~#2941 - not reviewed yet by @duvld , Backend part not done~~
6. ~~#2928~~
7. ~~#2900 - not reviewed yet by @duvld~~ built on top of public collections, but will be included in a later release
8. ~~#2872 - reviewed, mostly fixed, some questions left for @jnm~~
9. ~~#2537 - draft~~ built on top of public collections, but will be included in a later release

**Comment by jnm** [comment]
![lizz-go](https://user-images.githubusercontent.com/2085013/106830009-33ad8900-665b-11eb-84b7-6c8222a8c225.gif)

**Comment by jnm** [comment]
Closed by #2559
