### ISSUE TITLE
Changing language seems broken

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2313]
## Description

Switching language in the Header Account menu doesn't seem to work. It just reloads page and everything is still in english. Possibly related to #2302

**Comment by jnm** [comment]
I was able to fix this locally with these commands from the `Dockerfile`:
https://github.com/kobotoolbox/kpi/blob/bb8c9d42d4182598e7c23c3cb86fb30a19b7dd9e/Dockerfile#L102-L104
We need to remember to do this when working on a local instance, but I also have to figure out why it's not happening on the staging and dev. servers.

**Comment by jnm** [comment]
This still exists, but the cookie isn't being created: https://docs.djangoproject.com/en/2.2/ref/settings/#language-cookie-name
Maybe-useful reference: https://code.djangoproject.com/ticket/21473

**Comment by joshuaberetta** [comment]
@jnm can you confirm if this is still an issue?

**Comment by magicznyleszek** [comment]
Whenever the app is loaded, Front-end code is getting the `django_language` cookie value, and is setting it to `extra_details.last_ui_language` of `/me` endpoint.

If `django_language` is not present, Front end falls back to `en`:

```ts
export function currentLang(): string {
  return cookies.get(LANGUAGE_COOKIE_NAME) || 'en';
}
```

Back end seems to fall back not to `en` but to the browser language (somehow).

**Comment by magicznyleszek** [comment]
Note: this causes the `extra_details.last_ui_language` of `/me` endpoint to give untrue values, and we use it for language usage statistics.
