### ISSUE TITLE
Display `Asset` permission names differently depending on `asset_type`

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2316]
Use the type-dependent `label` returned by `/api/v2/assets/[asset uid]/permissions/` when displaying permissions in the frontend. See https://github.com/kobotoolbox/kpi/issues/2316#issuecomment-524524123. History: https://www.flowdock.com/app/kobotoolbox/kobo/threads/FnkA7h0HnqTZ4O8WPfcf5OU0oMX

**Comment by jnm** [comment]
from @tinok, this is the per-`asset_type` naming we should use:

* asset_type = 'survey': Form
* asset_type = 'template': Template
* asset_type = 'block': Block
* asset_type = 'question': Question
* asset_type = 'collection': Collection

**Comment by magicznyleszek** [comment]
I think that `'Can view {asset_type}'` is perfectly fine, would just vote for `'Can view ##asset_type##'`, as this is an existing convention on Frontend :)

**Comment by jnm** [comment]
@magicznyleszek, I pushed [a branch](https://github.com/kobotoolbox/kpi/compare/two-databases...2316-permission-labels-by-asset-type?expand=1) where the API returns a type-dependent `label` for each _assigned_ permission, e.g. `/api/v2/assets/awu9kEjGa7AhHXaJbnJAmq/permissions/` returns something that includes:
```json
{
    "url": "http://kf.kobo.local:9000/api/v2/assets/awu9kEjGa7AhHXaJbnJAmq/permissions/pNzPwd383ypfpxjRMqkcCw/",
    "user": "http://kf.kobo.local:9000/api/v2/users/regular/",
    "permission": "http://kf.kobo.local:9000/api/v2/permissions/change_asset/",
    "label": "Change form"
},
```
Is this useful to you on the frontend? I haven't done anything with Collections yet.

**Comment by magicznyleszek** [comment]
@jnm I confirm it would be useful :) Instead of getting the name from global config based on permission codename, we would just use it directly from permission. And we should probably remove permissions `name` from `${ROOT_URL}/api/v2/permissions/` while changing this?

**Comment by jnm** [comment]
Great :) I'll make a PR for Oli. I left `name` in `${ROOT_URL}/api/v2/permissions/`, but it now returns what Django considers the "name," which we previously had in `description`. I removed `description` from the endpoint.

**Comment by magicznyleszek** [comment]
@jnm so I should create a branch from `two-databases` after #2379 is done, right?

**Comment by jnm** [comment]
Yes :)

**Comment by magicznyleszek** [comment]
As in https://www.flowdock.com/app/kobotoolbox/ux-ui/threads/FeWz58-251l3_IX7lJ1ZYPWJE1F and https://www.flowdock.com/app/kobotoolbox/ux-ui/threads/S8vu7f3BLUiblPgR2ZTOhWD2QM4 it seems this issue is about more than one thing.

We want to display type-flavored labels of permissions:

1. In the list of given user's permissions - to not use word "asset", but be more user friendly and specific:
    <img width="590" alt="Screenshot 2019-09-10 at 21 10 19" src="https://user-images.githubusercontent.com/2521888/64642858-8572c500-d40f-11e9-8244-651e55465d01.png">

2. In the permissions editor - to make the checkboxes use permissions names they are connected to:
    <img width="579" alt="Screenshot 2019-09-10 at 21 10 42" src="https://user-images.githubusercontent.com/2521888/64642880-91f71d80-d40f-11e9-89b3-714ab8890c66.png">

So #2379 is unfortunately only useful for fixing 1., but wouldn't be useful for 2.

**Comment by jnm** [comment]
Oops, yes, #2379 was somewhat counterproductive :smirk:
@magicznyleszek, @noliveleger, @tinok, let's:

- [ ] Put the mapping of asset types to labels (e.g. "survey" :arrow_right: "form") from the [comment above](https://github.com/kobotoolbox/kpi/issues/2316#issuecomment-511896354) somewhere in the `/environment` endpoint;
- [ ] Have `/api/v2/permissions/` return a `label` that includes a placeholder for the asset type, e.g. `View ##asset_type##`;
- [ ] Have the frontend interpolate those `label`s using the asset type labels from the `/environment` endpoint;
- [ ] Capitalize consistently: we seem to be using an initial-capital style (except for titles) in the currently-deployed permissions UI, e.g. "Who has access" and "Invite collaborators." The labels for permissions ("View Form", "Edit Submissions") are an exception to that, but I think we should change them to capitalize the first letter _only_;
- [ ] Banish "Can" from the permissions UI. "View form" is enough; "Can view form," especially when followed by "Can edit form, Can change form, Can view submissions" etc. is unnecessary and creates clutter.

**Comment by jnm** [comment]
…except as @magicznyleszek mentioned to me, there's already a mapping between asset types and labels on the frontend, and it calls `survey` a `project`:
https://github.com/kobotoolbox/kpi/blob/290c29b0da98414b108c609c25b02c897ac45c82/jsapp/js/constants.es6#L88-L91

This makes sense to me since an asset whose type is `survey` includes both the blank _form_ and the collected submission data. We don't want to call a `survey` asset a `form` everywhere; rather, we need to show that a `survey` asset has separate permissions for viewing its blank form and viewing its collected submissions.

**Comment by jnm** [comment]
Here we go:

- [ ] Make sure the frontend doesn't need the embedded list of assigned permissions that's currently included in `api/v2/assets` (list) and `api/v2/assets/[asset uid]` (detail)
- [ ] Remove those embedded lists
- [ ] Add `assignable_permissions` as a new embedded list in `api/v2/assets/[asset uid]` (detail)
- [ ] Populate that list with objects that each contain an `api/v2/permissions/[codename]` URL and a `label`
- [ ] Make the `label` appropriate for that particular asset object
- [ ] ? Hard-code the labels we want for collections in the front-end, instead of working on the collections API, due to #2332
