### ISSUE TITLE
Filtering validation status doesn't refresh pagination info. 

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#2319]
## Description

When you have several submissions (more than the number of rows allowed per page when data is paginated), if you want to narrow down results per their validation status, pagination doesn't change and stays the same likewise no filters were applied.

## Steps to Reproduce

1. Create a form
2. Submit data more than 10 times. (Let's say 12)
3. On Table view, display results with 10 rows per page.
4. Go to Page 2, update records to (for example) `Approved` status.
5. Go to Page 1, filter results by choosing `Approved` from the dropdown

## Expected behavior 

On header: Title should be: 1 - 10 of 10 results.
On footer: Page should be: 1 of 1 
Next button is disabled

## Actual behavior 

On header: Title is:  1 - 10 of 12 results.
On footer: Page is: 1 of 2
Next button is enabled

**Comment by arsea** [comment]
Code is ready for a PR but waiting on #2320 and #2321
