### ISSUE TITLE
When adding question from formbuilder, user can choose which collection to save it under (if any)

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#232]

**Comment by magicznyleszek** [comment]
Do we have some idea how it should work/look like? I think when Form Builder is open for library items (i.e. `/#/library/new`), we could display additional select dropdown in one of two places here:
<img width="817" alt="screen shot 2018-06-05 at 11 36 23" src="https://user-images.githubusercontent.com/2521888/40967971-b9a511e2-68b4-11e8-8419-a31b454366a3.png">

**Comment by pmusaraj** [comment]
Closing this, it's an old ticket, this has been resolved in the Library now.
