### ISSUE TITLE
Update table view after updating validation statuses if a filter is applied

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#2320]
## Description

Related to #2319, but not a bug. The message I received after having updated filtered data confused me from `Approved` to `Not Approved`.
> The query did not return any results.

## Steps to Reproduce

1. Create a form
2. Submit data more than 10 times. (Let's say 12)
3. On Table view, display results with 10 rows per page.
4. Go to Page 2 and update records to (for example) `Approved` status.
5. Go to Page 1, filter results by choosing `Approved` from the dropdown
6. Check the main checkbox in the header row. 
7. Click `Select All` 
8. Click `Update Selected`, choose a different status. 

## Expected behavior 

- Table view should refresh as an empty table, still filtered.
- The Notification ("query didn't return results") should not be displayed.

## Actual behavior 

Nothing changes and message `The query did not return any results.` is displayed

## Additional details

**Comment by magicznyleszek** [comment]
I would say that confusing messages are not good - this would be best to test and fix while working on #2319

**Comment by arsea** [comment]
Code is ready for a PR but waiting on #2326
