### ISSUE TITLE
Unassigned validation status doesn't return anything

### ISSUE THREAD

**Issue by arsea** [kobotoolbox/kpi#2326]
## Description

When filtering with the "-" status, the API call returns empty results and a count of 0.

## Steps to Reproduce

1. Go in a table that has submissions without any validation status (-)
2. Filter with "-"

## Expected behavior 
You should be able to see the submissions without a validation status.

## Actual behavior 
The table is empty and says the query didn't return results.

**Comment by noliveleger** [comment]
It seems to be a FE bug,. It doesn't send correct value to BE. 
It sends : `{"_validation_status.uid":"—"}` instead of `{"_validation_status.uid": null}`
