### ISSUE TITLE
EE URL copied into clipboard should not contain any formatting

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2333]
## Description

When using the 'COPY' button on the `/landing` page of a deployed project, the URL in the clipboard includes formatting. 

As a user when trying to paste the URL into an email or Word document I would prefer it didn't have any formatting. 

## Steps to Reproduce

1. Open deployed project
2. Click 'copy' button in 'Collect data' box. 
3. Paste into Gmail text box

## Expected output
![image](https://user-images.githubusercontent.com/673511/62152947-8fae8900-b2d1-11e9-8c9b-bb36572d6b16.png)

## Current 
![image](https://user-images.githubusercontent.com/673511/62152905-76a5d800-b2d1-11e9-9547-a3a756f3c9ba.png)

**Comment by jnm** [comment]
Alrighty-o. I see this in Chrome but not Firefox. Looks like we can pass some `options` to [`react-copy-to-clipboard`](https://www.npmjs.com/package/react-copy-to-clipboard#options--proptypesshapedebug-bool-message-string), [including](https://www.npmjs.com/package/copy-to-clipboard#api) a `format` set to `text/plain`.
