### ISSUE TITLE
`/private-media/` (used for exports) only works with session authentication

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2338]
It should allow all the methods supported by the rest of the API:
https://github.com/kobotoolbox/kpi/blob/5d5764be09b42b29c29d32b387d37ee096943e4a/kobo/settings/base.py#L285-L291

Problem is, this isn't a DRF view. Can it be made into / wrapped by a DRF view, or do we need to add some kind of middleware? The endpoint is provided by https://github.com/edoburu/django-private-storage

**Comment by noliveleger** [comment]
@jnm: Maybe what we did for `attachments` is enough?
https://github.com/kobotoolbox/kobocat/blob/bb826cc10a31d1dd512d2aecab9847641076f635/onadata/apps/viewer/views.py#L714-L727

**Comment by jnm** [comment]
@noliveleger, yeah. Maybe that logic could go into a function that gets set as `PRIVATE_STORAGE_AUTH_FUNCTION`, and we won't have to write our own view:
https://github.com/edoburu/django-private-storage/blob/v2.1.2/private_storage/views.py#L30-L31

**Comment by jnm** [comment]
Closed by #2447
