### ISSUE TITLE
ConnectionDoesNotExist at /me/

### ISSUE THREAD

**Issue by sarveshwaranj** [kobotoolbox/kpi#2339]
How to solve this problem

Request Method: | GET
-- | --
http://localhost:8001/me/
1.8.19
ConnectionDoesNotExist
The connection kobocat doesn't exist
/home/ewall-py-02/environment/kobotoolbox/local/lib/python2.7/site-packages/django/db/utils.py in ensure_defaults, line 171
/home/ewall-py-02/environment/kobotoolbox/bin/python
2.7.15
['/home/ewall-py-02/Desktop/kobotoolbox_dev/kpi',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/plat-x86_64-linux-gnu',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/lib-tk',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/lib-old',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/home/ewall-py-02/environment/kobotoolbox/local/lib/python2.7/site-packages',  '/home/ewall-py-02/environment/kobotoolbox/src/django-digest',  '/home/ewall-py-02/environment/kobotoolbox/src/formpack/src',  '/home/ewall-py-02/environment/kobotoolbox/lib/python2.7/site-packages',  '/home/ewall-py-02/Desktop/kobotoolbox_dev/kpi']

I am running kobocat in localhost:8000, kpi in localhost:8001,enketo in localhost:8002

**Comment by jnm** [comment]
This shouldn't happen with https://github.com/kobotoolbox/kobo-install. If you're trying a setup that needs special modification beyond what kobo-install can handle, try using kobo-install first and then tweaking the configuration that it creates.

To troubleshoot your setup further, please post at https://community.kobotoolbox.org/c/kobo-install.
