### ISSUE TITLE
"User not found" message during server/network failure

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2341]
When handling a failed `queryUserExistence()` request:
https://github.com/kobotoolbox/kpi/blob/57794d49f4b7a74fcb9472e55e80d095e76b7029/jsapp/js/stores.es6#L400
It would be nice to make a distinction between a network/server failure and bad user input. For example, if I disconnect from the internet and try to grant permissions, I see `User not found: [username]` for valid usernames. Since we now (#2289) display an alert (`notifyUnknownUser()`) instead of a more-ambiguous greyed-out button, it would be better to show `User not found` only when receiving a 404 from the backend.

**Comment by magicznyleszek** [comment]
This was fixed with a simple 🩹, as more general and complex solution needs to be implemented (see #2685)
