### ISSUE TITLE
form_title is not imported

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2344]
## Description

When importing an XLSForm the form_title is ignored by KPI. 

## Steps to Reproduce

1. Create new project with [no_title.xlsx](https://github.com/kobotoolbox/kpi/files/3478241/no_title.xlsx)

## Expected behavior 

form_title from settings sheet is used in the imported asset's Project Name. 

## Actual behavior 

Project Name uses file name (without extension). 

## Additional details

Seems to be regression of #473. Possibly related to #507.

**Comment by magicznyleszek** [comment]
I think the same problem could be with the change I made during https://github.com/kobotoolbox/kpi/pull/1913 - to be precise this line: https://github.com/kobotoolbox/kpi/pull/1913/files#diff-2bc16222e1a7cda9d355e231b8803691R380 - when creating new project, if you import file from url, the created project's name will be the filename.

**Comment by mpas** [comment]
Having the same issue with a form_title not being used
