### ISSUE TITLE
255 character limit error of asset title is not shown in UI

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2345]
## Description

When using a form title that is too long the user does not see any error message. The API call receives a 400 error with the relevant message (max 255 characters exceeded) but this isn't used in the UI through an alert.

## Steps to Reproduce

1. Try to change project/asset title text to very long string (255+ chars)

## Expected behavior 

User is shown error in bottom left alert.

## Actual behavior 

See [long form title not saved.mov.zip](https://github.com/kobotoolbox/kpi/files/3478293/long.form.title.not.saved.mov.zip)

**Comment by magicznyleszek** [comment]
Talking about it here: https://www.flowdock.com/app/kobotoolbox/kobo/threads/PfU4QJZGY_QLzOlQ9gmqzItGv_0 - we agreed that FE will just limit all the inputs for changing project name to not allow more than 255 chars.

**Comment by magicznyleszek** [comment]
Merged into `two-databases`, will be released with it
