### ISSUE TITLE
Improve project deletion modal

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2347]
There is some confusion with the project deletion modal. Here is an attempt to fix that:

 - [x] The second and third tick box of the modal refer to the same thing (questions/form being deleted). I suggest we remove `All questions created for this form will be deleted.`
- [x] The first item (`All data gathered for this form will be deleted.`) shouldn't be displayed if the form doesn't have any submissions

![image](https://user-images.githubusercontent.com/673511/62650793-9c605c00-b925-11e9-962f-a230c21c60c3.png)

**Comment by arsea** [comment]
PR created (https://github.com/kobotoolbox/kpi/pull/2362)
