### ISSUE TITLE
Second user with validation permission cannot validate submissions

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2348]
## Description

In a project created by user 1 and shared with user 2 (giving 'can validate' permission), user 2 is not able to validate any submissions. 

## Steps to Reproduce

1. In a deployed project with data, add 'can validate' permission to another user
2. Login as the other user
3. Go to Data>Table and try to validate any submission

## Expected behavior 

Validation status is saved. 

## Actual behavior 

* Validation status does not change in UI
* NO error message in UI
* Console shows 403 response:

![image](https://user-images.githubusercontent.com/673511/62651488-1ba25f80-b927-11e9-8312-7c5af138f758.png)

## Additional details

Maybe related to #2345, which also doesn't show BE error in UI.

**Comment by noliveleger** [comment]
It's a `kc` issue. Closing this one but use it as a reference to describe the bug.
