### ISSUE TITLE
Remove unnecessary iframe from general settings screen

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2349]
The kc iframe is no longer needed in the general settings page. It now has its own section in Media:

![image](https://user-images.githubusercontent.com/673511/62652766-1f83b100-b92a-11e9-87dc-f8d5062875cc.png)

**Comment by arsea** [comment]
I think we should also remove [this scss block](https://github.com/kobotoolbox/kpi/blob/094fea0cfb04fe8f394b8a20c18d4bba1a359ce0/jsapp/scss/components/_kobo.form-view.scss#L478).

I'm not sure why it's there and the bottom padding is ignored, making the "Delete project and Data" button stick to the bottom of the div.

What do you think @tinok ?
