### ISSUE TITLE
Improve the meta description of the default login screen for search engines

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2355]
## Description

At the moment the default login screen shows up on Google as follows: 
![image](https://user-images.githubusercontent.com/673511/62786302-4c51d880-ba90-11e9-9caa-e4975529b1eb.png)
![image](https://user-images.githubusercontent.com/673511/62786359-6ab7d400-ba90-11e9-839f-ecaf295abaea.png)

We should add some short text that replicates some of the information on https://www.kobotoolbox.org or on the registration screen (https://kf.kobotoolbox.org/accounts/register/#/)

**Comment by magicznyleszek** [comment]
Fixed by #2356
