### ISSUE TITLE
kobo-install: not returning correct link when deleting projects

### ISSUE THREAD

**Issue by arsea** [kobotoolbox/kpi#2361]
## Description

As discussed, we don't know exactly what needs to be fixed (kpi or kobocat) but we had to use a temporary patch, replacing
```
url = self.external_to_internal_url(self.backend_response['url'])
```
with
```
logging.error(self.backend_response['url'])
url = self.backend_response['url'].replace(':8088', '')
logging.error('URL')
logging.error(url)
```
in line 314 in `kpi/deployment_backends/kobocat_backend.py`

## Steps to Reproduce

1. Setup project with kobo-install
2. Create project
3. Delete project

## Expected behavior 

Project should delete

## Actual behavior 

we get this error and the project is not deleted
<img width="542" alt="Screen Shot 2019-08-14 at 10 56 52" src="https://user-images.githubusercontent.com/1126329/63100582-5b7bcf00-bf45-11e9-9031-0a4a78199a64.png">

**Comment by noliveleger** [comment]
Not related to `kobo-install`. 
This issue occurs when using `dev` mode and a custom web port. There is already a PR for this in `kobo-docker` https://github.com/kobotoolbox/kobo-docker/pull/247.
