### ISSUE TITLE
Questions dragged into group are not in the group after saving

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2380]
## Description

Copied from [flowdock thread](https://www.flowdock.com/app/kobotoolbox/support/threads/ycf4pX3b5a_3hOPAlRyQQtzKVic):

> When dragging additional questions into a group they will appear to be added ok, but if you save, close and re-edit the form these questions will no longer be inside the group. https://community.kobotoolbox.org/t/new-bug-in-kpi-when-adding-question-to-groups/4874

> The issue occurs when you put the question in the bottom of the group, it turns blue and does not stay in the group after you save, however I just found that if you place the question in the top part of the group first, they do not turn blue and they stay in the group after you save

Possibly related to #2242

**Comment by tiritea** [comment]
FYI Ive seen this behavior dragging a new question into the top, bottom or middle of a simple 2-question group.

**Comment by tiritea** [comment]
Sample form showing behavior. Drag Q2 into group and drop in at various positions.

[groupbug.xlsx](https://github.com/kobotoolbox/kpi/files/3557481/groupbug.xlsx)

**Comment by Kalyan-Lama** [comment]
**Just for the records:** Similar case reported in the forum!

https://community.kobotoolbox.org/t/errors-when-editing-groups/5137

**Comment by tiritea** [comment]
bump. Any progress on this? It does rather seriously impact building forms, as you keep losing changes when you save.

**Comment by magicznyleszek** [comment]
@tiritea I started looking into this :) I was able to reproduce it easily, so it shouldn't be extremely hard to fix 👍

**Comment by magicznyleszek** [comment]
This is done and will be released when `two-databases` is merged into `master` :+1:

**Comment by tiritea** [comment]
awesome. thnx. 👍

**Comment by jnm** [comment]
this is held up behind our big effort to deploy Python 3 & Django 2, so i backported #2441 to https://github.com/kobotoolbox/kpi/releases/tag/two-databases_2.019.49 and will deploy that on our production servers

**Comment by tiritea** [comment]
thanks for the update
