### ISSUE TITLE
[two databases] Permissions sent to BE are sometimes wrong when assigning `partial permissions`

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#2384]
## Steps to Reproduce

1. Create a form 
2. Assign User B `add submissions`, `partial View submissions` for `User B` and `User C`
3. Assign User C `add submissions`

## Expected behavior 
Permissions are saved
Payload should be: 
```
[{
	"user": "http://kpi.kobo.local/api/v2/users/userC/",
	"permission": "http://kpi.kobo.local/api/v2/permissions/add_submissions/"
}, {
	"user": "http://kpi.kobo.local/api/v2/users/userB/",
	"permission": "http://kpi.kobo.local/api/v2/permissions/partial_submissions/",
	"partial_permissions": [{
		"url": "http://kpi.kobo.local/api/v2/permissions/view_submissions/",
		"filters": [{
			"_submitted_by": {
				"$in": ["userB", "userC"]
			}
		}]
	}]
}, {
	"user": "http://kpi.kobo.local/api/v2/users/userB/",
	"permission": "http://kpi.kobo.local/api/v2/permissions/add_submissions/"
}]
```

## Actual behavior 
Permissions are not saved, Backend returns a 500.

Payload is: 
```
[{
	"user": "http://kpi.kobo.local/api/v2/users/userB/",
	"permission": "http://kpi.kobo.local/api/v2/permissions/partial_submissions/"
}, {
	"user": "http://kpi.kobo.local/api/v2/users/userB/",
	"permission": "http://kpi.kobo.local/api/v2/permissions/view_asset/"
}, {
	"user": "http://kpi.kobo.local/api/v2/users/userB/",
	"permission": "http://kpi.kobo.local/api/v2/permissions/add_submissions/"
}, {
	"user": "http://kpi.kobo.local/api/v2/users/userC/",
	"permission": "http://kpi.kobo.local/api/v2/permissions/add_submissions/"
}]
```

## Additional info.
`view_asset` is implied from `partial_submissions` or `add_submissions`. It can be omitted in that case (but not mandatory to omit)

**Comment by jnm** [comment]
@noliveleger, I've assigned you because the backend shouldn't 500 if it receives invalid permissions.
@magicznyleszek and @arsea, please decide amongst yourselves who would like to tackle the missing `partial_submissions` request data.

**Comment by noliveleger** [comment]
@jnm as per our discussion, a one-liner fix has been pushed to `two-databases for backend issue.
