### ISSUE TITLE
Use stronger confirmation modal when erasing all submissions

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2389]
Using the new [`Select all ##`](https://github.com/kobotoolbox/kpi/blob/98858c29e06b79918e6c4efa71d0ac5c9b2944a0/jsapp/js/components/table.es6#L900) feature introduced by #2321 makes it too easy to erase all submissions in a project:
![image](https://user-images.githubusercontent.com/2085013/64299297-b56d2480-cf46-11e9-8b3b-8a72f080e459.png)

We should require the person deleting to tick multiple boxes as we currently do when someone tries to delete a project. I will disable `Select all ##` prior to merging #2321, but let's bring it back after strengthening the warning modal.

**Comment by magicznyleszek** [comment]
Done in `two-databases` branch, so closing
