### ISSUE TITLE
Add /single/once option to dropdown on form landing page

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2398]
## Description

As a user I'd like to take advantage of Enketo's `/survey/single/once` feature ([see API details](https://apidocs.enketo.org/v2#/post-survey-single-once)) so that survey respondents can only submit data once to an online survey. 

We already support `/survey/single` in [`formLanding`](https://github.com/kobotoolbox/kpi/blob/b0a1d0adc186df619504ab217dd3b4d7134b0318/jsapp/js/components/formLanding.es6#L205-L208).

Label text: 
`Online-only (once per respondent) `

Description:
`This allows your web form to only be submitted once per user, using basic protection to prevent the same user (on the same browser & device) from submitting more than once.`

See #1466 for a the last round of adding EE options to the dropdown.

**Comment by magicznyleszek** [comment]
Merged into `two-databases`, will be released with it
