### ISSUE TITLE
Display API token in user account settings

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2418]
## Description

As a user I'd like to see the API token in my account settings rather than having to navigate to  https://[kpi-url]/token/?format=json. 

## Suggested UI implementation

The token could be displayed in clear text or hidden by default (e.g. clicking a 👁 button to toggle visibility). 

It could be placed under the Change Password button.

**Comment by magicznyleszek** [comment]
This is done and will be released when `two-databases` is merged into `master`
