### ISSUE TITLE
Allow users to add custom wrapper code for REST submissions

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2423]
https://www.flowdock.com/app/kobotoolbox/kobo/threads/mRpcBQgbF0_UeIgyXybyDxueOW3

- [x] FE UI work as shown below
- [x] FE interchange with "Add custom wrapper" using `hook` attribute called `payload_template`
- [x] BE uses template when `POST`ing to external server (@noliveleger)

## Description

As a user I'd like to be able to submit data to AirTable and similar services. AirTable requires a wrapper around the actual JSON submission, which I would like to specify in the UI when creating a new REST service. 

## Suggested UI design

![image](https://user-images.githubusercontent.com/673511/65622489-c16f6380-df93-11e9-8f25-d67ff9a34fd6.png)

## Example wrapper code 

```
{
    "fields":  %SUBMISSION%
}
```

**Comment by magicznyleszek** [comment]
Merged into `two-databases`, will be released with it
