### ISSUE TITLE
Improve basic auth fields in REST service modal

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2428]
When a user selects "Basic authorization" in the Security section of the Edit REST Service modal, the username and password fields are shown in the wrong location: They are shown below the `Select fields subset` section instead of above it.

Instead, username and password fields should be displayed right below the Security dropdown. 

![image](https://user-images.githubusercontent.com/673511/65979298-0afff880-e443-11e9-9dfb-75d3e1a2bed5.png)

**Comment by jnm** [comment]
Hey @duvld, I think you did this already :smile:
Please open a PR using `two-databases` as the base branch when you have a chance. Ping me on Flowdock if you have any trouble. Thanks!
