### ISSUE TITLE
When printing from the single record view, make sure multi-line responses are not cut off

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2437]
Might require adding new appearance to text questions, e.g. `overflow`

(converted from note by @jnm

**Comment by magicznyleszek** [comment]
@tinok could you please add a reproduction steps :) I'm not very familiar with printing

**Comment by tinok** [comment]
@magicznyleszek Here is an example: The paragraph text in the right column is only shown up to the page break. 

![image](https://user-images.githubusercontent.com/673511/72375454-1fa68a80-36da-11ea-96bd-92ff52eed102.png)

While testing I found that the single record view isn't currently printing the entire record--only the first page -- twice.

**Comment by tinok** [comment]
I'm closing this issue since the original report applies to printing from Enketo, not the kpi single submission view. So this is being replaced by both https://github.com/enketo/enketo-express/issues/128 and kpi#2551.
