### ISSUE TITLE
Filtering by blocks results in 504 timeout for specific user account

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2438]
## Description

When filtering block assets for a particular user the server responds with 504.

## Steps to Reproduce

1. Go to question library for user `tinokreutzer` on HHI
2. Choose blocks in filter dropdown, OR
3. go to https://kf.kobotoolbox.org/api/v2/assets/?q=asset_type%3Ablock&limit=200

## Expected behavior 

Blocks are displayed in list

## Actual behavior 

Server times out, user sees error message (failed to list assets) and console shows 504 response.

## Additional details

The account has 449 library assets and loads fine for the default view (limited to 200).

**Comment by noliveleger** [comment]
@tinok, I think this is fixed within the public collection branch, isn't it?

**Comment by tinok** [comment]
@noliveleger There is no filter button anymore for only displaying blocks. What is the search syntax that would achieve the same?

**Comment by noliveleger** [comment]
@tinok: `?q=asset_type:block`

**Comment by noliveleger** [comment]
The problem does not occur anymore (as time of writing). It's possible the server was overwhelmed at this moment.
`kf.beta`. The response time is twice as fast as production with less CPU and RAM resources. 
I'm closing this issue.
Tino, feel free to reopen it if you still face the issue (after public-collections release)
