### ISSUE TITLE
File select button unavailable after failed import of xlsform

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2445]
## Steps to Reproduce

1. create an xlsform file where the survey sheet is called `not_survey` (or use [wont_upload.xlsx](https://github.com/kobotoolbox/kpi/files/3708319/wont_upload.xlsx))
2. in kpi: New > upload from xls > choose file
3. form import will fail, asking user to correct xlsform file (which needs to contain a `survey` sheet)

## Expected behavior 

User can click on Select file to upload button again to choose updated / different file

## Actual behavior 

User can't select file again; button still shows "uploading file...". 
ALSO: the "Back" button is disabled in this case. 

![image](https://user-images.githubusercontent.com/673511/66498267-cbad5980-ea8b-11e9-9854-d8c5316b4872.png)

**Comment by magicznyleszek** [comment]
Merged into `two-databases`, will be released with it
