### ISSUE TITLE
Feature: email integration on browser

### ISSUE THREAD

**Issue by ellieallien** [kobotoolbox/kpi#2459]
## Description
The feature would allow sending a copy (as csv) of responses to an email adress specified by the user, in the same way as is possible through Android application.  The request has been [posted here](https://community.kobotoolbox.org/t/copy-of-submitted-form-to-respondent/3206), and I believe the api would be the easiest way to access it. 
`ideas`

**Comment by joshuaberetta** [comment]
Refer to the linked thread in the community for discussion.
