### ISSUE TITLE
Unable to retrieve or add REST service with change_asset permission 

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2461]
## Description

A user who is not the project owner but has `change_asset` permissions cannot retrieve or add REST services. 

## Steps to Reproduce

1. Create project with user 1
2. Add REST service
2. Sharing with user 2, give all possible permissions (including change_asset _and view_submissions_)
3. Sign in as user 2 
4. Try to see first created REST service
4. Try to add new REST service

## Expected behavior 

User 2 can add new REST service. 
User 2 can see first created REST service. 

## Actual behavior 
User sees error message; error in the console. 

![image](https://user-images.githubusercontent.com/673511/67136595-4c8bf400-f1f6-11e9-9b40-af31ef8cdd5b.png)

**Comment by magicznyleszek** [comment]
@magicznyleszek note to self: disable access to anything REST Services related for non-owners

**Comment by jnm** [comment]
Update: we'll show REST Services only to those with `view_submissions` and `change_asset`? People with `partial_submissions` should not have access. I'll make the needed back-end changes.
