### ISSUE TITLE
Question: `type`s in model.configs.coffee

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2467]
Does it make sense to you that this always uses the name as the type? In https://github.com/kobotoolbox/kpi/blob/2187-audit/jsapp/xlform/src/model.configs.coffee, there's a `type` inside the `asJson` object for each setting, but I can't tell where that's used for anything except this one check: https://github.com/kobotoolbox/kpi/blob/f62a0c58a0b4c90c6e5a96182feb86a54a74dcfb/jsapp/xlform/src/model.surveyFragment.coffee#L346-L356

Of course, all the `name`s in the `asJson`s happen to be identical to the `type`s :slightly_smiling_face:

_Originally posted by @jnm in https://github.com/kobotoolbox/kpi/pull/2429_

**Comment by tinok** [comment]
For the audit meta question at least, the type and name both need to be `audit`. I'm not sure that's a requirement for `start`, `today`, etc.
