### ISSUE TITLE
Unable to view project data with shareable link 

### ISSUE THREAD

**Issue by mdestaubin** [kobotoolbox/kpi#2480]
Bug initially [reported](https://community.kobotoolbox.org/t/view-submissions-permission-for-anonymous-user-not-working/6009) by KoBo community member [raphaelmerx](https://community.kobotoolbox.org/u/raphaelmerx/summary)

## Description

I have a form with publicly accessible submissions at https://kf.kobotoolbox.org/#/forms/akBmyLiqU9UNjLhHdqs9Ma/landing 1. Until recently all Kobo users could access submission data for this form in the Data > Table tab. Now they can access the Data > Reports tabs, but all other tabs under Data show “Access Denied”

## Steps to Reproduce

1. Create a form, make submissions publicly accessible
2. Log in as a user that isn’t part of the “Who has access” list
3. Try accessing submission data through the /forms/<form_id>/data/table URL. It shows “Access denied”

## Expected behavior 

All users can see submission data for a form that has public submissions.

## Actual behavior 

Users that are not explicitly added in the sharing tab are denied access to submission data.

**Comment by jnm** [comment]
Fixed by #2481
