### ISSUE TITLE
Logout all user sessions after password change

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2486]
As a survey admin, I want to make sure anyone else using my account is logged out as soon as I change my account password in order to protect collected data. 

I would also like to sign out all other users even if I don't change my password (similar to Gmail feature) 

## UX flow
1. Log in to User1 on computer 1 and computer 2 (or different browsers)
2. Go to profile, modify password
3. User on computer 2 should be redirected to login page (as soon as next request is made).

Relevant settings file: 
https://github.com/kobotoolbox/kpi/blob/7b5a1e708d5436d6d6348eb9066ae223507fc4ef/kobo/settings/base.py#L112-L114

**Comment by magicznyleszek** [comment]
@tinok is this a duplicate of https://github.com/kobotoolbox/kpi/issues/2258 ?

**Comment by tinok** [comment]
@magicznyleszek it is indeed. I'm closing this and moved relevant details to the original issue.
