### ISSUE TITLE
Create new 'edit without deleting' permission

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2488]
As a survey admin, I  would like to allow one of my team members to edit submissions but not delete them so that I don't have to worry about accidental data loss. 

At the moment (after #2367) any user with 'edit submission' rights can also delete submissions.

**Comment by noliveleger** [comment]
@tinok, will new `delete submission` permission imply `edit submission` or they have to be separated?
Does this logic have to be applied to KoBoCat too?  I guess the answer is yes, but for some reasons, we could want to keep old behaviour on KoBoCat and just modify KPI's API.

**Comment by tinok** [comment]
@noliveleger The new permission should be `edit without deleting` -- not `delete`. The current `edit submission` permission should be left as it is in kc and kpi. The new permission should allow modifications to existing data but not deleting rows or all data.

**Comment by noliveleger** [comment]
As per our discussion: 

> we will add a new delete permission, and then everyone who currently has the change permission will be assigned the delete permission as well.
> In the future, though, to get the current behavior of "change", the survey admin will have to add both "change" and "delete"
