### ISSUE TITLE
Remove `return`s from `__init__()`s

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2510]
They're useless and only pass muster when the returned value is `None`.

The interpreter is explicit in Python 2 and 3:
```
TypeError: __init__() should return None, not [blah]
```
This would fail if somehow the ancestor's initializer returned something other than `None`. We should remove `return`s from all `__init__()`s.

This was probably me not being attentive to the difference between [`__new__()`](https://docs.python.org/3/reference/datamodel.html#object.__new__) and [`__init__()`](https://docs.python.org/3/reference/datamodel.html#object.__init__).

_Originally posted by @jnm in https://github.com/kobotoolbox/kpi/pull/2504_

**Comment by noliveleger** [comment]
They've been removed in #2508.
