### ISSUE TITLE
REST Services fails to notify editions

### ISSUE THREAD

**Issue by kryptt** [kobotoolbox/kpi#2515]
## Description

When editing a submitted form. Rest Service calls about the edition are unreliable

## Steps to Reproduce

1. Setup Rest Services on a form
2. Submit an instance (I did it via Enketo)
3. Edit the submitted instance (also from the generated enketo view)

## Expected behavior 

At least 2 Calls should be made to the registered Rest Service: 
1. for the initial submission of the form
1. another corresponding to the submission of the editted response

## Actual behavior 

Sometimes only 1 submission is made. Only the initial submission seems to be reliable.

## Additional details

Whenever the edit is made, at least the meta/deprecatedId field is correctly set.

**Comment by noliveleger** [comment]
Hi @kryptt,
Data is submitted to external REST Services only once (one submission is created). 
Nothing is sent after editing an existing submission. 
Please have look at [this related issue](https://github.com/kobotoolbox/kobocat/issues/572#issuecomment-531913895)

**Comment by kryptt** [comment]
@noliveleger Oddly enough, I was able to sporadically get the service to be called. So there is a bug either way. It is easy enough to identify a new submission vs an edit entry, to I'm inclined to fix things in the direction of always posting...

**Comment by noliveleger** [comment]
Have you faced the issue on your own server or one we support (kf.kobotoolbox.org, kobo.humanitarianresponse.info)? 
We identified an issue that submission was never sent to external service when the notification of a new submission was not sent to KPI. (e.g. communication error between KoBoCat and KPI)
We plan to rewrite the way RESTService work. https://github.com/kobotoolbox/kpi/issues/2501

**Comment by kryptt** [comment]
Hi @noliveleger on our own deployment using kobo-install. 

Cool, I will track that issue for more info (If I were more of a python developer I would love to see how I could help out more.. )

**Comment by noliveleger** [comment]
I'm closing the issue.  Re-open it if you find out what fails on your side (and it's a KPI bug obviously ;-) )
