### ISSUE TITLE
Include __version__ field in xls/csv exports

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2517]
In general: are there any columns we legitimately want to exclude from exports or the table view? I believe that the table view already has a UI to hide columns if desired. —jnm

## Description

As a user I want to see the version ID for each submission in my XLS and CSV tables so I can attribute the data to different deployed form versions.

## Expected behavior 

__version__ column is included at the beginning of the metadata section (just like in kobocat exports).

## Additional details

Optional, but we could also export the _notes and _tags columns available in KC but not in KPI since users may have stored something there through the KC API.

**Comment by jnm** [comment]
Also should include `_submitted_by`

**Comment by jnm** [comment]
and `_status` :sunglasses:

**Comment by Kalyan-Lama** [comment]
Community link: https://community.kobotoolbox.org/t/submitted-by-field-not-showing-up-in-xls-download-file/15567

**Comment by jnm** [comment]
Closed by #2968
