### ISSUE TITLE
Don't show red warning for groups without labels

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2526]
## Description

Currently, the formbuilder requires a label for all groups and shows a red error if a group has no label, whereas xlsform allows unlabeled groups. This makes it confusing for users to use the formbuilder when a form needs logical groups that shouldn't be visible in Collect or Enketo. 

For example: 
* a group around questions for a particular household member that should be displayed only the person is older than 30 
* a group around 4 questions to force a new row in Enketo's grid theme format

## Steps to Reproduce

1. Create questions
2. Create group around questions
3. Remove the default 'Group' label

## Expected behavior 

User sees no text in group title, and does not see any errors. 
![image](https://user-images.githubusercontent.com/673511/72749929-6805f280-3b89-11ea-8707-51a4283bcc0f.png)

## Actual behavior 

Form shows `Group title is required`. 

## Additional details

See https://github.com/kobotoolbox/kpi/issues/950.

**Comment by duvld** [comment]
Not sure if this is what you're looking for, but if the form is saved anyway regardless of the error shown the group has no label when looking at a data entry:
![Screen Shot 2020-01-16 at 1 28 57 PM](https://user-images.githubusercontent.com/16762675/72552120-2fea7100-3864-11ea-8140-09e08bf28ee2.png)

**Comment by tinok** [comment]
@duvld You're right, the formbuilder does allow saving the form despite the red error. I will change the name and description of the issue slightly.
