### ISSUE TITLE
Toast message appears twice on assigning permissions failure

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#2527]
It seems to be 2 different messages because the case in not the same and usage of plural.
`failed to remove permission` vs `Failed to remove permissions` 

<img width="786" alt="Screen Shot 2019-12-04 at 09 55 23" src="https://user-images.githubusercontent.com/24226825/70153167-8157eb80-167c-11ea-9ca2-f501d4d7aa70.png">

## Steps to Reproduce
A bug (#2528) in the backend led to this issue

1. Create a collection
2. Create a form 
3. `PATCH` the form with collection's hyperlink identity url
``` 
{
    "parent": "http://kf.kobo.local/api/v2/assets/{collection_uid}/"
}
````
3. Make the collection `PUBLIC`
4. Uncheck `Anyone can view this form` from sharing modal of the form

**Comment by magicznyleszek** [comment]
@noliveleger this is on `two-databases` branch correct?

**Comment by noliveleger** [comment]
yep, but precisely `2529-denied-permissions-exposed`

**Comment by duvld** [comment]
it looks like the plural message is called during the same fail state as the non-plural message:
* non-plural: https://github.com/kobotoolbox/kpi/commit/798719c0749a340b3ec174a1306dd934e567e855
* plural: https://github.com/kobotoolbox/kpi/commit/5c9d786f4d5edb8d292b7cbd77c69b13a44c476b
namely the case when `permissionsActions.removeAssetPermission` fails. The plural message is added after the non-plural one, do we think we can remove the non-plural notify?

**Comment by magicznyleszek** [comment]
@duvld let's remove both `notify(t('failed to remove permission'), 'error');` from `permissions.es6` and keep the ones in `actions.es6`
