### ISSUE TITLE
Assets endpoint sorting

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2539]
## Description

`/api/v2/assets/` should allow for sorting by:
- `settings.country`
- `asset_type`
- `settings.languages`
- `date_modified`
- `name`
- `settings.organization`
- `owner__username`
- `settings.sector`
- `subscribers_count`

Could be `sort={"owner__username":-1}` to be consistent with submissions endpoint, but it's not a fixed requirement.

## Additional details

Requirement for #2293

**Comment by noliveleger** [comment]
@magicznyleszek, as per our discussion: 

- `settings.country`
- `summary.languages`
- `settings.organization`
- `settings.sector`
won't be used to sort list.
