### ISSUE TITLE
Printing single record shows only questions on first page (twice)

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2551]
## Description

When trying to print a complete single record, only the first page is included (twice). 

## Steps to Reproduce

1. Open project with at least 20 questions and some data
2. Data > Table > Click on any single record
3. Use browser function to print (e.g. to PDF).

## Expected behavior 

Entire record is printed, including all questions and responses. 

## Actual behavior 

Only the questions that fit on the first page are included, but they are also repeated on page 2. 

## Additional details

Regular single record view:
![image](https://user-images.githubusercontent.com/673511/72375904-f5a19800-36da-11ea-8a84-d4391a601b55.png)

Same record printed to PDF: 
![image](https://user-images.githubusercontent.com/673511/72376111-6a74d200-36db-11ea-8f0c-90394048279e.png)

**Comment by magicznyleszek** [comment]
This will be closes as soon as `two-databases` is merged
