### ISSUE TITLE
Ignore or reset `map_styles` if it references a non-geo question

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2558]
`Invalid LatLng object: (АХ, 3401ВМ)` crashes the map and makes it impossible for the user to reset the map styles: https://sentry.kbtdev.org/kobo/kpi-frontend/issues/306249/.

https://www.flowdock.com/app/kobotoolbox/support/threads/UIW_CFgYidVCrXUFarQatVaaGT5
https://community.kobotoolbox.org/t/could-not-load-gps-data-on-view-on-map/3234/10

Guess as to how this happened:

1. Form has Cyrillic labels, so all question names are autogenerated and consist only of underscores and numbers;
1. A question named `__046` was a geo question in a previous version;
1. While that version was current, `map_styles` was set to `{u'colorSet': u'a', u'selectedQuestion': u'__046'}`;
1. The `__046` question was changed to type `text`;
1. Non-geo data `АХ, 3401ВМ` was entered as responses to `__046`;
1. The map crashed trying to process those responses.

**Comment by magicznyleszek** [comment]
This was done on `two-databases` and will be closed when it is merged to `master`
