### ISSUE TITLE
Drop object-assign package

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2584]
## Description

We use `object-assign` package to have the new ES `Object.assign` functionality. But `@babel/polyfill` is already ~~fixing~~ polyfilling all `Object.assign` usages.

What to do exactly? 
1. Drop the package from the code
2. Find all `assign(` calls and change them to `Object.assign(`
3. Stop importing `assign` defined in `utils.es6`

Ideally wait for `two-databases` and `public-collections-all` to be merged, to avoid leftovers.

**Comment by p2edwards** [comment]
Done in #4659
