### ISSUE TITLE
Updated asset title are not stored properly

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2586]
## Description

When making changes to the asset titles there is a lag between the different PATCHes that means that anything typed after a PATCH was sent is lost until the server responds to the request. 

Each PATCH request takes 1-6 seconds so there are a lot of edits that will not be saved this way. 

## Steps to Reproduce

1. Give a form a long title like "This is a long form title and I'm about to edit it"
2. Quickly change different characters or words 

## Expected behavior 

All edits are saved and displayed normally.

## Actual behavior 

Only some edits are stored. Some edits are ignored and overridden (unless they are done very slowly (doing no keystrokes for several seconds).

## Additional details

See screencast. 
[asset title update.mov.zip](https://github.com/kobotoolbox/kpi/files/4300322/asset.title.update.mov.zip)

**Comment by tinok** [comment]
Maybe the easiest solution from a UI perspective would be an old fashioned Save button?

**Comment by magicznyleszek** [comment]
We could also add some small spinner inside/next to asset title input (or some other indication for user) that will be displayed when there are unsaved changes. FYI on `public-collections-all` branch that John is reviewing I made the [header title editor](https://github.com/kobotoolbox/kpi/blob/9a30c1776e5b1a501e88677e5bdadc7dc958689e/jsapp/js/components/header/headerTitleEditor.es6) save changes only after 1,5 second after user stops typing or after user hits ENTER .

**Comment by tinok** [comment]
That sounds like a solution to me then. Wait 1.5 sec before saving or after user hits enter. Guess we can close this issue?

**Comment by magicznyleszek** [comment]
I could mark the Pull Request for Public Collections to close this issue :)

**Comment by jnm** [comment]
Fixed by #2559
