### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2590]
## Description

**No JSON object could be decoded** error message seen when trying to deploy a form in KoBoToolbox.

## Steps to Reproduce

1. Construct an xlsform with ``{age}>15 instead of ${age}>15 under the relevant column`` **(scenario 1, xlsform attached below)** or ``{age}>15 instead of ${age}>15 under the constraint column`` **(scenario 2, xlsform attached below)**  or ``${Q2}=!${Q1} instead of ${Q2}!=${Q1}`` **(scenario 3, xlsform attached below)**
2. Upload the xlsform.
3. Deploy the xlsform.
4. Error message seen.

## Expected behavior 

Show an error message that the variable {age} is not properly named with the row number where this typo occurred instead of simply giving an error message **No JSON object could be decoded**.

## Actual behavior 

See an error message **No JSON object could be decoded** as shown in the image below:

![image](https://user-images.githubusercontent.com/50188479/76335807-28ec5600-631d-11ea-9c4e-20f5b14d15b9.png)

## Additional details

**xlsform for scenario 1:**
[Test JSON Error Message (Scenario 1).xlsx](https://github.com/kobotoolbox/kpi/files/4313621/Test.JSON.Error.Message.Scenario.1.xlsx)

**xlsform for scenario 2:**
[Test JSON Error Message (Scenario 2).xlsx](https://github.com/kobotoolbox/kpi/files/4313623/Test.JSON.Error.Message.Scenario.2.xlsx)

**xlsform for scenario 3:**
[Test JSON Error Message (Scenario 3).xlsx](https://github.com/kobotoolbox/kpi/files/4567626/Test.JSON.Error.Message.Scenario.3.xlsx)

**Comment by jnm** [comment]
Probably caused by https://github.com/kobotoolbox/kobocat/issues/545

**Comment by joshuaberetta** [comment]
The three example XLSForms now give a more useful error message on an attempt to deploy:
1.
<img width="548" alt="Screen Shot 2021-09-10 at 4 38 04 PM" src="https://user-images.githubusercontent.com/50016008/132928069-d51bd01f-4f78-45fe-8972-7864b4a949b6.png">
2.
<img width="538" alt="Screen Shot 2021-09-10 at 4 38 34 PM" src="https://user-images.githubusercontent.com/50016008/132928075-85e086a2-157e-4200-a60e-b7b135820475.png">
3.
<img width="540" alt="Screen Shot 2021-09-10 at 4 39 12 PM" src="https://user-images.githubusercontent.com/50016008/132928084-8126dde8-e9cf-42f2-89a3-37505fe268c5.png">
