### ISSUE TITLE
Set up new UX/UI documentation (Google Doc)

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/kpi#2613]
Create and develop documentation defining the purpose of both the UX role for KoBo Toolbox as a whole and the purpose of the documentation itself. This document will also cover:

- Workflows and how the UX work integrates with the rest of the team
- General research strategies and when to use them
- Styles and overall design guidelines for KoBo
- Components and UI
- Links to standards and useful resources

This card will be updated over time as the needs evolve

**Comment by magicznyleszek** [comment]
Alternatively you can also set up documentation on https://github.com/kobotoolbox/kpi/wiki :) It's markdown and you don't need to fight with google docs 😛

**Comment by Ig-Rebollo** [comment]
That's actually a much better idea... thanks for the tip Leszek!

**Comment by Ig-Rebollo** [comment]
@tinok this is the [initial draft of the framework](https://docs.google.com/document/d/1D5Ry3GFqNtg5dn3ajCOeYweYiv8bi8rg_TNgIlJ814k/edit?usp=sharing) I mentioned. I have been putting it together in the last week, and still needs to be developed much further, but I think it is a good starting point. 

Let me know what you think and feel free to comment directly on the document.
