### ISSUE TITLE
An endpoint with all user tags

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2624]
## Description

Frontend needs an endpoint that will return a list of all tags from all user assets. E.g. if I have "Form A" with three tags `["done", "short", "simple", ]`, and "Form B" with two tags `["done", "long" ]`, the endpoint would return `["done", "long", "short", "simple"]`.

This endpoint is needed for an autocomplete/suggestion feature #161. It would be called only when user starts editing tags.

See also: #308

**Comment by joshuaberetta** [comment]
moved to: https://www.notion.so/kobotoolbox/Advanced-improved-asset-tag-management-9f4083794c2a4a71aeb097c1b8111be3
