### ISSUE TITLE
An endpoint with a list of pending imports

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2625]
## Description

It should return a list of pending imports for user uploaded files and for URL imports too. Every import should have at least these pieces of information:

- uploaded filename or uploaded URL
- date import started
- status (pending, error, …?)

Do we want a retry option on failed ones? From a FE standpoint it could be similar in architecture to the REST Services endpoint.

Needed for #476 and partially for #1981 .

**Comment by joshuaberetta** [comment]
moved to: https://www.notion.so/kobotoolbox/Give-user-feedback-on-status-of-background-library-imports-93f987e37d964cbb9add4f8320d08879
