### ISSUE TITLE
Bug in sharing permissions feature in KoBoToolbox (in both OCHA as well as HHI server)

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2646]
## Description

Sharing permissions can be edited by users other than the project owner/admin (with whom the project is being shared). 

## Steps to Reproduce

1. Assume you have 2 accounts `Account A` and `Account B`. 
2. Create a form named **Test Project** in `Account A` and share it with `Account B` with the following permissions: **View form + Edit form + View submissions**.
3. The person holding `Account B` is able to add other features by him/herself (i.e. without requesting `Account A` to provide him/her with the access to other permissions) viz. **Add submission**, **Edit and delete submissions** and **Validate submissions**.

## Expected behavior 

A user should not be able to add other permissions (by himself/herself) not granted by the project owner (who have shared the survey project with the user).

## Actual behavior 

Users are able to add permissions (by themselves) not granted by the project owner. This could be a risk to the project data.

## Additional details

If you simply provide **View form** access or a combination of **View form + Edit form** access or a combination of **View form + View submissions** access or a combination of **View form + Add submissions** access or combination of **View form + View submissions + Add submissions** access from `Account A` to `Account B`, `Account B` is still not able to add other permissions by him/herself. i.e. these combination does not have error so far!

For detail please visit the community forum [**here**](https://community.kobotoolbox.org/t/sharing-permissions-can-be-edited-by-added-users-not-owner-admin/8982).

**Comment by noliveleger** [comment]
As per discussed, as of today, that's the correct behaviour. 
When users received `Edit Form`, they can edit permissions without owner's authorization.

To avoid confusion, a message could be displayed when checking `Edit Form` telling users about permission until we decide to add a new permission to edit permissions.

@Kalyan-Lama found a bug that prevents granted users to see `Media`, `Sharing` and `Rest Services` menus in `Settings`. I'll open a new issue for that.
