### ISSUE TITLE
Single submission screen returns blank when clicking quickly on Next

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2669]
## Description

When a user quickly clicks on the Next button within the single submission view, a blank modal sometimes appears instead of the next record. Right before the single submission screen comes back blank the main table is reloaded (instead of the single submission). 

## Steps to Reproduce

1. Open first record in table view
2. Quickly click on Next

## Expected behavior 

Second record opens.

## Actual behavior 

Blank modal window without data record.

## Additional details

This doesn't always happen but generally seems to be related to how quickly the user clicks on Next.

**Comment by magicznyleszek** [comment]
After some debugging and clicking heavily I've discovered that speed isn't the issue, but clicking the small arrow is:

<img width="266" alt="Screenshot 2020-05-15 at 22 06 11" src="https://user-images.githubusercontent.com/2521888/82091919-8ecbd400-96f8-11ea-8e17-54412fa6d30b.png">

Fix is coming :)
