### ISSUE TITLE
Fetch old form media from KoBoCAT

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2675]
Since KPI is going to be handling form media (#2487, #2537, #2673, #2674) we need a way to get existing form media files from KoBoCAT into KPI. Note that some KoBoCAT `XForm`s simply won't have any corresponding KPI `Asset`, and ~~we should ignore those~~ [we can't ignore them if we're taking away the settings interface in KoBoCAT]. This is kind of like `sync_kobocat_xforms` :neutral_face: although we have no intention of running it periodically.

**Comment by jnm** [comment]
Idea: "deleted" flag on KPI media file object
1. unicorn.png is a media file that was uploaded to KPI
1. person wants to delete unicorn.png; UI or whatever sends HTTP DELETE to KPI back end
1. KPI deletes unicorn.png from storage immediately, and sets "deleted" flag to true on media file object associated with unicorn.png
    * we must hide all media file objects that have the "deleted" flag set to true
1. person redeploys their magical creatures form that previously had unicorn.png in it
1. because unicorn.png media file object is marked as deleted, KPI sends HTTP DELETE to KoBoCAT to remove unicorn.png
1. once KPI receives successful response (or maybe 404 too; see form deletion logic), KPI removes the unicorn.png media file object entirely from the database

this would solve the issue of KoBoCAT media getting unintentionally trashed after we deploy KPI media file handling, but it would not make any of the old KoBoCAT media visible in KPI.

**Comment by jnm** [comment]
i think this is related *enough* to stash here to avoid forgetting about it:

1. the kpi database cannot enforce uniqueness because the filename comes from either the `content` (for an uploaded file) or the `metadata` (for a URL)
1. however, kobocat does enforce uniqueness (of uploaded files and URLs separately?)
1. there are possibly sticky situations where a user would have to go into the kobocat ui and remove a file to solve a conflict(?)
1. can we generally fix this by adding some new parameter to the kobocat endpoint for form media file uploads that would allow overwriting a file with the same name instead of failing with an `IntegrityError` (or whatever it does now)

_Originally posted by @jnm in https://github.com/kobotoolbox/kpi/pull/2537#discussion_r608792158_

**Comment by joshuaberetta** [comment]
> Idea: "deleted" flag on KPI media file object
> 
>     1. unicorn.png is a media file that was uploaded to KPI
> 
>     2. person wants to delete unicorn.png; UI or whatever sends HTTP DELETE to KPI back end
> 
>     3. KPI deletes unicorn.png from storage immediately, and sets "deleted" flag to true on media file object associated with unicorn.png
>        
>        * we must hide all media file objects that have the "deleted" flag set to true
> 
>     4. person redeploys their magical creatures form that previously had unicorn.png in it
> 
>     5. because unicorn.png media file object is marked as deleted, KPI sends HTTP DELETE to KoBoCAT to remove unicorn.png
> 
>     6. if other media files exist for the magical creatures form in KoBoCAT but not in KPI, they will _not_ be deleted*
> 
>     7. once KPI receives successful response (or maybe 404 too; see form deletion logic), KPI removes the unicorn.png media file object entirely from the database
> 
> 
> *this would solve the issue of KoBoCAT media getting unintentionally trashed after we deploy KPI media file handling, but it would not make any of the old KoBoCAT media visible in KPI.

@noliveleger, it seems as though this currently isn't the behaviour of KPI's form-media — have things changed since this comment?

cc @jnm

**Comment by noliveleger** [comment]
@joshuaberetta, au contraire mon frère, it's exactly how KPI's form-media works. At least in the latest version.

**Comment by joshuaberetta** [comment]
Interesting... I'll test it again on one of the other branches then 👌
