### ISSUE TITLE
Nest the report detail view inside the v2 asset endpoint

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2679]
`/reports/` was probably added when it was difficult to write nested endpoints. Times have changed!

The `/reports/` list view seems never to be called by our front-end code, and it's basically an incomplete re-implementation of the asset list view that also filters for deployed assets and `view_submission`/`partial_submission` privileges. The front end always directly queries the `/reports/{asset uid}/` detail view.

Also, this is problematic **(and is now fixed by #2680)**:
https://github.com/kobotoolbox/kpi/blob/1acf9a54ae80816d5b2c5f087fdde45d4e3118d1/kobo/apps/reports/views.py#L35-L37
We shouldn't be serving up a list of all assets with public data, only the assets that have public data _and_ are inside a discoverable collection. Again, this is an incomplete redo of the asset list view: contrast with the handling of `all_public` in [`KpiObjectPermissionsFilter`](https://github.com/kobotoolbox/kpi/blob/8b930f5d871feafd31077327b311396d7108c2c4/kpi/filters.py#L31).

**Comment by magicznyleszek** [comment]
@jnm do we neeed to create a GH issue for FE to adapt to new endpoint?
