### ISSUE TITLE
App crashes when trying to view the map for a project without any geographic questions

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2682]
## Description
Where previously we showed `The map is not available because this form does not have a "geopoint" field.` (current behavior on kf.kobotoolbox.org), we're now crashing on kf.master.kbtdev.org. This is possibly related to #2670.

Exception: `TypeError: e.label is undefined`
Sentry: https://sentry.kbtdev.org/kobo/kpi-frontend-dev/issues/309411/
```javascript
      requestData(map, nextViewBy = '') {
        // TODO: support area / line geodata questions
        let selectedQuestion = this.props.asset.map_styles.selectedQuestion || null;
        this.props.asset.content.survey.forEach(function(row) {
          /******* NEXT LINE FAILS *******/
          if (row.label !== null && selectedQuestion === row.label[0] && row.type !== QUESTION_TYPES.get('geopoint').id) {
            selectedQuestion = null; //Ignore if not a geopoint question type
          }
        });
        let queryLimit = QUERY_LIMIT_DEFAULT;
```

## Steps to Reproduce

1. Create a form _without_ any geographic questions
2. Deploy it
3. Collect some data
4. Click on Data
5. Click on Map

## Expected behavior 

A message tells me there's nothing to show on a map.

## Actual behavior 

The application crashes.

**Comment by magicznyleszek** [comment]
Fixed by #2683
