### ISSUE TITLE
Permissions config not ready crashes app

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2684]
## Description

This happens before permissions config is needed for all permissions related checks on frontend (so anything related to displaying asset stuff) and it will throw when not ready.

```
Permission config is not ready or failed to initialize!
```

I implemented two fixes for that, but it seems that not all cases were covered:

1. #2660
2. https://github.com/kobotoolbox/kpi/commit/19ed38669b2b6da23dfeeb0f3ab2d36561316092

Note that the bug is not trivial to reproduce and it could happen for multiple different reasons.

## Additional details

Sentry entry: https://sentry.kbtdev.org/kobo/kpi-frontend/issues/306157/

**Comment by jnm** [comment]
It seems like this is fixed; we can re-open it if anyone reports the problem again.
