### ISSUE TITLE
It's not possible to whitelist IP addresses for SSRF protection

### ISSUE THREAD

**Issue by paolagrisales** [kobotoolbox/kpi#2697]
## Description

I'm trying to configure a hook inside kobo kpi module, but this kobotoolbox is internal to the organization and is deployed in the same location of kobo node. 
When i try to call the service (sending some data to the server with a form instantiated), it gives me the folliwing error:
![image](https://user-images.githubusercontent.com/5765016/83341786-48a47200-a2ad-11ea-8966-c84c93cae4fd.png)

Reviewing a little of the soruce code, it happens when the module tries to send the server payload through a post invocation using the request module. 

However, seems that it uses a ServerSideRequestForgery protection through your [ssrf-protect](https://github.com/kobotoolbox/ssrf-protect) module before execute the invocation. So that i couldn't invoke this hook. 

* Is there a way to invoke this hook?
* Is there a way in kobotoolbox to configure the allowed_ip_addresses and let that the local request could pass?

Thanks for your help.

## Steps to Reproduce

1. Create a rest service with POST; deploy it in an onpremise installation
2. Create a sample form, using an onpremise deployment
3. Configure the form to call the exposed service a as a hook
4. send the form

sent of this form seems to be executed including a message inside a queue where the message is published through celery. 

5. this is the log information of the docker logs:

![image](https://user-images.githubusercontent.com/5765016/83341977-1dbb1d80-a2af-11ea-8c6c-ceeda527eb90.png)

## Expected behavior 

a way to configure internal ip addresses

## Actual behavior 

request not sent to the hook

## Additional details

Environment: docekr deploy over ubuntu 20.04 LTS on premise installation

**Comment by paolagrisales** [comment]
using a ngrok host we can bypass the issue, and it serves as a workaround but this is not considered an expected behavior

![image](https://user-images.githubusercontent.com/5765016/83342041-f9ac0c00-a2af-11ea-9841-084fc84c153d.png)

**Comment by noliveleger** [comment]
Hi @paolagrisales, thank you. 
Indeed, the SSRF options should be customizable from KPI as Django settings. 

https://github.com/kobotoolbox/kpi/blob/master/kobo/apps/hook/models/service_definition_interface.py#L105

Something like
```
from django.conf import settings

SSRFProtect.validate(self._hook.endpoint, settings.SSRF_OPTIONS)
```

Where `settings.SSRF_OPTIONS` would be something like that 
```
SSRF_OPTIONS = {
    'allowed_ip_addresses': ['x.x.x.x'],
    'denied_ip_addresses': ['x.x.x.x'],
}
```
