### ISSUE TITLE
API returns `name: "Untitled"` when XLSForm uploaded without `form_title` setting

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2700]
![image](https://user-images.githubusercontent.com/2085013/83781113-0fc51e00-a65c-11ea-82aa-3b2b4decfb97.png)

Expected: the uploaded file's name is used to create the asset `name`

**Comment by dorey** [comment]
The initial form is created with `Untitled` as the name.

https://github.com/kobotoolbox/kpi/blob/master/jsapp/js/components/modalForms/projectSettings.es6#L399

I propose that we create it with an empty name and then if we are updating content and a filename is available then we replace the name with the file name.

**Comment by jnm** [comment]
Cool, so this is the front end's job:
> we create it with an empty name

…and the back end does this?
> if we are updating content and a filename is available then we replace the name with the file name

Do we do that only if the name is unset?

If so, let's go :+1:

**Comment by dorey** [comment]
It looks like it's passed through `asset.summary` which is gets overridden. Even when getting the `import_task` to run synchronously I can't figure out why `asset.summary['filename']` gets removed before it gets processed.
