### ISSUE TITLE
grid-theme forms with translations shows empty labels in preview

### ISSUE THREAD

**Issue by duvld** [kobotoolbox/kpi#2707]
## Description

Small 🐛 that is semi-related to #2676. In the same flowdock thread (https://www.flowdock.com/app/kobotoolbox/support/threads/w7pzaSyCBbROAcUz7riyBWkhExs) the first mentioned issue is for a form that shows empty group labels when previewing a form that has a `grid-theme` but empty labels:
![image](https://user-images.githubusercontent.com/16762675/84179911-aa56a000-aa54-11ea-8e79-909600bee1d1.png)
Deploying the form and opening it does not show this issue (only shows up in preview).

## Steps to Reproduce

1. Upload a form with `grid-theme` and multiple languages such as 
[Testing_matrix_constraint.xlsx](https://github.com/kobotoolbox/kpi/files/4753730/Testing_matrix_constraint.xlsx)
2. Open the formbuilder, save the form (without any changes to group labels)
3. Preview the form
## Expected behavior 
No empty group labels.

## Actual behavior 
Shows empty group labels like the image above.

## Additional details

#2676 shows a case where a `grid-theme` with no group labels and only one language and cannot reproduce the issue with no group labels and multiple languages. Creating this separate issue as the fix for this would be unrelated to #2676.

**Comment by jnm** [comment]
I think this may be entirely a back-end problem. Consider this form content:
```json
{
    "schema": "1",
    "survey": [
        {
            "name": "start",
            "type": "start",
            "$kuid": "03TSALUCs",
            "$autoname": "start"
        },
        {
            "name": "end",
            "type": "end",
            "$kuid": "q2YMHzR5M",
            "$autoname": "end"
        },
        {
            "name": "group_name",
            "type": "begin_group",
            "$kuid": "qp8bo30",
            "label": [
                ""
            ],
            "$autoname": "group_name"
        },
        {
            "name": "question_name_in_group",
            "type": "text",
            "$kuid": "ld5gg52",
            "label": [
                "question label in group"
            ],
            "required": false,
            "$autoname": "question_name_in_group"
        },
        {
            "type": "end_group",
            "$kuid": "/qp8bo30"
        }
    ],
    "settings": {
        "style": "theme-grid no-text-transform"
    },
    "translated": [
        "label"
    ],
    "translations": [
        null
    ]
}
```
It previews just fine, despite the group having `"label": [""]`:
![image](https://user-images.githubusercontent.com/2085013/100837749-331c2a80-343f-11eb-9879-3dfb1237807c.png)

However, as soon as I name the language, e.g. changing
```json
    "settings": {
        "style": "theme-grid no-text-transform"
    },
    "translated": [
        "label"
    ],
    "translations": [
        null
    ]
```
to
```json
    "settings": {
        "style": "theme-grid no-text-transform",
        "default_language": "English (en)"
    },
    "translated": [
        "label"
    ],
    "translations": [
        "English (en)"
    ]
```
the preview starts showing the empty group label:
![image](https://user-images.githubusercontent.com/2085013/100837839-59da6100-343f-11eb-9a06-b37adba63a91.png)

**Comment by jnm** [comment]
<strong>*WHY*</strong> does this only happen during previews, you may ask? When deploying a form, the asset content is actually written to an XLS before being sent to KoBoCAT (see #1494). KoBoCAT then reads in that XLS with our [good friend](https://github.com/kobotoolbox/kpi/pull/2887) `xls_to_dict()`, which explicitly ignores any cells that are empty:
https://github.com/XLSForm/pyxform/blob/v0.15.1/pyxform/xls2json_backends.py#L87-L92

I think we can fix the entire issue in formpack by modifying [this work](https://github.com/kobotoolbox/formpack/commit/42e8766e051dcab7c377461f3a02a2349fe1a58a) to remove labels that are empty strings.

**Comment by jnm** [comment]
We'll still need to update KPI's formpack requirement after kobotoolbox/formpack#227 is merged. Let's consider reverting #2708 after that, and perhaps closing #2909.
