### ISSUE TITLE
Edited record in data table now refusing to pull data from csv

### ISSUE THREAD

**Issue by kalawac** [kobotoolbox/kpi#2714]
## Description

`bug` I edited a record in the data table using the edit feature. The change should not have affected any skip logic. The form in question opens with a UID request that pulls data from a csv -- if the UID matches a UID on the csv (and the data pull works) the rest of the form opens up, as the enclosing group only begins if the UID matches. (Screenshots + form and csv with dummy data, saved as an xlsx file, attached.) Is it possible that the record has somehow become disconnected from the csv? The rest of the unedited data in the table remains fine. Two new records were collected after this issue started and they are fine but the issue remains.

![KT-BugReport1](https://user-images.githubusercontent.com/8592862/84636961-d5a91700-aeba-11ea-9e18-a1e6f3d65959.png)
![KT-BugReport2](https://user-images.githubusercontent.com/8592862/84636978-d8a40780-aeba-11ea-8d09-498ae26b73ff.png)
![KT-BugReport3](https://user-images.githubusercontent.com/8592862/84637751-b1016f00-aebb-11ea-972d-b9bfa782efd2.png)

[initial-risk-assessment_kt_v20200605.xlsx](https://github.com/kobotoolbox/kpi/files/4777431/initial-risk-assessment_kt_v20200605.xlsx)
[clarendon.xlsx](https://github.com/kobotoolbox/kpi/files/4777434/clarendon.xlsx)

## Steps to Reproduce

1. Click on pencil icon in table to edit submitted record.
2. Edited two domains' scores (violence history and mental health), changing them from low to moderate.
3. Submit form and receive thank you message.

## Expected behavior 

Edited record reflects changes and otherwise is maintained.
UID is a match (see screenshot of me entering the UID into Enketo via a link to collect data).
![KT-BugReport4_expected](https://user-images.githubusercontent.com/8592862/84639299-cc6d7980-aebd-11ea-85c1-fe5cf65e7ca1.png)

## Actual behavior 

Form rejects UID match and will not begin the group that makes the rest of the form available, nullifying all collected data.

## Additional details

Tried going into the form to re-enter UID.
Tried entering other UIDs that should match.
Checked entering the UID into a new form and it worked.

Note: I updated the csv attached to this form but it was before the record in question was collected and submitted.

**Comment by noliveleger** [comment]
Maybe related to https://github.com/kobotoolbox/kobocat/issues/658

**Comment by Kalyan-Lama** [comment]
**Forum:** https://community.kobotoolbox.org/t/edited-data-record-no-longer-pulling-data-from-csv/10041

**Comment by jnm** [comment]
The fix has been deployed to production servers: https://community.kobotoolbox.org/t/release-notes-kobocat-version-2-020-44/13360
