### ISSUE TITLE
Handle Internet Explorer 11

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2716]
Decision: we'll drop support for IE and display a more helpful message.

## Description

The old version of KPI on kobo.humanitarianresponse.info seems to work with IE11:
![ocha ie11 Screenshot_2020-06-18_15-10-18](https://user-images.githubusercontent.com/2085013/85062304-462f8c80-b176-11ea-9e14-f9c5f58d6fa5.png)

However, the new version `2.020.25` does not load the login screen properly. It allows login but shows a blank page afterwards:
![image](https://user-images.githubusercontent.com/2085013/85062437-7e36cf80-b176-11ea-8a2c-fe472209b8ff.png)
![image](https://user-images.githubusercontent.com/2085013/85062448-82fb8380-b176-11ea-8e37-07621ed09cf6.png)

Exception:
![hhi ie11 Screenshot_2020-06-18_15-11-37](https://user-images.githubusercontent.com/2085013/85062468-87c03780-b176-11ea-9910-607a7d68bd1a.png)

## Expected behavior 

Either KPI loads, or the user is redirected to an informative page telling them to use a newer browser. Enketo, for example, has dropped all IE support and shows this message to IE visitors:
![image](https://user-images.githubusercontent.com/2085013/85062600-c0601100-b176-11ea-819c-edfa6a40a794.png)

**Comment by jnm** [comment]
Should we detect the user agent in the front-end code and use JS to display a message, or is there some advantage to redirecting to a separate page the way Enketo does?

**Comment by dorey** [comment]
Looks like the actual place it's throwing the error is here:
https://github.com/kobotoolbox/kpi/blob/master/jsapp/xlform/src/view.icons.coffee#L10

Something is causing [`js/constants.es6`](https://github.com/kobotoolbox/kpi/blob/master/jsapp/js/constants.es6) to not export the proper values?

**Comment by jnm** [comment]
Closed by #2718
