### ISSUE TITLE
Remove T&C and privacy URLs from base.py

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2722]
## Description

Anyone forking and hosting their copy of kpi includes by default the links to the privacy policies and T&C for the HHI server. These are only valid for kf.kobotoolbox.org and should not be used by other servers. 

See [base.py](https://github.com/kobotoolbox/kpi/blob/7956a680b0bda7ae56fcc7a3a8b59f132c9257d2/kobo/settings/base.py#L136-L139).

The two URLs should only be set for the HHI server but otherwise not be in kpi anymore.

**Comment by jnm** [comment]
I just overrode these URLs in https://kf.kobotoolbox.org/admin/constance/config/, so they should be set properly on HHI production even after merging and deploying #2746.
