### ISSUE TITLE
Search wildcards should be documented

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#276]
~~https://kf.kbtdev.org/assets/?q=tag:*wash matches assets tagged with "clusters:wash", but https://kf.kbtdev.org/assets/?q=tag:wash does not. This isn't clear from the README.md documentation.~~

The docstring in https://github.com/kobotoolbox/kpi/blob/main/kpi/utils/query_parser/query_parser.py (linked from README.md) should explain a bit more about the availability of Django [field lookups](https://docs.djangoproject.com/en/3.2/topics/db/queries/#field-lookups) when searching.

**Comment by joshuaberetta** [comment]
@jnm, just confirming that this is no longer the behaviour of the query parser?

**Comment by jnm** [comment]
Right. There actually isn't any `tag:` field for searching anymore; it's now necessary to follow Django conventions and use `tags__name:`.

Regarding wildcards, they're different too. Django supports `__regex`, so you can actually say `tags__name__regex:.*wash`. You can also use other Django-isms like `tags__name__iendswith:wash` to achieve the same thing.

The README nowadays just points at https://github.com/kobotoolbox/kpi/blob/main/kpi/utils/query_parser/query_parser.py, but that documents `__` only as traversing object relations—it doesn't mention the other Django operators (if that's the right word) like `__iexact`, `__lte`, `__startswith`, etc. Let's keep this issue open for that.

**Comment by JacquelineMorrissette** [comment]
@jnm If I'm reading this right, what we need to do here is add the lookups to the appropriate documentation?
