### ISSUE TITLE
Row level access for edit, validate, and delete

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2768]
Depends on #2488.

Extending #2259, provide for edit, validate, and delete permissions to be restricted based on which user uploaded the submission.

- [ ] Carry out back-end changes to support this
    - [ ] KoBoCAT
    - [ ] KPI
- [ ] Review UX; is it going to be too clunky if we simply follow the example of what we already have? (Screenshot below)
- [ ] Implement front-end changes

_imagine_ :sparkle: that the appropriate check boxes are checked
![Screen Shot 2020-08-24 at 09 50 06](https://user-images.githubusercontent.com/2085013/91052305-46715b80-e5ef-11ea-9669-f3ac7ee25345.png)

**Comment by jnm** [comment]
The current UX is not bad, especially for a MVP. What we could do is allow pasting many usernames in the `Enter usernames separated by spaces` field.

**Comment by magicznyleszek** [comment]
@jnm Bunch of questions:

1. When we delete a user from the system (does it happen often?), do we re-check partial submissions assigned to this user?
2. Currently we have a permission named `partial_submissions` - do we change it to `view_submissions_partial`, so we can have `add_submissions_partial`, `change_submissions_partial` and `validate_submissions_partial`??
3. Do we need to check the usernames for partial usernames or should FE rely on BE throwing errors and display them?

**Comment by jnm** [comment]
just taking some notes from our call:

1. we don't :)
2. the existing json structure should support all the row-level permissions we need:
   ```json
   {
      "user": "https://[kpi]/api/v2/users/{username}/",
      "permission": "https://[kpi]/api/v2/permissions/partial_submissions/",
      "partial_permissions": [
          {
              "url": "https://[kpi]/api/v2/permissions/{THIS is where we would have view_submissions, change_submissions, validate_submissions, delete_submissions}/",
              "filters": [
                  {"_submitted_by": {"$in": ["{username}", "{username}"]}}
              ]
         },
      ]
   }
   ```
3. let's accept that they're not checked anywhere for the MVP. it will be tricky to check on the backend because we accept an arbitrary mongo filter, not just a list of usernames. it will be tricky to check on the frontend because we will have to make many api calls if someone pastes many usernames into the list (which is a use-case we're explicitly trying to support).
4. the rules in `https://[kpi]/api/v2/permissions/` (`implied` and `contradictory`) should cover this

**Comment by Ig-Rebollo** [comment]
Adding some suggestions here @jnm @magicznyleszek 

However I will say I went back and forth with this issue a lot, and I'm still not sure about this option. Tried many variations in an attempt to improve the UX, but the arrangement we currently have works very well. It might not look amazing visually, but it is very functional given the multiple combinations we have to allow. Honestly, it is quite hard to improve without compromising that flexibility.

Here is the initial attempt:
![Files-attached-2](https://user-images.githubusercontent.com/22472326/94971571-4c533a00-04d5-11eb-841b-9bbfa704be79.jpg)

If I click on 'add user':
![Files-attached-1](https://user-images.githubusercontent.com/22472326/94971618-6856db80-04d5-11eb-8537-b461531595d7.jpg)

The result of adding the fourth user:
![Files-attached](https://user-images.githubusercontent.com/22472326/94971653-8290b980-04d5-11eb-95e4-350bde66be9b.jpg)

And finally, if you click on 'edit permissions':
![Files-attached-3](https://user-images.githubusercontent.com/22472326/94971710-a653ff80-04d5-11eb-8260-55a7084c3fc5.jpg)

Not sure if it is worth implementing this when the current option is fine and easy to use. As @jnm said, the current arrangement works very well for an MVP. In any case, happy to hear what you think. Maybe we can use some of this further down the road.

**Comment by Ig-Rebollo** [comment]
Also might be worth considering having user groups (i.e. organizations) and/or roles (i.e. admin, editor, contributor, viewer...) to group the most common combinations and simplify the structure. Here is an [article that explains these ideas very nicely](https://uxdesign.cc/design-permissions-for-a-saas-app-db6c1825f20e). Not saying we should do exactly what it proposes, but it is true that eventually we might run into a more and more complex permission system that needs to be simplified somehow. (cc @tinok )

**Comment by tinok** [comment]
I like this approach. Up to @jnm if this should be kept for a later iteration outside of #2768, though. Some suggestions:

* the big "owner" label/button looks odd; I think the first row could just be a greyed out version of all the buttons/controls.
* maybe add another column for 'add submissions' since it's very different from all the others that relate to viewing data. In most project there could be dozens of people with submission rights but only one or two others who can view data
* I definitely support the idea of grouping permissions -- and then having another option called 'Custom' (or to have a button that enables a user to fine tune permissions based on the defaults). These could be:
    * Form editor
    * Data collector
    * Data analyst

**Comment by magicznyleszek** [comment]
@Ig-Rebollo just FYI: the content we display at Settings > Sharing is the same content we display in sharing modal. I think we will just make the sharing modal bigger than currently and there will be no problems :)

**Comment by magicznyleszek** [comment]
Some BE problems I've found:
- `api/v2/assets/<uid>` in `assignable_perms` for `partial_submissions` the `label` property is no longer valid. It says `"View submissions only from specific users"` but now `partial_submissions` can contain more permissions than "view". It should be changed to something more general that would make sense for all `add`, `view`, `edit`, `validate` and `delete` or to a `"##keyword## submissions only from specific users"`, so FE could fill in a proper word.
- `api/v2/permissions` the `contradictory` for `partial_submissions` shouldn't also include `add_submissions`?

**Comment by Ig-Rebollo** [comment]
@tinok agree on the owner button. Will standardize it so it looks like more similar to the other rows. 

On your comment:
> maybe add another column for 'add submissions' since it's very different from all the others that relate to viewing data. In most project there could be dozens of people with submission rights but only one or two others who can view data
Not sure if I understood. Do you mean separating the 'add' column and make it a more distinct column? Or actually adding a new fifth column for adding submissions? If the latter, how would that be different from the current 'add' submissions?

Regarding grouping permissions into roles, I'm assuming it would be part of a different implementation. If we do it now it would need additional mockups. We would need to think where/how those roles could be created, managed, etc.

@magicznyleszek If making the sharing modal bigger is possible and doesn't involve too many problems, that sounds good to me as well :)

Regarding the BE problem, that makes sense. Right now only 'view submissions' can have a 'from specific users', but we're expanding it to all others as well. Filling in the keyword in the FE makes sense to me, but probably something worth checking with @jnm

**Comment by tinok** [comment]
@Ig-Rebollo What I meant was a separate column at the top level where the 'add' permissions are located (so to have Form, Add data, and View/edit data). I don't think they should be wedged between "View" and "Edit/delete" because they are so different. 

![image](https://user-images.githubusercontent.com/673511/105860415-88963300-5fbb-11eb-8085-a8741840477a.png)
