### ISSUE TITLE
Create new submission based on existing submission (aka duplicate record)

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2769]
After chatting with @tinok, the expected way for this to work is:

1. I want to duplicate submission 4567890
1. I follow the submission-duplication UX flow for 4567890 (#2895, #2896)
1. The KPI front end (#2896) sends a request instructing the KPI back end (#2894) to duplicate 4567890
1. 4567890 is duplicated immediately in the Postgres and Mongo databases (#2893)
    * Let's say the duplicate submission ID is 5559876
1. The KPI back end (#2894) returns the JSON content of the new submission (including the ID 5559876)
1. [Unsure if this step will be skipped] I see the new submission in the single-submission-view modal
1. [Unsure if this step will be skipped] I click Edit
1. The KPI front end (#2896) executes the existing edit process for submission 5559876
1. I see the Enketo edit interface open in a new tab for submission 5559876
1. I change some responses and click Submit

Original description from UNHCR: 

Duplicate a record from the "table view" to create a new record (for easy editing). The ID of the new record would be different. For already submitted entries, there should be a possibility of duplicating the entry such that the record can be updated without  entry everything afresh. The date should be the duplicated date and time with the additional date of duplication.

Original user flow from UNHCR:

* Users submit various original records, e.g. about each refugee camp
* A month later, in the office, information for each camp needs to be updated with NEW SUBMISSION in case of changes and to preserve original
* User navigates to table view, selects most recent record for Camp A, clicks on "CLONE SUBMISSION" (or "CREATE SUBMISSION FROM THIS RECORD") button
* New submission opens in Enketo view with all previous fields pre-populated; user edits only where needed.

### Old stuff, for reference only (do not do this :smile:)

Idea:

Let's use Enketo's `defaults[]` to begin a _new_ submission with all responses initially set to match the source submission. Then, the person performing the clone can modify any response as they like before submitting.

Work items:

:hand: Let's hold on this until we receive a response at https://github.com/enketo/enketo-express/issues/216

* Try (manually) using Enketo's `defaults[]` to set responses in complex situations like repeating groups
    * "optional parameter defaults[] can be used to dynamically override survey field defaults (defaults[/path/to/node]=value)" (https://apidocs.enketo.org/v2#/post-survey)
    * Example of someone using this feature: https://community.kobotoolbox.org/t/prefill-fields-via-url-in-enketo/2698
    * Does Enketo accept `defaults[]` in `POST`? :crossed_fingers: If not, what's the query string length limit for `GET`, and will it cause problems?
* Figure out how to parse an existing submission into XML paths and values. Perhaps it's best to fetch the XML submission (vs. JSON) from the API and parse that. I would prefer to do this in front-end code—since it needs no special knowledge from the back-end—but if it's much easier to do it in Python, that's an option.
* Implement clone button in table view, with logic to open new Enketo submission with pre-filled responses in a new tab

**Comment by magicznyleszek** [comment]
It could look something like this:

<img width="435" alt="Screenshot 2020-09-08 at 13 33 42" src="https://user-images.githubusercontent.com/2521888/92471292-f93cde80-f1d7-11ea-8397-efa7bf796e11.png">

<img width="1171" alt="Screenshot 2020-09-08 at 13 39 20" src="https://user-images.githubusercontent.com/2521888/92471741-b7f8fe80-f1d8-11ea-8043-57e778aa4a38.png">

**Comment by Ig-Rebollo** [comment]
I think what @magicznyleszek proposed might be be best way to go @jnm . I linked that idea to the proposal in #2760, which I think would work pretty smoothly from a usability point of view. I used 'cloning' instead of 'duplicating' to differentiate from other functions we already have... but we could use 'duplicate' for everything as well.

![Attach-files-info](https://user-images.githubusercontent.com/22472326/94955578-c7f2be00-04b8-11eb-838d-dd0224c8a721.jpg)
![Attach-files-info-1](https://user-images.githubusercontent.com/22472326/94955646-e3f65f80-04b8-11eb-86e1-197b81610819.jpg)

**Comment by tinok** [comment]
Hi @shadimh Would love your feedback on these designs.

**Comment by tinok** [comment]
@jnm Thanks for updating the description. I wonder if after/as part of 

> 4567890 is duplicated immediately in the Postgres and Mongo databases (#2893)

we could update the submission time to reflect the current server time?

**Comment by jnm** [comment]
That should happen automatically as part of
> 5. POST that XML to KoBoCAT's submission endpoint
