### ISSUE TITLE
Sharing form to many users is very slow

### ISSUE THREAD

**Issue by djordjemarusic** [kobotoolbox/kpi#2779]
## Description

Sharing a form if it's already shared with a large number of users is very slow. It takes about a few minutes to complete the operation after it's shared with a few hundred users and during that period the UI is unresponsive. It happened on the installation of Kobo on a separate server (Ubuntu 18.04, 16GB RAM, 8 cores CPU). The form itself is not very long, it has about twenty questions.

## Steps to Reproduce

Create a form, share it with many users and at some point, the sharing will become very slow.

## Expected behavior 

The form sharing operation should be optimized for a large number of users and the system should be responsive during the operation.

## Additional details

https://community.kobotoolbox.org/t/slow-sharing-permissions/11351/3

**Comment by Raph33** [comment]
This issue effectively makes Kobo unusable. The sharing is so slow that it makes it impossible to share the forms with new users or add permissions. To remedy this, we had to change permissions directly in the database, but this is not a sustainable solution because it is not something that the end users of Kobo can do themselves.

**Comment by noliveleger** [comment]
@djordjemarusic , how many users would you say you start to face the slowness of the sharing form.

**Comment by jnm** [comment]
"a few hundred users," from the original forum post.

@djordjemarusic or @Raph33, it'd be helpful to have answers to the questions I posted in the forum: https://community.kobotoolbox.org/t/slow-sharing-permissions/11351/8?u=jnm.

> we had to change permissions directly in the database

Could you share your method for doing this? Contrasting that to the normal queries run by the API could provide a clue about the bottleneck.

**Comment by djordjemarusic** [comment]
> "a few hundred users," from the original forum post.
> 
> @djordjemarusic or @Raph33, it'd be helpful to have answers to the questions I posted in the forum: https://community.kobotoolbox.org/t/slow-sharing-permissions/11351/8?u=jnm.
> 
> > we had to change permissions directly in the database
> 
> Could you share your method for doing this? Contrasting that to the normal queries run by the API could provide a clue about the bottleneck.

I just checked, one of the forms is shared with 511 users and the other one with 378. We did not change the access rights in the database directly, Raph probably meant on the scripts we used to add users or check permissions. However, this behavior occurs when we share a form with a user in the manner described [here](https://support.kobotoolbox.org/managing_permissions.html?highlight=sharing).

**Comment by Kalyan-Lama** [comment]
Community link: https://community.kobotoolbox.org/t/adding-new-users-takes-unexpectedly-long-time/19449
