### ISSUE TITLE
Scrolling in library context menu not possible to choose collection

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2783]
## Description

When trying to move an asset to a different collection it’s not possible to scroll in the menu box. 
![image](https://user-images.githubusercontent.com/673511/92032931-da9e9980-ed38-11ea-82af-76e4e67f87ac.png)

## Steps to Reproduce

1. Create multiple collections
2. Click context menu for a library asset
3. Try to scroll among the list of collections

## Expected behavior 

User can scroll in the list by clicking on the scroll bar.

## Actual behavior 

Clicking on the scroll bar makes the context menu disappear. 

## Additional details

Tested on kf.master.

**Comment by magicznyleszek** [comment]
@tinok this will be fixed by #2559 :)

**Comment by magicznyleszek** [comment]
@Ig-Rebollo I think I might have another topic to tackle for you :-) #2786

**Comment by jnm** [comment]
Fixed by #2559
