### ISSUE TITLE
User should see all available information in sidebar

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#280]
In the library sidebar the following should be visible:
- [ ] Total results (count)
- [ ] For each block: 
  Number of children, list of question labels of each question

**Comment by magicznyleszek** [comment]
@tinok this is how it looks like right now:

<img width="262" alt="screenshot 2018-12-05 at 12 57 10" src="https://user-images.githubusercontent.com/2521888/49512154-6138f500-f88d-11e8-83a1-199be8db3048.png">

Total results are displayed in the footer of the list. Number of children is displayed in rounded rectangles. It seems that only list of question labels is missing - there's only `…and other X questions` label, and only if you don't add label to `block` (related issue: #663)

How should the list look like? Do you think we should totally ignore the user-entered label for `question`/`block` and always display first question label plus optional count number?

**Comment by magicznyleszek** [comment]
Note: this will somehow be done by #2559 as whole library was rebuilt there

**Comment by joshuaberetta** [comment]
resolved in #2559
