### ISSUE TITLE
Meta question types get added as separate assets when uploaded to the library

### ISSUE THREAD

**Issue by duvld** [kobotoolbox/kpi#2801]
## Description

When uploading a collection to the Library, each `meta` question (start, end etc.) gets added with it as a separate asset. 

`begin/end_group` tags should also be rejected. We should also tell the user if they want to upload groups of questions to the Library, these tags will only work for library imports if there is a block column preceding it:
![image](https://user-images.githubusercontent.com/16762675/94059334-42805700-fdb0-11ea-8aec-79635f9c7f88.png)

This can be an issue since meta question types are always added when downloading a form from KPI.

## Steps to Reproduce

1. Download a xlsform from KPI
2. Change the `survey` sheet to `library`
3. Upload the form to the Library

## Expected behavior 

Only non meta questions are added to the Library 

## Actual behavior 

Every question (including start, end, and calculate containing versions) is added to the form as a separate asset

## Additional details

Here's a form that can be the simplest recreation of this issue
[basic-text.xlsx](https://github.com/kobotoolbox/kpi/files/5241604/basic-text.xlsx)

**Comment by jnm** [comment]
It's possible that this behavior is fine as-is because the `library` sheet is for bulk-uploading multiple library items. If someone wants to upload an entire XLSForm to the library, they ~~can~~ (should be able to) do so as a library template.

@dorey will close this and the associated PR if all is as it should be.

**Comment by dorey** [comment]
Yeah. I think this is working as it should
