### ISSUE TITLE
Search term without field should query `asset.name`

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2814]
The query parser expands `hello` to `summary:hello`, but we should have it expand to `summary:hello OR name:hello`. Both of these should use `icontains` when translated into `Q` objects.

https://github.com/kobotoolbox/kpi/blob/0deff9668027e73ecc7199132cee908ce25a41b8/kpi/utils/query_parser/query_parser.py#L110-L113

**Comment by noliveleger** [comment]
As per discussed in https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/Public.20Collection.20feedback/near/1205 

Default search will be a little bit more complex.
