### ISSUE TITLE
Library items are mutated when added to a survey from the sidebar

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2822]
OK, we know this seems bad:
https://github.com/kobotoolbox/kpi/blob/d3d39dbc25d64f35e90125b0b58004e63176a649/jsapp/xlform/src/model.inputParser.coffee#L111-L121

and in certain circumstances, it is indeed:
1. Here, we load a library asset from the back end, but we save it in a store—so subsequent loads won't refresh it:
    https://github.com/kobotoolbox/kpi/blob/0deff9668027e73ecc7199132cee908ce25a41b8/jsapp/js/stores.es6#L277-L282
1. [`Survey.loadDict()`](https://github.com/kobotoolbox/kpi/blob/0deff9668027e73ecc7199132cee908ce25a41b8/jsapp/xlform/src/model.survey.coffee#L333) calls `inputParser.parse()` (see above), which mutates `asset.content`: it nullifies the default/first translation and causes subsequent import attempts to fail (see #2800).

My proposal: let's have `addExternalItemAtPosition()` make a copy of `asset.content` before doing anything with it. Easy enough; I'll make a PR. @magicznyleszek, are there tests for this kind of thing?

**Comment by magicznyleszek** [comment]
@jnm I don't think there are tests for that. I didn't add any tests to coffee code to be honest - just for the nullify es6 functions.

**Comment by jnm** [comment]
Gotcha :ok_hand: Thanks for the merge :+1:
