### ISSUE TITLE
Library & Public Collections UX Review

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/kpi#2833]
There are several UX issues with the latest implementation of the Public Collections and Library.

Notes from the meeting with Tino, Anji and Leszek on Oct 9, 2020.

- In "My Library" view type column header should be filtering not ordering
- Collection meta on collection page should be all hidden, not half toggle like now - display some data with "Show more details" button. Everything could be just one line by default (unless expanded)
- Collection content is displaying only 10 items (bug ?). Ideally it should display the full list of assets contained in that collection.
- When typing a keyword on the search, can it also look for assets within a collection (in case assets in a collection can only be accessed by clicking in that collection). Searching for a question inside a collection - is it possible from My Library?
- Remove some columns from the collection view (Country, Org)
- Do we want to change all columns to ordering instead of filtering? (Ignacio votes for changing to just sorting temporarily -if we need to get this out soon- until we can do the filtering better. Better not to have a feature than to have it done wrong)
- Move the asset title from header to the content and the search box is always searching global
- **You can't add subscribed collection items in Form Builder (bug!)**
- **In Form Builder in "Add from Library" the no results message shouldn't be draggable (bug!)**
- Should it be possible to add an asset to multiple collections? At the moment, no

The main ideas for library view:
1. Leave current view and order collections first in the table
2. Items not in collection displayed in an "not in collection" custom collection
3. Split "My Library" into two separate items in sidebar: "My Collections" and "My Assets"
  - "My Collections" list the collections you have access too (owned, shared with and subscribed)
  - "My Assets" list the questions, blocks and templatest you have access too (regardless if they are inside collection or not)
4. Leave current view (collections + non-collected items) and add quick filters in sidebar under "My Library":
  - "just collections"
  - "items not in collection"
  - "shared with me"
  - "subscribed"

**Comment by Ig-Rebollo** [comment]
@duvld @tinok @magicznyleszek @jnm 

Leaving here a proposal based on our discussion today. We will need to see:
1. If this is what we all envisioned
2. How much of this is possible/we want to prioritize in the time we have

Starting with the 'My Library', I created this option where you can choose between three categories: overview (shows collections and assets that are not part of any collection), My Collections (only shows collections you created or subscribed to) and My assets (displays all questions and blocks, both those that are part of a collection and not part of any collection)
![MacBook Pro - 7](https://user-images.githubusercontent.com/22472326/95637627-30fda700-0a60-11eb-98dc-62f8afd4bf6a.jpg)
![MacBook Pro - 9](https://user-images.githubusercontent.com/22472326/95637638-3b1fa580-0a60-11eb-82e5-acab7e63274c.jpg)
Note how the column 'collection' gets added to the table in the 'My Assets' category:
![MacBook Pro - 10](https://user-images.githubusercontent.com/22472326/95637690-5b4f6480-0a60-11eb-93d1-b3f7485d69d7.jpg)

You could also filter by type of file, and the filters would appear to the right of the section title:
![MacBook Pro - 11](https://user-images.githubusercontent.com/22472326/95637745-7de17d80-0a60-11eb-9e9d-297107c26901.jpg)
![MacBook Pro - 12](https://user-images.githubusercontent.com/22472326/95637753-85088b80-0a60-11eb-8ac6-680a6a5f73c3.jpg)

When clicking on a collection, I would go to the collection view, which would show me all the assets inside, and have a more streamlined view as we discussed:
![MacBook Pro - 13](https://user-images.githubusercontent.com/22472326/95637813-ad908580-0a60-11eb-9ec8-f63a9273223d.jpg)

The other alternative we also discussed, would be to get rid of the categories on the left sidebar, and collapse all assets that are not part of a collection into a 'folder' of sorts. This would mean that 'My Library' only shows collections/folder (essentially containers)
![MacBook Pro - 8](https://user-images.githubusercontent.com/22472326/95637903-0102d380-0a61-11eb-9bd3-73d49b766318.jpg)

Finally, Public collections would follow a similar method, with those squares with icon indicating 'collections'. They would all be greyed out by default, and only those you subscribe to would become blue (the tile colour in the My Library section collections indicates that they were created by you, and are not shared)
![MacBook Pro - 1](https://user-images.githubusercontent.com/22472326/95638013-5808a880-0a61-11eb-834f-00a970a5eb9e.jpg)
Finally, a nice to have would be to fix the header of the table as shown here, but this is definitely not essential:
![MacBook Pro - 6](https://user-images.githubusercontent.com/22472326/95638058-71a9f000-0a61-11eb-8a23-c3aec9d38922.jpg)

Let me know what you guys think, happy to have a call early next week to discuss this with John as well.

**Comment by magicznyleszek** [comment]
My thoughts:
- I like the collection icon + bold text, I feel it is enough distinction for it to work 👍
- The "Assets" column should be named differently ("Children"?) and displayed only for "My Collections" view, as collections have other assets inside, but questions/blocks/templates have questions/rows, so different counter and we shouldn't mix them
- I wonder if we shouldn't drop the counter next to "My Library", as it isn't clear as to what it should mean
- I like the fixed headers - should they be fixed on the single collection view?
- I like active filters - should we indicate somehow what columns did they belong to? So maybe indicate the column somehow or add a prefix with column name "type: Subscribed"
- to clarify: I expect that clicking on "Library" icon or on "My Library" (when already on `/library` route) will open "My Library > Overview"

**Comment by tinok** [comment]
Thanks @Ig-Rebollo, this is very helpful. My thoughts are: 

1. The 'Overview' view would be the most useful iteration over what we have now. We could leave out the Primary sector and Subscribers columns in my opinion --not essential. 
![image](https://user-images.githubusercontent.com/673511/95998183-9c4dcd00-0e02-11eb-8fc7-2e9aa15a21ba.png)

2. I suggest removing all three filters and just leaving "My Library" The 'My collections' and 'My assets' filters on the left don't seem necessary since the same content is accessible via 'Overview. 

3. I suggest we leave the whole filtering functionality for the next iteration, including by asset type. 

4. I really like the breadcrumb view you used for "My Library > My Collections". Why not use the same compact view when going inside a collection? I.e. "My Library > WASH Questions". This users less space, there's no need for the back button, and the same approach would work for viewing a public collection ("Public Collection > Tino's security questions").

5. I found the icons for collections a bit confusing, mostly due to the different colors. Since the checkmark and the blue color mean the same thing, maybe a single color for all collections (or no color at all?) would be better. 

6. Agree with Leszek on changing "Assets" (not a known name for users). What about "Items"? This could be used in all the different views.

**Comment by Ig-Rebollo** [comment]
@tinok @magicznyleszek @duvld 

Thanks for the feedback, here are the updated mockups based on your comments.
![MacBook Pro - 16](https://user-images.githubusercontent.com/22472326/96927819-9d779d80-1485-11eb-906e-b3a60554191c.jpg)
![MacBook Pro - 17](https://user-images.githubusercontent.com/22472326/96927833-a23c5180-1485-11eb-8128-83ef0518529c.jpg)

You can also click through this prototype I put together in Figma: [Link to prototype](https://www.figma.com/proto/ai6SnOBOYfTK4jEjh8gQ18/Public-Collections?node-id=30%3A392&viewport=-57%2C-1508%2C0.3016427457332611&scaling=scale-down)

Note that you can scroll down to see more rows, and you can click on "My WASH questions" to see a collection example. Clicking on the "owner" header will sort the table accordingly, and you can also click the "back" and the "display full details" in the collection example. Also, feel free to comment directly in the prototype (let me know if you can't).

cc @jnm

**Comment by tinok** [comment]
Can't open/comment on the Figma prototype yet but the screenshots address all remaining issues. Small nitpicks: 

* The Name column should be wider in favor of a more narrow 'Items' column
* We should use Items throughout (it says 'Assets' in two places in the collection preview)
* Collection preview: Instead of Display full details I suggest 'View all meta data'
* Collection preview: I think we could / should add all the meta details already shown in the public collections table (items, owner, languages, last modified), it should all fit in that single row. Is "Date" the same as "last modified" date?

@magicznyleszek do you still have concerns about the feasibility of this?

**Comment by magicznyleszek** [comment]
@tinok @Ig-Rebollo to boil down what I understand the changes are:

1. Always show collections first on the list (and thus only on first page of results)
2. Change the displayed columns
3. Change the looks of collections in table
4. Change the looks of collection page

**Comment by Ig-Rebollo** [comment]
@magicznyleszek (and @tinok) here are the svg files for all the icons in the designs. Let me know if you have any issues or questions on how/where to use them:
[Public collections icons.zip](https://github.com/kobotoolbox/kpi/files/5503736/Public.collections.icons.zip)

I also sent you an invite to the Figma file so you can inspect the designs and see all the specs (on the right hand side bar).

**Comment by tinok** [comment]
@Ig-Rebollo The Figma views look good to me and can be updated from my end @magicznyleszek. 

The only thing I could find that's missing from the UX screens are tags. I suppose we assume that if they exist they'd be displayed below the question label?

**Comment by Ig-Rebollo** [comment]
@tinok correct, the assumption is that the tags won't change from what we have now, and they would be displayed below as we have been doing so far.
