### ISSUE TITLE
[Public Collections] Single collection page only shows first page (10) of children with no way of loading more

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2834]
## Description

So the assumption was that `.children` will contain **all** the children. It was a bad assumption as `.children` have a standardized `count`, `next`, `previous` and `results` (the de facto list of children).

## Expected behavior 

Single collection page uses component from `assetsTable.es6` which has a built-in capability of displaing pagination and a change page callback.

There are two ways of handling this:

1. Easier - Use `AssetsTable`, 
~~provide proper pagination properties and on add a functionality to `assetRoute.es6` that uses the callback to load next or previous page of child assets.~~ 
`AssetsTable` already has pagination properties and expects its logic to be passed on instantiation, `collectionAssetTable` should be the one to pass the logic to it 
~~It would be nice to increase the default limit from `10` to a bigger number.~~ _(I've changed it already to `100`)_
2. ~~Harder - Drop pagination from `AssetsTable` and instead use an infinite scroll solution that will load next pages of results. This change will require to update all the places that uses `AssetsTable`.~~ It was agreed that we don't want infinite scroll :)

**Comment by magicznyleszek** [comment]
Note to a person fixing that: `assetRoute.es6` is being used to display all asset types. I think that it would be best to create a wrapper component for `collections`. This component should be used instead of `AssetsTable`, and contain the pagination functionality and rendering just the `AssetsTable`.

**Comment by jnm** [comment]
Fixed by #2882
