### ISSUE TITLE
The cursor automatically moves (scrolls) at the end when adding a question in the middle of the survey form.

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2837]
## Description

When adding a question in the middle of the survey form through the form builder UI, the cursor automatically moves (scrolls) at the end making users difficult to identify the question recently added.

## Steps to Reproduce

1. Design a survey form (which does not fit in your PC's screen).
2. Add a question somewhere in the middle of the survey form.
3. Your cursor automatically moves (scrolls) at the end of the form making users difficult to identify the question recently added.

## Expected behavior 

The cursor should not automatically move (scroll) to the bottom of the survey form.

## Actual behavior 

The cursor automatically moves (scrolls) to the bottom of the survey form.

## Additional details

**Link to the community forum:** https://community.kobotoolbox.org/t/stop-scrolling-to-the-bottom-when-adding-a-new-question/11999

**A sample video shared by the user:**

https://drive.google.com/file/d/1iCudX-koN5Ak-diHrgLlPVd9KtqWlLER/view

or it can also be viewed here:

https://community.kobotoolbox.org/t/stop-scrolling-to-the-bottom-when-adding-a-new-question/11999/15

**Comment by jnm** [comment]
I think I'm hallucinating, but I could swear that I saw some work that @magicznyleszek had already done that mentioned fixing this :dizzy_face:

**Comment by magicznyleszek** [comment]
Sorry, I don't recall fixing that 😕 I was able to reproduce it on `kf.beta`, but wasn't able to on `kf.master`, so it seems we've introduced it while doing some keyboard navigation or code cleanup changes.
