### ISSUE TITLE
Remove simserial and subscriberid from the form builder?

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2842]
Google is killing off Collect's access to these metadata: https://github.com/XLSForm/pyxform/issues/471

I guess we should remove them from our "Layout & Settings" sidebar. @tinok, what say you?

**Comment by tinok** [comment]
I agree, since after November 2020 they won't be receiving data anymore even if users are choosing to include them in their forms. We'll need to make sure this is explained in the changelog on the forum.

**Comment by jnm** [comment]
![image](https://user-images.githubusercontent.com/2085013/165367385-9168ff0a-32a3-4b22-9f33-c8050da43724.png)
