### ISSUE TITLE
Invalid KoBoCAT content types 

### ISSUE THREAD

**Issue by rroux** [kobotoolbox/kpi#2865]
Error from Sentry:
 
- Could not find KoBoCAT content type for api.organizationprofile
- Could not find KoBoCAT content type for api.team
- Could not find KoBoCAT content type for api.project

**Comment by noliveleger** [comment]
These content types do not exist anymore in latest release of KoBoCAT.

**Comment by jnm** [comment]
What's trying to reference them?
