### ISSUE TITLE
Data can't be accessed with publicly shared project when user has explicit view form permission

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2870]
## Description

When user 1 shares project data publicly AND shares the project's form with user2, user2 can't access the table view, map view, or export data. Any other user *without explicit permissions for the project* can access them as expected. 

## Steps to Reproduce

1. Create project for user1 (with GPS question), enter some data
2. Share data publicly, share form (view and edit) with user2
3. Sign in as user2, open table/map views or try to export data to XLS

## Expected behavior 

Table/map views open normally. Data exports to XLS.

## Actual behavior 

Table/map views do not load, they show `{"detail":"Not found."}`. 

When generated a data export it fails.

## Additional details

Tested with https://kf.kobotoolbox.org/#/forms/aitPkZ2AF6b59wjUeJKbBV/, user `tinok4`.

**Comment by jnm** [comment]
@Kalyan-Lama has tested this on kf.beta and reported:

XLS: Issue
XLS (Legacy): Working OK
CSV: Issue 
CSV (Legacy): Working OK 
Media Attachments ZIP: Working OK 
GPS Coordinates (KML): Working OK 
Excel Analyzer: Working OK 
SPSS Label: Issue

I believe everything listed as "Working OK" is handled by KoBoCAT

**Comment by noliveleger** [comment]
@Kalyan-Lama: I think the export issue is the known issue that John fixed https://github.com/kobotoolbox/kpi/pull/2868. 
I'm gonna merged it in to `kf.beta` and see

**Comment by jnm** [comment]
oh, @noliveleger, that's great. but just to confirm: #2868 works for this public data scenario, which is currently broken on production?

**Comment by noliveleger** [comment]
@jnm, nope :-(  #2868 only fixes the problem of exports @Kalyan-Lama reported.
The public data issue still remains.
