### ISSUE TITLE
[Public Collections] UI is not refreshed when clicking on projects under `Deployed`, `Drafts` or `Archived`

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#2885]
## Description

When you click on the project link in the sub-menu, the project panel is not refreshed entirely: 
- It seems as though the `asset-detail` endpoint is not being called,
- Additionally, the project title and number of submissions disappears,
- It seems to happen when projects share the same condition of length of submissions (i.e. 0 or more than 0) 

## Steps to Reproduce

1. Create 4 projects and deploy them
    - Project A (2 submissions)
    - Project B  (1 submission)
    - Project C  (0 submissions)
    - Project D  (0 submissions)
2. Two projects with 2 or more submissions
3. Two projects with 0 submissions
4. Expand `deployed` menu. 
5. Click on Project A
6. Click on Project C -> ok
6. Click on Project D ->  bug occurs
6. Click on Project B -> ok
6. Click on Project A -> bug occurs

## Additional details
Also happens when cloning a project and trying to go into it after cloning for the sub-menu.

Present on `kf.beta`, not `kf.master`

**Comment by jnm** [comment]
Closed by #2891
