### ISSUE TITLE
broken support link on Forms / Settings / Rest Services

### ISSUE THREAD

**Issue by nanometrenat** [kobotoolbox/kpi#2935]
## Description

https://kobo.humanitarianresponse.info/#/forms/avWN7sj2qxLvmpi3VK5TPz/settings/rest has a "Learn More" link that points to https://support.kobotoolbox.org/managing-your-project-s-data/rest-services - however since the restructure of the KoBo support portal that URL goes to a 404 not found page (Sorry. We couldn’t find this page).

Correct new link to support site should be https://support.kobotoolbox.org/rest_services.html

![image](https://user-images.githubusercontent.com/33625192/102570162-b336d580-414b-11eb-8b08-65bba36dad64.png)

Thanks!

**Comment by nanometrenat** [comment]
Also once the project DOES have a REST Service the same broken URL is shown in "Need help?" link - needs amendment to new support URL also.  Cheers
![image](https://user-images.githubusercontent.com/33625192/102572056-f72bd980-414f-11eb-8e30-9fd75c4d6aa7.png)

**Comment by jnm** [comment]
thanks!

**Comment by JacquelineMorrissette** [comment]
A Super User needs to login to the `{ROOT_URL}/admin/constance/config/` and change the SUPPORT_URL field to https://support.kobotoolbox.org/ and the links in both places should be updated automatically.
![image](https://user-images.githubusercontent.com/74968475/106039039-a2f90b00-60a6-11eb-9f01-43c3c16d751f.png)

**Comment by noliveleger** [comment]
@JacquelineMorrissette , if the fields is empty, does it fallback on the default or not?

**Comment by JacquelineMorrissette** [comment]
@noliveleger It does not. The links become text

**Comment by noliveleger** [comment]
It has already been fixed.
