### ISSUE TITLE
_id column sometimes doesn't show up in table view

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2937]
## Description

> Users are reporting that _id is not showing on the "Table" view of the interface since last deployment (see attachments). _id appears in the data export, just not on the table view. We checked our accounts and the same is happening - not to all forms, but to some of them

## Steps to Reproduce

1. Create a form with a `note` question type
2. Add some submissions
3. Obserwe all columns that are not other questions (or meta data selected in form settings, e.g. `start`, `simserial`) are not being displayed

## Expected behavior 

`_id` column should always appear and should be available for freezing

## Additional info

This was introduced in #2599

**Comment by jnm** [comment]
I asked for a sample form. Sorry, should've done that before asking you to have a look :kissing_heart:
