### ISSUE TITLE
Loading error seen like trying to collect data through Enketo

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2942]
## Description

The recent upgrade of `Enketo` seems to be affecting data collection through `Enketo`. When trying to collect data through `Enketo` users see `Loading error` issue.

## Steps to Reproduce

1. Upload and deploy a simple sample xlsform. For ease you may try this out:
[BUG_Test01.xlsx](https://github.com/kobotoolbox/kpi/files/5765377/BUG_Test01.xlsx)
2. Deploy and collect with `Collect android app`, everything works smoothly. However, if you try using `Enketo`, you will be seeing a `Loading error` issue as shown in the image below:
![Image 1](https://user-images.githubusercontent.com/50188479/103549662-d72a4300-4ecf-11eb-8ee3-53a68bd6c4c6.png)

## Expected behavior 

Users should not be seeing the `Loading error` issue while collecting data with `Enketo`.

## Actual behavior 

Users are seeing `Loading error` issue while collecting data with `Enketo`. 

## Additional details

The xlsform does not show any issue while validating it with the [online validator](https://getodk.org/xlsform/).

**Comment by jnm** [comment]
Thanks for documenting this. Martijn is working on it [here](https://github.com/enketo/openrosa-xpath-evaluator/issues/67), and as you know, we've rolled back to a version that does not contain this bug.
