### ISSUE TITLE
Hide edit permissions option from Sharing Modal if user doesn't have necessary permissions

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2944]
## Description

As a user who is not an owner and with only "View form" permission I can still access the edit permissions form (it does fail to do anything if trying to use it though):

<img width="593" alt="Screenshot 2021-01-05 at 17 08 03" src="https://user-images.githubusercontent.com/2521888/103676758-63447500-4f79-11eb-9ca2-8dbc37833428.png">

**Comment by duvld** [comment]
Not exactly related but in the same genre as this issue: https://github.com/kobotoolbox/kpi/issues/2655  -- I can tackle them together since they both deal with parts of KPI that should be inaccessible without certain permissions.

**Comment by magicznyleszek** [comment]
@duvld I would say go for it :)
