### ISSUE TITLE
Overriding graph style with non-English UI crashes the reports

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2950]
## Description

Whole app crashes when "Override Graph Style" is used with non-English UI language.

## Steps to Reproduce

1. Create a form, deploy it and submit some data
2. Go to "Data" > "Reports"
3. Change app language to "Francais" (from the user dropdow in top right corner)
3. For some question choose "…" (the "Override Graph Style" option; in french it says "Remplacer le style de graphique")
4. Choose "Secteurs" and save ("Sauvegarder")
5. Observe the crash you can't fix through UI

## Expected behavior 

It should work :)

## Actual behavior 

App crashes with no way to fix it through the UI. It will crash each time user enters "Reports" route.

## Additional details

There are two problems here:
1. Frontend sends wrong graph style to the endpoint - instead of a constant english name (`report_type: "pie"`) it sends a translated name (`report_type: "secteurs"`)
2. Backend allows setting nonexistent graph styles

**Comment by jnm** [comment]
about (2), i'd say that the graph styles are a nice little nook for the front-end to put stuff. the back end never makes any graphs and doesn't know what's valid or not—though maybe we could communicate that somehow, in a shared definition of graph styles.

we've had other examples of the app crashing when this stuff gets messed up; should we ignore the custom styles if they are invalid and load the UI with the defaults?

**Comment by jnm** [comment]
The front-end aspect of this has been fixed by #2949.

Internal discussion of the back-end validation is at https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/Reports.20broken.20for.20non-English.20override

**Comment by jnm** [comment]
Closed by #2949. We won't add back-end validation for this.
