### ISSUE TITLE
Child assets not visible in list view of unsubscribed public collections

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#2951]
## Description

As described in #2872 in this [comment](https://github.com/kobotoolbox/kpi/pull/2872#issuecomment-751987137):
> When viewing someone else's public collection that I have not yet subscribed to, I cannot see the contents; "There are no assets to display" is shown. However, as soon as I click subscribe, I can see the contents as I should.

## Steps to Reproduce

1. Visit a public collection that has at least one child asset that you aren't subscribed to
2. The list of child assets is empty
3. Visit the url of the child asset(s) directly and they are visible

## Expected behavior 

Visiting an unsubscribed public collection with child assets should list them under the following circumstances (from Zulip conversation [here](https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/Public.20collections.20tweaks.20backend/near/12011)):

- I have a collection with 5 child assets
- I make the collection public (give anonymous the view permission)
- This permission is inherited by all 5 children
- Anyone should be able to see this collection and its 5 children
- Now, I explicitly remove the anonymous view permission from one of the children (set a "deny" permission on this child)
- Change: anyone should be able to see this collection and 4 out of 5 of its children

## Actual behavior 

List view of child assets is empty.

**Comment by jnm** [comment]
Closed by #2955
