### ISSUE TITLE
Hide sharing settings from those who can't change them

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#2964]
Only owners and people with "manage project" should see these controls (see #2956). Letting non-owners remove themselves from a shared project without access to these controls is covered by #2940.

> @jnm @duvld I know the plan is to remove the sharing modal for non-owners, but what about the edit feature buttons on the `settings/sharing` screen (highlighted in red below)? Currently it's confusing to users who continue to see them. 
> 
> ![image](https://user-images.githubusercontent.com/673511/105048478-a0a90800-5a39-11eb-8737-a55806657c92.png)
> 
> _Originally posted by @tinok in https://github.com/kobotoolbox/kpi/issues/2956#issuecomment-762879908_

**Comment by jnm** [comment]
Maybe this duplicates #2944? Or I guess it supersedes it because we're going to remove access to the modal and settings page altogether.

**Comment by JacquelineMorrissette** [comment]
Closing this because I was not able to find a way to access that screen without the `manage project` role
