### ISSUE TITLE
auto report broken because of translated graph type

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#2965]
## Description
If a user changes their UI language (e.g. to French) the graph types for auto reports are mistakenly translated as well, which causes the report to crash after customizing the graph type. 

Background: For [some projects](https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/Need.20help.20with.20PATCH.20request.20to.20fix.20broken.20auto.20report/near/13622) the UI of the auto report crashes (blank screen after loading #/forms/[uid]/data/report) after the user had customized one of the graphs. It seems that when customizing the graph the API was given incorrect (French) names for `report_type`: 

* instead of `horizontal` it used `barres_horizontales`
* instead of `pie` it used `secteurs`

Project 1 is set to: 

```json
"report_styles": {
        "default": {
            "groupDataBy": "",
            "report_type": "vertical",
            "translationIndex": 0
        },
        "specified": {
            "A01": {
                "width": false,
                "report_type": "secteurs",
                "report_colors": false
            }

```

project 2:

```json
  "report_styles": {
        "default": {
            "groupDataBy": "",
            "report_type": "vertical",
            "translationIndex": 0
        },
        "specified": {
            "Etes_vous_enceinte": {},
            "Genre_de_la_personne_interroge": {},
            "A01b_Financement_de_la_structure": {
                "width": false,
                "report_type": "barres_horizontales",
                "report_colors": false
            }
        },

```

## Steps to Reproduce

1. Open existing project with data
2. Change UI language to French
3. Open auto report for that project
4. Change the type of one of the graphs to "Barres verticales" (meaning pie chart)

## Expected behavior 

Graphs are set to the correct graph type in the `PATCH` request (`vertical`) when overriding the default types; report loads fine.

## Actual behavior 

PATCH request sends `barres_verticales` as graph type. 

Report page loads as blank screen.

In addition, the images from the graph modal are not showing up. See screenshot showing the wrong `value` for the horizontal graph type in the source code: 

![image](https://user-images.githubusercontent.com/673511/105372458-9e7ab100-5bd3-11eb-868d-65619c2fb93c.png)

**Comment by tinok** [comment]
I think this line is the culprit: https://github.com/kobotoolbox/kpi/blob/03861efdb9a2d3ecb4aa0052ea6f3f860a264283/jsapp/js/components/reports.es6#L27

**Comment by jnm** [comment]
Isn't this the same thing as #2950? If so, then the question is whether or not "high priority" means backporting the fix to the `master` branch and doing a separate release for that instead of waiting until public collections, which includes #2949, is released.

**Comment by tinok** [comment]
No separate release needed @jnm, closing this as duplicate.
