### ISSUE TITLE
Page goes blank when users click the eye like preview button from DATA>Table!

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#2969]
## Description

Page goes blank when users click the `eye like preview button` from `DATA>Table`.

## Steps to Reproduce

1. Open the project.
2. Go to `DATA>Table`.
3. Click the `eye like preview button`. The page goes blank.

## Expected behavior 

User should be able to preview the data that is present in their account.

## Actual behavior 

Page goes blank.

## Additional details

Viewing the `custom report`, `editing the submission` has no effect i.e. they work smoothly as expected. **Link to the community forum:** https://community.kobotoolbox.org/t/kobotoolbox-returning-a-blank-page-after-clicking-the-submitted-form/15288/9

**Comment by magicznyleszek** [comment]
Zulip conversation about this issue: https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Bugs.20on.20viewing.20a.20form.20using.20the.20eye.20button/near/13688
