### ISSUE TITLE
[Public Collections] Assets Table column filter clearing UX improvement

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#2996]
## Description

After you choose filter option from a dropdown (e.g. "Francais (fr)" language) it's not clear how to unselect it (so to be "any language"). _Currently it requires to select the same dropdown option again._ Possible solutions:
  - wait for #2990 and make clearing happen in the search box _(Note: what if we don't have search box visible, but we have assets table with filters - like at single collection route?)_
  - always include "All <name>" (e.g. "All languages") option that will clear the filter
  - add some "x" clear button next to a filter if it has some selection

## Additional details

Connected issues:
- #2835
- #2990

**Comment by jnm** [comment]
closed by #3026
