### ISSUE TITLE
Libraries beta UX/UI review

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/kpi#3000]
@jnm @magicznyleszek @tinok 

Including here some feedback from the review of https://kf.beta.kbtdev.org/

You can find everything in this PDF: 
[LibrariesUXUIreview.pdf](https://github.com/kobotoolbox/kpi/files/5928215/LibrariesUXUIreview.pdf)

Below I pasted images of each page.

**Comment by Ig-Rebollo** [comment]
![LibrariesA](https://user-images.githubusercontent.com/22472326/106949249-b6d1ec00-66fa-11eb-83bc-d9bf312cd9bf.jpg)
![LibrariesB](https://user-images.githubusercontent.com/22472326/106949251-b76a8280-66fa-11eb-9c50-1a5183af9abe.jpg)
![LibrariesC](https://user-images.githubusercontent.com/22472326/106949255-b8031900-66fa-11eb-9b6c-b55243b5c832.jpg)
![LibrariesD](https://user-images.githubusercontent.com/22472326/106949259-b89baf80-66fa-11eb-8a01-0a26f579de47.jpg)
![LibrariesE](https://user-images.githubusercontent.com/22472326/106949263-b9344600-66fa-11eb-864d-2fb9aaa16f19.jpg)
![LibrariesF](https://user-images.githubusercontent.com/22472326/106949264-b9ccdc80-66fa-11eb-8359-b76b04d24bd6.jpg)
![LibrariesG](https://user-images.githubusercontent.com/22472326/106949265-b9ccdc80-66fa-11eb-84bb-11db6188f83c.jpg)
![LibrariesH](https://user-images.githubusercontent.com/22472326/106949266-b9ccdc80-66fa-11eb-9f42-7740318e4282.jpg)
![LibrariesI](https://user-images.githubusercontent.com/22472326/106949269-ba657300-66fa-11eb-95e7-69f7a94ae355.jpg)

**Comment by Ig-Rebollo** [comment]
Leaving screenshots here for easier reference:

![LibrariesA](https://user-images.githubusercontent.com/22472326/106949562-1cbe7380-66fb-11eb-959d-f2ed105a1dc8.jpg)
1. The title ‘public collections’ has too much space below and not enough to its left. I would do the padding 15px on the top, bottom, left and right, as opposed to the current 20px 10px
2. Rows on hover should be a different colour than the grey of the header, otherwise the limits of the table become unclear. We could use the same light tile green that we use for the hover in the data table
3. The bottom space with the options is too crammed. We could either give it extra space and mark the border line more, or make it look like the header (light grey) so it is clear that it is not a row in the table

![LibrariesB](https://user-images.githubusercontent.com/22472326/106949667-411a5000-66fb-11eb-8edf-e91a94fb3bb6.jpg)
1. Titles of the table that sort their own columns (such as Name) can’t go back to ‘normal’ after you click on them. If I click on Name it sorts alphabetically, and if I click again it sorts alphabetically but starting from the end (the Z). I think with a third click it should go back to ‘no sorting’ or default.
2. Toggle fullscreen should go on the top right corner. Just over the table. It is very hard to find otherwise

![LibrariesC](https://user-images.githubusercontent.com/22472326/106949762-627b3c00-66fb-11eb-8b4a-00f276285f6d.jpg)
1. Some titles allow filtering instead of sorting. This can be confusing. Sorting and filtering should be separated. In the data tables we use a different row for each function (sorting or filtering. We should stay consistent with that. Maybe something to fix at a later stage, but worth keeping in mind
2. Not very important, but just to make it more visually pleasing, the drop downs could have the same width than the grey square of the heading/title. If the information doesn’t fit, it simply goes to a second line. The only important thing when allowing text to go into a second line is that the space between two lines that belong to the same cell must be narrower than the space between two unrelated lines

![LibrariesD](https://user-images.githubusercontent.com/22472326/106949814-7b83ed00-66fb-11eb-884b-306aff7be581.jpg)
1. All the text in the table is the same colour (almost black). I would make the text from all the columns that are not ‘Name’ a slightly lighter grey. This will highlight more the main piece of information, wwhich is ultimately the name. It is also important that those other columns (such as owner or last modified) don‘t go too light, as they still need to provide enough contrast. Something like #585B6F should work well.
2. Subscribe doesn’t need a shadow effect. In fact the way I originally thought of it it doesn’t have filling either, though I can see how that would be challenging as it is ‘on top’ of the date. We can leave that as is, but the hover should also work like this (see screenshot)

![LibrariesE](https://user-images.githubusercontent.com/22472326/106949904-9d7d6f80-66fb-11eb-9228-8fb4dc90c789.jpg)
1. Why is there so much empty space on top of the title/breadcrumbs? Couldn’t it be aligned with the subscribe button?
2. Same than in previous screen. No shadow, fill on hover.
3. Tags may look confusing as they are right now. They look crammed and busy with so many lines, plus, they could be confused with clickable buttons. I would style them just like the number of questions marker on the right side. light grey background, no border, round corners. It will make it more consistent but also less busy.
4. Same than before, I would make the text in these columns lighter (#585B6F)

**Comment by magicznyleszek** [comment]
I was able to fix most of the problems (leaving the most time consuming to be done later):
- [x] The title ‘public collections’ has not enough space
- [x] Rows on hover should be a different colour than the grey of the header
- [x] The bottom space with the options is too crammed
- [x] the drop downs could have the same width than the grey square of the heading/title
- [x] I would make the text from all the columns that are not ‘Name’ a slightly lighter grey
- [x] Subscribe doesn’t need a shadow effect (…) the hover should also work like this (see screenshot)
- [x] Tags may look confusing as they are right now
- [x] Icons would also benefit from a change in color
- [x] Same as before, I would also change the icons to a lighter grey here.
- [x] This ‘show more’ appears on some screens but not others(…)
- [x] I would leave a lot more separation space between the ‘make public’ button and the icons

**Comment by magicznyleszek** [comment]
The things we didn't do will be implemented in a possibly different way (or not implemented at all). We will get back to Library in far future with some fresh ideas too. I'm closing this.
