### ISSUE TITLE
Can't type in the bulk edit submissions modal text box

### ISSUE THREAD

**Issue by duvld** [kobotoolbox/kpi#3003]
## Description

Trying to type in the bulk edit submissions text box gives:
```
Uncaught TypeError: Cannot read property 'preventDefault' of undefined
```
at this line:
https://github.com/kobotoolbox/kpi/blob/57a64333903704086f725b9c7068c88b4259c72a/jsapp/js/components/modalForms/bulkEditSubmissionsForm.es6#L458

## Steps to Reproduce

1. Try to edit multiple submissions
2. Type replacement submission in text box

**Comment by magicznyleszek** [comment]
@duvld Could you re-test it with latest `beta` and confirm it is fixed? :pray:

**Comment by duvld** [comment]
https://github.com/kobotoolbox/kpi/commit/95e7688ede6ed73d48bf1cf22a85e63eabfc9f7c fixes this :)
