### ISSUE TITLE
Back-end work for "locking" library templates

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3005]
This issue tracks the back-end work needed to implement #2991.

Should we use a single JSONB field for all the locking settings? Could re-use the [`settings` field](https://github.com/kobotoolbox/kpi/blob/53cbd561d12d2b8d94fae83fb96048309d50a15e/kpi/models/asset.py#L485)?

Things we need to store for both templates and surveys created from templates:
1. "Locked" status of entire asset
1. "Core", "Pinned", or nothing-special status of each question

These settings need to be copied from the template to any surveys created from that template.

When someone saves a survey that's locked, there's no need to validate on the back end that only authorized things have been changed. The restrictions will be implemented by the front end only.

We should disable XLSForm uploads for locked surveys. Again, though, this can be a front-end only restriction. The goal is to prevent people from accidentally undermining data aggregation across many surveys, not to implement a permission system that's robust against malicious actors.

**Comment by jnm** [comment]
@noliveleger, the scope of our last estimate is incomplete. We have to design some kind of KoBo-specific XLSForm syntax that lets form authors include the per-template and per-question locking status within their spreadsheets. Then, we'll have to copy this to the `settings` (or whatever) JSONB upon import.

**Comment by noliveleger** [comment]
Let's use a namespace for that (in XLSForm I mean), just to be sure we don't interfere with global settings.
