### ISSUE TITLE
Create new warning box component

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3014]
## Description

Currently we use these:

<img width="893" alt="Screenshot 2021-02-17 at 16 28 47" src="https://user-images.githubusercontent.com/2521888/108234997-4c2ea080-713d-11eb-9c2f-867e61e7e7e5.png">
<img width="1132" alt="Screenshot 2021-02-17 at 16 29 07" src="https://user-images.githubusercontent.com/2521888/108234999-4cc73700-713d-11eb-8392-ec94e3e1c863.png">
<img width="946" alt="Screenshot 2021-02-17 at 16 29 14" src="https://user-images.githubusercontent.com/2521888/108235001-4d5fcd80-713d-11eb-965b-81cb9a17737d.png">

But we need this instead:

<img width="902" alt="Screenshot 2021-02-17 at 16 27 19" src="https://user-images.githubusercontent.com/2521888/108234868-23a6a680-713d-11eb-91c5-58edf16b3160.png">

The component will need:
- message (required)
- button name (defaults to "OK", not required)
- type (changes the color and the icon):
  1. warning
  2. info
  3. error
- interactivity uid (optional unique ID that enables "OK" button)
  1. empty (no "OK" button)
  2. provided 
    - "OK" button that should remove the message when clicked
    - store that action in `localStorage`
    - check if its really unique?

**Comment by Ig-Rebollo** [comment]
Thanks for creating this @magicznyleszek 

The main issue I see with some of the current banners/notifications is that they don't provide enough contrast:
![image](https://user-images.githubusercontent.com/22472326/108242643-24c6dc00-711b-11eb-9bc0-de5a048853ea.png)

This is what I had in mind for the banners. The list is of course totally open for discussions, these are just some of the cases I found more important. The color contrast in these examples is still improvable, but it has a better ratio and covers more indicators:
![notification_banners](https://user-images.githubusercontent.com/22472326/108242876-6e172b80-711b-11eb-8666-43f27dd5d4d7.jpg)

Here are some of the specs.
All rectangles:
```
/* Rectangles */
height: 46px;
border-radius: 2px;

/* text */
font-family: Roboto;
font-weight: normal;
font-size: 14px;
line-height: 18px;

/* OK */
font-family: Roboto;
font-style: normal;
font-weight: bold;
font-size: 14px;
line-height: 18px;
```

Colours:
```
/* 1 */
background: #FFE3C9;
/* text */ color: #845947;
/* ok */ color: #FF8933;
/* icon */ color: #D28E70;
/* 2 */
background: #C0FFFB;
/* text */ color: #414453;
/* icon */ color: #52C5D0;
/* 3 */
background: #E8E9ED;
/* text */ color: #845947;
/* ok */ color: #2095F3;
/* icon */ color: #6E738C;
/* 4 */
background: #585B6F;
/* text */ color: #FFFFFF;
/* ok */ color: #A1D2F7;
/* icon */ color: #CBCED7;
/* 5 */
background: #FFDEE2;
/* text */ color: #834149;
/* dismiss */ color: #FF556A;
/* icon */ color: #FF556A;
/* 6 */
background: #FFDEE2;
/* text */ color: #834149;
/* icon */ color: #FF556A;
```

**Comment by JacquelineMorrissette** [comment]
Closing, I believe we have moved on from these improves styles on top of the original ones
