### ISSUE TITLE
Empty (or low-content) collections should not be public

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3031]
Original discussion: https://github.com/kobotoolbox/kpi/projects/3#card-54251758

A lot of people have been trying out public collections (which is great!) and publishing empty or one-item collections. As we roll out our revamp of the library, we should remove the `discover_asset` flag from these collections so that they do not clutter up the search results and make people's first experience with the new design a negative one.

We will remove all collections that
* ~~Either~~ have zero children ~~*or*~~
* ~~Do not have metadata for "Name, organization and sector"~~

Commands to run in `./manage.py shell_plus`:
```python
from kpi.constants import ASSET_TYPE_COLLECTION
from kpi.models.object_permission import get_anonymous_user

anon_can_discover = ObjectPermission.objects.filter(
    user=get_anonymous_user(), permission__codename='discover_asset'
)
unpublicd = []
for perm_assignment in anon_can_discover:
    asset = perm_assignment.asset
    if asset.asset_type != ASSET_TYPE_COLLECTION:
        continue
    # if not all(
    #     (asset.name, asset.settings.get('organization'), asset.settings.get('sector'))
    # ) or (not asset.children.exists()):
    if not asset.children.exists():
        print('Removing discoverable permission from', asset, asset.children.count(), asset.settings)
        ObjectPermission.objects.filter(user=get_anonymous_user(), asset=asset).delete()
        unpublicd.append(asset)

for u in unpublicd: print(u.pk, u.uid, u.owner.username, u.name)
```

**It would be prudent to check for half-public collections**, i.e. those where `AnonymousUser` has `view_asset` but not `discover_asset`, at this time and remove these `view_asset` assignments:
```python
from kpi.constants import (
    ASSET_TYPE_COLLECTION,
    PERM_VIEW_ASSET,
    PERM_DISCOVER_ASSET,
)
from kpi.models.object_permission import get_anonymous_user

anon_can_view = ObjectPermission.objects.filter(
    user=get_anonymous_user(),
    permission__codename=PERM_VIEW_ASSET,
    asset__asset_type=ASSET_TYPE_COLLECTION,
)
for perm_assignment in anon_can_view:
    if not ObjectPermission.objects.filter(
        user=perm_assignment.user,
        asset=perm_assignment.asset,
        permission__codename=PERM_DISCOVER_ASSET,
    ).exists():
        print('Half-public collection', perm_assignment.asset, perm_assignment.asset.owner)
```

**Comment by tinok** [comment]
I guess the right course is to leave the ones in that are missing meta details and only remove the ones with 0 assets. We can later on deal with the issue of getting mandatory meta data later on through a request in the UI.

**Comment by jnm** [comment]
Now complete on both HHI and OCHA (not performed on UNHCR)
