### ISSUE TITLE
Support select_one from repeats by upgrading pyxform to v1.3.1+

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3040]
## Description

[Online validator](https://getodk.org/xlsform/) seems to support this cool new feature where a user can create a `select one` choices from a text question from within a repeat group. 

![Image 1](https://user-images.githubusercontent.com/50188479/109484101-23e16300-7aa8-11eb-9aa4-3a107fbbf0ba.png)

It would be good to see this feature in KoBoToolbox too. The requirement for this feature, however, is `pyxform v1.3.1`.

**Reference xlsform:**

[select-one-from-repeats.xlsx](/user_uploads/2/de/OGNb3hv0hq-a3k7xU5o5MNn1/select-one-from-repeats.xlsx) 

**Link to the community post:** https://community.kobotoolbox.org/t/select-one-from-repeats-not-supported-in-kobotoolbox/16451

**Comment by jnm** [comment]
Hi @Kalyan-Lama, could I suggest making the issue title something more descriptive that states either the problem or solution? For example, it could state that the select one from repeat feature doesn't work with KoBo, or state that KoBo should upgrade to pyxform 1.3.1 (to gain new features including select one from repeat). These kinds of titles allow people reading the issue list to get an idea of each task without needing to click on each issue. Your description is great, though, so thank you!

For future reference, the documentation: https://docs.getodk.org/form-logic/#generating-select-ones-from-repeats
(This feature is not documented on xlsform.org)

**Comment by jnm** [comment]
Please reopen if this does not work as expected.
