### ISSUE TITLE
Stored XSS which takes hostile data

### ISSUE THREAD

**Issue by WinnyTroy** [kobotoolbox/kpi#3048]
## Description of the Vulnerability
Stored XSS which takes hostile data, stores it in a file, a database, or another back-end system, and then at a later stage, displays the data to the user, unfiltered.

Bug Type: Stored XSS
Bug Severity: High
Affected Users: All users

Location of bug: https://forms.ona.io/#/forms/<asset_uid>/edit
Attack string (payloads): `prompt(document.cookie);>#\"><img src=x onerror=prompt(document.cookie);>#\"><img src=x onerror=prompt(document.cookie);>#\"><img src=x onerror=prompt(document.cookie);>`
## Steps to Reproduce
1. Launch a form on Formbuilder
2. Add Question and Select File upload
3. Put your payload in Default Response and Click Save

## Expected behavior 

Creating/ Updating assets with malicious content should fail on save

## Actual behavior 

![kpi_vulnerability](https://user-images.githubusercontent.com/11174326/110088605-1f69c280-7da6-11eb-8494-87029522c323.png)

**Comment by jnm** [comment]
Hi @WinnyTroy, thanks for reporting this and thanks especially for proposing a fix.

1. In the future, please don't post something you consider to be a high-severity security vulnerability that affects all users to a public venue like this. You can contact us via info@kobotoolbox.org, as listed on our [GitHub organization page](https://github.com/kobotoolbox) and our [website](https://www.kobotoolbox.org). Luckily, KoBoToolbox does not seem to be affected by this particular issue, so this disclosure doesn't expose our users to any risk.
1. I cannot reproduce this on KoBoToolbox at all, so I think the behavior you've seen may relate to Ona-specific modifications.
    1. Clicking "SAVE" in the KoBo form builder does not invoke ODK Validate. That only happens on form (re)deployment, after KPI passes the form content to KoBoCAT.
    1. I did test your adding string as the "Default Response" for a "File" question in the form builder, and I had no problem saving, previewing, and deploying the form, nor did I see any issue when opening the deployed form in Enketo. No errors were displayed, and no injected JavaScript was executed by the browser.
    ![image](https://user-images.githubusercontent.com/2085013/110195703-3bed1580-7e0d-11eb-83eb-01f487fda915.png)
    1. I placed your string in another field where it did cause an ODK Validate error, but that still didn't lead to a vulnerability because KoBoToolbox [currently cannot display these ODK Validate messages](https://github.com/kobotoolbox/kobocat/issues/545). We'll be attentive to the issue you've raised here when fixing KoBoCAT so that it passes through validation errors.
