### ISSUE TITLE
Custom exports UI tweaks

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3062]
## Description

Things to be changed:
1. Move group separator to advanced view under "Include groups in header" and make it behave similarly to "name your custom export" and "Save selection as custom export" pair.
2. Rename "Export select_multiple responses" options to:
  - Options in columns and summary
  - Options distributed in columns
  - Only summary
3. "Export select_multiple responses" shouldn't be bold

**Comment by Ig-Rebollo** [comment]
Thanks @magicznyleszek 

Points 1. and 3. are clear I think. For 1, if both options are the same amount of work, let's make them unlock on check, instead of appear/disappear. It's always nicer to have the layout stable as opposed to changing sizes all the time. 

For point 2. we just need confirmation from @tinok . Maybe it can be simplified, something like:

- Option columns and summary
- Option columns
- Summary

**Comment by tinok** [comment]
> For point 2. we just need confirmation from @tinok . Maybe it can be simplified, something like:
> 
> Option columns and summary
> Option columns
> Summary

First, I think the category should be called 

* Export _Select Many_ questions as...

Then the three dropdowns could be: 

* Separate columns
* Single column
* Single and separate columns [note that I moved this to the end, even though it would remain our default]

### New issues 

- I think **Custom selection export** needs to be renamed to **Select which questions to be exported**
- When creating a regular export without making any changes to the advanced settings field, the "Custom exports" box appears anyway. I get that it's just saving whatever the most recent export settings were, even if they are our defaults. Maybe the field could just be renamed to something more intuitive, like `Export settings`?
- Usability: I find the dropdown for file type too small, seems unnecessary to have to scroll. XLS is very far down although it's the default for most users; maybe the options shouldn't be alphabetical. The legacy options could appear together at the end of the dropdown.  
- Missing feature? If you choose a custom export there is no way to go back to the default export (the one where the field just says "Select ..." in grey). I think this could be improved, something like a "Default" option that should always be there.  ![image](https://user-images.githubusercontent.com/673511/111238722-047d2680-85ce-11eb-8172-ae88fd29ce20.png)
- After entering a name in the `name custom export` field the dropdown below doesn't update, it still shows "Select..." even though the custom report was created (and would be used again if I clicked export)

Nice to have/enhancements:
- A shortcut to deselect all questions when creating a custom export 
- The table of previous exports should indicate if a subset of columns was used and/or include the name of the custom report if one was used

**Comment by Ig-Rebollo** [comment]
Fully agree with everything @tinok pointed out. Some additional comments from my side:

Custom exports could be named ```saved exports``` or even better ```saved export settings```. I also think the delete button looks strange where it is, it isn't clear what deletes. I would propose something like this:

![image](https://user-images.githubusercontent.com/22472326/111341116-98db9d80-864f-11eb-8f28-837b4cb4a9b3.png)
![image](https://user-images.githubusercontent.com/22472326/111341152-a2650580-864f-11eb-8cb9-93160822b83e.png)

Note that:
- Saved options can be deleted **in** the dropdown
- Selecting none = "no export settings selected" text in the textbox
- Selected options **do not have a blue background** (as in Tino's screenshot) but simply make the font bold and blue.

I agree that the dropdown is too small in some cases. If we can avoid scrolls, much better. Also, I'd say the dropdowns are too separated from the text boxes they belong to. I would not leave more than 3 or 4 px of distance max.
![image](https://user-images.githubusercontent.com/22472326/111344033-61babb80-8652-11eb-8133-6d95c3bbe1cb.png)

We can add on the top right corner small text buttons to select/deselect all. These would be greyed out with the same opacity than the rest of the table when this functionality is not enabled:
![image](https://user-images.githubusercontent.com/22472326/111343402-c4f81e00-8651-11eb-86ae-83bb9c45892c.png)

**Comment by magicznyleszek** [comment]
Things fixed:
- moved group separator to advanced view
- reordered export types options: first XLS, then non-legacy alphabetically and then legacy alphabetically
- turned off the dropdown height limit
- changed the dropdown selected option styles (note that this is a global change for all dropdowns)
- changed the opened dropdown distance to zero
- added pointer cursor to dropdown (don't know why wasn't it there before)
- removed bold from first row labels of advanced view
- added "None" option which resets all to default
- renamed "Export Select Many questions as…"
- changed "Export Select Many questions as..." options labels and their order
- renamed "Select which questions to be exported"
- renamed "Save selection as…" (to not use "custom export" naming)
- renamed "Name your export settings"
- renamed "Apply saved export settings" and "No export settings selected" when nothning selected

**Comment by magicznyleszek** [comment]
I will probably address the rest issues tomorrow :)

**Comment by magicznyleszek** [comment]
@tinok 
> After entering a name in the `name custom export` field the dropdown below doesn't update, it still shows "Select..." even though the custom report was created (and would be used again if I clicked export)

I don't know if I understand what you mean. To save export settings you need to enter the name and click "Export". The settings will be saved only if you make an actual export (it saves the settings and creates export immediately after that). And the dropdown will be updated then.

---

> The table of previous exports should indicate if a subset of columns was used and/or include the name of the custom report if one was used

Should it be a column "Custom selection" and "Yes"/"No" values? Or would you rather have a way to see which columns were selected?

And by "custom report" you mean "saved export settings"? If yes, then this would be a bit tricky. Each export stores the exact settings that were used to generate it, but I would need to match these with existing saved settings. This means that if user deletes saved export settings their name will not be possible to match with export. Or if user changes a saved export settings (saves different settings with the existing name), then the match will also be lost. What could be possible to do actually is to have an option for each export to load settings used for given export - what do you think about that option?

**Comment by magicznyleszek** [comment]
@Ig-Rebollo moving the delete button inside the dropdown will be quite complex. How important is it? :)

**Comment by tinok** [comment]
@Ig-Rebollo I'm guessing adding a delete button for the "None" row from your [earlier screenshot](https://github.com/kobotoolbox/kpi/issues/3062#issuecomment-800407861) was a mistake?

**Comment by tinok** [comment]
@magicznyleszek 
> 
> > After entering a name in the `name custom export` field the dropdown below doesn't update, it still shows "Select..." even though the custom report was created (and would be used again if I clicked export)
> 
> I don't know if I understand what you mean. To save export settings you need to enter the name and click "Export". The settings will be saved only if you make an actual export (it saves the settings and creates export immediately after that). And the dropdown will be updated then.

What I mean is that the name isn't filled in the dropdown after I click export. It's a small thing, but it felt like it hadn't saved my report. My expectation is like when saving a document that the document title is displayed once it was saved. So in that case the custom export name should selected in the dropdown. 
 
> > The table of previous exports should indicate if a subset of columns was used and/or include the name of the custom report if one was used
> 
> Should it be a column "Custom selection" and "Yes"/"No" values? Or would you rather have a way to see which columns were selected?
> 
> And by "custom report" you mean "saved export settings"? If yes, then this would be a bit tricky. Each export stores the exact settings that were used to generate it, but I would need to match these with existing saved settings. This means that if user deletes saved export settings their name will not be possible to match with export. Or if user changes a saved export settings (saves different settings with the existing name), then the match will also be lost. What could be possible to do actually is to have an option for each export to load settings used for given export - what do you think about that option?

I wouldn't want to see all the columns that were selected, there could be hundreds. The goal would be to know which row in the downloads corresponds to which export. E.g., I may create two custom exports ("Q&A" and "Map data only"), and every other day I generate a download for each and want to make sure I save each one in a separate location on my drive. 

Could we store and display the name of each custom export in the downloads list? Even if the export is deleted or updated after the fact it would be useful to see the name of the custom report that was used. I suggest we spin this off as a new issue.

**Comment by Ig-Rebollo** [comment]
> @Ig-Rebollo moving the delete button inside the dropdown will be quite complex. How important is it? :)

It would be a very nice to have because it clearly tells you what the trash icon is doing. When you place it beside the dropdown it is unclear if it deletes the template or the functionality (i.e. all the saved templates). But if it's going to add too much work it might not be worth it. **An easier alternative** would be to simply remove the outline around the trash icon you have right now. It will do the same thing and behave the same way, but it will look less like a button and be more subtle. This will help since deleting saved settings is a very secondary functionality, so it shouldn't be so prominent.

> @Ig-Rebollo I'm guessing adding a delete button for the "None" row from your earlier screenshot was a mistake?

Absolutely, that was a mistake. My bad. The 'none' option should always be there and it would not be possible to delete it.

**Comment by magicznyleszek** [comment]
> @magicznyleszek
> 
> > > After entering a name in the `name custom export` field the dropdown below doesn't update, it still shows "Select..." even though the custom report was created (and would be used again if I clicked export)
> > 
> > 
> > I don't know if I understand what you mean. To save export settings you need to enter the name and click "Export". The settings will be saved only if you make an actual export (it saves the settings and creates export immediately after that). And the dropdown will be updated then.
> 
> What I mean is that the name isn't filled in the dropdown after I click export. It's a small thing, but it felt like it hadn't saved my report. My expectation is like when saving a document that the document title is displayed once it was saved. So in that case the custom export name should selected in the dropdown.

Ah, right! Pushed a fix for that :)

> > > The table of previous exports should indicate if a subset of columns was used and/or include the name of the custom report if one was used
> > 
> > 
> > Should it be a column "Custom selection" and "Yes"/"No" values? Or would you rather have a way to see which columns were selected?
> > And by "custom report" you mean "saved export settings"? If yes, then this would be a bit tricky. Each export stores the exact settings that were used to generate it, but I would need to match these with existing saved settings. This means that if user deletes saved export settings their name will not be possible to match with export. Or if user changes a saved export settings (saves different settings with the existing name), then the match will also be lost. What could be possible to do actually is to have an option for each export to load settings used for given export - what do you think about that option?
> 
> I wouldn't want to see all the columns that were selected, there could be hundreds. The goal would be to know which row in the downloads corresponds to which export. E.g., I may create two custom exports ("Q&A" and "Map data only"), and every other day I generate a download for each and want to make sure I save each one in a separate location on my drive.
> 
> Could we store and display the name of each custom export in the downloads list? Even if the export is deleted or updated after the fact it would be useful to see the name of the custom report that was used. I suggest we spin this off as a new issue.

New issue: #3078 🆕

**Comment by magicznyleszek** [comment]
> > @Ig-Rebollo moving the delete button inside the dropdown will be quite complex. How important is it? :)
> 
> It would be a very nice to have because it clearly tells you what the trash icon is doing. When you place it beside the dropdown it is unclear if it deletes the template or the functionality (i.e. all the saved templates). But if it's going to add too much work it might not be worth it. **An easier alternative** would be to simply remove the outline around the trash icon you have right now. It will do the same thing and behave the same way, but it will look less like a button and be more subtle. This will help since deleting saved settings is a very secondary functionality, so it shouldn't be so prominent.

I made the delete button less prominent :+1:

**Comment by magicznyleszek** [comment]
I say we close it :) @Ig-Rebollo ?

**Comment by Ig-Rebollo** [comment]
I think all or most of our points were addressed so yes!
