### ISSUE TITLE
Report - Number of users by organization

### ISSUE THREAD

**Issue by JacquelineMorrissette** [kobotoolbox/kpi#3066]
## Description
Create a report using the user's self-reported organization and the domain of the user's email domain.
This should be accessible in Django admin and downloadable in `.csv` file format. This can be done using the server's database

## Suggestions
- The information should be made available in the Django admin panel

**Comment by tinok** [comment]
I assume it would be two separate tables? One by domain name, one by reported organization name.

**Comment by jnm** [comment]
> The report can be generated from the attachments model

I think this belonged to another report, maybe. Assuming it's talking about KoBoCAT's `logger.Attachment`, that won't help here.
