### ISSUE TITLE
Report - Continued usage statistics

### ISSUE THREAD

**Issue by JacquelineMorrissette** [kobotoolbox/kpi#3068]
## Description
Create a report for active users, who during the last 3, 6, or 12 months have done one of the following:
- Signed in
- Deployed a form
- Made a submission
- Received a submission

This also includes a comparison with previous years and quarters

## Suggestions
- Using a table, have a counter for each user every month and year which updates every time a new form and every time they login
OR
- Using server logs, aggregate the data once a month with a cron job
Note: We might be able to do this with a Django module

**Comment by tinok** [comment]
Added Received because we care also consider users as active whose accounts are actively receiving submissions _from other users_.

**Comment by jnm** [comment]
> Added Received because we care also consider users as active whose accounts are actively receiving submissions from other users.

Right. I think I mentioned this on the call but forgot our decision: do we count people who have access to a project that actively receives submissions, but who aren't the owner, also as active? (Even if we want that, maybe it could be saved for a second pass to keep the initial complexity down.)

**Comment by tinok** [comment]
We can keep this for a second pass or leave it out altogether. It's probably not an important difference: Someone owning a project that has received submissions over the last 3, 6, 12 months has likely also signed in to their project during that time.
