### ISSUE TITLE
[NLP] Usage tracking

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3098]
## Description (@JacquelineMorrissette and @jnm, 20221130)

This issue is about tracking **seconds** of ASR usage and **characters** of MT usage. We'll store these numbers separately for each NLP engine.

We will do it per project, following the example of the kobocat `MonthlyXFormSubmissionCounter` model. We will not have a daily counter at this time. We will not store a grand total for each user either, but we may add that later as a performance optimization (as a separate task from this one).

Let's deviate from the `MonthlyXFormSubmissionCounter` approach by storing the counters in a `JSONField`. That way, we can keep track of the different engines as well as ASR and MT usage in the same model. The structure could be like this:
```json
{
  "asr_seconds": {"google": 123},
  "mt_characters": {"google": 456},
}
```
This seems to work well with database aggregation features (assuming the `JSONField` is called `counters`):
```python
MonthlyNLPUsageCounter.objects.aggregate(
    total_google_asr_seconds=Sum(
        Cast('counters__google_asr_seconds', IntegerField())
    )
)
```
…but we should definitely write unit tests to verify that it works as expected in different scenarios, such as when someone just hasn't used a particular service in some months, which would cause the attribute for that service to be missing from the `counters` JSON object of certain `MonthlyNLPUsageCounter` instances.

For now, let's assume the least-charitable interpretation of usage counting: whitespace characters count, as do seconds of silence in the audio files.

Let's add to the count of ASR seconds after this line executes:
https://github.com/kobotoolbox/kpi/blob/5a34e87b3987b303727ae43cfa95481740a37b17/kobo/apps/subsequences/integrations/google/google_transcribe.py#L125

Let's add to the count of MT characters (`len(content)`) after this line executes:
https://github.com/kobotoolbox/kpi/blob/5a34e87b3987b303727ae43cfa95481740a37b17/kobo/apps/subsequences/models.py#L109

xref https://www.notion.so/kobotoolbox/NLP-Track-ASR-and-MT-usage-ce04b8d7198744f58023c295417feb8b

## From original issue description

Already complete:
  - current submissions usage :heavy_check_mark: 
  - current storage usage :heavy_check_mark: 

Tracked elsewhere:
  - ~~current plan (this plus payment plans configuration #3105 gives frontend enough information to disable functionalites)~~

**Comment by jnm** [comment]
@JacquelineMorrissette, for reference, here are some Django features that might be helpful:
https://docs.djangoproject.com/en/2.2/ref/models/expressions/#f-expressions
https://docs.djangoproject.com/en/2.2/topics/db/transactions/#django.db.transaction.atomic
https://docs.djangoproject.com/en/2.2/ref/models/querysets/#select-for-update

We discussed following the example of `XForm.num_of_submissions` and `UserProfile.num_of_submissions` when storing the total attachment storage space per project and per user. I certainly wouldn't treat the existing approach as infallible :)

It might be worth splitting this work into a new issue on KoBoCAT, but I'll leave that up to you :+1:
