### ISSUE TITLE
Auto-renaming of duplicate question names results in wrong name being changed

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#3116]
## Description

When a question is added after an initial deployment with a name that already exists, the original question name is automatically changed rather than the new question. This results in previous submissions being put under the new question name rather than the original. 

## Steps to Reproduce

1. Create a form with at least one question and a name such as `test`
2. Deploy
3. Submit data
4. Edit form and add another question with the name `test`
5. Deploy
6. Submit data

## Expected behavior 

Auto-renaming to avoid conflicts should change the new question name to something like `test_001`.

## Actual behavior 

The original question is renamed to `test_001`, the new question remains `test` and the old submissions are now under the new `test` column rather than `test_001`.

**Comment by jnm** [comment]
Perhaps related to #1358.

Could you clarify what you mean by "Create a form" and "Edit form"? Is this done by uploading XLSForm or using the form builder?

**Comment by joshuaberetta** [comment]
@jnm, you are correct -- I think this is a duplicate of that issue. I'll close this one 💁‍♂️

I saw this behaviour using form builder, but it was noted by OSM that this was the case when uploading an XLSForm too.
