### ISSUE TITLE
Review permissions for duplicate submission feature

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#3148]
## Description

Currently, users need `Edit submissions` to be able to duplicate a submission. When writing the unit tests for row level permissions I wondered whether it would be better to assign `Add submissions` because duplicating a submission is like adding a new submission. 

But @jnm said:
> One wrinkle is that the use case for duplicating submissions assumes the duplicate will usually be edited immediately after creation

That means the owner/ the managers should assign both permissions. It would be make sense, but as @tinok said
> from a UX side I think it's easier to assign one permission instead of two.

If we decide to use both, we would need to document it. Front-end code should be updated too.

related to #2768

**Comment by tinok** [comment]
@noliveleger I would say let's leave it with just `edit submissions` as you have it. Logically someone with that permission is able to do drastic changes to the collected data, so duplicating a row is not something I can imagine someone would want to restrict a collaborator from doing that.

**Comment by noliveleger** [comment]
As per our last discussion: Users will need both permissions:

- `add_submissions` to create the new duplicated submission 
- `change_submissions` to edit the new duplicated submission
