### ISSUE TITLE
Self-service sync_kobocat_xforms

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3150]
Extend #3002 so that people can synchronize their own forms. We used to offer this in a hacky way:

https://github.com/kobotoolbox/kpi/commit/b8351171428bd7a048c6334c68b0064167cf7845#diff-1483cb549cd31083151fa35593cfd9cd1d460bcca38c32a0049ac004d4459f1eL20

We need back-end support for this as well as some minimal UI component to invoke it. I'm unsure whether the UI component will be in KPI or KoBoCAT, but probably KoBoCAT given that we'll be [showing a notice](https://github.com/kobotoolbox/kobocat/issues/700) there?

**Comment by Ig-Rebollo** [comment]
I'd say definitely KoBoCAT. Given the need for it, probably we should place the UI (button?) in a prominent place, like right beside the 'Projects' heading, on top of the table.

**Comment by noliveleger** [comment]
@joshuaberetta, have a look at this PR too https://github.com/kobotoolbox/kpi/pull/3002/files 
It may help.
