### ISSUE TITLE
Non-owners with `manage_asset` permission unable to delete other non-owners' permissions

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#3154]
## Description

Non-owners with `manage_asset` permission should be able to manage all permissions of a project, other than removing the owner's permissions.

## Steps to Reproduce

1. User A creates form, gives user B `manage_asset` permissions and user C any permissions
2. User B is unable to remove user C from the project

## Expected behavior 

User B can remove all permissions from user C.

## Actual behavior 

User B can only edit permissions of user C, but not delete them entirely.

**Comment by jnm** [comment]
whoops, i should've closed this as it was fixed by #3155.

@joshuaberetta, seeing this not automatically close reminds me that a fix to a bug like this that's currently on production should be PR'd to `master` instead of `beta`. just for future reference :+1:
