### ISSUE TITLE
It is not possible to archive draft project

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3159]
## Description

The question probably is should it be possible. Currently we display Archive button for draft projects. We could either make it work or hide it.

## Actual behavior 

`405 Method Not Allowed` when `PATCH`ing `/api/v2/assets/<uid>/deployment/` - that's what archive does.

**Comment by jnm** [comment]
"archiving" right now means "stop accepting submissions", so it's not relevant for anything that hasn't been deployed. giving it an additional meaning to help with organization of drafts could be a future possibility, but that's not needed at this time.
