### ISSUE TITLE
Password reset email shows HTML as text

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3168]
Check out the `<a>` tag for the URL. Also, I thought we'd changed the default `kobo.humanitarianresponse.info Management` signature to something better already :thinking: 

> Greetings jnm,
> 
> 
> You are receiving this email because you (or someone pretending to be you)
> requested that your password be reset on the kobo.humanitarianresponse.info site. If you do not
> wish to reset your password, please ignore this message.
> 
> 
> 
> To reset your password, please click the following link, or copy and paste it
> into your web browser:
> 
> 
> <a rel="noreferrer" href="https://kobo.humanitarianresponse.info/accounts/password/reset/confirm/redacted">
>   https://kobo.humanitarianresponse.info/accounts/password/reset/confirm/redacted/
> </a>
> 
> Your username, in case you've forgotten: jnm
> 
> 
> Best regards,
> kobo.humanitarianresponse.info Management

**Comment by JacquelineMorrissette** [comment]
It was likely fixed with the switch to Django Allauth

```Quote
Hello from KoboToolbox,

We’ve received a password reset request for your user account.

To reset your password, click the link below.
https://kobo.humanitarianresponse.info/accounts/password/reset/key/4t2y-btd3gj-2474e29952be08ce6eb7ada7fe11b39b/

Your username is jackiemorrissette.

If you did not request a password reset, you can safely ignore this email.

Best,
KoboToolbox
```
