### ISSUE TITLE
Report shows same label multiple times

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3183]
## Description

https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Issue.20with.20custom.20report/near/29068

1. Use the particular form: [Label-issues.xlsx](https://github.com/kobotoolbox/kpi/files/6430653/Label-issues.xlsx)
2. Have some data submitted
3. Go to `/forms/<uid>/data/report`
4. Observe duplicated labels:
  <img width="748" alt="Screenshot 2021-05-05 at 23 40 30" src="https://user-images.githubusercontent.com/2521888/117218578-5175c000-adfb-11eb-95cb-84b5706408cd.png">

It seems that the problem with only labels being wrongly assigned. Please check `reports.es6` creating `reportData[i].data.responseLabels = [];`

**Comment by Kalyan-Lama** [comment]
For community reference: https://community.kobotoolbox.org/t/differing-data-between-reports-on-kobotoolbox-and-stata-dta-file/18540
