### ISSUE TITLE
Add additional GPS question types

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#319]
The two new questiontypes `geotrace` and `geoshape` should be added to the standard question types.  

| UI label | pyxform value |
| --- | --- |
| Single GPS point | geopoint |
| Multiple points / Line | geotrace |
| Multiple points / Polygon | geoshape |

**Comment by geomapdev** [comment]
I'm very interested in this feature, is there any update on it's status?  

Is it just a matter of including geoshape and geotrace everywhere that geopoint is found in kpi code, starting here?
https://github.com/kobotoolbox/kpi/blob/2749446ca9071fe027c76ae80d43960dd4464081/jsapp/xlform/src/model.configs.coffee#L168

**Comment by dorey** [comment]
This would be the simplest way to implement this but in general we are trying to avoid adding more options to the question type list.

What if we rename `"geopoint"` to `"geo"` and then make `point | trace | shape` options within the settings of the geo question?

**Comment by geomapdev** [comment]
That approach would require some changes in Kobocat and probably elsewhere:
https://github.com/geomapdev/kobocat/blob/master/onadata/apps/main/static/js/formManagers.js#L67

Since XLSForms treats geopoint, geotrace and geoshape as different question types, I think it would make sense to have the form builder match.
http://xlsform.org/#question-types

**Comment by geomapdev** [comment]
I ended up implementing this the easy way here:
https://github.com/geomapdev/kpi/tree/geofeatures-formbuilder

it's working well so far, let me know if you'd like me to create a PR.

**Comment by dorey** [comment]
Great. Yes, please do make a PR. It looks like that branch has everything we would need to merge.
Thanks!

**Comment by geomapdev** [comment]
done, thanks!
https://github.com/kobotoolbox/kpi/pull/1279
