### ISSUE TITLE
API to update single submissions?

### ISSUE THREAD

**Issue by Niush** [kobotoolbox/kpi#3190]
## Description

Is there any API "https://kf.kobotoolbox.org/api/v2/" to update single submissions? I did a lot of research and could not find any option to update submitted forms data using API.

From the Documentation:
> It is not possible to update a submission directly with kpi's API as this is handled by kobocat's `/submissions` endpoint. Instead, it returns the URL where the instance can be opened in Enketo for editing in the UI.

But, there is no `/submissions` endpoint, and the old version seems to be deprecated slowly.

## My Setup
Currently, I have set-up a Rest Service which calls my webhook API. This API uses the submitted POST data to perform some calculations and generate result. Now, I want to update the submission in kobo toolbox using the "**_id**" value and store the generated result in certain pre-defined field.

Is this possible in Kobo Toolbox with V2 API?

**Comment by jnm** [comment]
> But, there is no `/submissions` endpoint, and the old version seems to be deprecated slowly.

Sorry, this appears to be a typo: it should be `/submission`:
![image](https://user-images.githubusercontent.com/2085013/117695260-0c041a80-b18e-11eb-9548-f13f505a8457.png)

This endpoint is **not** being deprecated.

For information on how to submit an edit to an existing submission, i.e. including `<deprecatedID>my-old-submission-id</deprecatedID>` in the [submission XML](https://docs.getodk.org/openrosa-metadata/?highlight=deprecatedid#metadata-scheme), please see https://community.kobotoolbox.org/t/updating-records-via-the-api/4291/4?u=jnm.

Good luck!
