### ISSUE TITLE
Report data responses should consist of names not labels

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3192]
## Description

For choice questions currently `reports/<uid>/` endpoint returns submission choices `label`s (from default language) instead of `name`s. This is problematic as labels are ambiguous, and names are unique so it could lead to bugs (like #3183).

## Additional details

This would require FE changes too for adapting the new data format.

**Comment by magicznyleszek** [comment]
This could be done while implementing reports v2 endpoint? To not cause destructive changes for current users of API

**Comment by jnm** [comment]
Possibly here? (thanks to @joshuaberetta)
https://github.com/kobotoolbox/formpack/blob/661d64292246796a7080efccff5b3c0bf5836e18/src/formpack/schema/fields.py#L324-L327

**Comment by magicznyleszek** [comment]
Actually it seems reports v2 already exist: https://github.com/kobotoolbox/kpi/pull/3009

**Comment by magicznyleszek** [comment]
Tested it on `beta` and it seems to have been fixed :shrug:
