### ISSUE TITLE
Background audio recording functionality

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/kpi#3193]
Background recording of a survey is now available in Collect. This issue outlines how this functionality should work in KPI. 

### In the form builder
This feature would record the entire survey, producing a long file with all the questions and answers for a given submission. The background recording is not really a question type, but a form level function. It makes more sense to access this functionality in settings, even if it displays as a question of sorts afterwards in the form builder. See animation below:
![backgroundaudio-formbuilder2](https://user-images.githubusercontent.com/22472326/118563760-2cf3df00-b73d-11eb-9629-ed9962e3ab6b.gif)
![backgroundaudio-formbuilder](https://user-images.githubusercontent.com/22472326/118564038-9a077480-b73d-11eb-960d-656c6543aae8.jpg)

**Modifications in the form builder**
- [x] Create a section within settings to enable background recording. When activated, display options below (for the time being, the only choice available is audio quality).
- [x] When activated, this function will create a box with the background recording icon and a message indicating that the survey will be recorded.
- [x] The section in settings must include a note highlighting the fact that this feature only works on KoboCollect

### In the Table view
The designs used in this section are those of the new table view UI, which is described in more detail in #3198 and #3199. The addition of the background recording feature to the table view **does not require these updates**, so it could be implemented using the old UI until the updates are possible.
The background audio would be the first of the metadata columns. It would display an audio file icon and the total duration of the recording:
![Table view redesign](https://user-images.githubusercontent.com/22472326/119181008-0ab0d880-ba3f-11eb-9857-5977bb49d5ed.jpg)
It would also appear on the single submission view. Ideally, the single submission view could also be revamped as it appears on the mockup. If this is not possible at the moment, the same audio play functionality would be included on top of the data, opposed to Validation status.
Version without any major changes:
![singlesub old brec](https://user-images.githubusercontent.com/22472326/117724064-3a472180-b1b1-11eb-91f9-a0c4727ec24a.jpg)

**Important updates:**
- [x] Background recording should have a dedicated column, and this column should be right after validation status, as a metadata field and not a normal question
- [ ] The column should include file icons that are clickable. On hover they will appear full blue (our buttons blue). On click, they will open a modal (this modal could be styled with new UI or the old one, depending on time available) That would allow users to play the audio.
- [ ] When clicking on the single submission icon, the background recording should available to play, and it should not be treated as a regular question. Either as metadata (in the new UI) or simply on top of the questions/answers table (as in the version with few updates)

For additional details and specs, see [the Figma file here](https://www.figma.com/file/cJhbMFYOsQeHBqVJtV8sXA/Background-recording-feature?node-id=0%3A1)

**Comment by Ig-Rebollo** [comment]
See important updates in form builder side of things @duvld (change in message style, longer message, reduction of options in settings, and disclaimer highlighting this feature only works with Collect)

cc @tinok

**Comment by jnm** [comment]
@Ig-Rebollo, @duvld should we close this issue? I'm not sure if there are any tasks remaining in it that aren't captured by other issues.
