### ISSUE TITLE
Add group to library as block functionality

### ISSUE THREAD

**Issue by gushil** [kobotoolbox/kpi#3237]
## Description

Question: Is there a way to add a group (and its content) to library as block. If not, is there any plan to add this / any general idea how to implement this?

**Comment by magicznyleszek** [comment]
Currently there is no way[[1]](https://github.com/kobotoolbox/kpi/issues/1861#issuecomment-847857557) to do this. We have a GH issue opened already for this: #1861. We want to do it, but it's not on our todo list right now.
