### ISSUE TITLE
Remove 'beta' label from score/ranking questions

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#324]
Requested by OCHA

**Comment by jnm** [comment]
@tinok, Leszek is cleaning up some of these tickets. Do you remember what OCHA wanted? UNHCR just mentioned that the `beta` label on matrix questions helped excuse some of their limitations, but it looks like only rating and ranking questions display `beta` :question: 
![image](https://user-images.githubusercontent.com/2085013/47378004-d3ca8880-d6c4-11e8-8562-7c88bda46a7c.png)

**Comment by tinok** [comment]
I vote to remove it. At the time @dorey and I decided to put this on in case the resulting XLSForm/Xform didn't look as expected, but we've had no bugs or other reports related to this as long as I can remember.
