### ISSUE TITLE
Grey scale standardization

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/kpi#3254]
Update greys in kpi to fit the new library, using the HSL system where all greys are:
H: 225
S: 16

And only L changes to create all the shades.

This is part of a larger project to standardize all colours and necessary for the implementation of new styles in the table view. At this point though, only the greys are necessary, plus maybe some additions to the colours to create the new validation status look.

![image](https://user-images.githubusercontent.com/22472326/120554525-d7b7fe80-c3c7-11eb-990e-5cb3b2a15697.png)

You can also find the specs directly in [this Figma file](https://www.figma.com/file/Q04O151tZ2r4ObqL860Nqu/KoboToolbox-Design-System-2.0?node-id=260%3A0)

We will leave standardization of other colours for further down the road, but you can check the future plans on this in the [Notion page](https://www.notion.so/kobotoolbox/Establish-consistent-library-of-colours-and-styles-bd6c2defecf2433fb807eff4e916383d).

**Comment by magicznyleszek** [comment]
Done on `beta`, will be closed as soon as #3246 ends up on `master` :)
