### ISSUE TITLE
Broken skip logic on beta branch

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3279]
## Steps to Reproduce

1. Create new form
2. Add `select_one` question
3. Add `text` question
4. For the `text` question open "Settings" and "Skip Logic"
5. Use "+ ADD A CONDITION" button and select the `select_one` question from the list
6. Observe that after "=" selector there is no choice selector

## Expected behavior 

<img width="1018" alt="Screenshot 2021-06-11 at 19 42 17" src="https://user-images.githubusercontent.com/2521888/121728164-cd42e680-cae4-11eb-87f2-c5956a474268.png">

## Actual behavior 

(Disregard the different button styles and the "X" button)

<img width="754" alt="Screenshot 2021-06-11 at 19 41 37" src="https://user-images.githubusercontent.com/2521888/121728184-d338c780-cae4-11eb-909d-5757739afef2.png">

**Comment by jnm** [comment]
closed by #3281
