### ISSUE TITLE
Block with group can't be imported to form

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#330]
A block that contains a group can't be dragged into a form. The console throws the following error: 

![image](https://cloud.githubusercontent.com/assets/673511/9694957/30c0593c-532b-11e5-868b-4936d70ed154.png)

To recreate: 
1. Create a block with a group (begin group, text, end group)
2. Try to import it into a form

**Comment by pmusaraj** [comment]
Fixed via #1590.
