### ISSUE TITLE
Filename changes to download when downloading media

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3315]
## Description

Filename changes to `download` when downloading media from `SETTINGS>Media`. See the image below:

![image](https://user-images.githubusercontent.com/50188479/123126552-31609580-d469-11eb-80dc-ff7a6da397a2.png)

## Expected behavior 

Would be good to have the same filename that was there under `SETTINGS>Media` and not have the filename `download`.

## Actual behavior 

Filename changes to `download`.

## Additional details

xref: https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Filename.20changes.20to.20download.20when.20downloading.20media

**Comment by jnm** [comment]
@duvld this is what I was vaguely recalling earlier. If you think it's best to fix on the front end, that's fine; otherwise, we can set `content-disposition` on the back end to specify a more meaningful name. Your call :)
