### ISSUE TITLE
Form-builder allows invalid matrix question `Data Column Suffix` value

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#3326]
## Description

The `Data Column Suffix` field in the matrix question settings does not replace spaces with underscores as it does with other question names, therefore leaving it open to user error and incomplete data exports, such as in this case: https://community.kobotoolbox.org/t/missing-data-on-export-yet-its-there-in-the-tool-its-a-group-question/20130

<img width="1041" alt="" src="https://user-images.githubusercontent.com/50016008/124035179-0d450d00-d9b1-11eb-9b8b-a14fe042a1d5.png">

The Enketo preview gives this error:
```
[row : 6] Invalid question name [group_hl59k79_header_a space] Names must begin with a letter, colon, or underscore.Subsequent characters can include numbers, dashes, and periods.
```
Strangely the form opens and one can submit without error. When one tries to export with KPI, the data in the matrix is not included because of this now invalid name (fortunately the legacy export includes the data).

## Steps to Reproduce

1. Create a matrix question
2. Enter a value with spaces in the `Data Column Suffix` field
2. Try previewing the form
3. Submit data
4. Try exporting through KPI 

## Expected behavior 

The spaces are replaced to create a valid field value.

## Actual behavior 

Invalid values are allowed through.

**Comment by jnm** [comment]
Let's make sure we don't close this until we understand why there's a discrepancy between
* what's deployed to KoBoCAT and what KPI serves up when downloading the XLSForm, and
* what's used when exports are attempted

Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/form-builder.20issues/near/41915
