### ISSUE TITLE
Media attachments inaccessible to users with partial view permission

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3371]
Likely requires work here as well as in KoBoCAT (no issue opened there yet)

> Maybe a backend issue but it looks like media attachments are saved via the owner of the submission, i.e., the owner's username is in the media attachment url, not the submitter's.
> 
> This is normally okay for a blanket `view_submissions` but for partial permissions it looks like viewing the attachment is blocked

_Originally posted by @duvld in https://github.com/kobotoolbox/kpi/pull/2900#discussion_r674267110_

**Comment by JacquelineMorrissette** [comment]
I will investigate :)

**Comment by noliveleger** [comment]
They are.
