### ISSUE TITLE
[NLP] Convert audio files to a common format

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3384]
## Description

We need the `audio` file types sent to frontend to be in a single common format supported by browsers (to play audio in KPI) and by automated transcription/translation services.

As for browsers I've found [this SO answer](https://stackoverflow.com/a/42850975/2311247):

> In conclusion you are pretty safe on the video side using H.264 via the MP4 container using MP3/AAC for audio. For just audio MP3 seem to be supported across all browsers.

Information still missing:
- What automated services we plan to use? We need them to know what format they need

**Comment by jnm** [comment]
MP3 might be a good bet for serving a standardized format to browsers. It's probably _not_ the right choice for uploading to transcription engines (Jackie suggests FLAC for that). On the plus side, MP3 no longer requires licensing agreements. For the MVP, we only need a browser-compatible format, which probably should be lossy to improve loading times on slow connections.

1. Transcode on-demand, every time
2. Transcode on-demand, but store result for future requests :star: 
    * Probably the best compromise, and (I think) what KoBoCAT already does for image uploads. [Potential related issue: this might be a good opportunity to figure out how to automatically remove transcoded audio files and scaled images after they have not been accessed for some amount of time.]
3. Some kind of background transcoding operation, possibly at submission time?

Per Jackie: takes about 10-20 seconds to transcode about an hour of content on a single-CPU VM with 4 GB of RAM.
