### ISSUE TITLE
Allow multiple session per user

### ISSUE THREAD

**Issue by jdugh** [kobotoolbox/kpi#3403]
## Description
`question` 
I have my own kpi server instance ; When I log in on kpi on my laptop then I log in on my smartphone, if I refresh my first session on my laptop, I have been log out.

Do you know why ? I may have forgotten a configuration with my cookies ?
Thank you for help

**Comment by jdugh** [comment]
The error comes from my code to connect on my ldap.
Sorry

**Comment by poVoq** [comment]
@jdugh is the LDAP connector you wrote available somewhere?

**Comment by jdugh** [comment]
HI @poVoq , sorry for the delay.

First of all, your env file : 
```
export AUTH_LDAP_1_ACTIVE=True
export AUTH_LDAP_1_SERVER_URI=ldap://127.0.0.1
export AUTH_LDAP_1_ALWAYS_UPDATE_USER=True
export AUTH_LDAP_1_BIND_AS_AUTHENTICATING_USER=False # if your have service account 
export AUTH_LDAP_1_BIND_DN="CN=my_service_account,OU=Service Accounts,[...]"
export AUTH_LDAP_1_BIND_PASSWORD="XXXX" #my_service_account password
export AUTH_LDAP_1_BASE_DN="OU=XXX,DC=XXX,DC=fr"
export AUTH_LDAP_1_SEARCH_FILTER="(|(sAMAccountName=%(user)s) (CN=%(user)s))" # Looking for in sAMAccountName and CN
```

If you have multiple LDAP server, user AUTH_LADP_2[...] ...

In your django settings file, add some : 
```
# ldap import
import ldap
from django_auth_ldap.config import LDAPSearch

#...

# ldap user attributes : 

```
