### ISSUE TITLE
With partial view_submissions the data endpoint doesn't return data

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3408]
## Description

Submissions from specific users are not showing up in the `data` endpoint.

## Steps to Reproduce

1. Create three users: `jan`, `ulrich` and `varg`
2. For user `jan` create a form "Jan's project" with some simple questions
3. Deploy the form
4. Share the project:
   - `ulrich` gets `Add submissions`
   - `varg` gets `View submissions only from specific users (ulrich)`
5. Add few submissions as `jan`
6. Log in as `ulrich` and add few submissions
7. Log in as `varg` and open the project
8. Observe the `DATA` tab is disabled :bug: (ultimately caused by the next point)
9. Manually go to `#/forms/<uid>/data/table`, and in `Network` calls you can see that `/api/v2/assets/<uid>/data/` call is returning `0` responses - it should return the number of responses `ulrich` have added :bug:

## Additional details

As observed on `beta` with local dev environment.

**Comment by jnm** [comment]
"Require authentication to see forms and submit data" strikes again. We will improve the UX for this ASAP. See #2620.

I'll also find the link for the "real" fix for this, which is moving "Require authentication…" from an account-level setting to a per-project setting.

**Comment by jnm** [comment]
UX improvement is #3409
