### ISSUE TITLE
Double leading slash in call to `ENKETO_PREVIEW_ENDPOINT`

### ISSUE THREAD

**Issue by Yann-J** [kobotoolbox/kpi#3413]
## Description

In [settings/base.py](https://github.com/kobotoolbox/kpi/blob/master/kobo/settings/base.py#L385), `ENKETO_SERVER` is getting a trailing slash.

However in [asset_snapshot.py](https://github.com/kobotoolbox/kpi/blob/master/kpi/views/v2/asset_snapshot.py#L104) a call is made to `ENKETO_SERVER/ENKETO_PREVIEW_ENDPOINT`, therefore with a double slash between host and path.

This causes preview calls to fail in my setup whenever trying to preview a form

![image](https://user-images.githubusercontent.com/59641363/129418117-8ce2298f-c73c-4fb8-9090-33dcefc942c1.png)

This double slash is clearly the root cause as the same calls works without it:

```
$ curl -XPOST  "https://ee.qa.oneacrefund.org/api/v2/survey/preview/iframe?server_url=https://kc.qa.oneacrefund.org&form_id=ahqY8bFfyNAvMzKedif3DL" -u "xxxx:" -H "Content-Type: application/x-www-form-urlencoded"
{
    "preview_iframe_url": "https://ee.qa.oneacrefund.org/preview/i/S89aP54j",
    "preview_url": "https://ee.qa.oneacrefund.org/preview/i/S89aP54j",
    "code": 201
}

$ curl -XPOST  "https://ee.qa.oneacrefund.org//api/v2/survey/preview/iframe?server_url=https://kc.qa.oneacrefund.org&form_id=ahqY8bFfyNAvMzKedif3DL" -u "xxxx:" -H "Content-Type: application/x-www-form-urlencoded"
<!DOCTYPE html><html lang="en" dir="ltr"><head><title>Enketo Express for KoBo Toolbox</title><meta charset="utf-8"><meta name="author" content="Martijn van de Rijdt (Enketo LLC)"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="shortcut icon" href="/images/favicon.ico"><link rel="icon" type="image/png" sizes="180x180" href="/images/icon_180x180.png"><link rel="apple-touch-icon" sizes="180x180" href="/images/icon_180x180.png"><link rel="stylesheet" href="/css/error.css"></head><body><h1 class="error">Page not Found<span class="status-code">Error Code: 404</span></h1></body></html>%
```

Strangely, this was fixed 5 years ago for calls to `ENKETO_SURVEY_ENDPOINT` in #1232, but not for `ENKETO_PREVIEW_ENDPOINT`

What I can't explain is why my setup used to work until my recent upgrade...

**Comment by noliveleger** [comment]
Thank you @Yann-J for reporting this.
It's weird because we haven't seen this yet too. 
To which version have you upgraded recently? Latest `master` or something else?

**Comment by Yann-J** [comment]
We just upgraded our docker images from `2.021.12b` to `2.021.24b` (i.e. from [this](https://github.com/kobotoolbox/kpi/commit/27cff694f9a63fd091ba8b803ac925f77b8f513b) to [that](https://github.com/kobotoolbox/kpi/commit/480100f7a1626affff60835d8d4a9746907b62e1)).

There are a few other differences in our setup, which maybe explain why I didn't see this before - e.g. now Enketo is served directly by our load-balancer and not by the Kobo nginx... I'm not certain...

**Comment by jnm** [comment]
> There are a few other differences in our setup, which maybe explain why I didn't see this before - e.g. now Enketo is served directly by our load-balancer and not by the Kobo nginx... I'm not certain...

I think that's probably the determining factor, because extraneous slashes don't affect our typical setup:
```
$ curl --user "$api_key": 'http://ee.kobo.local:9000///////////////////////////api/v2/survey/preview?server_url=http://kc.kobo.local:9000/aa&form_id=aQNrgKDyDHkeqeDVptj4WK'; echo
{
    "preview_url": "http://ee.kobo.local:9000/preview/l8lD9gIB",
    "code": 200
}
$ curl --user "$api_key": 'http://ee.kobo.local:9000//api/v2/survey/preview?server_url=http://kc.kobo.local:9000/aa&form_id=aQNrgKDyDHkeqeDVptj4WK'; echo
{
    "preview_url": "http://ee.kobo.local:9000/preview/l8lD9gIB",
    "code": 200
}
$ curl --user "$api_key": 'http://ee.kobo.local:9000/api/v2/survey/preview?server_url=http://kc.kobo.local:9000/aa&form_id=aQNrgKDyDHkeqeDVptj4WK'; echo
{
    "preview_url": "http://ee.kobo.local:9000/preview/l8lD9gIB",
    "code": 200
}
```

That said, we should certainly fix this, and thanks for your PR.

**Comment by noliveleger** [comment]
@jnm Just a comment about this. 
What about removing the trailing slash of `ENKETO_SERVER` at the first place and use endpoints with leading slashes, to be consistent with `KOBOCAT_URL` and `KOBOFORM_URL` ?

**Comment by Yann-J** [comment]
I do have to say... I find this proposal (no trailing slash on host + leading slash on endpoint paths) cleaner and more in line with standards... but since the other direction was already taken for `ENKETO_SURVEY_ENDPOINT` I thought I'd just follow...

**Comment by noliveleger** [comment]
@Yann-J -> kpi#3430
