### ISSUE TITLE
How to overcome   SSRF protection  exception issue?

### ISSUE THREAD

**Issue by bawantha** [kobotoolbox/kpi#3460]
I'm getting this error while I'm using local kobo . I have used kobo-install to get kobotoolbox can you tell me how to mitigate  this  `SSRFProtectException`

> ssrf_protect.exceptions.SSRFProtectException: URL http://xxx.xxx.xxx.xxx:8080/hello is not allowed because it resolves to a private IP address

**Comment by jnm** [comment]
You can add SSRF protection exemptions via the Django admin interface, i.e. https://your-kpi-host/admin. This capability was added in https://github.com/kobotoolbox/kpi/pull/2713. If you cannot understand how to proceed, please post your question at https://community.kobotoolbox.org/. Thank you.
