### ISSUE TITLE
Could someone explain to me how I can edit a record from python? (apprentice level)

### ISSUE THREAD

**Issue by gabroliveros** [kobotoolbox/kpi#3461]
I don't have much programming experience and it is quite difficult for me to understand this API. I wish someone could write some code in python 3.9 to know how to edit or change the value of a record. Thanks in advance.

**Comment by jnm** [comment]
Thanks for your interest, but this isn't quite the right venue for your question. This is an issue tracker used by the core team to keep track of important work needed to maintain the KoBoToolbox software. Consider posting at https://community.kobotoolbox.org/ instead :slightly_smiling_face:
