### ISSUE TITLE
Fix short multi word search phrase problem

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3483]
## Description

There is a bug with the search feature: if I search for a combination of words (e.g. `opt in form`) that starts with a short one, the server responds with "Your query is too short".

The response from `/api/v2/assets/?q=(opt in form) AND (asset_type=survey)&limit=200` endpoint:

```json
{"detail":"Your query is too short"}
```

**Comment by jnm** [comment]
> We should change the query to be ("opt in form").

Not sure about that :thinking: Possibly the back end should accept this as `opt AND in AND form`? We should test performance
