### ISSUE TITLE
Updates to the Table View to fit more data in a normal screen

### ISSUE THREAD

**Issue by ignatiusgr** [kobotoolbox/kpi#3491]
The size of rows, columns, cells and fonts in the table view seems to be excessive for some users, as they don't see many entries/responses compared to the previous table or even to similar tools (Airtable, Excel...)

**Updates and fixes:**

- [x] Reduce font size to 13px, as it was before
- [x] Reduce height of rows from the current 42px to 36px (I believe this will still provide enough space to breathe as long as the font size is reduced to 13px)
- [x] Use three letter abbreviations for months in dates (`September` becomes `Sep`)
- [x] Reduce default width of `Start` and `End` to 120px
- [x] Change 'Validation Status' to simply 'Validation' since the full name doesn't fit in the default space anyways.
- [x] If possible without cutting the 'not approved' label, also reduce the Validation column to 120px, ideally reducing margins. If the label gets cut by doing this, give it the min width needed for the label to fit.
- [x] Reduce the default column width from 160px to 140px
- [x] Align all column headings to the left (for some reason 'Start' and 'End' and centred in their respective columns)
- [x] Stop using monospaced font in table

cc @tinok

**Comment by magicznyleszek** [comment]
It's done on `beta`
