### ISSUE TITLE
[NLP] Gather a list of transcription providers with their available languages list

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3511]
## Description

We need a list of the transcription providers (urls, names, logos?) and their provided languages (codes and labels?).

### Providers

Amazon, IBM, Google, Microsoft, and TWB. (see [here](https://chat.kobotoolbox.org/#narrow/stream/7-UX.2FUI/topic/NLP.20feature.20UI.20.26.20UX.20review/near/67243))

**Comment by magicznyleszek** [comment]
Amazon is here: https://docs.aws.amazon.com/transcribe/latest/dg/supported-languages.html

**Comment by JacquelineMorrissette** [comment]
I don't think we need to worry about having the languages pairs, any language can be translated to any language in the list with the exceptions of Basque and Catalan for IBM

| Google ASR          | Google MT            | Amazon ASR | Amazon MT | IBM ASR | IBM MT | Microsoft ASR | Microsoft MT |
|---------------------|----------------------|------------|-----------|---------|--------|---------------|--------------|
| af-ZA               | af                   | af-ZA      | af        | ar      | ar     | ar-DZ         | af           |
| am-ET               | am                   | ar-AE      | sq        | zh      | eu     | ar-BH         | sq           |
| ar-AE               | ar                   | ar-SA      | am        | cs      | bn     | ar-EG         | am           |
| ar-BH               | az                   | zh-CN      | ar        | nl      | bs     | ar-IQ         | ar           |
| ar-DZ               | be                   | zh-TW      | hy        | en-US   | bg     | ar-IL         | hy           |
| ar-EG               | bg                   | da-DK      | az        | fr-CA   | ca     | ar-JO         | as           |
| ar-IL               | bn                   | nl-NL      | bn        | de      | zh     | ar-KW         | az           |
| ar-IQ               | bs                   | en-AU      | bs        | it      | zh-TW  | ar-LB         | bn           |
| ar-JO               | ca                   | en-GB      | bg        | ja      | hr     | ar-LY         | ba           |
| ar-KW               | ceb (ISO-639-2)      | en-IN      | ca        | ko      | cs     | ar-MA         | bs           |
| ar-LB               | co                   | en-IE      | zh        | pt-BR   | da     | ar-OM         | bg           |
| ar-MA               | cs                   | en-NZ      | zh-TW     | es      | nl     | ar-QA         | yue          |
| ar-OM               | cy                   | en-AB      | hr        | sv      | en     | ar-SA         | ca           |
| ar-PS               | da                   | en-ZA      | cs        | nl-BE   | et     | ar-PS         | lzh          |
| ar-QA               | de                   | en-US      | da        | en-AU   | fi     | ar-SY         | zh-Hans      |
| ar-SA               | el                   | en-WL      | fa-AF     | en-GB   | fr     | ar-TN         | zh-Hant      |
| ar-TN               | en                   | fr-FR      | nl        | fr-FR   | fr-CA  | ar-AE         | hr           |
| ar-YE               | eo                   | fr-CA      | en        |         | de     | ar-YE         | cs           |
| az-AZ               | es                   | fa-IR      | et        |         | el     | bg-BG         | da           |
| bg-BG               | et                   | de-DE      | fa        |         | gu     | ca-ES         | prs          |
| bn-BD               | eu                   | de-CH      | tl        |         | he     | zh-HK         | dv           |
| bn-IN               | fa                   | he-IL      | fi        |         | hi     | zh-CN         | nl           |
| bs-BA               | fi                   | hi-IN      | fr        |         | hu     | zh-TW         | en           |
| ca-ES               | fr                   | id-ID      | fr-CA     |         | ga     | hr-HR         | et           |
| cs-CZ               | fy                   | it-IT      | ka        |         | id     | cs-CZ         | fj           |
| da-DK               | ga                   | ja-JP      | de        |         | it     | da-DK         | fil          |
| de-AT               | gd                   | ko-KR      | el        |         | ja     | nl-NL         | fi           |
| de-CH               | gl                   | ms-MY      | gu        |         | ko     | en-AU         | fr           |
| de-DE               | gu                   | pt-PT      | ht        |         | lv     | en-CA         | fr-ca        |
| el-GR               | ha                   | pt-BR      | ha        |         | li     | en-GH         | ka           |
| en-AU               | haw (ISO-639-2)      | ru-RU      | he        |         | ms     | en-HK         | de           |
| en-CA               | he or iw             | es-ES      | hi        |         | ml     | en-IN         | el           |
| en-GB               | hi                   | es-US      | hu        |         | mt     | en-IE         | gu           |
| en-GH               | hmn (ISO-639-2)      | ta-IN      | is        |         | ne     | en-KE         | ht           |
| en-HK               | hr                   | te-IN      | id        |         | cnr    | en-NZ         | he           |
| en-IE               | ht                   | th-TH      | it        |         | nb     | en-NG         | hi           |
| en-IN               | hu                   | tr-TR      | ja        |         | pl     | en-PH         | mww          |
| en-KE               | hy                   |            | kn        |         | pt     | en-SG         | hu           |
| en-NG               | id                   |            | kk        |         | ro     | en-ZA         | is           |
| en-NZ               | ig                   |            | ko        |         | ru     | en-TZ         | id           |
| en-PH               | is                   |            | lv        |         | sr     | en-GB         | iu           |
| en-PK               | it                   |            | lt        |         | si     | en-US         | ga           |
| en-SG               | ja                   |            | mk        |         | sk     | et-EE         | it           |
| en-TZ               | jv                   |            | ms        |         | sl     | fil-PH        | ja           |
| en-US               | ka                   |            | ml        |         | es     | fi-FI         | kn           |
| en-ZA               | kk                   |            | mt        |         | sv     | fr-CA         | kk           |
| es-AR               | km                   |            | mn        |         | ta     | fr-FR         | km           |
| es-BO               | kn                   |            | no        |         | te     | fr-CH         | tlh-Latn     |
| es-CL               | ko                   |            | ps        |         | th     | de-AT         | tlh-Piqd     |
| es-CO               | ku                   |            | pl        |         | tr     | de-CH         | ko           |
| es-CR               | ky                   |            | pt        |         | uk     | de-DE         | ku           |
| es-DO               | lb                   |            | ro        |         | ur     | el-GR         | kmr          |
| es-EC               | lo                   |            | ru        |         | vi     | gu-IN         | ky           |
| es-ES               | lt                   |            | sr        |         | cy     | he-IL         | lo           |
| es-GT               | lv                   |            | si        |         |        | hi-IN         | lv           |
| es-HN               | mg                   |            | sk        |         |        | hu-HU         | lt           |
| es-MX               | mi                   |            | sl        |         |        | id-ID         | mk           |
| es-NI               | mk                   |            | so        |         |        | ga-IE         | mg           |
| es-PA               | ml                   |            | es        |         |        | it-IT         | ms           |
| es-PE               | mn                   |            | es-MX     |         |        | ja-JP         | ml           |
| es-PR               | mr                   |            | sw        |         |        | kn-IN         | mt           |
| es-PY               | ms                   |            | sv        |         |        | ko-KR         | mi           |
| es-SV               | mt                   |            | ta        |         |        | lv-LV         | mr           |
| es-US               | my                   |            | te        |         |        | lt-LT         | mn-Cyrl      |
| es-UY               | ne                   |            | th        |         |        | ms-MY         | mn-Mong      |
| es-VE               | nl                   |            | tr        |         |        | mt-MT         | my           |
| et-EE               | no                   |            | uk        |         |        | mr-IN         | ne           |
| eu-ES               | ny                   |            | ur        |         |        | nb-NO         | nb           |
| fa-IR               | or                   |            | uz        |         |        | fa-IR         | or           |
| fi-FI               | pa                   |            | vi        |         |        | pl-PL         | ps           |
| fil-PH              | pl                   |            | cy        |         |        | pt-BR         | fa           |
| fr-BE               | ps                   |            |           |         |        | pt-PT         | pl           |
| fr-CA               | pt                   |            |           |         |        | ro-RO         | pt           |
| fr-CH               | ro                   |            |           |         |        | ru-RU         | pt-pt        |
| fr-FR               | ru                   |            |           |         |        | sk-SK         | pa           |
| gl-ES               | rw                   |            |           |         |        | sl-SI         | otq          |
| gu-IN               | sd                   |            |           |         |        | es-AR         | ro           |
| hi-IN               | si                   |            |           |         |        | es-BO         | ru           |
| hr-HR               | sk                   |            |           |         |        | es-CL         | sm           |
| hu-HU               | sl                   |            |           |         |        | es-CO         | sr-Cyrl      |
| hy-AM               | sm                   |            |           |         |        | es-CR         | sr-Latn      |
| id-ID               | sn                   |            |           |         |        | es-CU         | sk           |
| is-IS               | so                   |            |           |         |        | es-DO         | sl           |
| it-CH               | sq                   |            |           |         |        | es-EC         | es           |
| it-IT               | sr                   |            |           |         |        | es-SV         | sw           |
| iw-IL               | st                   |            |           |         |        | es-GQ         | sv           |
| ja-JP               | su                   |            |           |         |        | es-GT         | ty           |
| jv-ID               | sv                   |            |           |         |        | es-HN         | ta           |
| ka-GE               | sw                   |            |           |         |        | es-MX         | tt           |
| kk-KZ               | ta                   |            |           |         |        | es-NI         | te           |
| km-KH               | te                   |            |           |         |        | es-PA         | th           |
| kn-IN               | tg                   |            |           |         |        | es-PY         | bo           |
| ko-KR               | th                   |            |           |         |        | es-PE         | ti           |
| lo-LA               | tk                   |            |           |         |        | es-PR         | to           |
| lt-LT               | tl                   |            |           |         |        | es-ES         | tr           |
| lv-LV               | tr                   |            |           |         |        | es-UY         | tk           |
| mk-MK               | tt                   |            |           |         |        | es-US         | uk           |
| ml-IN               | ug                   |            |           |         |        | es-VE         | ur           |
| mn-MN               | uk                   |            |           |         |        | sw-KE         | ug           |
| mr-IN               | ur                   |            |           |         |        | sv-SE         | uz           |
| ms-MY               | uz                   |            |           |         |        | ta-IN         | vi           |
| my-MM               | vi                   |            |           |         |        | te-IN         | cy           |
| ne-NP               | xh                   |            |           |         |        | th-TH         | yua          |
| nl-BE               | yi                   |            |           |         |        | tr-TR         |              |
| nl-NL               | yo                   |            |           |         |        | vi-VN         |              |
| no-NO               | zh-CN or zh (BCP-47) |            |           |         |        |               |              |
| pa-Guru-IN          | zh-TW (BCP-47)       |            |           |         |        |               |              |
| pl-PL               | zu                   |            |           |         |        |               |              |
| pt-BR               |                      |            |           |         |        |               |              |
| pt-PT               |                      |            |           |         |        |               |              |
| ro-RO               |                      |            |           |         |        |               |              |
| ru-RU               |                      |            |           |         |        |               |              |
| si-LK               |                      |            |           |         |        |               |              |
| sk-SK               |                      |            |           |         |        |               |              |
| sl-SI               |                      |            |           |         |        |               |              |
| sq-AL               |                      |            |           |         |        |               |              |
| sr-RS               |                      |            |           |         |        |               |              |
| su-ID               |                      |            |           |         |        |               |              |
| sv-SE               |                      |            |           |         |        |               |              |
| sw-KE               |                      |            |           |         |        |               |              |
| sw-TZ               |                      |            |           |         |        |               |              |
| ta-IN               |                      |            |           |         |        |               |              |
| ta-LK               |                      |            |           |         |        |               |              |
| ta-MY               |                      |            |           |         |        |               |              |
| ta-SG               |                      |            |           |         |        |               |              |
| te-IN               |                      |            |           |         |        |               |              |
| th-TH               |                      |            |           |         |        |               |              |
| tr-TR               |                      |            |           |         |        |               |              |
| uk-UA               |                      |            |           |         |        |               |              |
| ur-IN               |                      |            |           |         |        |               |              |
| ur-PK               |                      |            |           |         |        |               |              |
| uz-UZ               |                      |            |           |         |        |               |              |
| vi-VN               |                      |            |           |         |        |               |              |
| yue-Hant-HK         |                      |            |           |         |        |               |              |
| zh (cmn-Hans-CN)    |                      |            |           |         |        |               |              |
| zh-TW (cmn-Hant-TW) |                      |            |           |         |        |               |              |
| zu-ZA               |                      |            |           |         |        |               |              |
