### ISSUE TITLE
2FA Designs

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/kpi#3552]
Uploading here the mockups and designs for the 2FA functionality in KPI. 

For any additional specs, here is also the [Figma working file](https://www.figma.com/file/wSLzU28E4dThJJIkEu1iFj/New-Login-and-2FA?node-id=0%3A1)

When logging in
![MacBook Pro - 25](https://user-images.githubusercontent.com/22472326/141514301-b56cd932-8964-462f-83a1-c2b36c925f5c.jpg)
![MacBook Pro - 26](https://user-images.githubusercontent.com/22472326/141514321-494f35fc-1ac3-4a3e-a5e1-ed111de84995.jpg)

If 2FA is already enabled
![MacBook Pro - 28](https://user-images.githubusercontent.com/22472326/141514437-03a90371-70b8-4dcd-8b6e-d9abf2ddd67e.jpg)

In account settings, included a new side menu, specific for account settings. For now, we can put most of the info there as is, and worry about it later on. Mockup below just to get an idea of how it could look like in the future
![MacBook Pro - 18](https://user-images.githubusercontent.com/22472326/141514648-51083313-a094-428c-a2f3-6e8f61e45c47.jpg)

When clicking on security, I can see my password, API token, etc.
![MacBook Pro - 19](https://user-images.githubusercontent.com/22472326/141514727-2c4e7717-388c-4032-ab88-30b7051a2246.jpg)

If I enable 2FA (in case it wasn't done on login), it pops up the modal with the QRcode and so on
![MacBook Pro - 22](https://user-images.githubusercontent.com/22472326/143046925-78fd679a-6467-48cd-b2e8-02a54a45355b.jpg)
![MacBook Pro - 23](https://user-images.githubusercontent.com/22472326/143047519-d9a6cc2e-10fe-4b50-a41b-af662678966b.jpg)

If I click on 'enter key manually':
![MacBook Pro - 29](https://user-images.githubusercontent.com/22472326/143047202-0cb7d680-7b3c-4f11-a7a4-78d34ed3f7b2.jpg)

Finally it would remain visible in the 2FA section
![MacBook Pro - 21](https://user-images.githubusercontent.com/22472326/143047655-dae3f92a-9a11-4906-9cf6-eec2d8fc7170.jpg)

**Comment by noliveleger** [comment]
@Ig-Rebollo, FYI: we don't want to save `recovery codes`. We will regenerate new ones instead. 
The design lets me think what we keep them.

**Comment by Ig-Rebollo** [comment]
@noliveleger I see. Would the mockups work if instead of 'show' the button in the last screen said 'generate new ones' or something similar?

**Comment by noliveleger** [comment]
@Ig-Rebollo IMHO, It would.

**Comment by Ig-Rebollo** [comment]
Updated the mockups in the description @noliveleger @dorey with the changes you mentioned. Let me know if this works!

**Comment by noliveleger** [comment]
@Ig-Rebollo , IMO, I would put the secret key on the same screen as the QR code. If your app is capable of scanning the QR code, there is no needs to see the extra step for the secret key, isn't it?

**Comment by jnm** [comment]
There are some new mock ups that aren't included in the original description. I don't have access to the Figma file, so I'm pasting them here from Zulip (https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/MFA/near/84373).

![image](https://user-images.githubusercontent.com/2085013/153978113-d2cd1e8f-7f79-4451-a57b-21ed0e774840.png)

![image](https://user-images.githubusercontent.com/2085013/153978119-4ded2d4f-b9e8-4418-9a50-1c5ccfb41dac.png)

![image](https://user-images.githubusercontent.com/2085013/153978130-b1a2d3d7-cefe-4d9b-8ae8-e15ec3b06f86.png)
