### ISSUE TITLE
Report View truncates long names unnecessarily

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3564]
## Description

When form has `select_multiple` question with long option names, we truncate the text options (22 characters) for the graph canvas rendering (an ok thing), but the truncation also happens in the table (the :bug:).

<img width="771" alt="Screenshot 2021-11-22 at 17 04 22" src="https://user-images.githubusercontent.com/2521888/142904319-eff8634e-1348-4de4-a1a8-69d86a801505.png">

## Expected outcome

We want to truncate the labels in the graph. The labels in the table should definitely not be truncated.

## Additional details

A test form file: [Long names select multiple.xlsx](https://github.com/kobotoolbox/kpi/files/7582979/Long.names.select.multiple.xlsx)

**Comment by Kalyan-Lama** [comment]
Community: https://community.kobotoolbox.org/t/report-view-truncates-long-names-unnecessarily/24746
