### ISSUE TITLE
uWSGI hangs sometimes

### ISSUE THREAD

**Issue by j-manu** [kobotoolbox/kpi#3566]
## Description

uWSGI worker hangs sometimes after respawning. See WID 4 below with RSS 0 and VSZ 0. 

![image](https://user-images.githubusercontent.com/72501/142876765-5d28d6de-c4cd-4404-8a14-b063ddf56af1.png)
## Steps to Reproduce

Unfortunately, couldn't replicate reliably by load testing. 

## Additional details

Self hosted KPI version 2.021.45b 
Sentry not enabled

This seems similar to https://github.com/kobotoolbox/kobocat/issues/377 & https://github.com/DataDog/dd-trace-py/issues/491

Why not set `lazy-apps = true` in uwsgi.ini ?

**Comment by noliveleger** [comment]
Hello @j-manu, 
We were able to reproduce the problem with low settings and lots of requests. 
According to our tests, it does seem to fix the problem with `lazy-apps = true`. Unfortunately, it also increases the resources footprint. Especially, when you have a lots of workers.
We'll continue to investigate.

**Comment by j-manu** [comment]
@noliveleger What do you mean by "low settings"?
