### ISSUE TITLE
[NLP] Updated header for Single Processing View

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/kpi#3570]
After the user testing sessions, we collected a fair amount of feedback related to the header, which led us to update it entirely. 

This new design for the header should be included in the MVP, as much as possible. 

New designs can be found in [this Figma file](https://www.figma.com/file/ssmaK5p4FYSZUq7O7T1RhY/KoBo-Qualitative-Processing-Prototype?node-id=322%3A9453)

### Changes
- [x] Total height of the header is reduced to 60px
- [x] Question becomes a dropdown, which allows you to select other relevant questions (only questions with some type of media that can be processed - maybe for MVP only audios)
- [x] In this dropdown, each question has an icon to its left. This icon shows the type of media (audio, image, video, etc.). These icons should be visible when opening the dropdown, so it's easier to identify the question you're looking for.
- [x] Submission number is the same functionality but styled differently, to have a similar presence as the question.
- [x] Done button is smaller, uses lowercase, and a 1px border (not 2px)

![image](https://user-images.githubusercontent.com/22472326/143289655-d15e52fd-8970-48e1-a844-4c9fd68c4d92.png)

**Comment by magicznyleszek** [comment]
This was done :)
