### ISSUE TITLE
Data Table issues with repeating groups

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#3594]
## Description

Repeating groups can show in the table view as `[object Object]...`

## Steps to Reproduce

Have a form with a repeat group, then change the repeat to a normal group (same name):

**Version 1:**
| type | name | label |
| --- | --- | --- |
| begin_repeat | person | Person |
| text | name | What is your name? |
| integer | age | What is your age? |
| end_repeat |

**Version 2:**
| type | name | label |
| --- | --- | --- |
| begin_group | person | Person |
| text | name | What is your name? |
| integer | age | What is your age? |
| end_group |

```diff
--- v1.md
+++ v2.md
@@ -1,6 +1,6 @@
 | type         | name   | label              |
 | ---          | ---    | ---                |
-| begin_repeat | person | Person             |
+| begin_group  | person | Person             |
 | text         | name   | What is your name? |
 | integer      | age    | What is your age?  |
-| end_repeat   |        |                    |
+| end_group    |        |                    |
```

<img width="983" alt="object1" src="https://user-images.githubusercontent.com/50016008/145873931-8b3de6cf-d4f8-4389-8df5-65fe45c1ea37.png">

Or remove the grouping completely:
```diff
--- v1.md
+++ v3.md
@@ -1,6 +1,6 @@
 | type         | name   | label              |
 | ---          | ---    | ---                |
-| begin_repeat | person | Person             |
 | text         | name   | What is your name? |
 | integer      | age    | What is your age?  |
-| end_repeat   |        |                    |
```
<img width="989" alt="object2" src="https://user-images.githubusercontent.com/50016008/145873961-329f6b01-f11c-47c3-9098-0d8b10e16a92.png">

**Comment by Kalyan-Lama** [comment]
Community reference: https://community.kobotoolbox.org/t/data-missing-after-massive-update/25079
