### ISSUE TITLE
Delete user from the KPI Admin

### ISSUE THREAD

**Issue by jdugh** [kobotoolbox/kpi#3609]
## Description

Since 2.021.45 release, I cannot remove a user from the KPI Admin - or change username.
In the 2.021.21, seem work.

## Steps to Reproduce

1. Create a new user via KPI Admin
2. Remove this user via KPI Admin

## Expected behavior 

User delete both KPI and Kobocat

## Actual behavior 

I feel the Admin panel cannot route correctly between kpi and Kobocat DB.
I have this error 
```
Internal Server Error: /admin/auth/user/10/delete/
Traceback (most recent call last):
  File "/srv/kobo/venvkpi/lib/python3.8/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: ERREUR:  la relation « logger_instance » n'existe pas
LINE 1: ...user"."is_active", "auth_user"."date_joined" FROM "logger_in...
```
Where `logger_instance` is a table from Kobocat.

If I try to change the username : 
```
File "./kpi/deployment_backends/kc_access/shadow_models.py", line 331, in sync
    assert kc_auth_user.username == auth_user.username
```

This is an error on my configuration or do you have the same error ?

**Comment by JacquelineMorrissette** [comment]
This is resolved with #4373
