### ISSUE TITLE
Fix bulk edit throwing `TypeError`

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#3647]
## Description

`xml.etree.ElementTree` is being used to parse the submission XML but `lxml.etree` is being used to modify, causing:

```
...
  File "/srv/src/kpi/kpi/views/v2/data.py", line 333, in bulk
    json_response = action_(bulk_actions_validator.data, request.user)
  File "/srv/src/kpi/kpi/deployment_backends/kobocat_backend.py", line 173, in bulk_update_submissions
    edit_submission_xml(xml_parsed, path, value)
  File "/srv/src/kpi/kpi/utils/xml.py", line 184, in edit_submission_xml
    element = etree.SubElement(parent, node)
TypeError: Argument '_parent' has incorrect type (expected lxml.etree._Element, got xml.etree.ElementTree.Element)
```

## Steps to Reproduce

1. Create form, v1, with question, q1
2. Submit submission, s1
3. Create, v2, with an additional question, q2
4. Edit s1 with bulk edit feature to add value to q2

## Expected behavior 

New value is applied to q2.

## Actual behavior 

```
TypeError: Argument '_parent' has incorrect type (expected lxml.etree._Element, got xml.etree.ElementTree.Element)
```

**Comment by kryptt** [comment]
This is exactly the issue we've run into as we were exploring different versions of KPI to be able to run this exact use case!!! ...
