### ISSUE TITLE
500 error shows "Access denied" message

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3653]
:monocle_face: Not quite:
![image](https://user-images.githubusercontent.com/2085013/152063556-355a7cb3-0a74-4880-a3b0-a4187c0ff578.png)
**[end of screenshot]**

My preferences below—@Ig-Rebollo, what do you think?
1. Show the above message *only* for 404 errors.
2. For a 403, show the above message *without* the "Either…or this page simply doesn't exist" language. It exists and the client simply does not have access.
3. For a 401, redirect to the login page, or, if that's problematic, show the same message as (2).
4. For any 5xx, display some variation on "please try again, and contact support if you keep seeing this message." The header should be some kind of apology or "something went wrong", but definitely not "access denied".

Handy reference: https://httpstatusdogs.com/

See also #3318

Canonical discussion now at https://www.notion.so/kobotoolbox/Create-better-error-pages-9ae143db568c4b8ba6766d0750bd0faa

**Comment by LMNTL** [comment]
Fixed by [kpi#4693](https://github.com/kobotoolbox/kpi/pull/4693).
