### ISSUE TITLE
Issues in deleting a matrix row

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3697]
## Description

After creating a matrix question, it seems that a user is not able to delete a row using the `Trash can` icon. 

## Steps to Reproduce

1. Create a matrix question.

![image](https://user-images.githubusercontent.com/50188479/155478917-8e52a972-097e-4800-bc2f-7e595bac6e3a.png)

There is an issue when deleting a matrix row. I have boxed that in red. While there is no issue when deleting a matrix column. I have boxed that in green.

2. Now say I wish to delete `Truck` from the matrix row. I then select the setting that is next to `Truck`:

![image](https://user-images.githubusercontent.com/50188479/155479089-e811293a-3920-4225-8cf1-126f70af08d1.png)

Here you will see 2 places (maybe even one) that should allow you to delete the row. The `Delete row` and the `Trash can`. When selecting either of them, you should see this dialogue box. Which is fine till here:

![image](https://user-images.githubusercontent.com/50188479/155479244-3dea91bf-fa3e-4b27-bdc9-d65e51ac5b8b.png)

3. When selecting the `Delete row`, you are able to delete it after you press the `DELETE` that you see in the dialogue box. However, when you select the `Trash can`, you should see the dialogue box, but once again, when you press the `DELETE` that you see in the dialogue box, nothing happens. Instead, it will simply return this page:

![image](https://user-images.githubusercontent.com/50188479/155479376-82ec9d32-3a71-4257-b3bb-12b94539039a.png)

## Expected behavior 

Users should be able to delete the content by pressing either `Delete row` or the `Trash can`.

## Actual behavior 

A user is able to delete the content by pressing the `Delete row` but not by pressing the `Trash can`.

## Additional details

Zulip: https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Issues.20with.20deleting.20a.20matrix.20row

**Comment by magicznyleszek** [comment]
This is fixed on `beta` branch, will be released in one of upcoming releases :)
