### ISSUE TITLE
Filename not taken from the XLSForm when uploading an XLSForm

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3703]
## Description

This is an issue seen when testing for 2.022.08 release (in the master server).

When uploading an XLSForm the file does not automatically take the name as it should usually do from the XLSForm. Instead, it prompts a dialogue box requesting a user to fill up the `Project Name (required)`, `Description` and `Sector` like it does while creating a new project (as shown in the image below).

![image](https://user-images.githubusercontent.com/50188479/155684347-ced52990-d040-4d33-82e0-8a66c3796ea6.png)

This dialogue box is seen in both cases i.e. when you have/ have not specified `form_title` under the settings sheet of the XLSForm.

## Steps to Reproduce

1. Upload an XLSForm.
2. You will be prompted with this dialogue box:

![image](https://user-images.githubusercontent.com/50188479/155684347-ced52990-d040-4d33-82e0-8a66c3796ea6.png)

## Expected behavior 

The system should be able to take the name of the XLSForm automatically (if no name has been provided in the `form_title` of settings tab of the XLSForm or should be able to take the name from the `form_title` defined under the settings tab of the XLSForm.

## Actual behavior 

When uploading an XLSForm the file does not automatically take the name as it should usually do from the XLSForm.

**Comment by jnm** [comment]
I see that `name` is returned by the back end according to `form_title` or the XLSForm file name. In fact, if you click the X to close this screen:
![image](https://user-images.githubusercontent.com/2085013/157543285-608b63d5-5ccd-458a-8794-8f97a68ac293.png)
…you will end up with a new project in your drafts that has the correct name :thinking:
