### ISSUE TITLE
Error message "Your query is too short" shows up!

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3712]
## Description

When you make a search in the library/public collection, you will see an error message `Your query is too short`. Please see the image below:

![image](https://user-images.githubusercontent.com/50188479/156553148-4d742d76-fdbe-45cc-a549-eee852a92f9d.png)

## Additional details

This is from the test made in the masters' server for `2.022.08 Release`.

**Comment by joshuaberetta** [comment]
@Kalyan-Lama this is by design 🙂 

https://github.com/kobotoolbox/kpi/blob/f6800fcb544aeb009fdd9a9f91449495691bf2f3/kpi/utils/query_parser/query_parser.py#L134-L139
