### ISSUE TITLE
Unable to delete a project in Master Server

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3790]
## Description

When you are here and try to delete a project by selecting `DELETE PROJECT AND DATA`...

![Image 1](https://user-images.githubusercontent.com/50188479/166428156-46f07344-3b73-48ca-acd3-1adb782f2c24.png)

The project would not delete. Instead, you would see the following error message ...

![Image 2](https://user-images.githubusercontent.com/50188479/166428318-c9227f12-9dda-4886-a626-6f088edb5878.png)

**Comment by jnm** [comment]
Hey @Kalyan-Lama, do you still see this problem? I tried to reproduce it but couldn't.

**Comment by Kalyan-Lama** [comment]
@jnm, it seems to be resolved now. Thank you for the follow-up ❤️
