### ISSUE TITLE
Seeing `DELETE PROJECT AND DATA` even when the project has no data in it

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3791]
## Description

Under the SETTINGS Option, you see `DELETE PROJECT AND DATA` even when the project has no data in it.

![Image 1](https://user-images.githubusercontent.com/50188479/166428996-090636d1-5315-45db-ad07-77a2e34e9ddc.png)

Maybe it would be good to rephrase it as `DELETE PROJECT` when the project has no data and `DELETE PROJECT AND DATA` when the project has data in it.

**Comment by pauloamorimbr** [comment]
Implemented in https://github.com/kobotoolbox/kpi/pull/5104 👍🏻
