### ISSUE TITLE
Calculate project summary stats on the backend, new endpoint 

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#3795]
## Description

Project summary stats are constrained by the [submission limit of 30k](https://github.com/kobotoolbox/kpi/blob/master/kobo/settings/base.py#L357) and require 3 API calls to populate. For large projects this produces slow and inaccurate summaries.

Discussion: https://chat.kobotoolbox.org/#narrow/stream/4-Kobo-Dev/topic/Project.20summary.20limitations/near/105461

## Steps to Reproduce

1. Create a project, add submissions
2. View project summary
3. See three calls are made per refresh, stats are calculated based on array of submissions (could be up to 3*30000 submissions in total on each refresh)

## Expected behavior 

Single call, no limit to submission totals.

## Actual behavior 

All running totals are constrained by 30k limit.
![large-project-summary-stats](https://user-images.githubusercontent.com/50016008/166893914-720f670c-b767-46bc-b647-ac4e197c7d68.png)

**Comment by noliveleger** [comment]
As per our internal discussion, we would create another endpoint which would provide these metrics. The front end would not have to fetch the data endpoint 3 times and would not be limited with the API rate limits.

**Comment by JacquelineMorrissette** [comment]
Fixed by #4285
