### ISSUE TITLE
Add language selector to login page

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3804]
## Description

There is no way to change language here:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/2521888/168114456-b36c58b2-62e2-4ce6-ba93-d4147e61f3e4.png">

We want a way to change it :)

Note: there is a language selector dropdown at `accounts/signup/`, let's try simply duplicating it. 

We also need one at "Forgot your password".

We also need the back-end to pass language in the email about password reset, so we could display form in user's language.

**Comment by noliveleger** [comment]
@magicznyleszek we need to add to "Forgot your password" too and back-end should pass the language in the email to get the password reset form in the user's language. 
Should we open another issue for that or just update the description of this one?

**Comment by magicznyleszek** [comment]
@noliveleger I've updated the description and added the back end label
