### ISSUE TITLE
Forms with this meta-data `start-geopoint` cannot be opened in the form editor. The page breaks!

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3824]
## Description

Forms with this meta-data `start-geopoint` cannot be opened in the form editor. The page breaks and looks like this:

![Image 1](https://user-images.githubusercontent.com/50188479/170178588-5f66b3fd-7ac8-48ab-bb13-e150e9d72fd7.png)

## Additional details

For ease, you could test this with the following XLSForm:

[start-geopoint.xlsx](https://github.com/kobotoolbox/kpi/files/8767881/start-geopoint.xlsx)

**Link to the community forum:** 

https://community.kobotoolbox.org/t/is-the-start-geopoint-feature-supported-right-now-for-kobotoolbox/27742/3

**Comment by jnm** [comment]
Thanks, @Kalyan-Lama. It looks like this has been reported twice before: #2919, #3725.
