### ISSUE TITLE
Label for grouping options not clearly seen in Formbuilder (it's cut off at the left)

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3830]
## Description

Label for grouping options not clearly seen in Formbuilder (it's cut off at the left). See the image below:

![Image 1](https://user-images.githubusercontent.com/50188479/170427905-4b2d9a8c-685a-4ac7-92c3-fbc2033c74cd.png)

**Comment by magicznyleszek** [comment]
Note: there is a special class name defined in `/jsapp/scss/components/_kobo.tooltips.scss` that we should use here.
