### ISSUE TITLE
[NLP] UI fixes before release

### ISSUE THREAD

**Issue by Ig-Rebollo** [kobotoolbox/kpi#3873]
The following are the minimum necessary modifications to the UI to make the MVP version accessible and understandable.

- [x] There needs to be a more obvious and direct way to access the transcription/translation features than just in the modal. There are several options we could go with:

1. Simplified/bare minimum option: We get rid of the modal completely, and replace the audio icon for a button that takes you directly to the processing view. 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/22472326/173929308-a725e922-7bd6-42ff-b6a9-c8f150a3a4fd.png">

2. Slight modification option: We keep the modal and the icon, but add a direct button in the columns that allows you to go straight to the processing view without having to open the modal. 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/22472326/173929359-3ec3b1d1-2e64-4f77-984a-7b6130e9a9f7.png">

3. Ideal (not for MVP, but in the future) option: We get rid of the modal, but instead add a play option that allows users to play the recording directly from the table view. In addition, a button allows them to go to the processing view directly. If we want to allow download, it would be done directly in the processing view. 
<img width="317" alt="image" src="https://user-images.githubusercontent.com/22472326/173929404-51672598-0bd6-4f6a-8cb3-56a5d1b849cc.png">

- [x] Depending on the option we go with for this immediate release, change the word 'Process' in the buttons for simply 'Transcribe', or 'Open audio'. This might change in the future but for the time being it will make the functionality more obvious. Note that this would not only affect the modals (if we keep them) but also the single submission view.

- [x] (optional for MVP) For the purpose of consistency, if we keep the modal, it should have the same buttons as the single submission view. This means it should also include the download button. This is not an absolute necessity but we will have to do it eventually. Alternatively, we could remove the download button from the single submission view for now. This is an example of how it could be done in both places to save some space: 
<img width="737" alt="image" src="https://user-images.githubusercontent.com/22472326/173929977-b99e98e4-ba8d-4627-8595-1e7ce9a52e98.png">

**Comment by Ig-Rebollo** [comment]
@tinok @jnm @magicznyleszek I made this issue with some of the UI fixes I think we should tackle before release. Please let me now which of the options presented is more feasible without upsetting much any timelines.

This list should also include one more fix, though it seems you may have already tackled it:
-> When the only option is manual transcription/translation, the button simply says 'manual' - It should instead say 'manual transcription' or 'manual translation'. When the two options exist, no change is needed.
If this still needs to be done and it is not documented anywhere, I can add it to the checklist above.

**Comment by magicznyleszek** [comment]
@Ig-Rebollo I would go with 3 (ideal), as it's not as different (and removing code is nice!) from option 1 (simplified). 2 (add button) feels weird. Or go with option 1 (merged, tested, ready to deploy), and in the mean time try to finish 3.

The question is how should the MiniAudioPlayer behave, my assumption would be:
- before audio is loaded, we show nothing (i.e. no spinner) rather than multiple spinners, OR grayed out play button and time being `--:--`
- "play" button changes into "stop" while playing (not "pause", to avoid issues with hadling displayed time)
- when playing, we show time passed
- only one instance of MiniAudioPlayer can be playing - if I click "play" on one, and then "play" on other, it stops the first one automatically

**Comment by magicznyleszek** [comment]
@Ig-Rebollo as for lone "manual" button, I made the change already - now it displays these buttons:
- "manual" + "automatic" (when both available)
- "transcribe" (when only manual is available, and it's a transcription)
- "translate" (when only manual is available, and it's a translation)

Is that good enough?

**Comment by magicznyleszek** [comment]
@Ig-Rebollo And one more question: are these changes required for the release with just the manual NLP, or for the release of automatic NLP?

**Comment by tinok** [comment]
@magicznyleszek They are required for the manual release. But that's why we want to go with the option that requires the least time. So Option 1 for the manual release and then Option 3 for the next release seems to make most sense.

**Comment by Ig-Rebollo** [comment]
Hi @magicznyleszek that all sounds wonderful! thanks for the quick fix and sorry for the delay. To reply in more detail to your questions:

1. Option 3, if it is not too much work, would indeed be ideal. If it is not too different from the others, let's go with it. Options 1 an 2 were just my other acceptable alternatives in case playing audio in table is too problematic or time consuming. If they are not going to save time, we might as well go with what we really want!
2. Your assumption on how the play would work are spot on. No spinner, and grayed out play button with time being --:-- would be perfect. When playing, show time passing. And also you're right, "Play" button changes into "stop" while playing, not pause. Finally, if I play a different audio while another one is playing, it stops the previous one.
3. The buttons displaying just transcribe and translate works too. We can definitely leave it like that for now.
4. On the timeline, as Tino said, ideally this would be for the manual release, so if we need to implement option 1 as an intermediary stage and leave option 3 for the next release, that works too.

**Comment by magicznyleszek** [comment]
MiniAudioPlayer was implemented and is being used.
