### ISSUE TITLE
[NLP] Endpoint for big languages list

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3879]
## Description

An endpoint that returns all languages. Additional features:

- search by text phrase - searches in both names and language codes (all possible codes, e.g. if the source data has multiple codes available for a language), should work with minimum 2 characters
- a boolean flag to be set on selected languages ("is default" or "is initial"?) and a way to filter out languages by that property
- translations of names if possible should be done in same way as `transcription_languages` from `/environment` endpoint (a guess, I don't know how it's done)
- a way of getting a single language by it's code

## Languages list source

The list we want is https://docs.google.com/spreadsheets/d/1iQWjiujD8rRRsB3wRNOjVuczMGAmgiXr/edit#gid=1104688046 (@tinok made it); need to filter by 'Kobo list long' = yes.

From that list we need these columns:
- Kobo code
- Kobo name
- Kobo list short (`is_highlighted`?)
- some way to map kobo code with services code, see: https://chat.kobotoolbox.org/#narrow/stream/7-UX.2FUI/topic/Managing.20language.20and.20locale.20lists/near/128444

Initially we need to just build this list from the spreadsheet. In the future we would need to come up with a way to update it automagically.

## Why?

This is needed for Language Selector component. We will be displaying a short initial list and the rest of the languages will be available via text search.

<img width="659" alt="Screenshot 2022-06-16 at 23 35 44" src="https://user-images.githubusercontent.com/2521888/174672177-17b1c740-20bd-4d3f-a477-36c58e3c6d89.png">

## Future

When this is done, it most probably means that the `all_languages` list (from `/environment` endpoint) could be removed. Frontend uses it only in single place (the Language Selector component).

**Comment by jnm** [comment]
Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/7-UX.2FUI/topic/Managing.20language.20and.20locale.20lists

**Comment by noliveleger** [comment]
@magicznyleszek , FYI, the field `is_highlighted` is called `featured` in the back-end. The `static_list.py` entries have not been removed yet. I'd rather wait for the PR to be reviewed and merged in NLP children branches to get rid of it.
