### ISSUE TITLE
Don't regenerate snapshots for `/xform` view

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#3880]
## Description

The `/xform` view is for debugging xforms in the UI, but if it regenerates a snapshot, then the same problems in #3876 occur. Remove the call with `regenerate=True`.

**Comment by jnm** [comment]
Consult https://chat.kobotoolbox.org/#narrow/stream/4-Kobo-Dev/topic/AssetSnapshot before proceeding

**Comment by jnm** [comment]
Closing as we'll regenerate but explicitly allow multiple snapshots per version: #3996
