### ISSUE TITLE
Form style is not retained in form builder

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3887]
Originally reported by @Kalyan-Lama as part of #3792.

Once you save, deploy and exit a project with `Grid theme` under the `Form style` with a matrix question and then again come back to the form editor, you will see the `Form style` back to `Default - single page`:

![image](https://user-images.githubusercontent.com/50188479/166432334-cf5af6eb-6a64-4de1-98d7-ac4b93f27cb6.png)

Wouldn't it be ok to have the `Form style` to be stored to the last setting?

**Comment by LMNTL** [comment]
Fixed by [kpi#4753](https://github.com/kobotoolbox/kpi/pull/4753)
