### ISSUE TITLE
Date picker in an image gallery not compatible with dark mode

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3892]
## Description

The date picker in an image gallery is not compatible with dark mode. When using the dark mode it's not clearly visible. See image below:

![Image 1 2](https://user-images.githubusercontent.com/50188479/176607929-46adc709-6845-4ac2-b529-a75771fdc8c2.png)

This however is not an issue when the dark mode is turned off. See image below:

![Image 1 1](https://user-images.githubusercontent.com/50188479/176607990-7d2101db-fd4c-4fc7-8e1f-0c7c3c528942.png)

## Expected behavior 

Since a lot of users prefer the dark mode, it would be great to have this filter being compatible with the dark mode too.

**Comment by Ig-Rebollo** [comment]
As @Kalyan-Lama said, a lot of users seem to prefer the dark mode, so at some point we will need to make a decision on whether we truly support it across the platform or not. 

It is also true though that, as @jnm mentioned, given the current workload and list of urgent priorities, this is not something we can spend time on, at least these days. 

My suggestion would be **creating a Notion page called 'Supporting dark mode across the platform'** and document in there, over time, all the instances you find of elements not working well in that mode. Whenever we have time to prioritize it, or can add it to a larger project (for instance when we upgrade KPI's layout, maybe it can be linked with that other Notion page) we'll be able to quickly see what we need to fix.

**Comment by jnm** [comment]
I've linked the Notion page to this issue and will close this for now.
