### ISSUE TITLE
Date range not working as expected under the Gallery

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#3893]
## Description

When entering the date range, the image does not seem to filter properly.

When you select the starting range, the filter works as expected. See image below:

![Image 2 1](https://user-images.githubusercontent.com/50188479/176609138-3f428c2e-2a3e-43de-8315-810ed3dd6caa.png)

But when you enter the ending range, the filter does not seem to work as expected. See image below:

![Image 2 2](https://user-images.githubusercontent.com/50188479/176609338-93b4b333-7a61-49b8-9ff8-cd7101139e0e.png)

It however works when the ending range is increased by 1 day. See image below:

![Image 2 3](https://user-images.githubusercontent.com/50188479/176609581-e0327462-2838-4dd4-a7af-7db65039bc73.png)

**Note:** Here I was trying to filter all the images submitted on June 30th 2022.

**Comment by jnm** [comment]
Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/4-Kobo-Dev/topic/New.20Gallery/near/129500
