### ISSUE TITLE
Additional processing columns should only appear for audio questions

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3900]
## Description

Currently the Data Table is displaying additional transcript/translation columns for text, audio and video questions. It should be limited to audio only (text and video would potentially come in the future).

## Additional details

The reason this is happening is:

1. When Processing View is being opened, and a transcript or translation being added, `asset` gains `advanced_features`.
2. For `advanced_features` backend is looking for all text, audio, and video questions in given form and is enabling all of them (questions names end up in `values` array).
3. Frontend in Data Table is looking in the `values` array to see which questions are "enabled", and for all of them is producing new columns.

## Solution

1. Preferable: backend modifies `advanced_features` to not include text and video questions 🌈 
2. Hack: frontend filters out text and video questions from the `values` array every time it is being read 🤢

**Comment by jnm** [comment]
This is covered by #3939. It's not an exclusion based on type (it's possible to transcribe videos and do things like qualitative analysis on text questions—these types were chosen on purpose), but rather that we must not show extra columns for questions of any kind where the user has not desired any transcript, translation, or analysis. The current solution for this is `Asset.known_cols` (#3939)
