### ISSUE TITLE
`_submission_time` needs to be treated as UTC in the UI

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3941]
## Summary

Please treat all timestamps lacking a time zone offset as UTC. The server always uses Universal Time unless there's an explicit indication otherwise.

## Details

In the response from `https://kf.kobotoolbox.org/api/v2/assets/[asset-id]/data/`, there are a variety of timestamps for each submission. Some of them include time zone offsets:
* `"start": "2022-07-17T09:43:10.266-04:00",`
* `"end": "2022-07-17T13:53:11.481+00:00",`

The front end converts these to local time when displaying them in the table view. So far, so good.

However, `_submission_time` does **not** include an offset:
```json
"_submission_time": "2022-07-17T13:53:11",
```
This is where the trouble starts: the front end interprets this as a local time and displays it in the table view without any conversion. This leads to confusion because `_submission_time` is actually UTC.

Ideally, this would be changed to
```
"_submission_time": "2022-07-17T13:53:11+00:00",
```
…but that would involve rewriting millions of records, or adding an ugly hack to rewrite these timestamps on the fly as they are served by the API.

**Comment by jnm** [comment]
Assigned to @magicznyleszek for delegation. Maybe this could be an "introductory" issue?

**Comment by p2edwards** [comment]
I see what @magicznyleszek was getting at. 

* Updating our utils.[formatTime](https://github.com/kobotoolbox/kpi/blob/c9fa0b1e600763abb6e9bc2be4e7a5cb7f7fef71/jsapp/js/utils.ts#L30-L60)() functions to use moment.[parseZone](https://momentjs.com/docs/#/parsing/intro/:~:text=moment.parseZone()%20keep%20the%20input%20zone%20passed%20in.%20Ambiguous%20input%20is%20assumed%20to%20be%20UTC.)(), which defaults UTC, looks like it should resolve this. 
* This approach also assumes the formatTime utils won't be reused for local zoneless stamps by some of the frontend. So far that seems true.

However, the `_submission_time` rendering doesn't seem to follow the [intended formatTimeDateShort branch](https://github.com/kobotoolbox/kpi/blob/c9fa0b1e600763abb6e9bc2be4e7a5cb7f7fef71/jsapp/js/components/submissions/table.es6#L729-L736). Instead, the submission time cell falls back to the unformatted catch-all case [here](https://github.com/kobotoolbox/kpi/blob/c9fa0b1e600763abb6e9bc2be4e7a5cb7f7fef71/jsapp/js/components/submissions/table.es6#L750-L752). So the conditional might need some adjustment.

I'm looking into it.
