### ISSUE TITLE
Images are not scaled in the single submission modal

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#3945]
A large image dominates the single submission modal and actually goes outside the table boundaries:
![image](https://user-images.githubusercontent.com/2085013/179899038-10a643e3-b91e-420b-ae02-d7b53cb37690.png)
![image](https://user-images.githubusercontent.com/2085013/179899173-c2cb1967-6e41-47e0-92f7-ad6d260c5665.png)

_Originally posted by @amks1 in https://github.com/kobotoolbox/kpi/issues/3672#issuecomment-1189652765:_
> It's not necessary to return the resized image, there can be a CSS style with:
> ```
> max-width: 100%;
> object-fit: contain;
> ```
> for the `<img>` tag which would solve the interface problem.
> 
> ![image](https://user-images.githubusercontent.com/68153785/179865903-c6d1de30-d8ec-4a81-8f2f-fc387fc5ee3f.png)

**Comment by magicznyleszek** [comment]
Note: actually it might make more sense to write a global CSS for all images, as we definitely don't have a case where we want the images to not fit :smile::

```
img {
  max-width: 100%;
  object-fit: contain;
}
```
