### ISSUE TITLE
Form Landing view questions counter is wrong

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#3951]
## Description

That small text with question counter is counting all rows - groups and questions. It shouldn't count groups and any other non-answerable rows (like a `note`).

In this example below I have two groups, first with 2 questions, and second with 1 question. It shows 5, but it should show 3:

<img width="464" alt="Screenshot 2022-07-22 at 14 15 40" src="https://user-images.githubusercontent.com/2521888/180437318-bc719d84-bbd0-44c9-9f4e-80962225a8ce.png">

**Comment by ebbieaden** [comment]
I found this issue on https://ovio.org/projects and would love to contribute!
