### ISSUE TITLE
Data collection Issue (RSU Guinea)

### ISSUE THREAD

**Issue by ballamoussa1508** [kobotoolbox/kpi#4035]
Hello Sir

We are facing a very serious problem with the data that we are currently collecting. The data collection has started a month ago and we have almost 200,000 households registered with photos.

Since 28 September 2022  around 22:00, we do not have access to our account: fdsi_rsu

We can neither submit new data, nor download data already submitted.

We are coming to you to help us recover the parameters (password especially) so that we can access our data. These data are intended for targeting poor and vulnerable households in the Republic of Guinea. They are intended to fight against poverty and inequality

Please accept, Sir/Madam, the expression of our deep concern
Balla (FDSI-RSU Guinea)

**Comment by jnm** [comment]
https://github.com/kobotoolbox/covidportal/issues/7

GitHub is not a support venue; please never post requests like this here. This is a place for developers, who largely do not even have access to any data on a production server, to organize their work.

I see you are receiving support via email from our team already.
