### ISSUE TITLE
Ascending and descending icons in data table view aren't correct

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#4076]
We have these icons that appear in the header row of the data table when sorting is enabled:
![image](https://user-images.githubusercontent.com/2085013/195368315-6e0d25f9-e281-4370-9db1-8e21e801f120.png)

Choosing "Ascending" from the drop-down menu causes `sort-up.svg` to be displayed, and choosing "Decending" [sic] shows `sort-down.svg`. Someone [complained](https://community.kobotoolbox.org/t/ascending-and-descending-are-switched-in-the-data-table/34350) that these are backwards, but I don't think that's the problem. I believe the issue is that both icons, due to the arrow reversing direction, effectively show the same concept of "biggest to littlest".

[Edit: I misunderstood the forum post as a complaint about the icons not matching the sort action. Instead, the sort action does not send the correct command to the database. See #4077.]

We should communicate visually that "ascending" means "littlest to biggest" and "descending" means "biggest to littlest". This could be done perhaps by removing the arrows altogether, or by making them point in the same direction. The arrows are not particularly legible at their actual size in the UI:
![image](https://user-images.githubusercontent.com/2085013/195369704-7fe95cc0-9dba-4f2d-a6a0-826b09057ee8.png)

In some ways, I'd prefer some kind of "A-Z" and "Z-A" indicators to convey that the sorting is always lexicographic, but:
* I don't have any ideas for doing that in a culturally-inclusive way, and
* Someday, we can hopefully sort numeric columns numerically, despite all values coming in as text owing to the OpenRosa XML submission format. [(internal discussion)](https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Ascending.20.26.20Descending.20switched.20in.20table.20view/near/161377)

**Comment by magicznyleszek** [comment]
This will be fixed on `feature/regional_projects` branch
