### ISSUE TITLE
Data table sort action sends wrong query

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#4077]
Clicking "Decending" [sic] in the table view sends a query like this:
```
http://thingo/api/v2/assets/aGivv6eYSmjpbsPz4u9aBf/data/?limit=30&start=0&sort={"_123":1}
```
"Ascending" sends a query like this:
```
http://thingo/api/v2/assets/aGivv6eYSmjpbsPz4u9aBf/data/?limit=30&start=0&sort={"_123":-1}
```
These are reversed. https://www.mongodb.com/docs/manual/reference/operator/update/sort/ says:
> specify `1` for ascending or `-1` for descending

Please also change the drop down to use the correct spelling of "descending".

See also #4076

**Comment by magicznyleszek** [comment]
This was fixed together with #4076
