### ISSUE TITLE
Front-end should be prepared for incorrect Export Settings

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4105]
## Description

It's possible to get an exception:
```
Uncaught TypeError: can't access property "length", e.export_settings.fields is undefined
```
Resulting in the EXPORT button and whole "Advanced options" section being disabled. A guess is that user tried exporting through the API and didn't include a `fields` key in the export settings dict.

Front-end should handle something like that more gracefully.

## Additional details

Zulip topic: https://chat.kobotoolbox.org/#narrow/stream/7-UX.2FUI/topic/Custom.20exports/near/168730

**Comment by pauloamorimbr** [comment]
Closing this issue since it has been fixed in https://github.com/kobotoolbox/kpi/pull/4727
