### ISSUE TITLE
Tooltip for grouping questions in Form Builder not fully visible

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4106]
## Description

The tooltip in Form Builder is appearing centered, but due to the button position near screen, some of the tooltip content falls off the screen:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/2521888/200091063-26cda14b-b4b2-487d-b964-a579bd2a4cff.png">

Our tooltip CSS component has `right-tooltip` and `left-tooltip` helper classes, we should use them here.

**Comment by akshay-patade** [comment]
I would like to work on this issue

**Comment by magicznyleszek** [comment]
> I would like to work on this issue

Go ahead :)
