### ISSUE TITLE
MFA Methods cannot be opened in the admin interface on large servers

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#4142]
You can't have a dropdown like this on a large instance. Please change it to a simple text box. There's precedent for this elsewhere in the code.
![image](https://user-images.githubusercontent.com/2085013/202324647-e72bc80e-c486-4d3c-af5a-3900ace93e1b.png)

**Comment by noliveleger** [comment]
I would get rid of this possibility to add MFA Methods from the admin altogether.  
What are the chances that an admin can do this manually?
