### ISSUE TITLE
Queries needed for filtering by all available fields and conditions

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4153]
Front-end needs to know what query should it put into endpoint call to filter things correctly.

We need to handle all these fields with all these conditions (if possible):

```ts
export type FilterConditionName = 'contains' | 'doesNotContain' | 'endsWith' |
'is' | 'isEmpty' | 'isNot' | 'isNotEmpty' | 'startsWith';

export type ProjectFieldName = 'countries' | 'dateDeployed' | 'dateModified' |
'description' | 'languages' | 'name' | 'ownerEmail' | 'ownerFullName' |
'ownerOrganisation' | 'ownerUsername' | 'sector' | 'status' | 'submissions';
```

Front-end code already have regex phrases defined for each condition, needs to verify if these are correct, and what's the URL syntax for using them.

**Comment by jnm** [comment]
I think the task now is to make sure the new API endpoints support `?q=django__query__stuff:value` and then to give Leszek some guidance on how to use these. To my surprise, the query parser does support regex because Django has a `__regex` field lookup. **However**, I don't recommend using regex for these queries, because there are other clearer and less error prone field lookups for all the necessary queries. The documentation, unfortunately, is lacking; see https://github.com/kobotoolbox/kpi/issues/276#issuecomment-1315883142.

@noliveleger knows how these queries work. @joshuaberetta probably knows if the API works with the query parser :smile: I'm available to help as needed.

**Comment by noliveleger** [comment]
@magicznyleszek what you can do with `?q=`



| fields | back-end names | (i)contains | (i)startswith | (i)endswith | empty | comments |
| ----  |  ---- |  ---- |  ---- |  ---- |  ---- | ---- |
| countries | `settings__country__value` |  🚫    | 🚫   | 🚫   | 🚫   |  needs #4178 | 
| dateModified |  `date_modified` |  🚫   |  🚫  |  🚫  |  🚫   |  works with `gte` or `lte` |
| description |  `settings__description` |  ✅    | ✅  |  ✅  | ✅  |   | 
| languages |  `summary__languages` | icontains  |  🚫 | 🚫  | 🚫  |  must use `__icontains` (e.g. `summary__languages__icontains="English (en)"`) | 
| ownerEmail | `owner__email` |  ✅  | ✅  |  ✅  | ✅  | 
| ownerFullName |  `owner__extra_details__data__name` |  icontains  |  ✅  | 🚫  | ✅  |
| ownerOrganisation |  `owner__extra_details__data__organization` | ✅    | ✅  |  ✅  | 🚫  |   | 
| ownerUsername |  `owner__username` |  ✅  |  ✅  | ✅  | 🚫  | 
| sector |  `owner__extra_details__data__sector__value` |  ✅  | ✅  |  ✅  |  🚫  |  | 
| status |  🚫   |  🚫 |  🚫  | 🚫 | 🚫  | |
| submissions |  🚫    | 🚫  |  🚫  |  🚫  |  🚫 |

**Comment by jnm** [comment]
Meeting notes from December 6, 2022.

Current Problems:
* `country` value can contain single object or an array of objects
    * or it can be null
    * or the attribute can be missing entirely
* negation doesn't work as expected when any jsonb attribute is empty or missing (e.g. `country`)
    * search for "not USA" would show, for example, a Canadian project, but would omit all projects whose country is unset
* `languages`
    * can be array of strings
    * can be null
    * can be `[null]`
* `status` is not a database column, but is based on the content of `_deployment_data`
* `submissions` isn't in kpi at all: it's from kobocat
    
"Solutions"
* standardize all `country` and `language` settings to arrays
* standardize "empty" to `[]`
* make sure all expected JSON attributes in  `Asset.settings`, `Asset.summary`, `ExtraUserDetail.data` exist and follow our expected schema
* write python code to fix up existing values
* run that python code in the models' `save()` methods
* run that python code in a management command

…for `status`:
* drafts: `_deployment_data__iexact:{}` 🤢
* deployed: `_deployment_data__active:true`
* archived: `_deployment_data__active:false`

…for `submissions`:
would prefer not to support this while it still requires accessing kobocat's database. Could handle as a separate parameter, filter the `XForm`s first, then filter the assets to include only those matching the `XForm`s

(!) more investigation needed:
* languages come from the asset summary, which comes from the asset content, which comes from…

**Comment by noliveleger** [comment]
**Always wrap search term in double-quotes if it contains spaces.**

## Trivial cases

### Field names mapping

| fields | back-end names
| ----  |  ---- |
| description |  `settings__description` 
| ownerEmail | `owner__email`
| ownerFullName |  `owner__extra_details__data__name`
| ownerOrganisation |  `owner__extra_details__data__organization`
| ownerUsername |  `owner__username` 

### Lookups support

| Lookup | Supported | Syntax | Case insensitve
| ----  |  ---- |  ---- | ---- |
| exact | ✅ |  `<field>:<term>` |  `<field>__iexact:<term>`
| contains |  ✅ | `<field>__contains:<term>` | `<field>__icontains:<term>`
| startswith |  ✅ | `<field>__startswith:<term>` | `<field>__istartswith:<term>`
| endswith |  ✅ |  `<field>__endswith:<term>`  | `<field>__iendswith:<term>`
| empty |  ✅ |  `<field>:""`  | 🚫 
| not |  ✅ |  NOT `<query>` | 🚫

## Exceptions (Arrays)

### Field names mapping

| fields | back-end names
| ----  |  ---- |
| languages |  `summary__languages[]` 
| countries | `settings__country_codes[]`

### Lookups support

| Lookup | Supported | Syntax | Comments
| ----  |  ---- |  ---- | ---- |
| exact | ✅ |  `<field>:<term>` |  Returns all records which have only one occurence that matchs `<term>`
| contains |  ✅ | `<field>__contains:<term>` | Return all records which have at least one occurrence that equals `<term>` (case-sensitive). 
| startswith |  🚫 | 🚫 |
| endswith |  🚫 | 🚫 |
| empty |  ✅ |  `<field>:""`  | 
| not |  ✅ |  NOT `<query>` |

Example:
Let's consider 2 projects:
- Project A has 2 languages: "English (en)" and "Français (fr)"
- Project B has 1 language: "English (en)"

**queries:**
- `summary__languages[]:"English (en)"` will return Project B
- `summary__languages[]:"english (en)"` will return nothing
- `summary__languages[]__contains=English` will return nothing, do not work with substrings
- `summary__languages[]__contains="English (en)"` will return Project A and Project B. Case-sensitive
- `summary__languages[]__iexact:"english (en)"` will return Project B
- `summary__languages[]__iexact:"english"` will return Project B, works with substrings and case-insensitive


## Exceptions (Boolean)

**status:**
Obvisously, none of the lookups work with `status`

- `_deployment_data__iexact:{}`. Draft
- `_deployment_data__active:true`. Deployed
- `_deployment_data__active:false`. Archives


**submissions:**

not yet supported.
