### ISSUE TITLE
Improve ProjectsFilter to use countries list

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4176]
- Use countries list from `/environment` for the `countries` field when creating a filter
- Should be either a dropdown or an autocomplete field (try `<datalist>` tag https://stackoverflow.com/a/33985301/2311247?)
- it is needed, because the filter requires a code (e.g. `DEU` for "Germany") to work, and there is no place we display codes

**Comment by tinok** [comment]
Can we use the same country selector as in the project metadata fields?

**Comment by p2edwards** [comment]
@magicznyleszek Is there a way to combine filters with "OR"? 

- Example: I want to create a filter to see all projects in Canada, USA, and Mexico. 
- If I add a "Filter by ... Country" for CAN, and a filter for USA, and a filter for Mexico, it will treat them as "AND", and I'll see nothing.

**Comment by magicznyleszek** [comment]
@p2edwards Right. With current UI it would be impossible. We would need to ask @noliveleger if such query would be possible with API call (I'm guessing it would be). Then we would need @Ig-Rebollo to thing about how we would display such OR choice in UI.

**Comment by magicznyleszek** [comment]
Also I think it would be nice to update `KoboSelect` to allow selecting multiple countries. Because the select component in project settings is an older one that ideally should not be used (due to visual design reasons mostly). 

Perhaps let's do this:
1. in this issue just replace the text input with `KoboSelect` that allows selecting one country
2. create a separate issue, that would be about updating `KoboSelect` with `isMulti` option, and then using it to allow selecting multiple countries (with a proper OR query)

This way we get rid of that country codes issue quickly

**Comment by duvld** [comment]
> @p2edwards Right. With current UI it would be impossible. We would need to ask @noliveleger if such query would be possible with API call (I'm guessing it would be). Then we would need @Ig-Rebollo to thing about how we would display such OR choice in UI.

For a 'simple' solution I think we should use a switch in the corner that switches between AND or OR. That way the entire filter is applied as such. Of course we could get more in depth (grouping filters of ANDs and ORs) but I'd say this is sufficient atm.

**Comment by noliveleger** [comment]
@magicznyleszek : sure you can like we already do with asset_type in library.
`q=settings__country_codes[]__contains:CAN OR settings__country_codes[]__contains:USA`

Remember that if you want to do a mix, you would need to use parenthesis? E.g: `q=summary__languages[]__contains:French AND (settings__country_codes[]__contains:CAN OR settings__country_codes[]__contains:USA)`

BTW: Isn't Phil the author of the QueryParser ;-)?
