### ISSUE TITLE
Bulk edit should be disabled when a project is archived

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#4218]
1. Make project
1. Make submissions
1. Archive project
1. Click eyeball on submission
1. "EDIT" and "DUPLICATE" are disabled :heavy_check_mark: 
1. Tick check box next to a submission
1. "Edit" appears at top of list, not disabled :bug: 
1. Attempting to proceed with edits results in "Failed to update submissions values."

Assigned to the wizard for delegation :mage:

**Comment by LMNTL** [comment]
Fixed by kpi#4762
