### ISSUE TITLE
Clicking X button when viewing Single Project should go back to previous view

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4234]
Let's address this:

> When I click the x button to close a project it returns to My Projects rather than going back to the project view I was in. My expectation would be to go back to the project view with the same filters/sorting applied.

All the filters and sorting are being remembered on the endpoint, so a simple `const navigate = useNavigate(); navigate(-1);` should get us almost everything w need.

The optional improvement here would be to ensure that the project we are going back from is being displayed in the table. So if user was scrolling down on the table and loaded further pages, going back would also load these pages and scroll down the project row into view (like `Element.scrollIntoView()`)

**Comment by jamesrkiger** [comment]
Fixed in #4450
