### ISSUE TITLE
Remove duplicated Details section from Form Builder

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4241]
## Description

We need to remove the section from Form Builder sidebar. The "Details" header and everything below.

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/2521888/216147654-9c40f41f-acd0-4fd5-ad1a-6948ee0e32db.png">

All these settings are available in different view, so there is no point in confusing users.

**Comment by LMNTL** [comment]
Fixed by [kpi#4820](https://github.com/kobotoolbox/kpi/pull/4820)
