### ISSUE TITLE
Allow editing SSO signup email

### ISSUE THREAD

**Issue by david-code** [kobotoolbox/kpi#4261]
## Description

I'm currently working on adding some features to the OpenID Connect SSO functionality for Tech Matters. Working on a separate issue, I discussed the page presented to the user on SSO signup with @bufke . He suggested that we modify the current default behaviour, which sets the email input field to be read-only. Here is the suggested solution:

- There will a settings / env variable `UNSAFE_SSO_REGISTRATION_EMAIL_DISABLE` with a default set to `False`
- The default behaviour will then be to allow the user to edit the email input (i.e. the attribute "readonly" will not be set on the HTML input).
- If the variable is set to `True`, the attribute "readonly" will be set on the email input.

**Comment by david-code** [comment]
@bufke could you take a look at this too!

**Comment by bufke** [comment]
Makes sense to me.
