### ISSUE TITLE
App crashes when navigating quickly between form routes

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4276]
## Description

When navigating between Form sub routes very quickly (Summary, Form, Data, and Settings tabs), the whole app crashes.

<img width="474" alt="Screenshot 2023-02-16 at 09 57 32" src="https://user-images.githubusercontent.com/2521888/219316687-11a56a0e-1f76-432b-8370-4a954a073bec.png">

[Video](https://www.dropbox.com/s/s2sadvez7ml1519/quick%20fox%20jumps%20into%20the%20white%20void.mov?dl=0)

## Steps to Reproduce

1. Open a project (`#/forms/<uid>/summary`)
2. Start clicking quickly between tabs (Summary, Form, Data, and Settings tabs)
3. Observe the crash 🐛 💥 

## Expected behavior 

Not crashing 😜 

## Additional details

It seems this is connected to `PermProtectedRoute`. Possibly some components are not prepared to get `null` as loaded asset (guess).

**Comment by jamesrkiger** [comment]
Closing this as the bug fix PR was merged.
