### ISSUE TITLE
Only the asset owner has permissions for export settings endpoint

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#4292]
## Description

Export settings should be available to all users who have `view_submissions` permissions and above.

**Comment by JacquelineMorrissette** [comment]
@joshuaberetta would you mind retesting or providing exact steps for this when you have a chance? I can't seem to duplicate this

**Comment by joshuaberetta** [comment]
@JacquelineMorrissette I've just tested and this issue seems to have been resolved already :)
