### ISSUE TITLE
Make it possible to sort projects by status

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4312]
Currently "Status" column is an outcome of `asset.has_deployment` and `asset.deployment__active`. Using these two fields combined we can say if project is Draft, Deployed, or Archived. Given these are two separate fields it is not possible to sort by "Status" column. We would need a way to sort on both `/api/v2/project-views/${viewUid}/assets/` and `/api/v2/assets/` endpoints.

**Comment by p2edwards** [comment]
People who are used to the old projects table might be expecting to see something like this:

- **Deployed**
   - sorted by modified
- **Draft**
   - sorted by modified
- **Archived**
   - sorted by modified

To recreate this in the new view, you'd need to be able to group (or sort first) by "status", and then sort by date modified within that.

**Comment by jnm** [comment]
We'll use PostgreSQL `order by array_position` to accomplish this [(h/t)](https://stackoverflow.com/a/41386038/2402324). 

Just to prove that it works as expected, let's do an example where we impose an arbitrary order based on `asset_type` and also sort descending by `date_modified`. User with ID 30 is Tino and has 500+ assets. Many rows of the output were snipped.
```
koboform=# select uid, asset_type, date_modified, name
from kpi_asset where owner_id=30
order by array_position(array['survey', 'question', 'block', 'collection'], asset_type), date_modified desc;
Time: 2.132 ms
```
Result:
          uid           | asset_type |         date_modified         | name
------------------------|------------|-------------------------------|------
 axxxxxxxxxxxxxxxxxxxxx | survey     | 2020-12-09 18:04:09.480062+00 | Start geopoint testing
 axxxxxxxxxxxxxxxxxxxxx | survey     | 2020-12-01 15:57:08.024584+00 | mediacolumns
 axxxxxxxxxxxxxxxxxxxxx | survey     | 2020-12-01 15:49:33.324699+00 | an image form
 axxxxxxxxxxxxxxxxxxxxx | survey     | 2020-11-25 17:35:55.026347+00 | an image form
 axxxxxxxxxxxxxxxxxxxxx | survey     | 2020-11-12 15:22:53.741238+00 | naming
 axxxxxxxxxxxxxxxxxxxxx | survey     | 2020-11-10 17:44:43.952624+00 | Public sharing bug
 axxxxxxxxxxxxxxxxxxxxx | survey     | 2020-11-05 16:13:53.517695+00 | Detailed Registration 10/16
 axxxxxxxxxxxxxxxxxxxxx | survey     | 2020-11-05 15:59:49.551069+00 | Untitled
 axxxxxxxxxxxxxxxxxxxxx | question   | 2020-07-17 08:09:10.202011+00 |
 axxxxxxxxxxxxxxxxxxxxx | question   | 2017-08-14 16:56:34.792445+00 |
 axxxxxxxxxxxxxxxxxxxxx | question   | 2017-08-14 16:56:32.832872+00 |
 axxxxxxxxxxxxxxxxxxxxx | question   | 2017-03-04 00:31:41.891022+00 |
 axxxxxxxxxxxxxxxxxxxxx | block      | 2020-12-01 18:57:24.231634+00 | Details type of shelter at community level
 axxxxxxxxxxxxxxxxxxxxx | block      | 2020-10-09 17:44:16.856891+00 | HH income sources and borrowing
 axxxxxxxxxxxxxxxxxxxxx | block      | 2020-09-17 14:02:38.511928+00 | integer_questions
 axxxxxxxxxxxxxxxxxxxxx | block      | 2020-09-17 14:01:19.511571+00 | matrix_E
 axxxxxxxxxxxxxxxxxxxxx | block      | 2020-09-03 15:51:38.817077+00 | matrix_E
 axxxxxxxxxxxxxxxxxxxxx | collection | 2020-09-03 15:51:18.934038+00 | brand new
 axxxxxxxxxxxxxxxxxxxxx | collection | 2018-04-06 17:05:57.424973+00 | Testing Collections PM
 axxxxxxxxxxxxxxxxxxxxx | collection | 2017-08-14 16:56:31.40748+00  | Testing QB
 axxxxxxxxxxxxxxxxxxxxx | collection | 2017-03-04 00:31:40.108356+00 | collection import sample
 axxxxxxxxxxxxxxxxxxxxx | template   | 2019-10-03 15:49:30.574465+00 | tino's 2 question form template

Django doesn't support this SQL out of the box, but @noliveleger will implement it.

Our idea is that this this would **only** be available as the default sorting, i.e. when the user has not requested sorting by any column. It would not be possible to mix and match this with other sort options. How will this work in the UI? I'd propose:
1. No custom sorting chosen: use this default, special ordering
2. User specifies they want to sort ascending or descending by "Status": sort alphabetically by Status (only), ascending or descending. Modification date would not be taken into account

Does the UI have a provision for people to get back to the default sorting after they've picked another column to sort by? If not, I think we should :smile: but an alternative that I don't favor would be making the "Status" column always invoke the default, special ordering—which implicitly takes into account the modification date :grimacing:
