### ISSUE TITLE
Small UI tweaks to Projects Table

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4313]
#### Done in #4408 - Project Table UI/UX Adjustments

 - [x] Adjust Project Name hover link styles 
 - [x] Make all column contents left-aligned
 - [x] Click anywhere in the Project Name cell to navigate to that project. Don't navigate when clicking other cells.
      - Clicking on non-project name cells could also toggle the selection for that row, acting like the checkbox. This would making quick actions easier to access. We could try it.
        - Another idea: Clicking on the row "solo's" the clicked row, to make it easier to access the quick actions without "un-clicking" the previous selected checkbox
      - Keep gray row background on hover as is - helps with legibility on wide tables and makes the UI feel more like it's "listening" to user input
- [x] Reposition dropdown triangle to the left side of the dropdown label (field name), keeping the "sorting indictor" on the right, and giving the sorting indicator a different color.
    - [x] Color the "sorting indicator" teal or alt-blue.
    - [x] Align the label (field name) text so its left edge ideally lines up with the cell text in the same column
- [x] Make whole header cell clickable to trigger dropdown
    
#### Done in #4246 - Allow manual column resizing

- [x] Resizing tweaks
    - [x] Ideally keep resizing indicators visible during drag even when the cursor leaves the area
    - [x] Darken resizer indicators (did this during the call)
    - [x] Remove left indicator for leftmost column as suggested by Leszek's PR review
      - [x] Need to re-establish this again since the checkbox selection merge changes what selector should be used

#### Done elsewhere

- [x] Adjust tooltip styles to avoid cropping -- [internal discussion](https://chat.kobotoolbox.org/#narrow/stream/4-Kobo-Dev/topic/My.20Projects.20redo/near/221758) -- fixed [here](https://github.com/kobotoolbox/kpi/commit/ec542a167e26d58fe6f9ecae9e4c4d93edc7ffbb)

#### Not done yet

- [ ] related Searchbox behavior tweaks
 
Reference discussions (internal):

- [table](https://chat.kobotoolbox.org/#narrow/stream/7-UX.2FUI.2FProduct/topic/Frontend.20.2F.20design.20weekly.20checkins/near/207998)
- [searchbox](https://chat.kobotoolbox.org/#narrow/stream/7-UX.2FUI.2FProduct/topic/Frontend.20.2F.20design.20weekly.20checkins/near/211103)

**Comment by p2edwards** [comment]
I think "Make whole header cell clickable to trigger dropdown" will involve a slightly more gnarly diff. "Adjust bulk actions tooltip to avoid cropping" depends on some changes that are in another branch. 

The rest is review-ready so I'll split the issue and make this review-ready.
