### ISSUE TITLE
Ommitting `social_accounts` causes `PATCH` to fail on `/me/` endpoint

### ISSUE THREAD

**Issue by JacquelineMorrissette** [kobotoolbox/kpi#4397]
## Description
Sending a `PATCH` request to the `/me/` endpoint fails unless it includes the `social_accounts` field.

## Steps to Reproduce

1. Go to `[KPI]/me/`
2. Scroll to the box at the bottom
3. Pick a field to update and remove `"social_accounts": []`
4. Send `PATCH` request
5. Response will be an error `"detail": "JSON parse error - Expecting property name enclosed in double quotes: line 5 column 1 (char 99)"`

## Expected behaviour 

The `PATCH` request should be successful

**Comment by jnm** [comment]
I think this might be because there's a trailing comma after the last value. If you remove `"social_accounts": []`, and it that was the last attribute in the object,  you need also to remove the preceding comma. Unfortunately, JSON demands this. Python does not.
