### ISSUE TITLE
Page not rendering properly on back/forward navigation

### ISSUE THREAD

**Issue by LMNTL** [kobotoolbox/kpi#4410]
## Description

Clicking 'Manage' or 'Upgrade' and then navigating back to the Plans page more than once causes the buttons to become disabled.

## Steps to Reproduce

1. Go to [https://kf.billing.kbtdev.org/#/account/plan](https://kf.billing.kbtdev.org/#/account/plan) or checkout `feature/billing` and navigate to `#/account/plan`.
2. Click on the 'Upgrade' or 'Manage' button for a plan
3. Navigate back to the Plans page
4. Repeat steps 2-3 once
5. Notice that the 'Upgrade'/'Manage' buttons are still greyed-out

## Expected behavior 

Buttons are re-enabled upon navigating back to the Plans page.

## Actual behavior 

Upgrade and Manage buttons are still deactivated.

## Additional details

This only happens when [bfcache](https://web.dev/bfcache/) is enabled in the user's browser (if you're using Chrome, you can check that it's enabled by navigating to chrome://flags/#back-forward-cache) Because of that, it's only reproducible when browsing a non-local site - on Chrome, you can reproduce on a local site by clicking [test back/forward cache](https://developer.chrome.com/docs/devtools/application/back-forward-cache/) in place of steps 2/3, or you could just use a tool like `expose` to browse it through a tunnel. This may work differently cross-browser due to bfcache implementation, but is confirmed in Firefox and Chrome.

The issue happens because the buttons get enabled in `useEffect`, which doesn't get triggered (regardless of dependencies) when serving from the bfcache. There's code to partially mitigate it on the Plans page, which is why it gets the button state right after the first back/forward navigation. More importantly, this issue will also affect any other place in the app where we expect `useEffect` or `componentDidMount` events to happen when a page is navigated to. The bfcache basically freezes the JS objects on the page when navigating away, restoring them in-place once they navigate back, thus skipping lifecycle methods unless you can force them to re-run. For instance, this snippet from `accountSettingsRoute.tsx`:

```
  useEffect(() => {
    if (
      !sessionStore.isPending &&
      sessionStore.isInitialLoadComplete &&
      !sessionStore.isInitialRoute
    ) {
      sessionStore.refreshAccount();
    }
  }, []);
```

When the account page is served from bfcache, `useEffect` won't run, and the account details won't be refreshed.

Possible solutions I've researched so far include:

- Using `cache-control: no-store` for any page that shouldn't get stored in bfcache - prevents issues with bfcache but also keeps the page from being cached *completely*
- Registering an `onunload` event handler - not a guarantee cross-browser, creates a confirmation dialog when navigating away from page
- Updating the dependencies array of `useEffect` - tried a variety of values, no luck so far
- Reloading page or re-fetching data when we detect `event.persisted` during the `pageshow` event - probably needs to happen outside of the React component. Not sure if this would introduce a memory leak(?) since we'd need to keep the event handler hooked in after navigating away

**Comment by tinok** [comment]
I agree, let's close and reopen if there are any new reports for this.
