### ISSUE TITLE
After upgrading "your current plan" flashes on the community plan

### ISSUE THREAD

**Issue by srartese** [kobotoolbox/kpi#4411]
## Description

After upgrading and returning to the plans page the "your current plan" banner shows for a split second above the free community plan.

## Steps to Reproduce

1. Go to https://kf.billing.kbtdev.org/#/account/plan or checkout feature/billing and navigate to #/account/plan.
2. Make sure the account being used is with no plan (community plan)
3. Click on the 'Upgrade' button for a plan
2. Checkout with payment (test card here https://stripe.com/docs/testing) 
4. Navigate back to the Plans page

## Expected behavior 

When page redirects the banner should not show until data is updated so it only shows on current plan. 

## Actual behavior 

When page redirects the banner will flash and then move. 

## Additional details

Shouldn't display the banner until after its done loading the data. This would be a good place for isLoading and a spinner until data is set. This is happening because we are not done loading the new set of information after upgrading when the page loads. If we hold off on loading until all is complete this will eliminate the flashing.

**Comment by jnm** [comment]
Assuming this was fixed by #4420
