### ISSUE TITLE
Table view dropdown filter missing labels when XML Values selected

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kpi#4412]
## Description

A bug in the table view filtering for select type questions if the XML values are used: the values don't show in the dropdown, but you can still click on the invisible items and it will filter the data. 

Labels chosen:
```html
<select style="width: 100%;">
    <option value="">Show All</option>
    <option value="a">A</option>
    <option value="b">B</option>
    <option value="c">C</option>
</select>
```

XML Values chosen:
```html
<select style="width: 100%;">
    <option value="">Show All</option>
    <option value="a"></option>
    <option value="b"></option>
    <option value="c"></option>
</select>
```

## Steps to Reproduce

1. Have a form with a select question, submit some data
2. Select XML Values for table view
3. Click on filter for select question

## Expected behavior 

Labels appear in the dropdown.

## Actual behavior 

No labels in the dropdown.

**Comment by LMNTL** [comment]
Fixed by #4662
