### ISSUE TITLE
Infinite redirecting loop

### ISSUE THREAD

**Issue by dik23** [kobotoolbox/kpi#4416]
## Description

Kobo loops forever when [https://ee.kobotoolbox.org/x](https://ee.kobotoolbox.org/x) is opened

## Steps to Reproduce

Visit [https://ee.kobotoolbox.org/x/](https://ee.kobotoolbox.org/x)

Tried on Chromium 112.0.5615.49, Firefox 112.0.1, Android Firefox etc

## Expected behavior 

Not this!

## Additional details

This is a perfect way for a user to get banned

![image](https://user-images.githubusercontent.com/15139568/232549280-544970a0-328d-4afe-b872-06cf1fa1bdce.png)

**Comment by dik23** [comment]
Is also true of [https://ee.kobotoolbox.org/x/](https://ee.kobotoolbox.org/x/)

**Comment by jnm** [comment]
Thanks for the report. I've opened an issue for you on the correct repository:
https://github.com/enketo/enketo-express/issues/549
