### ISSUE TITLE
Remove `seed=` once the number is removed from the `seed` in the form builder

### ISSUE THREAD

**Issue by Kalyan-Lama** [kobotoolbox/kpi#4421]
## Description

When the seed value is removed from the form builder `seed=` is still stored within the system. This blocks the project from being deployed.

## Steps to Reproduce

1. Enter any value (not `0`) in the seed.
2. Deploy the form.
3. Remove the seed value from the form builder.
4. Deploy the project. The system does not allow to deploy. This error message is seen:

![Image-4](https://user-images.githubusercontent.com/50188479/233069877-f3f4e45b-15af-456d-a85c-fbec1b4f7fe7.png)

## Expected behavior 

Once the seed value entered in the form builder is removed, the system should not block the project from getting deployed.

## Additional details

**Internal discussion:** https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/A.20possible.20bug.20with.20randomize.20choice

**Community Forum:** https://community.kobotoolbox.org/t/randomize-choice-issue/40232

**Comment by RuthShryock** [comment]
Fixed by #4695
