### ISSUE TITLE
User not found - full stop in username

### ISSUE THREAD

**Issue by dik23** [kobotoolbox/kpi#4425]
## Description

Unable to share forms with usernames with full stops . in

## Steps to Reproduce

Django administration > Home > Authentication and Authorization > Users > Add user

Username:  
Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only

Add user : user.name 

Deployed form > Settings > Add User > user.name

User not found : user.name

This is not an issue if I add users username or user_name

## Expected behavior 

Add user.name to the form

## Actual behavior 

![image](https://user-images.githubusercontent.com/15139568/234277852-29176d15-d58d-461e-b3d0-a108a08aeb53.png)

## Additional details

kobo-install Version: 8.0.2 (build 6b0b9bb)
Ubuntu 22.04

**Comment by jnm** [comment]
Thanks for the report. These usernames are forbidden and not allowed by the registration page. They were previously allowed in the Django admin interface, but we have closed that loophole: https://github.com/kobotoolbox/kpi/pull/4281

If you create your users programmatically or through direct database access, you must adhere to our username requirements for the application to function correctly.

**Comment by jnm** [comment]
Additionally duplicates https://github.com/kobotoolbox/kpi/issues/4139

**Comment by jnm** [comment]
To reiterate:

> They were previously allowed in the Django admin interface, but we have closed that loophole: #4281

This is a relatively new change. You're probably running a version prior to this PR being merged, but if not, please feel free to open an issue about the hint, validation error, or whatever it is you're quoting being wrong.

Thanks and take care.

**Comment by jnm** [comment]
Version that includes #4281 looks like this:
![image](https://user-images.githubusercontent.com/2085013/235241060-151d10b0-9fee-4458-9fe4-385c9ef99257.png)
