### ISSUE TITLE
"Next" button not included in keyboard navigation of forms

### ISSUE THREAD

**Issue by notufotofuton** [kobotoolbox/kpi#4427]
## Description
UI/UX Bug. 

Tab key navigation of a form does not include the "Next" button.

## Steps to Reproduce

1. Create a survey with a multiple-choice or text field as the last question in a group, and additional questions after that group (so that "Next" is displayed rather than "Submit" when the form is filled out).
2. Preview form (or deploy and collect data in "Online-Only (single submission)" mode (other modes may work too).
3. Answer the last question on the page with the test group.
4. Hit Tab.

## Expected behavior 
- The "Next" button should show some form of highlight or selection, and
- Hitting Enter should be the equivalent of clicking on "Next": the form should go to the next page

## Actual behavior 
The "Next" button does not change, and hitting Enter causes the browser to leave the survey and open the home page for enketo.org (!!)

## Additional details
This occurs because the Next button **_is not_** in the tabbing order for the page, but the link to enketo.org **_is_** (in the "Powered by Enketo" tag in the lower right of the page). This is the opposite of what it should be.

This is unexpected and disconcerting behavior, especially for respondents who are taking a web-based survey on their own (that is, without an interviewer). Furthermore, there is no indication to the user why it happened or how to recover. Most users may know enough to hit the "Back" button, but I've know plenty who would jump to thinking of malware or hacking.

Also, not having "Next" in the tabbing order is a barrier for users who cannot use a mouse due to physical challenges, and inconvenient for those who use the keyboard for efficiency.

The "Verify" button (or "Submit" if deployed) also has issues. It seems it is sometimes in the tab ordering where one would expect it, and sometimes not. I haven't investigated fully.

Browser: latest version of Firefox for Linux.
Surveys hosted on the KoboToolbox Non-humanitarian server.
Reported in Forums [here](https://community.kobotoolbox.org/t/tabbing-sequence-on-web-forms/39935).

**Comment by jnm** [comment]
Hi, I appreciate you reporting this, but Enketo has its own repository and issue tracker at https://github.com/enketo/enketo-express/issues/. GitHub does not allow me to transfer your issue automatically, so I must ask you to re-post your content there. Thanks for your understanding.
