### ISSUE TITLE
Add validated_password flag to accounts

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4473]
- All accounts start with `validated_password: true` - superuser will manually switch them to `false` (for example based on account not changing password for x days after the new password constraints come into effect - using “last date of password change” from the point mentioned above)
- Account with `validated_password: false` will have restricted access to some APIs - handled by kobocat
- Account with `validated_password: false` will see a screen instead of KPI interface (handled by other issue) 
- Updating password should automatically switch the flag to `true`
- We need to build something into kpi so that whenever the superuser sets `validated_password: false` for an account, kpi will somehow flag that account in kobocat so that it cannot do anything except collect data (and reverse `validated_password: true` should work too, and unlock account)
- This flag should be exposted to frontend (in `/me` endpoint?)

**Comment by jnm** [comment]
Please make it a distinct column on `ExtraUserDetail`
