### ISSUE TITLE
Config for zxcvbn disabling

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4481]
Proposed variable name: `ENABLE_PASSWORD_ENTROPY_METER` and the accompanying help text in the Django admin interface: `Display an entropy meter and password quality suggestions whenever users change their passwords`. This should be exposed to Front end through `/environment` endpoint and also be accessible in the templates (similarly to `google_analytics_token` or `config.logo`).

**Comment by noliveleger** [comment]
@magicznyleszek the wording in not the correct one in back end. I'll create a new PR to fix that and send to the front end what's suggested in the description of this issue. 
cc @JacquelineMorrissette
