### ISSUE TITLE
regex with double quotes is stripped on saving form

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#466]
When using double quotes in manual validation/constraint the formbuilder strips all parts of the code starting with the first double quote. 

To reproduce: 
1. Start form with a text question
1. Add this condition as a manual constraint: `regex ( ., "^[0-9]{10}")`
1. Save the form and reopen (or open in json view)

Expected: The condition is saved as `regex ( ., "^[0-9]{10}")`

Instead: The condition only remains as `regex ( .,`

**Comment by magicznyleszek** [comment]
@dorey could you write short note on the `research-actionability` label you've added here (so it's not lost on us in future)? :)

**Comment by JacquelineMorrissette** [comment]
This looks like it has been fixed, I haven't been able to duplicate the error
