### ISSUE TITLE
Submission counts endpoint doesn't omit deleted submissions

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4667]
## Description

The `/api/v2/assets/<uid>/counts/` endpoint includes deleted submissions in the daily counts.

## Steps to Reproduce

1. Create new project
2. Deploy
3. Add one submission
4. Note that `/api/v2/assets/<uid>/counts/` returns:
   ```
   {
     "daily_submission_counts": {
       "2023-09-27": 1
     },
     "total_submission_count": 1
   }
   ```
5. Go to Data Table and delete the submission
6. Note that `/api/v2/assets/<uid>/counts/` now returns:
   ```
   {
     "daily_submission_counts": {
       "2023-09-27": 1
     },
     "total_submission_count": 0
   }
   ```
7. :bug:

## Expected behavior 

I think that `daily_submission_counts` should be an empty object?

**Comment by magicznyleszek** [comment]
@JacquelineMorrissette assigned this to you as you wrote the endpoint code #3984 - feel free to unassign yourself though :)

**Comment by jnm** [comment]
The `daily_submission_counts` are behaving as intended. Once a submission is received, it has contributed to the strain on our infrastructure, and it counts as usage. These counters are never decremented when submissions are deleted.

I'm unsure whether or not `total_submission_count` decreasing from 1 to 0 is desired.
