### ISSUE TITLE
500 error on Data Table causes the error page HTML code being displayed

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kpi#4698]
## Description

If `/api/v2/assets/<uid>/data/?limit=30&start=0&sort={%22_id%22:-1}` fails with 500 error, the whole response (that is a HTML page) is being displayed in a places that expects a string.

<img width="1263" alt="Screenshot 2023-10-24 at 23 43 43" src="https://github.com/kobotoolbox/kpi/assets/2521888/100629e5-b31a-4145-9adb-3f3c3eb72b75">

We should do a better error handling. Detecting if error is HTML code should be straghtforwad (see `handleApiFail` function).

**Comment by LMNTL** [comment]
Fixed by #4707
