### ISSUE TITLE
Give user feedback on status of background library imports.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kpi#476]

**Comment by magicznyleszek** [comment]
Maybe simply a section in forms list:

<img width="1273" alt="screenshot 2019-01-02 at 17 44 27" src="https://user-images.githubusercontent.com/2521888/50603359-92233e80-0eba-11e9-9edc-199599b71beb.png">

I could get it from BE on page load and then populate with just FE when user starts upload?

**Comment by magicznyleszek** [comment]
I've added "needs-design", as although there is a proposition, it doesn't feel thought through thoroughly

**Comment by magicznyleszek** [comment]
Blocked by #2625

**Comment by joshuaberetta** [comment]
moved to: https://www.notion.so/kobotoolbox/Give-user-feedback-on-status-of-background-library-imports-93f987e37d964cbb9add4f8320d08879
