### ISSUE TITLE
Audio processing modal does not load attachments in repeat groups

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#4846]
## Description

When opening the audio processing modal for files in repeated group. Transcript, Translations and Analysis tabs are not available. 

## Expected behavior 

Should be able to transcript and translate each audio file in the group

## Actual behavior 

Message `There is no data for this question for the current submission` appears

## Additional details

May be related to the detection of the `qpath`.  Audio files in the same repeated group have the same `qpath`.

**Comment by jnm** [comment]
Closed. Not supported. Can be reopened once this work is scheduled.
