### ISSUE TITLE
Background Audio Files do not play in the submission preview

### ISSUE THREAD

**Issue by JacquelineMorrissette** [kobotoolbox/kpi#4859]
## Description
Background audio files do not play in the submission preview. This is true for both AMR and M4A files. 
It looks like there is no audio attached to the audio player. On inspection of the element, there is no `src` for the audio player to play. 

![image](https://github.com/kobotoolbox/kpi/assets/74968475/2babf37a-d266-46be-824e-ca52f0087ba1)
xref: https://chat.kobotoolbox.org/#narrow/stream/6-Kobo-Support/topic/Background.20Audio.20not.20playing.20with.20Editing.20Mode!

**Comment by Kalyan-Lama** [comment]
**Community:** https://community.kobotoolbox.org/t/cant-open-background-audio-recording/50316
