### ISSUE TITLE
Replacing an attached file in the Media does not work as expected

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kpi#4914]
## Steps to Reproduce

- Upload the xlsform to the server that had pulldata function.
- Upload the CSV file.
- Deploy
- Now update the revised CSV file (with some new records).
- Replace it with the existing CSV file from SETTINGS>Media.
- Redeployed the survey project.

## Expected behavior 

To be able to pull data from the CSV

## Actual behavior 

You are not able to pull data from the CSV file for the new changes you have made in the CSV file.

**Comment by nanometrenat** [comment]
xref https://community.kobotoolbox.org/t/failure-to-access-csv-file-uploaded-to-settings-media/52241/22 and the many linked community posts

**Comment by nanometrenat** [comment]
xref https://community.kobotoolbox.org/t/failure-to-access-csv-file-uploaded-to-settings-media/52241/22 and the other linked community posts

**Comment by jnm** [comment]
Fixed by #4915
