### ISSUE TITLE
 Data in Kobo Toolbox webforms saved as draft disappeared without deleting them or clearing the cache,  what do i do to retreive the data?

### ISSUE THREAD

**Issue by hhh77766** [kobotoolbox/kpi#5121]
## Steps to Reproduce

1. …
2. …
3. …

**Comment by jnm** [comment]
Hi, sorry to hear about your problem, but we cannot help with a support request that is written in the title of a GitHub issue and contains absolutely no information in the issue description (except total disregard for our issue template).

We have a friendly support community at https://community.kobotoolbox.org/, where other users and paid staff alike are able to help troubleshoot your issue.

If you're a developer and believe you've found a bug in the code of KPI (vs. Enketo, which is in another repository), then you are welcome to open a new issue here, but take care that you fill out the issue template appropriately.
