### ISSUE TITLE
Add HEIC codec to gallery/image viewer

### ISSUE THREAD

**Issue by SchlennoB** [kobotoolbox/kpi#5209]
Currently submitted images and photos in HEIC format are not displayed in the gallery and in a submissions detailed view. Since iPhones have a significant share in the mobile market it might be reasonable to add a codec that allows to view submitted images in HEIC format in the backend. Especially in the context of self administered forms when users might not even be aware of the format their photos are saved with.

**Comment by jnm** [comment]
Thanks for the suggestion. Unfortunately, no browsers other than Safari support HEIC, so we cannot just pass the content through to the browser. Further working against us, if we were to try converting the images on the server, are the licensing issues around HEIC:

> It is hard for browsers to support HEIC because it is [complex and expensive to license](https://en.wikipedia.org/wiki/High_Efficiency_Video_Coding#Patent_licensing). [AVIF](https://caniuse.com/avif) and [JPEG XL](https://caniuse.com/jpegxl) provide free licenses and are designed to supersede HEIC. [(ref)](https://caniuse.com/heif])

A related request is whether we (or really https://github.com/enketo/enketo) could prevent HEICs from being uploaded in the first place: https://community.kobotoolbox.org/t/heic-image-files/30852. If that would help your use case, or you have another proposed solution, please suggest it at https://community.kobotoolbox.org/c/feature-wishlist/6.
