### ISSUE TITLE
Public collections

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#552]
A user should be able to make a collection public and remove this permission level again. 

A user should be able to view a list of public collections. (As opposed to collections shared by URL, which are not publicly listed.)

Users other than the owner can choose to "subscribe" to the collection, after which they can access the assets in the collection like all their collections. (A user can then also unsubscribe from the collection to remove the collection from their account.)

**Comment by jnm** [comment]
This issue will cover any changes needed to the permissions system and/or `Collection` model.
