### ISSUE TITLE
User can import cascading choice lists

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#560]
Imports will be done from copying-pasting pre-formatted XLS tables or importing them from a file. 

UX screens pending. 

#515 and #516 depend on this issue.

**Comment by dorey** [comment]
Working towards [cascading select import template](https://docs.google.com/spreadsheets/d/1n9gQwDzfXElgoqWngRv8whoPOYKlxCFkykL79Kxhp-M/edit#gid=1)
