### ISSUE TITLE
Remove trailing slash from activation link

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#605]
When users in some email clients (e.g. Yahoo mail) click on the kobotoolbox activation link, the hyperlink doesn't include the trailing slash. Without this slash the activation doesn't work and users are frustrated.  

Current workaround: User needs to copy-paste the URL into a new tab. 

Desired solution: Don't use a trailing slash in the activation link or forward requests without the slash to the URL with the slash.

**Comment by jnm** [comment]
OK, I can see that django-registration extension that we use will only ever use hexadecimal digits for activation keys:
https://github.com/macropin/django-registration/blob/e2d1e7fd3dda9501b4be7b8a7b2bbc5212d41f21/registration/models.py#L331-L332

It also looks like the trailing slash is part of the URL definition:
https://github.com/macropin/django-registration/blob/e2d1e7fd3dda9501b4be7b8a7b2bbc5212d41f21/registration/backends/default/urls.py#L36-L41

Testing locally, I see that requests with_out_ the trailing slash are 301 redirected to include the slash:
```
[13/Apr/2020 15:55:51] "GET /accounts/activate/546d0b006fb6a5d4c845ec0ca6c09fe7bd277673 HTTP/1.0" 301 0
[13/Apr/2020 15:55:51] "GET /accounts/activate/546d0b006fb6a5d4c845ec0ca6c09fe7bd277673/ HTTP/1.0" 302 0
[13/Apr/2020 15:55:51] "GET /accounts/activate/complete/ HTTP/1.0" 200 2266
```

@duvld, did removing the trailing slash from the email URL make things better in Yahoo mail and the rest?
https://github.com/kobotoolbox/kpi/pull/2622/files#diff-3a9e7bb63c072e5254296d76ec8e400eL8-R8

**Comment by duvld** [comment]
Just rechecked it again and there aren't any issues with how the link is shown (with or without the slash) for yahoo mail. I tried it on the basic view and the new interface and the issue (at least with yahoo) seems to be resolved now.
