### ISSUE TITLE
kpi redesign issues

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#613]
Smaller issues: 
- [x] the '?' button in the bottom right corder doesn't look right
- [x] User Profile in the user settings-dropdown links to the wrong page (/ is missing before settings)
- [x] When selecting an asset in the library, the context menu is in the wrong place. See [screenshot](https://cloud.githubusercontent.com/assets/673511/14319253/7a7ac150-fbde-11e5-8353-ab0d706681da.png)
- [x] The top header bar doesn't extend all the way to the left (See 
  [screenshot](https://cloud.githubusercontent.com/assets/673511/14319397/089f492e-fbdf-11e5-90cb-edcf7d3eb89a.png))
- [x] when using a narrow screen, the navigation sidebar can only be opened, not closed. See 
  [screenshot](https://cloud.githubusercontent.com/assets/673511/14320339/b00f0ffc-fbe2-11e5-97a2-2a8c7bfa3388.png)
- [x] When a user hovers over the B or Q in the library list, it should change to a square (like Google Inbox)
- [x] When editing a question library of block there is no more "X" button to close the  formbuilder
- [x] For each button in the Library list context menu there should be a hover state indicating the function (Edit, View, Download, etc.)
- [x] Remove the 'refresh' (turning arrows) from the tool menu in the library list page
- [x] Fix tag design on library list when a card is expanded (tags need to wrap into new line)
- [x] Fix layout for screens above 1400px wide
- [x] Can't scroll down in longer forms (no scroll bar)
- [x] Form name is not in the form title row but slightly below
- [x] 'click to add new option' is above the preview in terms of z-index 
  (see [screenshot](https://cloud.githubusercontent.com/assets/673511/14434711/54eb0492-ffe2-11e5-908d-153ab4fb8515.png)
- [x] form style overlaps (below) form questions

Bigger things:
- [x] Library page: When clicking on the collections on the left the filter is not applied on the right
- [x] The secondary sidebar on the left should only show collections when a user is on the Library page
- [x] The NEW button should show different options for when a user is on the Library and Forms page
- [x] When clicking on Language the page refreshes (instead of refreshing after picking a language)
- [x] When the formbuilder screen is open (editing a form, question, or block) the search and tag filter boxes on top should not be displayed

**Comment by pmusaraj** [comment]
This is now ready, with the final changes made in new-ui--webpack branch
