### ISSUE TITLE
Form title is not displayed in preview

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#620]
The form title displayed in kpi formbuilder preview is always shown as `Untitled`. See screenshot: ![image](https://cloud.githubusercontent.com/assets/673511/14396709/22de626a-fda7-11e5-8dd3-9859c5bd16fb.png)

**Comment by dorey** [comment]
* preview from form landing page displays title correctly
* preview from within formbuilder currently displays default value: "Snapshot XML" (!!)
