### ISSUE TITLE
pyxform error when creating preview should be displayed to user

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#621]
If a user makes a mistake in the form (or if there's a bug in the formbuilder that creates invalid xlsform code, the preview fails. No specific error is displayed. 

~~"failed to generate preview" is all that is shown to the user, but not the cause of the error, if provided by pyxform.~~

Currently the preview window opens (empty) but the asset_snapshot silently fails: 
![image](https://cloud.githubusercontent.com/assets/673511/15462529/a2aa6d2e-20c3-11e6-8d81-5324254c377a.png)

**Comment by tinok** [comment]
Possibly related to #631, although pyxform __is__ already providing useful errors in the console, just not to the user.

**Comment by dorey** [comment]
I've started on this here: e35053
