### ISSUE TITLE
store xlsform errors in summary

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#631]
when a survey asset is saved, we would want to store warnings and errors in a way that it can be presented to the user (as was done in dkobo)

https://github.com/kobotoolbox/dkobo/blob/master/dkobo/koboform/models.py#L76-L80

**Comment by tinok** [comment]
Should we create a separate issue for displaying the errors? They should be displayed import, save, preview.

**Comment by joshuaberetta** [comment]
moved to: https://www.notion.so/kobotoolbox/Store-xlsform-errors-in-summary-fd9cf32198ab4e33927569211da2137e
