### ISSUE TITLE
User should be able to add manual appearance values to groups

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#637]
A user should be able to specify other appearances to groups. Currently there's no text entry field, only the 'field-list' checkbox. 

Suggested implementation: 
![image](https://cloud.githubusercontent.com/assets/673511/14533865/da08d95c-0234-11e6-81b4-fe05af90ecd0.png)

**Comment by tinok** [comment]
This would allow using `grid-theme` fully, which requires adding appearances to groups for the number of columns, e.g. `w6` or `w3`.

**Comment by joshuaberetta** [comment]
moved to: https://www.notion.so/kobotoolbox/User-should-be-able-to-add-manual-appearance-values-to-groups-454bcfa98d03469c8d717c3ff2f24e9c
