### ISSUE TITLE
Large form can't be saved in KPI

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#642]
When trying to edit a large form in kpi the `PATCH` command gets a 413 response. 

To reproduce: 
1. Import [a large XLS form](https://www.flowdock.com/app/kobotoolbox/kobo/threads/wSBI25HgDnnC48BA-W1Nzi2EZHX)
2. Edit
3. Click Save

**Comment by magicznyleszek** [comment]
Works like a charm ✨
