### ISSUE TITLE
Create separate lists of KPI forms

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#646]
This is necessary for implementing the new UI. 

We need three lists: 
Deployed and active - "Active"
Non-deployed - "Forms"
Deployed and non-active - "Inactive"

**Comment by dorey** [comment]
[ ] DRF changes to the asset serializer
[ ] splitting up the react view based on the DRF changes

**Comment by tinok** [comment]
We need to include the number of submissions for each project as well.

**Comment by jnm** [comment]
I've tracked the need for retrieving the number of submissions from KC in a separate issue: https://github.com/kobotoolbox/kpi/issues/689
