### ISSUE TITLE
Changes to Library toolbar

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#664]
- [ ] Add Share button
- [ ] Add 'move to collection' button
- [ ] View button in toolbar should point to Preview (not asset landing page)

List page toolbar: 
![image](https://cloud.githubusercontent.com/assets/673511/14820624/738d266e-0b95-11e6-9fb1-4c55af516d23.png)

Landing page: 
![image](https://cloud.githubusercontent.com/assets/673511/14820614/627a680a-0b95-11e6-8af7-0601712a84ba.png)

**Comment by pmusaraj** [comment]
Started doing this today, only to realise that there is a more complex issue with this. Currently, the app's assetrow.es6 file displays each row of an asset (i.e. survey IINM), collection or question. However, in new design, the form list and library will diverge considerably and collections are removed from asset lists. 

So, @dorey, do we still keep a shared AssetRow component, or do I create a new assetrowLibrary component for the library only?
