### ISSUE TITLE
Library feedback

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#674]
Top priority:

- [x] Increase width of `select-input` so that adding additional tags is easier (width:30px) 
[see mockup](https://cloud.githubusercontent.com/assets/673511/15023728/b59f2e56-11ff-11e6-8d8a-7f37ef06aebf.png).
- [x] Change width of search bar to same width as 'name' column underneath. The search text should also be left-aligned. See [screenshot](https://cloud.githubusercontent.com/assets/673511/15023859/45df073e-1200-11e6-997f-3316ff09ba96.png)
- [x] Take out tickbox state when item is toggled
- [x] Asset card should only be toggled / untoggled when clicking on the top part, so that adding tags is possible. 
- [x] when the number of tags exceeds the right side of the "owner" column (see [screenshot] 
(https://cloud.githubusercontent.com/assets/15673694/15042483/4b34c786-1292-11e6-99dc-45d1339e06a3.png) ) wrap the remaining tags below.
- [x] entering a new tag larger than 10 characters pushes the remaining text off to the left so that the user cannot see what was previously typed [[See screenshot]]
(https://cloud.githubusercontent.com/assets/15673694/15042671/0ce140b6-1294-11e6-90c5-91867d306aca.png) . Change it so that the user can see the full text of what is written.

Lower priority:
- [ ] When a user hover overs the "b" icon, it should appear as an empty square. When a user clicks on it, it becomes a checked box.
- [x] the globe icon used in the side nav to represent projects is not the same one used in the design.
tool bar icons for duplicate and trash are not the same as the design.
- [x] Change "Add a tag" to "#tags". [See screenshot]
(https://cloud.githubusercontent.com/assets/15673694/15043172/74bb556a-1298-11e6-816b-3b71647bc374.png)
- [ ] Off: #000000, Opacity 54% Disabled: #000000, Opacity 26%. Light theme for checkboxes inhover, focused, pressed, disabled, and disabled focused states. [[See MD description of the checkboxes we use ](https://www.google.com/design/spec/components/selection-controls.html#)] 
- [x] when a user selects a collection, delete/sharing/edit will show up as icons. Please reference pg. 12 of the V3.3 mockups
- [x] please update the selected collection state to the newest design PDF (coming soon)
- [x] Please make the color of the row (Name, Owner, last modified, etc) ~~#FAFAFA~~ PM: #f7f8fa used following latest design
- [x] when user selects an item and the toolbar appears, change the color of this space to ~~#EDF4FD~~ PM: used #EDF7FD following design // and box-shadow: 0 0 2px
- [x] make Name/owner/last modified/questions a clearly defined space where all lines connect, see [screenshot from similar space in Drive]
(https://cloud.githubusercontent.com/assets/15673694/15042246/628f237e-1290-11e6-8b9f-390f8edfaec5.png)
- [x] there should be a + button on the right side of the tags so that users can add tags from this view.
- [x] divider lines in the table should connect on both ends to the card (take out the 8px padding on each side).
- [x] limit sidebar items to three lines, with ellipsis at end of third line where needed

**Comment by pmusaraj** [comment]
This should likely be closed, as designs have evolved since.  @emilykferguson do you agree?
