### ISSUE TITLE
Saving is not possible in IE11

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#676]
When clicking the Save button nothing happens in the browser (the unsaved state remains and nothing is sent to the server). 

An error is produced in the console: 
![image](https://cloud.githubusercontent.com/assets/673511/15030874/dae870e6-1222-11e6-81b2-a25c7cdcc416.png)

Debugger: 
![image](https://cloud.githubusercontent.com/assets/673511/15030900/09f4fee0-1223-11e6-8280-7ec0227096a0.png)

**Comment by pmusaraj** [comment]
This has surely been fixed since May.
