### ISSUE TITLE
User should be able to edit project title in KPI (outside of formbuilder)

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#679]
A user should be able to change the kpi asset name of a project/form without having to open the form in the formbuilder. 

When the user hovers the title and it should have a light grey box outline and a tooltip "Rename". Then when you click it, the box turns blue and the project title text automatically highlights for easy editing. Press enter or click away from it to save changes.

**Comment by pmusaraj** [comment]
Fixed via #1026
