### ISSUE TITLE
Remove unnecessary API calls from UI

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#702]
The kpi UI currently includes unnecessary API calls that slow down loading times: 

form list: 
- `/forms/assets/?q=asset_type%3Asurvey` is called twice

form landing page: 
- `/forms/collections/?parent=` should not be called
- `/forms/tags/?limit=9999&q=asset_type%3Asurvey`should not be called
- `/forms/collections/?parent=` should not be caled
- `/forms/assets/?q=asset_type%3Asurvey` should not be called again if the user just opened a form from the form list (we should keep the same content in the sidebar)

**Comment by tinok** [comment]
As part of this let's also load the queries sequentially by importance:
1. Assets
2. Collections (if inside the library)
3. Tags

#duplicate #queries

**Comment by pmusaraj** [comment]
Closing, the UI has fixed most of these, and new performance issues should be handled in a new ticket.
