### ISSUE TITLE
Cascades change when question name changes

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#706]
When a user updates the label of an imported cascade question the unique `name` is also updated, but the `choice_filter` value remains as it was originally -- thereby breaking the cascade logic. 

![image](https://cloud.githubusercontent.com/assets/673511/15295156/32c6f114-1b5d-11e6-82f7-745bd9b8cd72.png)

**Comment by jnm** [comment]
Reopened by #2938

**Comment by jnm** [comment]
Reference for the next time we attempt this: https://chat.kobotoolbox.org/#narrow/stream/4-KoBo-Dev/topic/Form.20builder.20question.20name.20regression
