### ISSUE TITLE
User can see assets that have been deleted

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#714]
When a user deletes a form or library asset it should be removed from the view immediately (maybe with some ease-out effect). Instead, they remain in the list until the page is refreshed.

**Comment by tinok** [comment]
@dorey Not sure if this is something that should be in your column?

**Comment by pmusaraj** [comment]
This issue seems to happen with old assets only. I created a new asset (locally and on staging) and then deleted it, and the asset got the "deleted" property updated, and visually it looks disabled, screenshot: https://monosnap.com/file/I4r1gHDTo2qwhq1L8kwPywJfbkhQds
