### ISSUE TITLE
Design feedback for Projects UI

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#727]
SIDE BAR:

- [x] Only “Deployed”, “Draft", and “Archived" in Roboto Medium. Project names should be in robot regular
- [x] Line height for projects should 17 (more vertical spacing than currently implemented) 
- [x] NEW Button should be squared, not beveled
- [x] Hover on PROJECTS and LIBRARY don’t match the other hovers

MAIN AREA: 

- [ ] “Deployed”, “Draft", and “Archived” headers in Roboto Medium
- [ ] “Name”, “Owner”, “Last Modified”, “questions”, in Roboto Medium
- [ ] Name, owner, last modified column a freeze frame
- [ ] Name, owner, last modified column should have a white background
- [ ] Incorrect refresh button (the correct one is in the current icon font)
- [x] EDIT pencil is too large - it should be the same height as others
- [x] VIEW icon is outdated, the current one does not have the pupil filled in
- [ ] the hover bubble on all actions should stay in one height: Triangle should touch the bottom of the column so it doesn’t bounce around if the cursor is moving up and down. 
- [ ] Accordion icon changed and animation introduced (I will mock that up. Since we use a “play” button as the deploy icon the triangle no longer works for accordion.
- [ ] Once a project is in the expanded view: TAGS were updated to grey (not blue since it makes it look like a button)

TOP NAV: 

- [ ] "Select tags” should be #DBEDF7 color
- [ ] Drop Down menu items should be Roboto Regular
- [ ] Username should be Roboto Regular
- [ ] Search and Tags should be updated to the square design. 

FORM LANDING:

- [x] Title in header should be Roboto regular (PM note: already Robot regular)
- [x] FORM, DATA should be Roboto regular (PM note: already Robot regular)
- [x] dropdown font should be Roboto regular (PM note: already Robot regular)
- [x] “show full history” should be grey with highlight color being black

**Comment by pmusaraj** [comment]
@emilykferguson is this still relevant?

**Comment by pmusaraj** [comment]
This is quite old, closing.
