### ISSUE TITLE
Automatic question names are not truncated

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#729]
Question names are supposed to be truncated but are currently not truncated at all, leading to broken XML / performance issues, and very long strings saved when transmitting XML to KC. 
[long_name.xlsx](https://github.com/kobotoolbox/kpi/files/286984/long_name.xlsx)

**Comment by dorey** [comment]
For this, I will write tests to ensure that [`kobo_to_xlsform.py`](https://github.com/kobotoolbox/kpi/blob/master/kpi/utils/kobo_to_xlsform.py) output matches [`$utils.sluggify(...)`](https://github.com/kobotoolbox/kpi/blob/master/jsapp/xlform/src/model.utils.coffee#L76)

**Comment by tinok** [comment]
Tested on staging, closing issue.
