### ISSUE TITLE
Library sends wrong API query when coming from Form list

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#754]
To reproduce: 

1. Open project page
2. Click on Library
3. Click on any existing collection to filter by it

Expected: https://kf.kbtdev.org/forms/assets/?subscribed=false&public_parent=false&q=(asset_type%3Aquestion+OR+asset_type%3Ablock)+AND+(parent__uid%xxx)

Instead:
https://kf.kbtdev.org/forms/assets/?subscribed=false&public_parent=false&q=(asset_type%3Asurvey)+AND+(parent__uid%xxx)

**Comment by jnm** [comment]
Closing since the fix has been merged into https://github.com/kobotoolbox/kpi/tree/develop.
