### ISSUE TITLE
Prevent user from entering long form names

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#762]
Form/ project names longer than 150 characters should not be allowed. When a user tries to enter longer names they should see an error message "Project names should be less than 150 characters".

**Comment by magicznyleszek** [comment]
@tinok is this still valid? Currently it's ok to have long project names. Plus what about existing projects that have long names?

**Comment by tinok** [comment]
I'm closing it @magicznyleszek . I can't remember if there was a hard reason, so it might just have been for aesthetic reasons.
