### ISSUE TITLE
Cloning a question breaks SL builder in UI

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#763]
In a form with skip logic, cloning a question breaks the UI SL builder. The SL condition is preserved, though. The SL builder displays properly again after saving and reopening the form. This does not happen if the form was saved **after** creating the SL condition and **before** cloning the question. 

This applies to all question types; the second dropdown appears to be removed when a question is cloned, making the SL look broken. 

To reproduce: 
1. Create a new form
2. Add two text questions
3. Create a SL condition for the second one (question 1 was answered) 
4. Click the clone question button
5. Check SL builder 

![image](https://cloud.githubusercontent.com/assets/673511/16228764/f4421dd8-3786-11e6-8df7-74c1a9298c35.png)

Expected: SL is still displayed 'Question 1 | was answered'

Instead: SL builder just shows 'Question 1' without the second dropdown'.

**Comment by magicznyleszek** [comment]
It turns out this works perfectly now :)
