### ISSUE TITLE
Implement new Project list columns, design

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#776]
- [ ] The project list should mirror the design, using the same columns (modified, created date, shared by, # of submissions). # of questions should be removed. 

- [ ] The project description should be displayed underneath the project name

**Comment by pmusaraj** [comment]
Commit adds columns for "Shared by" and "Created", with "Created" being hidden on the tablet view for lack of space. 

Right now we don't have the submissions count in the asset props. We don't have description either (and no UI yet to edit description in form builder or form view). The UI is ready to accommodate both, but for now I'm keeping Questions there. 

@tinok please open a separate issue for someone to add the backend source of submission counts and description.
