### ISSUE TITLE
Can't replace from XLS in Chrome on Mac OSX

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#777]
Replacing forms from XLS is not possible - only XLSX. kpi shows 'invalid filetype' when trying to upload an .xls file. 

This is important because the tool downloads forms in XLS format but they can't be re-uploaded.

**Comment by dorey** [comment]
uploaded files are converted to base64 in the browser, uploaded, and then converted back [here](https://github.com/kobotoolbox/kpi/blob/609efe5b04c7470dafd1703870e55b341b5e8c35/kpi/models/import_task.py#L168-L232).

The offending code could be in [`import_task. _b64_xls_to_dict`](https://github.com/kobotoolbox/kpi/blob/609efe5b04c7470dafd1703870e55b341b5e8c35/kpi/models/import_task.py#L234-L237).

**Comment by jnm** [comment]
[`import_task._b64_xls_to_dict()`](https://github.com/kobotoolbox/kpi/blob/609efe5b04c7470dafd1703870e55b341b5e8c35/kpi/models/import_task.py#L234-L237) calls [`pyxform.xls2json_backends.xls_to_dict()`](https://github.com/kobotoolbox/pyxform/blob/master/pyxform/xls2json_backends.py#L28), which calls [`xlrd.open_workbook()`](https://github.com/kobotoolbox/pyxform/blob/master/pyxform/xls2json_backends.py#L41), which is [supposed to accept XLS or XLSX in version 0.8.0](http://stackoverflow.com/a/12221066). It seems to work as expected; I can't reproduce the "invalid filetype" issue.

**Comment by tinok** [comment]
Steps to reproduce:

1. Create form
2. Save and close
3. Download form as XLS file
4. Click 'replace from XLS' and choose file downloaded in step (3) 

Expected: Form is replaced with the imported file
Instead: An error message is displayed `Invalid filetype: ''` Console output: 

![image](https://cloud.githubusercontent.com/assets/673511/17149489/7ed55028-5339-11e6-882d-92299ee06162.png)

**Comment by jnm** [comment]
I believe @pmusaraj fixed this. I just tested in BrowserStack and cannot reproduce the issue.
