### ISSUE TITLE
Standardize all kpi error modals

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#782]
Deployment failure: 

![image](https://cloud.githubusercontent.com/assets/673511/16402235/fcf9631e-3cb8-11e6-941c-37cd0e6cf2bb.png)

Formbuilder preview error: 

![image](https://cloud.githubusercontent.com/assets/673511/16402262/1a8678ea-3cb9-11e6-94fe-6e91ada735a3.png)

Import failure: 

![image](https://cloud.githubusercontent.com/assets/673511/16402269/2ce37ab0-3cb9-11e6-93af-4796d9828474.png)

Deletion and cloning modals: 

![image](https://cloud.githubusercontent.com/assets/673511/16402360/02347ade-3cba-11e6-8ea7-483be4377c7e.png)

![image](https://cloud.githubusercontent.com/assets/673511/16402375/1c7b8cd4-3cba-11e6-954d-41c99a6a0f10.png)

**Comment by southisack** [comment]
Here are some comments and changes that I noticed. 
[782.zip](https://github.com/kobotoolbox/kpi/files/742784/782.zip)

**Comment by southisack** [comment]
Here are my comments on the dialog

![782](https://cloud.githubusercontent.com/assets/4983734/22481402/1cd4d73a-e7c3-11e6-818d-e052ed461bd2.jpg)

**Comment by pmusaraj** [comment]
Hmm, these are all valid, but I think we should handle them at a second stage, when we approve the whole visual interface. (It would make little sense to updated fonts and form styles only for these dialogs...)

**Comment by Pedro719** [comment]
Dialogs are clear, I was wondering for the "unable to deploy" with code beneath it should we give the user a button or a link that allows them to report the issue from that instance if they want?

**Comment by pmusaraj** [comment]
The "report issue" would fall under the "new feature" category, to be handled separately from this issue.
