### ISSUE TITLE
Port over `kobocat/onadata/apps/survey_report/`.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kpi#785]

**Comment by emilykferguson** [comment]
Most functions completed. Remaining issues are #873, #874, #875, #876

**Comment by tinok** [comment]
Questions are displayed in reverse order: 

![image](https://cloud.githubusercontent.com/assets/673511/17938095/872efb46-69f2-11e6-85be-6bbef7a35c85.png)
