### ISSUE TITLE
Display success notification after replacing form from XLS

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#818]
Users should see a confirmation after replacing a form from XLS. Currently if a new form was successfully replaced there is no feedback at all for the user.

**Comment by tinok** [comment]
https://github.com/kobotoolbox/kpi/blob/master/jsapp/js/actions.es6#L276-L277

**Comment by pmusaraj** [comment]
Fixed already here: 
https://github.com/kobotoolbox/kpi/blob/master/jsapp/js/mixins.es6#L1039
