### ISSUE TITLE
Allow user to view and edit all profile settings (in KPI)

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#821]
This includes 

* all the fields available through #550
* Reset password button/view
* metadata field (we can possibly do without this one)

This should include a migration of all user profile details the user previously specified in KC into KPI's database.

**Comment by dorey** [comment]
Addressed here:

https://github.com/kobotoolbox/kpi/commit/4f4b8d00c38905902ad1d8284dceac949a45288a#diff-4b2441f86a503b441ed4286d32f6cab9R35

**Comment by tinok** [comment]
The user profile fields should be hidden in kc-templates as part of this issue.
