### ISSUE TITLE
Clone/upload/delete/deploy operations do not update sidebar

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#827]
Asset operations should update the form list sidebar as appropriate, i.e.
- Deleting an asset should remove it from the sidebar
- Cloning an asset should make the new asset appear in the sidebar
- Uploading an asset should make it appear in the sidebar
- Deploying an asset should move it from "Draft" to "Deployed" (and the counts for each category should be updated)

**Comment by pmusaraj** [comment]
The only still relevant issue here is updating the sidebar after deploying a form.
