### ISSUE TITLE
Line breaks are being stripped

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#849]
When importing an XLSForm file containing line breaks and deploying it, the line breaks are removed from the form. 

The formbuilder is expected to remove the line breaks (until we have a better solution) but KPI is expected to keep the form intact without making any changes at all. 

[line_breaks.xlsx](https://github.com/kobotoolbox/kpi/files/398281/line_breaks.xlsx)

**Comment by tinok** [comment]
This is closely related to #680.

**Comment by tinok** [comment]
I just troubleshooted why a note with lots of formatting doesn't work after deploying, and the answer is because it contained line breaks. Markdown header styles don't work because the linebreaks disappear, so `######` just appears inline instead of starting a new header paragraph. It looks like this:

![image](https://user-images.githubusercontent.com/673511/27924403-28a8830c-624f-11e7-9eed-a4b502017b3f.png)

Here's the XLSForm text for the note to test: 


```

#####<span style="color:black; font-style:normal">Dear Colleagues,</span>

######<span style="color:black; font-style:normal">Further to our message early January, .....</span>
######<span style="color:black; font-style:normal">This initiative is essential to adjust ....</span>

```

**Comment by jnm** [comment]
This issue is blocking us from disabling KC uploads.

**Comment by jnm** [comment]
* `\n` is present in form JSON after import
* Enketo preview shows line breaks correctly
* After deployment, line breaks are missing

**Comment by jnm** [comment]
The generated CSV that's sent to KC actually seems okay:
```
survey
,kuid,type,name,label,calculation
,B397M0HM,text,this_line_breaks,"this line
breaks"
,0GU91HNA,note,this_line_breaks_1,"this line 
breaks"
,,calculate,__version__,,'vG3gRp5erikqL3dn2Zx9m9'
settings
,form_title,version,id_string
,Testing line breaks,vG3gRp5erikqL3dn2Zx9m9,fail
```
However, to avoid digging into the KC CSV-reading code, let's switch to XLS (discussed with @dorey). This will involve making sure the `form_title` and `id_string` are in the XLS, since `to_csv_io()` is handling that now: https://github.com/kobotoolbox/kpi/blob/04360d504783b5026c89c2d990afd2a58ef083de/kpi/deployment_backends/kobocat_backend.py#L106
