### ISSUE TITLE
Implement Sharing Modal Updates

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#863]
- [x] Dropdown to include can view, can edit
- [x] Ability to turn off link sharing
- [ ] "More" option allows user to specify whether the link is active for the whole web, people with the link, or off/specific people

**Comment by emilykferguson** [comment]
[Summary_v1.1.pdf](https://github.com/kobotoolbox/kpi/files/411744/Summary_v1.1.pdf)

Sketch file is in the Google Drive.

**Comment by pmusaraj** [comment]
Completed, without the More option.
