### ISSUE TITLE
Duplicate form versions being created

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#878]
Multiple 7 year old versions being created of a form that should only have one https://kf.kbtdev.org/forms/#/forms/aNAL65dN8yBLCDjY9wLwSo

**Comment by tinok** [comment]
For new projects this seems to happen only once (one 'previous version' is created), e.g. https://kf.kbtdev.org/forms/#/forms/aUv5gEcaTvocnrnXLuqv3t

**Comment by dorey** [comment]
* 7 year old versions seem to be a UX bug that's been fixed
* Versions are created internally which have no noticeable effect on the UX
* Before space becomes an issue, we can create a task to garbage-collect stale versions or reduce the size of versions so that only changes are saved in the db
