### ISSUE TITLE
Unable to import questions from library in the formbuilder

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#879]
Steps to reproduce:
1. Create a new form
2. Try to drag any question from the library into the form.

Expected result: Question is shown in the form
Instead: form remains blank, several messages appear in the Console

![image](https://cloud.githubusercontent.com/assets/15673694/17937159/327fa526-69ef-11e6-9409-a49967c0150c.png)

**Comment by dorey** [comment]
No longer present
