### ISSUE TITLE
Report questions are in random order

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#881]
API call and UI output on staging show questions in random order from how they were created in the form. Test form has three questions but they are shown in different order (in this case reverse, but it's not always in that specific order): 

![image](https://cloud.githubusercontent.com/assets/673511/17939230/a7515b8a-69f7-11e6-8725-d990920fb3bc.png)

https://kf.kbtdev.org/forms/reports/axVTs6rpy3iMuKT5WG32Ez/

**Comment by esmail** [comment]
Is this related to kobotoolbox/formpack#60?

**Comment by tinok** [comment]
@esmail I don't think it's related. kobotoolbox/formpack#60 is only about the parsed select_multiple responses being out of order in data tables, but the questions are in order.

**Comment by magicznyleszek** [comment]
I can confirm by testing that this is fixed.
