### ISSUE TITLE
kc settings iframe forwards to kc project page

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kpi#884]
When uploading a media attachment or adding permissions for a user the iframe refreshes and shows the kc project page instead. 

![image](https://cloud.githubusercontent.com/assets/673511/17949730/d8e38b6e-6a24-11e6-8e4a-a4219f18d087.png)

**Comment by pmusaraj** [comment]
There is an old PR in KC that isn't yet merged, it's supposed to fix this: https://github.com/kobotoolbox/kobocat/pull/241
