### ISSUE TITLE
Implement Password Strength criteria

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#916]
Require users to create/update their passwords to fit our password strength criteria.

**Comment by magicznyleszek** [comment]
My two cents: as for password strengths I think we should follow the work Dropbox team did in 2012: https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/

**Comment by jnm** [comment]
Looks like there's also a Python implementation:
https://github.com/dwolfhub/zxcvbn-python

Registration is handled by (an [old version](https://github.com/kobotoolbox/kpi/blob/e0842b5ba7bdcdcf29627f489fecd0ba74158a74/dependencies/pip/requirements.txt#L41) of) https://github.com/macropin/django-registration. @magicznyleszek, have a look at a frontend-only implementation and we'll see if the backend can follow.

**Comment by magicznyleszek** [comment]
@jnm do we want to do anything else besides #2043 here? I don't remember why, but this PR wasn't set to close this… maybe you do :)

**Comment by jnm** [comment]
Yeah, thanks for mentioning this. We need to have the backend require a minimum level of password strength, if the sysadmin decides that's appropriate.
