### ISSUE TITLE
Redeploying does not update KC project name

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#932]
1. Add a new form and deploy it;
2. Change the form name in KPI;
3. Redeploy the form;
4. Notice the corresponding KC project retains the original name

Causes user confusion, e.g. http://support.kobotoolbox.org/customer/portal/questions/16557001-i-can-not-get-my-re-deployed-forms

**Comment by tinok** [comment]
@jnm I just tried to reproduce this and I believe it is fixed.
