### ISSUE TITLE
Drop zone at bottom of form is very small

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#940]
Ideally, all of the whitespace below the last question (or placeholder if there are no questions) should work as a drop zone for dragging and dropping library assets. See attached screencast
![anim](https://cloud.githubusercontent.com/assets/2085013/18888011/9ef1f3f4-84c4-11e6-987a-0841af37d26a.gif)

**Comment by smutnyleszek** [comment]
Dropzone has height set to `31px` and if there is zero space below last question it resizes the container (by simply being added to DOM) - so it should have some safe minimum height set
