### ISSUE TITLE
cascading select form cannot be previewed or deployed

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kpi#943]
```
ODK Validate Errors: [Fatal Error] tmpDQ6M39:71:14: The content of elements must consist of well-formed character data or markup. >> XML is invalid. See above for the errors. Result: Invalid
```
- Only present when formpack is used to flatten_content 
- likely has to do with new survey content format

**Comment by cattleyalinda** [comment]
I'm also experiencing the same problem. This happens when I put a condition in the choice filter. When I remove the condition, it does not display any errot

**Comment by joshuaberetta** [comment]
@dorey do you know how to reproduce this?

**Comment by dorey** [comment]
I think this is fixed. If we get a form that triggers this issue we can reopen.
