### ISSUE TITLE
Language names concatenated w/o separator on form landing page

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kpi#965]
When `languages` in the `summary` returned by the API contains more than one string, the language names appear concatenated together with no space or punctuation.
![screenshot - 10132016 - 11 12 17 pm](https://cloud.githubusercontent.com/assets/2085013/19374901/652469be-919d-11e6-9bf7-7faff7806651.png)

**Comment by pmusaraj** [comment]
This was fixed a while ago. 
<img width="1039" alt="screen shot 2016-11-29 at 2 13 06 pm" src="https://cloud.githubusercontent.com/assets/368961/20724890/025495e6-b63e-11e6-8b76-d0954300b370.png">
