### ISSUE TITLE
Add "archive project" in project list view

### ISSUE THREAD

**Issue by emilykferguson** [kobotoolbox/kpi#991]
Under the 3 dots, add "Archive Project" above "Delete".

**Comment by emilykferguson** [comment]
When user turns of submissions, the Project is set as "archived".

**Comment by Pedro719** [comment]
There are times when the archive button doesn't appear in the list. I had to refresh 3 times in order for the Archive button to appear in the list of options. When the Archive did appear the "Archive" button remained inactive for about 2 minutes.The delete button functions properly.
